export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'main_view',
  deviewId: '3d1a3f45b65156dbb31fcd3c9825d6c6',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.CRM_LEAD',
  },
  caption: '线索/商机',
  codeName: 'crm_lead_main_view',
  appDataEntityId: 'ibizodooapp.crm_lead',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container2',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'identifier',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 0,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'view_content',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 8,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '实体部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'control',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  heightMode: 'FULL',
                  layout: 'TABLE_24COL',
                },
                id: 'mail_thread_panel',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 4,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container1',
          },
        ],
        predefinedType: 'CONTAINER_GRID',
        layout: {
          layout: 'SIMPLEFLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '栅格容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_grid',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem1',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个保存按钮）',
        appDataEntityId: 'ibizodooapp.crm_lead',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '25823041a044e2dfc60cdebdb06ebd82',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.crm_lead',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ibizodooapp.crm_lead',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.crm_lead',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.crm_lead',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.crm_lead',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.crm_lead',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  align: 'space-between',
                  dir: 'row',
                  layout: 'FLEX',
                },
                deformDetails: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    buttonListType: 'UIACTIONGROUP',
                    uiactionGroup: {
                      uiactionGroupDetails: [
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          capLanguageRes: {
                            lanResTag: 'TBB.TEXT.*.NEW',
                          },
                          caption: '新建',
                          detailType: 'DEUIACTION',
                          uiactionId: 'editview_newaction',
                          tooltipLanguageRes: {
                            lanResTag: 'TBB.TOOLTIP.*.NEW',
                          },
                          showCaption: true,
                          showIcon: true,
                          sysImage: {
                            cssClass: 'fa fa-file-text-o',
                            glyph: 'xf0f6@FontAwesome',
                          },
                          id: 'u37757ea',
                        },
                      ],
                      appDataEntityId: 'ibizodooapp.crm_lead',
                      uniqueTag: 'crm_lead__A79119c50056dc4c1a2',
                      name: '商机编辑界面行为组',
                      id: 'a79119c50056dc4c1a2',
                    },
                    codeName: 'buttonlist1',
                    detailStyle: 'DEFAULT',
                    detailType: 'BUTTONLIST',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'buttonlist1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'stage_id',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'ibizodooapp.crm__crm_stage',
                      editorParams: {
                        duration_tracking: 'duration_tracking',
                      },
                      editorStyle: 'STATUS_BAR',
                      editorType: 'DROPDOWNLIST',
                      sysPFPluginId: 'odoo_status_bar',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'stage_id',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.CRM_LEAD.STAGE_ID',
                    },
                    caption: '阶段',
                    codeName: 'stage_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'stage_id',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.CRM_LEAD.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'contact_name',
                    editor: {
                      maxLength: 500,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'contact_name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.CRM_LEAD.CONTACT_NAME',
                    },
                    caption: '联系人姓名',
                    codeName: 'contact_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'contact_name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'phone',
                    editor: {
                      maxLength: 500,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'phone',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.CRM_LEAD.PHONE',
                    },
                    caption: '电话号码',
                    codeName: 'phone',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'phone',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'email_from',
                    editor: {
                      maxLength: 500,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'email_from',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.CRM_LEAD.EMAIL_FROM',
                    },
                    caption: '电子邮件',
                    codeName: 'email_from',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'email_from',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'company_id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'company_id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.CRM_LEAD.COMPANY_ID',
                    },
                    caption: '公司',
                    codeName: 'company_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    id: 'company_id',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'type',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'ibizodooapp.crm__crm_lead_type',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'type',
                    },
                    needCodeListConfig: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.CRM_LEAD.TYPE',
                    },
                    caption: '类型',
                    codeName: 'type',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'type',
                  },
                  {
                    dataType: 21,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'duration_tracking',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'OBJECT',
                      editable: true,
                      id: 'duration_tracking',
                    },
                    allowEmpty: true,
                    hidden: true,
                    caption: '状态时间',
                    codeName: 'duration_tracking',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 6,
                      layout: 'TABLE_24COL',
                    },
                    id: 'duration_tracking',
                  },
                ],
                caption: '基础信息',
                codeName: 'group_base',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group_base',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'file',
                    editor: {
                      editorParams: {
                        MAXFILECNT: '1',
                      },
                      editorType: 'FILEUPLOADER_ONE',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'file',
                    },
                    allowEmpty: true,
                    caption: '文件',
                    codeName: 'file',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'file',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'image',
                    editor: {
                      maxFileCount: 1,
                      editorParams: {
                        MAXCOUNT: '1',
                      },
                      editorType: 'PICTURE_ONE',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'image',
                    },
                    allowEmpty: true,
                    caption: '图片',
                    codeName: 'image',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'image',
                  },
                ],
                caption: '测试文件',
                codeName: 'grouppanel2',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel2',
              },
              {
                deformTabPages: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'street',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'street',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.STREET',
                            },
                            caption: '街道',
                            codeName: 'street',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'street',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'city',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'city',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.CITY',
                            },
                            caption: '城市',
                            codeName: 'city',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'city',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'state_id',
                            editor: {
                              editorType: 'HIDDEN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'state_id',
                            },
                            allowEmpty: true,
                            hidden: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.STATE_ID',
                            },
                            caption: '省/州',
                            codeName: 'state_id',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            id: 'state_id',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'zip',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'zip',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.ZIP',
                            },
                            caption: '邮编',
                            codeName: 'zip',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'zip',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'country_id',
                            editor: {
                              editorType: 'HIDDEN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'country_id',
                            },
                            allowEmpty: true,
                            hidden: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.COUNTRY_ID',
                            },
                            caption: '国家/地区',
                            codeName: 'country_id',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            id: 'country_id',
                          },
                        ],
                        caption: '地址详情',
                        codeName: 'group_address',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'group_address',
                      },
                    ],
                    caption: '地址信息',
                    codeName: 'address',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'address',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'user_id',
                            editor: {
                              editorType: 'HIDDEN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'user_id',
                            },
                            allowEmpty: true,
                            hidden: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.USER_ID',
                            },
                            caption: '销售人员',
                            codeName: 'user_id',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            id: 'user_id',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'priority',
                            editor: {
                              singleSelect: true,
                              appCodeListId:
                                'ibizodooapp.crm__crm_lead_priority',
                              editorType: 'DROPDOWNLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'priority',
                            },
                            allowEmpty: true,
                            needCodeListConfig: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.PRIORITY',
                            },
                            caption: '优先级',
                            codeName: 'priority',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'priority',
                          },
                          {
                            dataType: 7,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'probability',
                            editor: {
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'probability',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.PROBABILITY',
                            },
                            caption: '概率',
                            codeName: 'probability',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'probability',
                          },
                          {
                            dataType: 6,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'expected_revenue',
                            editor: {
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'expected_revenue',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.EXPECTED_REVENUE',
                            },
                            caption: '预期收入',
                            codeName: 'expected_revenue',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'expected_revenue',
                          },
                        ],
                        caption: '销售详情',
                        codeName: 'group_sales',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'group_sales',
                      },
                    ],
                    caption: '销售信息',
                    codeName: 'sales_info',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'sales_info',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 5,
                            enableCond: 3,
                            itemWidth: 230,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'activity_date_deadline',
                            editor: {
                              dateTimeFormat: 'YYYY-MM-DD',
                              editorParams: {
                                TIMEFMT: 'YYYY-MM-DD',
                              },
                              editorType: 'DATEPICKEREX_NOTIME',
                              editorWidth: 100,
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'activity_date_deadline',
                            },
                            valueFormat: 'YYYY-MM-DD',
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.CRM_LEAD.ACTIVITY_DATE_DEADLINE',
                            },
                            caption: '下一活动截止日期',
                            codeName: 'activity_date_deadline',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'activity_date_deadline',
                          },
                          {
                            dataType: 5,
                            enableCond: 3,
                            itemWidth: 230,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'my_activity_date_deadline',
                            editor: {
                              dateTimeFormat: 'YYYY-MM-DD',
                              editorParams: {
                                TIMEFMT: 'YYYY-MM-DD',
                              },
                              editorType: 'DATEPICKEREX_NOTIME',
                              editorWidth: 100,
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'my_activity_date_deadline',
                            },
                            valueFormat: 'YYYY-MM-DD',
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.CRM_LEAD.MY_ACTIVITY_DATE_DEADLINE',
                            },
                            caption: '我的活动截止时间',
                            codeName: 'my_activity_date_deadline',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'my_activity_date_deadline',
                          },
                          {
                            dataType: 5,
                            enableCond: 3,
                            itemWidth: 230,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'date_deadline',
                            editor: {
                              dateTimeFormat: 'YYYY-MM-DD',
                              editorParams: {
                                TIMEFMT: 'YYYY-MM-DD',
                              },
                              editorType: 'DATEPICKEREX_NOTIME',
                              editorWidth: 100,
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'date_deadline',
                            },
                            valueFormat: 'YYYY-MM-DD',
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_DEADLINE',
                            },
                            caption: '预期结束',
                            codeName: 'date_deadline',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'date_deadline',
                          },
                          {
                            dataType: 5,
                            enableCond: 3,
                            itemWidth: 290,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'date_open',
                            editor: {
                              dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                              editorParams: {
                                TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                              },
                              editorType: 'DATEPICKER',
                              editorWidth: 160,
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'date_open',
                            },
                            valueFormat: 'YYYY-MM-DD HH:mm:ss',
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_OPEN',
                            },
                            caption: '指派日期',
                            codeName: 'date_open',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'date_open',
                          },
                        ],
                        caption: '活动详情',
                        codeName: 'group_activity',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'group_activity',
                      },
                    ],
                    caption: '活动信息',
                    codeName: 'activity',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'activity',
                  },
                ],
                codeName: 'tabpanel_nested',
                detailStyle: 'DEFAULT',
                detailType: 'TABPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'tabpanel_nested',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.CRM_LEAD.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '客户信息',
            codeName: 'main_page',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'main_page',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'FORM',
        logicName: '主编辑表单',
        appDataEntityId: 'ibizodooapp.crm_lead',
        controlParam: {
          id: 'form',
        },
        modelId: '5aed6feb90b5a35ff379bc3eb1e0ac14',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ibizodooapp.crm_lead.main',
      },
      {
        embeddedAppDEViewId: 'ibizodooapp.mail_thread_component_view',
        codeName: 'main_view_control',
        controlType: 'VIEWPANEL',
        appDataEntityId: 'ibizodooapp.crm_lead',
        controlParam: {},
        name: 'control',
        id: 'main_view_control',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ibizodooapp.crm_lead',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.CRM_LEAD',
        },
        caption: '线索/商机',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.crm_lead',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'main_view_layout_new',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new',
    appDataEntityId: 'ibizodooapp.crm_lead',
    controlLogics: [
      {
        eventNames: 'onMounted',
        itemName: 'DRBAR',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", (state, isTrusted )=> {\r\n    console.log("");\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});\r\n\r\nconst topContext = view.context;\r\nconst appEntityId = view.model.appDataEntityId;\r\nconst entityName = appEntityId.split(\'.\').pop();\r\nconst bExist = topContext[entityName];\r\nconst drbar = view.getCtrl("DRBAR", "drbar");\r\nif(!bExist){\r\n    drbar.disabled({ mode: \'BLANK\' })\r\n    //  drbar.disabled({ mode: \'MASK\' })\r\n\r\n}\r\n\r\n',
        triggerType: 'CTRLEVENT',
        id: 'drbar_draft_state',
      },
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onRegister',
        itemName: 'DRBAR',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode: "console.log('部件onRegister执行了');",
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\r\n   if (name === 'drbar') {\r\n      const topContext = view.context;\r\n      const appEntityId = view.model.appDataEntityId;\r\n      const entityName = appEntityId.split('.').pop();\r\n      const bExist = topContext[entityName];\r\n      if(!bExist){\r\n         ctrl?.disableCounter()\r\n      }\r\n   }\r\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '31fa7086ff6a353ca3fdf381a934b594',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout_new',
  },
  title: '线索/商机编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '6bb224d049bb7e2d0c242bfe26d8bde5',
  modelType: 'PSAPPDEVIEW',
  name: 'crm_leadmain_view',
  id: 'ibizodooapp.crm_lead_main_view',
};
