export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: 'bfa53022412d91a55fcd4894f9958056',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
  },
  caption: '讨论频道',
  codeName: 'discuss_channel_pickup_view',
  appDataEntityId: 'ibizodooapp.discuss_channel',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.discuss_channel_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
      },
      caption: '讨论频道',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.discuss_channel',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '讨论频道数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c9cd13804bd0612ffe9ec1f408250881',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_channelPickupView',
  id: 'ibizodooapp.discuss_channel_pickup_view',
};
