export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '132c885ec28ca4ae3a5f1f5c72981b28',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
  },
  caption: '讨论频道',
  codeName: 'discuss_channel_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.discuss_channel',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'write_uid',
          excelCaption: '更新人',
          appCodeListId: 'ibizodooapp.sysoperator',
          appDEFieldId: 'write_uid',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.WRITE_UID',
          },
          caption: '更新人',
          codeName: 'write_uid',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'write_uid',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'write_date',
          excelCaption: '更新时间',
          appDEFieldId: 'write_date',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.WRITE_DATE',
          },
          caption: '更新时间',
          codeName: 'write_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'write_date',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'write_uid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'write_uid',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'write_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'write_date',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'from_message_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'from_message_id',
        },
        {
          appDEFieldId: 'parent_channel_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_channel_id',
        },
        {
          appDEFieldId: 'group_public_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'group_public_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'grid',
      },
      modelId: 'd7eca7e21b52c9faf41727ef2fc5b9d5',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.discuss_channel.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.DISCUSS_CHANNEL.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'searchform',
      },
      modelId: '70851bbf98aede277f596aedf095cb8f',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.discuss_channel.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
      },
      caption: '讨论频道',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.discuss_channel',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '讨论频道选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'c7757cd8947adce7a84417db0fa0a033',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_channelPickupGridView',
  id: 'ibizodooapp.discuss_channel_pickup_grid_view',
};
