export default {
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPOVER',
  deviewCodeName: 'invite_member_view',
  deviewId: '2420f8dea8066d5acca77145bbfb0699',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
  },
  caption: '邀请成员',
  codeName: 'discuss_channel_invite_member_view',
  appDataEntityId: 'ibizodooapp.discuss_channel',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'add_members',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              editor: {
                pickupAppViewId: 'ibizodooapp.res_partner_pick_up_list_view',
                valueItemName: 'members',
                editorType: 'PICKUPVIEW',
                editorItems: [
                  {
                    id: 'members',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'membernames',
              },
              allowEmpty: true,
              codeName: 'membernames',
              contentHeight: 400,
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              height: 400,
              layoutPos: {
                colMD: 24,
                height: 400,
                heightMode: 'PX',
                layout: 'TABLE_24COL',
              },
              id: 'membernames',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'members',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'members',
              },
              allowEmpty: true,
              hidden: true,
              caption: '成员',
              codeName: 'members',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'members',
            },
            {
              dataType: 25,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'invitation_url',
              editor: {
                maxLength: 250,
                editorType: 'TEXTBOX',
                placeHolder: '邀请链接',
                valueType: 'SIMPLE',
                editable: true,
                id: 'invitation_url',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.INVITATION_URL',
              },
              caption: '邀请URL',
              codeName: 'invitation_url',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'invitation_url',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'invite_member',
      controlType: 'FORM',
      logicName: '频道邀请成员操作视图_表单',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'form',
      },
      modelId: 'd9a8d49d6ca2776d4050278d5b990179',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'ibizodooapp.discuss_channel.invite_member',
    },
    {
      codeName: 'invite_member_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'invite_member_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
      },
      caption: '邀请成员',
      codeName: 'invite_member_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {},
      name: 'captionbar',
      id: 'invite_member_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.discuss_channel',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '邀请成员',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 500,
  enableDP: true,
  showCaptionBar: false,
  modelId: '29d142ed0e99c1b96774cdc725a740fb',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_channelinvite_member_view',
  id: 'ibizodooapp.discuss_channel_invite_member_view',
};
