export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'sub_channel_grid_view',
  deviewId: '91ab412857239b0b43dc2898d21f164b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
  },
  caption: '子频道',
  codeName: 'discuss_channel_sub_channel_grid_view',
  appDataEntityId: 'ibizodooapp.discuss_channel',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '讨论频道快速配置视图',
      refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '讨论频道快速配置视图',
      refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 200,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                detailType: 'DEUIACTION',
                uiactionId: 'gridview_removeaction',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                },
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'uf676d6d',
              },
            ],
            name: '通用表格界面删除界面行为组',
            id: 'auto83146635',
          },
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 200,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                detailType: 'DEUIACTION',
                uiactionId: 'gridview_removeaction',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                },
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'uf676d6d',
              },
            ],
            name: '通用表格界面删除界面行为组',
            id: 'auto83146635',
          },
          aggMode: 'NONE',
          align: 'RIGHT',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 70,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'from_message_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'from_message_id',
        },
        {
          appDEFieldId: 'parent_channel_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_channel_id',
        },
        {
          appDEFieldId: 'group_public_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'group_public_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 500,
      sortMode: 'REMOTE',
      enableCustomized: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'sub_channel',
      controlType: 'GRID',
      logicName: '子频道表格',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'grid',
      },
      modelId: '1952679d850aad2b7a9a323289a3085b',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.discuss_channel.sub_channel',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
      },
      caption: '子频道',
      codeName: 'sub_channel_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      controlParam: {},
      name: 'captionbar',
      id: 'sub_channel_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.discuss_channel',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '子频道列表',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '05f317643084d42538cadacc6312def9',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_channelsub_channel_grid_view',
  id: 'ibizodooapp.discuss_channel_sub_channel_grid_view',
};
