export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'quick_cfg_view',
  deviewId: '55df788fe06f30a62c791061fb1876d1',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
  },
  caption: '讨论频道',
  codeName: 'discuss_channel_quick_cfg_view',
  appDataEntityId: 'ibizodooapp.discuss_channel',
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '邀请人员',
                      detailType: 'DEUIACTION',
                      uiactionId: 'invite_member@discuss_channel',
                      showCaption: true,
                      showIcon: true,
                      id: 'u1520f17',
                    },
                  ],
                  appDataEntityId: 'ibizodooapp.discuss_channel',
                  uniqueTag: 'discuss_channel__Acad8c265e5fb136ce8',
                  name: '编辑界面默认行为组01',
                  id: 'acad8c265e5fb136ce8',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'quick_cfg_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'quick_cfg_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.discuss_channel',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ibizodooapp.discuss_channel',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.discuss_channel',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.discuss_channel',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.discuss_channel',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.discuss_channel',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      showMaxLength: true,
                      editorParams: {
                        ISAUTO: 'true',
                      },
                      editorType: 'TEXTAREA',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'channel_type',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId:
                        'ibizodooapp.discuss__discuss_channel_channel_type',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'channel_type',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.CHANNEL_TYPE',
                    },
                    caption: '频道类型',
                    codeName: 'channel_type',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'channel_type',
                  },
                  {
                    dataType: 25,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'parent_channel_name',
                    editor: {
                      enablePickupView: true,
                      singleSelect: true,
                      pickupAppViewId:
                        'ibizodooapp.discuss_channel_pickup_view',
                      handlerType: 'PickupText',
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'ibizodooapp.discuss_channel',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'parent_channel_id',
                      editorParams: {
                        AC: 'TRUE',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'PICKER',
                      editorItems: [
                        {
                          id: 'parent_channel_id',
                        },
                      ],
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'parent_channel_name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.PARENT_CHANNEL_ID',
                    },
                    caption: '父频道名称',
                    codeName: 'parent_channel_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'parent_channel_name',
                  },
                  {
                    maskMode: 0,
                    appViewId:
                      'ibizodooapp.discuss_channel_sub_channel_grid_view',
                    navigateParams: [
                      {
                        key: 'n_parent_channel_id_eq',
                        value: 'discuss_channel',
                        id: 'n_parent_channel_id_eq',
                      },
                    ],
                    parentDataJO: {
                      SRFPARENTTYPE: 'DER1N',
                      srfparentdename: 'DISCUSS_CHANNEL',
                      srfparentmode:
                        'DER1N_DISCUSS_CHANNEL_DISCUSS_CHANNEL_PARENT_CHANNEL_ID',
                      srfparentdefname: 'PARENT_CHANNEL_ID',
                      SRFDER1NID:
                        'DER1N_DISCUSS_CHANNEL_DISCUSS_CHANNEL_PARENT_CHANNEL_ID',
                    },
                    codeName: 'druipart1',
                    contentHeight: 400,
                    detailStyle: 'DEFAULT',
                    detailType: 'DRUIPART',
                    height: 400,
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      height: 400,
                      heightMode: 'PX',
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'druipart1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'uuid',
                        editor: {
                          maxLength: 250,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'uuid',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.UUID',
                        },
                        caption: 'Sfu 服务器uuid',
                        codeName: 'uuid',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'uuid',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'sfu_server_url',
                        editor: {
                          maxLength: 250,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'sfu_server_url',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.SFU_SERVER_URL',
                        },
                        caption: 'Sfu 服务器网址',
                        codeName: 'sfu_server_url',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'sfu_server_url',
                      },
                    ],
                    caption: '标识信息',
                    codeName: 'identity',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'identity',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'invitation_url',
                    editor: {
                      maxLength: 250,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'invitation_url',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.INVITATION_URL',
                    },
                    caption: '邀请URL',
                    codeName: 'invitation_url',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'invitation_url',
                  },
                  {
                    deformTabPages: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'group_public_name',
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              pickupAppViewId:
                                'ibizodooapp.res_groups_pickup_view',
                              handlerType: 'PickupText',
                              appDEACModeId: 'default',
                              appDEDataSetId: 'fetch_default',
                              appDataEntityId: 'ibizodooapp.res_groups',
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'group_public_id',
                              editorParams: {
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'group_public_id',
                                },
                              ],
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'group_public_name',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.DISCUSS_CHANNEL.GROUP_PUBLIC_ID',
                            },
                            caption: '授权群组',
                            codeName: 'group_public_name',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'group_public_name',
                          },
                        ],
                        caption: '隐私',
                        codeName: 'tabpage1',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage1',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            appViewId:
                              'ibizodooapp.discuss_channel_member_grid_view',
                            parentDataJO: {
                              SRFPARENTTYPE: 'DER1N',
                              srfparentdename: 'DISCUSS_CHANNEL',
                              srfparentmode:
                                'DER1N_DISCUSS_CHANNEL_MEMBER_DISCUSS_CHANNEL_CHANNEL_ID',
                              srfparentdefname: 'CHANNEL_ID',
                              SRFDER1NID:
                                'DER1N_DISCUSS_CHANNEL_MEMBER_DISCUSS_CHANNEL_CHANNEL_ID',
                            },
                            codeName: 'druipart2',
                            contentHeight: 400,
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            height: 400,
                            layoutPos: {
                              colMD: 24,
                              height: 400,
                              heightMode: 'PX',
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'druipart2',
                          },
                        ],
                        caption: '成员',
                        codeName: 'tabpage2',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage2',
                      },
                    ],
                    codeName: 'tabpanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPANEL',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'tabpanel1',
                  },
                ],
                caption: '核心信息',
                codeName: 'base_info',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'base_info',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'group_public_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'group_public_id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.GROUP_PUBLIC_ID',
                },
                caption: '授权群组',
                codeName: 'group_public_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group_public_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'parent_channel_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'parent_channel_id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.PARENT_CHANNEL_ID',
                },
                caption: '父频道',
                codeName: 'parent_channel_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'parent_channel_id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'FORM',
        logicName: '主编辑表单',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: 'd7eca7e21b52c9faf41727ef2fc5b9d5',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ibizodooapp.discuss_channel.main',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'quick_cfg_view_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'quick_cfg_view_toolbar1',
      },
      {
        codeName: 'quick_cfg_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'quick_cfg_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
        },
        caption: '讨论频道',
        codeName: 'quick_cfg_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.discuss_channel',
        controlParam: {},
        name: 'captionbar',
        id: 'quick_cfg_view_captionbar',
      },
    ],
    codeName: 'main_view_layout_nocomment',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_无讨论',
    appDataEntityId: 'ibizodooapp.discuss_channel',
    controlLogics: [
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", (state, isTrusted )=> {\r\n    console.log("");\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});',
        triggerType: 'CTRLEVENT',
        id: 'init_domain_state_change',
      },
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: 'ef3f9bc56161de3135f01329747f91a3',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout_nocomment',
  },
  title: '讨论频道快速配置视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'bb235940d323bcb627b627052d5c9f97',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_channelquick_cfg_view',
  id: 'ibizodooapp.discuss_channel_quick_cfg_view',
};
