export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: '77d5fd7c17d6a208c154fab7cb038a9e',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL_MEMBER',
  },
  caption: '频道成员',
  codeName: 'discuss_channel_member_grid_view',
  appDataEntityId: 'ibizodooapp.discuss_channel_member',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'ibizodooapp.discuss_channel_member_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'ibizodooapp.discuss_channel_member_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'ibizodooapp.discuss_channel_member_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'ibizodooapp.discuss_channel_member_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      openMode: 'POPUPMODAL',
      realOpenMode: 'POPUPMODAL',
      realTitle: '频道成员编辑视图',
      refAppViewId: 'ibizodooapp.discuss_channel_member_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      openMode: 'POPUPMODAL',
      realOpenMode: 'POPUPMODAL',
      realTitle: '频道成员编辑视图',
      refAppViewId: 'ibizodooapp.discuss_channel_member_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'partner_name',
          excelCaption: '合作伙伴',
          appDEFieldId: 'partner_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.PARTNER_ID',
          },
          caption: '合作伙伴',
          codeName: 'partner_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'partner_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'guest_name',
          excelCaption: '访客',
          appDEFieldId: 'guest_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.GUEST_ID',
          },
          caption: '访客',
          codeName: 'guest_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'guest_name',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 200,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                detailType: 'DEUIACTION',
                uiactionId: 'gridview_removeaction',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                },
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash-o',
                  glyph: 'xf014@FontAwesome',
                },
                id: 'uf676d6d',
              },
            ],
            name: '通用表格界面删除界面行为组',
            id: 'auto83146635',
          },
          aggMode: 'NONE',
          align: 'RIGHT',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'partner_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'partner_name',
        },
        {
          appDEFieldId: 'guest_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'guest_name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'guest_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'guest_id',
        },
        {
          appDEFieldId: 'channel_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'channel_id',
        },
        {
          appDEFieldId: 'fetched_message_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'fetched_message_id',
        },
        {
          appDEFieldId: 'partner_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'partner_id',
        },
        {
          appDEFieldId: 'seen_message_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'seen_message_id',
        },
        {
          appDEFieldId: 'rtc_inviting_session_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'rtc_inviting_session_id',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 500,
      sortMode: 'REMOTE',
      enableCustomized: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.discuss_channel_member',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.discuss_channel_member',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.discuss_channel_member',
      controlParam: {
        id: 'grid',
      },
      modelId: '1ebd74287173b99d8af491cf47b4d433',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.discuss_channel_member.main',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel_member',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DISCUSS_CHANNEL_MEMBER',
      },
      caption: '频道成员',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.discuss_channel_member',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.discuss_channel_member',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '频道成员表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '6e56164976164c7fdf6eb0db76430189',
  modelType: 'PSAPPDEVIEW',
  name: 'discuss_channel_memberGridView',
  id: 'ibizodooapp.discuss_channel_member_grid_view',
};
