export default {
  appSwitchMode: 1,
  mainMenuAlign: 'TOP',
  enableAppSwitch: true,
  caption: '讨论',
  codeName: 'discuss_index_view',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          predefinedType: 'NAV_BREADCRUMB',
                          id: 'nav_breadcrumb',
                        },
                        caption: '面包屑导航',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_breadcrumb',
                      },
                      {
                        rawItem: {
                          predefinedType: 'NAV_POS_INDEX',
                          id: 'nav_pos_index',
                        },
                        caption: '导航区占位',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          grow: 1,
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_pos_index',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 100,
                    height: 100,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 100,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container4_all',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                },
                id: 'container6_all',
              },
              {
                rawItem: {
                  caption: '标签',
                  halign: 'LEFT',
                  renderMode: 'PARAGRAPH',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_LABEL',
                  id: 'static_label',
                },
                caption: '标签',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                sysPFPluginId: 'odoo_chat',
                showCaption: true,
                id: 'static_label',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
              width: 100,
              widthMode: 'PERCENTAGE',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              contentType: 'USER',
                              rawItemParams: [
                                {
                                  key: 'sourcetype',
                                  value: 'UTIL',
                                },
                              ],
                              predefinedType: 'APP_SWITCH',
                              id: 'app_switch',
                            },
                            caption: '应用切换器',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERMEDIUM',
                            },
                            showCaption: true,
                            id: 'app_switch',
                          },
                          {
                            caption: '首页菜单',
                            contentHeight: 60,
                            contentWidth: 800,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              grow: 1,
                              shrink: 1,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 800,
                              widthMode: 'PX',
                            },
                            width: 800,
                            showCaption: true,
                            id: 'appmenu',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'container2',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '文本内容',
                              halign: 'LEFT',
                              renderMode: 'TEXT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'INDEX_VIEW_SEARCH',
                              id: 'index_view_search',
                            },
                            caption: '搜索栏',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'index_view_search',
                          },
                        ],
                        layout: {
                          align: 'center',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 52,
                        height: 52,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          height: 52,
                          heightMode: 'PX',
                          layout: 'FLEX',
                        },
                        id: 'container',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  contentType: 'IMAGE',
                                  predefinedType: 'USERMESSAGE',
                                  id: 'usermessage',
                                },
                                caption: '消息通知',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 1,
                                  heightMode: 'FULL',
                                  layout: 'FLEX',
                                  widthMode: 'FULL',
                                },
                                showCaption: true,
                                id: 'usermessage',
                              },
                            ],
                            layout: {
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            contentHeight: 48,
                            contentWidth: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              height: 48,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 48,
                              widthMode: 'PX',
                            },
                            width: 48,
                            id: 'container1',
                          },
                          {
                            rawItem: {
                              rawItemParams: [
                                {
                                  key: 'AVATAR',
                                  value: 'avatar',
                                },
                                {
                                  key: 'TITLE',
                                  value: 'srfusername',
                                },
                                {
                                  key: 'SUBTITLE',
                                  value: 'loginname',
                                },
                                {
                                  key: 'NAVVIEWNAME',
                                  value: 'res_users_info_custom_view',
                                },
                              ],
                              predefinedType: 'AUTH_USERINFO',
                              rawItemHeight: 60,
                              id: 'auth_userinfo',
                            },
                            caption: '用户信息',
                            contentHeight: 60,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 0,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                            },
                            sysPFPluginId: 'custom_auth_userinfo',
                            showCaption: true,
                            id: 'auth_userinfo',
                          },
                        ],
                        predefinedType: 'INDEX_ACTIONS',
                        layout: {
                          align: 'space-between',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'indexactions',
                      },
                    ],
                    layout: {
                      align: 'space-between',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container7',
                  },
                ],
                predefinedType: 'AppHeader',
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                  widthMode: 'FULL',
                },
                id: 'app_header',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_HEADER',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentHeight: 60,
            height: 60,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'NORTH',
              height: 60,
              heightMode: 'PX',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_header',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        layoutMode: 'TABLE_24COL',
        appMenuItems: [
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'discuss',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            openDefault: true,
            valid: true,
            caption: '讨论',
            tooltip: '讨论',
            id: 'discuss',
          },
          {
            itemType: 'MENUITEM',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '配置',
            tooltip: '配置',
            id: 'discuss_config',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'discuss_index_view',
        controlType: 'APPMENU',
        logicName: '讨论',
        controlParam: {},
        modelId: '47290d04eedc3abddcd83ad6d03c1226',
        modelType: 'PSAPPMENU',
        name: 'appmenu',
        id: 'discuss_index_view',
      },
      {
        caption: '讨论',
        subCaption: '讨论',
        codeName: 'captionbar',
        controlType: 'CAPTIONBAR',
        controlParam: {},
        id: 'captionbar',
      },
    ],
    codeName: 'usr0816975858',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'AppIndexView',
    controlParam: {},
    modelId: '21f3f21b39a12e6aa06af432c6ee2d0b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0816975858',
  },
  subCaption: '讨论',
  title: '讨论',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f9210c8bef45bcc1f7ffe5fdfd373f13',
  modelType: 'PSAPPINDEXVIEW',
  userTag4: '10',
  name: 'DiscussIndexView',
  id: 'ibizodooapp.discuss_index_view',
};
