export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'department_hierarchy_view',
  deviewId: '8f1ae49bf5f5a29088b950cedc6c434a',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_DEPARTMENT',
  },
  caption: '组织架构',
  codeName: 'hr_department_department_hierarchy_view',
  appDataEntityId: 'ibizodooapp.hr_department',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'department',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-组织架构（department）',
          id: '默认根节点（root）-组织架构（department）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          codeListId: 'ibizodooapp.hr__department_hierarchy',
          navAppViewId: 'ibizodooapp.hr_employee_multi_data_view',
          nodeType: 'department',
          appDataEntityId: 'ibizodooapp.hr_department',
          navigateContexts: [
            {
              key: 'HR_DEPARTMENT',
              value: '${srfkey}',
              name: 'HR_DEPARTMENT',
              id: 'hr_department',
            },
          ],
          treeNodeType: 'CODELIST',
          name: '组织架构',
          id: 'department',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.hr_department',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'ibizodooapp.hr_department',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.hr_department',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.hr_department',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.hr_department',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'department_chart',
      controlType: 'TREEVIEW',
      logicName: '组织架构',
      appDataEntityId: 'ibizodooapp.hr_department',
      controlParam: {
        id: 'tree',
      },
      modelId: 'f24b611e4d342a7ed7eeb61101a9b771',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'ibizodooapp.hr_department.department_chart',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.hr_department',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_DEPARTMENT',
      },
      caption: '组织架构',
      codeName: 'department_hierarchy_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.hr_department',
      controlParam: {},
      name: 'captionbar',
      id: 'department_hierarchy_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.hr_department',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '组织架构',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f3a363b8a0be9bb21298df558bd41077',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_departmentdepartment_hierarchy_view',
  id: 'ibizodooapp.hr_department_department_hierarchy_view',
};
