export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '85a639e08727d065f6bf45d771257d6c',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_LEAVE',
  },
  caption: '休假',
  codeName: 'hr_leave_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.hr_leave',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'FRONT',
          dataItemName: 'write_uid',
          excelCaption: '更新人',
          appCodeListId: 'ibizodooapp.sysoperator',
          appDEFieldId: 'write_uid',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.WRITE_UID',
          },
          caption: '更新人',
          codeName: 'write_uid',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'write_uid',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'write_date',
          excelCaption: '更新时间',
          appDEFieldId: 'write_date',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.WRITE_DATE',
          },
          caption: '更新时间',
          codeName: 'write_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'write_date',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'write_uid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'write_uid',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'write_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'write_date',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'manager_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'manager_id',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'message_main_attachment_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'message_main_attachment_id',
        },
        {
          appDEFieldId: 'company_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_id',
        },
        {
          appDEFieldId: 'holiday_status_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'holiday_status_id',
        },
        {
          appDEFieldId: 'department_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'department_id',
        },
        {
          appDEFieldId: 'employee_company_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'employee_company_id',
        },
        {
          appDEFieldId: 'employee_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'employee_id',
        },
        {
          appDEFieldId: 'overtime_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'overtime_id',
        },
        {
          appDEFieldId: 'second_approver_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'second_approver_id',
        },
        {
          appDEFieldId: 'first_approver_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'first_approver_id',
        },
        {
          appDEFieldId: 'resource_calendar_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'resource_calendar_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.hr_leave',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.hr_leave',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.hr_leave',
      controlParam: {
        id: 'grid',
      },
      modelId: 'ddd28b3e1058d34d78f4eb5a7e59dcc5',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.hr_leave.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.HR_LEAVE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.hr_leave',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'dd6725ad986b3c2bfff6401b827121e9',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.hr_leave.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.hr_leave',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_LEAVE',
      },
      caption: '休假',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.hr_leave',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.hr_leave',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '休假选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a31fb0e415aaf5388ba39aae464bacf6',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_leavePickupGridView',
  id: 'ibizodooapp.hr_leave_pickup_grid_view',
};
