export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '4cd24bec81538b630bce957190a81949',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_LEAVE',
  },
  caption: '休假',
  codeName: 'hr_leave_pickup_view',
  appDataEntityId: 'ibizodooapp.hr_leave',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.hr_leave_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.hr_leave',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_LEAVE',
      },
      caption: '休假',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.hr_leave',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.hr_leave',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '休假数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'fe2b85d950e84ecc628805d7d23e3bcb',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_leavePickupView',
  id: 'ibizodooapp.hr_leave_pickup_view',
};
