export default {
  gridRowActiveMode: 1,
  enableRowEdit: true,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: 'a74995f12c25614b9b1cf1672efb82af',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_SKILL',
  },
  caption: '技能',
  codeName: 'hr_skill_grid_view',
  appDataEntityId: 'ibizodooapp.hr_skill',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                  spacingLeft: 'OUTERLARGE',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'ibizodooapp.hr_skill_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.hr_skill_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'ibizodooapp.hr_skill_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.hr_skill_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '技能编辑视图',
        refAppViewId: 'ibizodooapp.hr_skill_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '技能编辑视图',
        refAppViewId: 'ibizodooapp.hr_skill_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'ASC',
        minorSortAppDEFieldId: 'sequence',
        orderValueAppDEFieldId: 'sequence',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.HR_SKILL.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'gridview_removeaction',
                  tooltipLanguageRes: {
                    lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                  },
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-remove',
                    glyph: 'xf00d@FontAwesome',
                  },
                  id: 'u578507e',
                },
              ],
              appDataEntityId: 'ibizodooapp.hr_skill',
              uniqueTag: 'hr_skill__Auto76188473',
              name: '技能实体操作栏',
              id: 'auto76188473',
            },
            aggMode: 'NONE',
            align: 'RIGHT',
            codeName: 'uagridcolumn1',
            columnType: 'UAGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'uagridcolumn1',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'skill_type_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'skill_type_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '名称',
            codeName: 'name',
            enableCond: 3,
            appDEFieldId: 'name',
            editor: {
              maxLength: 200,
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'name',
            },
            allowEmpty: true,
            id: 'name',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enableRowEdit: true,
        enableRowEditOrder: true,
        enableRowNew: true,
        singleSelect: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.hr_skill',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'ibizodooapp.hr_skill',
          id: 'fetch',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.hr_skill',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.hr_skill',
          id: 'load',
        },
        moveControlAction: {
          appDEMethodId: 'moveorder',
          appDataEntityId: 'ibizodooapp.hr_skill',
          id: 'move',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.hr_skill',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.hr_skill',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'ibizodooapp.hr_skill',
        controlLogics: [
          {
            eventNames: 'onMounted',
            logicTag: 'grid',
            logicType: 'SCRIPT',
            scriptCode:
              'var gridCtrl = view.getCtrl("GRID", "grid");\nif (gridCtrl) {\n  gridCtrl.state.rowEditOpen=true;\n}',
            triggerType: 'CTRLEVENT',
            id: 'logic_row_edit_open',
          },
        ],
        controlParam: {
          id: 'grid',
        },
        modelId: 'a412f206e0d56dbf993a5368c2dbcccb',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'ibizodooapp.hr_skill.main',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'newrow@hr_departure_reason',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '添加行',
            itemType: 'DEUIACTION',
            tooltip: '添加行',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '技能实体表格视图_工具栏',
        appDataEntityId: 'ibizodooapp.hr_skill',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '0cce22ae1c4d440e3148343de08d347b',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.HR_SKILL.DEFAULT.FORMPAGE.FORMPAGE1',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'default',
        controlType: 'SEARCHFORM',
        logicName: '默认搜索表单',
        appDataEntityId: 'ibizodooapp.hr_skill',
        controlParam: {
          id: 'searchform',
        },
        modelId: '14ab116bc7880dfd276fb4cdfed53459',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'ibizodooapp.hr_skill.default',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'ibizodooapp.hr_skill',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_SKILL',
        },
        caption: '技能',
        codeName: 'grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.hr_skill',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_captionbar',
      },
    ],
    codeName: 'auto94410878',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '表格视图布局_工具栏置底部',
    appDataEntityId: 'ibizodooapp.hr_skill',
    controlParam: {},
    modelId: 'a13eeb1a845a3db03d246911b7ccb2bf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto94410878',
  },
  title: '技能表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '792f1b42f1421873f382c1d7f3b74359',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_skillGridView',
  id: 'ibizodooapp.hr_skill_grid_view',
};
