export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '6c46a7c08fa88798bb2eefcc9b2e7770',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_WORK_LOCATION',
  },
  caption: '工作地点',
  codeName: 'hr_work_location_pickup_view',
  appDataEntityId: 'ibizodooapp.hr_work_location',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.hr_work_location_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.hr_work_location',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_WORK_LOCATION',
      },
      caption: '工作地点',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.hr_work_location',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.hr_work_location',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作地点数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9fe52ee0fb676d975d1f220c97d2b6ee',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_work_locationPickupView',
  id: 'ibizodooapp.hr_work_location_pickup_view',
};
