export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'MAINVIEW',
  deviewCodeName: 'main_view',
  deviewId: '067f4349faa67aeea6164b50ee6934d0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_ACTIONS_SERVER',
  },
  caption: '服务器操作',
  codeName: 'ir_actions_server_main_view',
  appDataEntityId: 'ibizodooapp.ir_actions_server',
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar2',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'u3e46fa4',
                    },
                  ],
                  name: '通用编辑页面删除界面行为组',
                  id: 'auto94538916',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ibizodooapp.ir_actions_server',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.ir_actions_server',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ibizodooapp.ir_actions_server',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.ir_actions_server',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.ir_actions_server',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.ir_actions_server',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.ir_actions_server',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      showMaxLength: true,
                      editorParams: {
                        ISAUTO: 'true',
                      },
                      editorType: 'TEXTAREA',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'state',
                    editor: {
                      appCodeListId:
                        'ibizodooapp.base__ir_actions_server_state',
                      editorType: 'RADIOBUTTONLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'state',
                    },
                    needCodeListConfig: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.STATE',
                    },
                    caption: '类型',
                    codeName: 'state',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'state',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 43,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'model_id',
                        editor: {
                          singleSelect: true,
                          appCodeListId: 'ibizodooapp.base__ir_model',
                          editorType: 'DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'model_id',
                        },
                        allowEmpty: true,
                        needCodeListConfig: true,
                        caption: '模型',
                        codeName: 'model_id',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'model_id',
                      },
                    ],
                    caption: '技术设置',
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'update_field_id',
                            editor: {
                              maxLength: 100,
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'update_field_id',
                            },
                            allowEmpty: true,
                            caption: '更新',
                            codeName: 'update_field_id',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 8,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'update_field_id',
                          },
                          {
                            rawItem: {
                              caption: 'to',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem1',
                            },
                            codeName: 'rawitem1',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              colLG: 1,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem1',
                          },
                          {
                            dataType: 21,
                            enableCond: 3,
                            itemHeight: 80,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'value',
                            editor: {
                              maxLength: 1048576,
                              showMaxLength: true,
                              editorHeight: 80,
                              editorParams: {
                                HEIGHT: '200',
                              },
                              editorType: 'TEXTAREA_10',
                              placeHolder: '设置值...',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'update_value',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.VALUE',
                            },
                            caption: '值',
                            codeName: 'update_value',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMENABLE',
                                relatedDetailNames: ['update_field_id'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'update_field_id',
                                    logicType: 'SINGLE',
                                    name: 'update_field_id值不为空(NotNil)',
                                    id: 'update_field_id值不为空(notnil)',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colLG: 8,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'update_value',
                          },
                        ],
                        codeName: 'object_write_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'object_write',
                                logicType: 'SINGLE',
                                id: 'state等于(=) object_write',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'object_write_grouppanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'activity_type_name',
                                editor: {
                                  enablePickupView: true,
                                  singleSelect: true,
                                  pickupAppViewId:
                                    'ibizodooapp.mail_activity_type_pickup_view',
                                  handlerType: 'PickupText',
                                  appDEACModeId: 'default',
                                  appDEDataSetId: 'fetch_default',
                                  appDataEntityId:
                                    'ibizodooapp.mail_activity_type',
                                  enableAC: true,
                                  forceSelection: true,
                                  showTrigger: true,
                                  valueItemName: 'activity_type_id',
                                  editorParams: {
                                    AC: 'TRUE',
                                    PICKUPVIEW: 'TRUE',
                                  },
                                  editorType: 'PICKER',
                                  editorItems: [
                                    {
                                      id: 'activity_type_id',
                                    },
                                  ],
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'activity_type_name',
                                },
                                caption: '活动类型',
                                codeName: 'activity_type_name',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                defdgroupLogics: [
                                  {
                                    logicCat: 'ITEMBLANK',
                                    relatedDetailNames: ['state'],
                                    groupOP: 'AND',
                                    defdlogics: [
                                      {
                                        condOP: 'NOTEQ',
                                        defdname: 'state',
                                        value: 'next_activity',
                                        logicType: 'SINGLE',
                                        id: 'state不等于(<>) next_activity',
                                      },
                                    ],
                                    logicType: 'GROUP',
                                  },
                                ],
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'activity_type_name',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'activity_summary',
                                editor: {
                                  maxLength: 250,
                                  editorType: 'TEXTBOX',
                                  placeHolder: '例如.讨论提案',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'activity_summary',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_SUMMARY',
                                },
                                caption: '标题',
                                codeName: 'activity_summary',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'activity_summary',
                              },
                            ],
                            codeName: 'grouppanel3',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colLG: 12,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'grouppanel3',
                          },
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 9,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'activity_date_deadline_range',
                                editor: {
                                  editorType: 'TEXTBOX',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'activity_date_deadline_range',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_DATE_DEADLINE_RANGE',
                                },
                                caption: '截止日期至',
                                codeName: 'activity_date_deadline_range',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 10,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'activity_date_deadline_range',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'NONE',
                                noPrivDisplayMode: 1,
                                appDEFieldId:
                                  'activity_date_deadline_range_type',
                                editor: {
                                  singleSelect: true,
                                  appCodeListId:
                                    'ibizodooapp.base__ir_actions_server_activity_date_deadline_range_type',
                                  editorType: 'DROPDOWNLIST',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'activity_date_deadline_range_type',
                                },
                                allowEmpty: true,
                                needCodeListConfig: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_DATE_DEADLINE_RANGE_TYPE',
                                },
                                caption: '到期类型',
                                codeName: 'activity_date_deadline_range_type',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 4,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                id: 'activity_date_deadline_range_type',
                              },
                              {
                                createDV: 'specific',
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'activity_user_type',
                                editor: {
                                  singleSelect: true,
                                  appCodeListId:
                                    'ibizodooapp.base__ir_actions_server_activity_user_type',
                                  editorType: 'DROPDOWNLIST',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'activity_user_type',
                                },
                                allowEmpty: true,
                                needCodeListConfig: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_USER_TYPE',
                                },
                                caption: '用户类型',
                                codeName: 'activity_user_type',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'activity_user_type',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'activity_user_name',
                                editor: {
                                  enablePickupView: true,
                                  singleSelect: true,
                                  pickupAppViewId:
                                    'ibizodooapp.res_users_pickup_view',
                                  handlerType: 'PickupText',
                                  appDEACModeId: 'default',
                                  appDEDataSetId: 'fetch_default',
                                  appDataEntityId: 'ibizodooapp.res_users',
                                  enableAC: true,
                                  forceSelection: true,
                                  showTrigger: true,
                                  valueItemName: 'activity_user_id',
                                  editorParams: {
                                    AC: 'TRUE',
                                    PICKUPVIEW: 'TRUE',
                                  },
                                  editorType: 'PICKER',
                                  editorItems: [
                                    {
                                      id: 'activity_user_id',
                                    },
                                  ],
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'activity_user_name',
                                },
                                caption: '负责人',
                                codeName: 'activity_user_name',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                defdgroupLogics: [
                                  {
                                    logicCat: 'ITEMBLANK',
                                    relatedDetailNames: ['state'],
                                    groupOP: 'AND',
                                    defdlogics: [
                                      {
                                        condOP: 'NOTEQ',
                                        defdname: 'state',
                                        value: 'next_activity',
                                        logicType: 'SINGLE',
                                        id: 'state不等于(<>) next_activity',
                                      },
                                    ],
                                    logicType: 'GROUP',
                                  },
                                ],
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'activity_user_name',
                              },
                            ],
                            codeName: 'grouppanel4',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colLG: 12,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'grouppanel4',
                          },
                          {
                            dataType: 21,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'activity_note',
                            editor: {
                              editorType: 'HTMLEDITOR',
                              placeHolder: '为您的活动添加说明...',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'activity_note',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_NOTE',
                            },
                            caption: '备注',
                            codeName: 'activity_note',
                            contentHeight: 200,
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            height: 200,
                            layoutPos: {
                              colMD: 24,
                              height: 200,
                              heightMode: 'PX',
                              layout: 'TABLE_24COL',
                            },
                            id: 'activity_note',
                          },
                        ],
                        codeName: 'next_activity_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'next_activity',
                                logicType: 'SINGLE',
                                id: 'state等于(=) next_activity',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'next_activity_grouppanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 100,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'template_name',
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              pickupAppViewId:
                                'ibizodooapp.mail_template_pickup_view',
                              handlerType: 'PickupText',
                              appDEACModeId: 'default',
                              appDEDataSetId: 'fetch_default',
                              appDataEntityId: 'ibizodooapp.mail_template',
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'template_id',
                              editorParams: {
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'template_id',
                                },
                              ],
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'template_name',
                            },
                            caption: 'EMail模板',
                            codeName: 'template_name',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMBLANK',
                                relatedDetailNames: ['state'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'NOTEQ',
                                    defdname: 'state',
                                    value: 'mail_post',
                                    logicType: 'SINGLE',
                                    id: 'state不等于(<>) mail_post',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'template_name',
                          },
                          {
                            createDV: 'comment',
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 100,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'mail_post_method',
                            editor: {
                              singleSelect: true,
                              appCodeListId:
                                'ibizodooapp.base__ir_actions_server_mail_post_method',
                              editorType: 'DROPDOWNLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'mail_post_method',
                            },
                            allowEmpty: true,
                            needCodeListConfig: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.IR_ACTIONS_SERVER.MAIL_POST_METHOD',
                            },
                            caption: '发送电子邮件',
                            codeName: 'mail_post_method',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'mail_post_method',
                          },
                          {
                            rawItem: {
                              caption:
                                '信息将以电子邮件的形式发送给模板的收件人，不会出现在信息历史记录中。模板的收件人，不会出现在信息历史记录中。',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem2',
                            },
                            codeName: 'rawitem2',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: ['mail_post_method'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'EQ',
                                    defdname: 'mail_post_method',
                                    value: 'email',
                                    logicType: 'SINGLE',
                                    id: 'mail_post_method等于(=) email',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem2',
                          },
                          {
                            rawItem: {
                              caption:
                                '信息将作为内部备注发布，内部用户可在信息历史记录中看到。内部用户可见。',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem3',
                            },
                            codeName: 'rawitem3',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: ['mail_post_method'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'EQ',
                                    defdname: 'mail_post_method',
                                    value: 'note',
                                    logicType: 'SINGLE',
                                    id: 'mail_post_method等于(=) note',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem3',
                          },
                          {
                            rawItem: {
                              caption:
                                ' 信息将作为记录上的信息发布、通知所有关注者。它将出现在信息历史记录中。',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem4',
                            },
                            codeName: 'rawitem4',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: ['mail_post_method'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'EQ',
                                    defdname: 'mail_post_method',
                                    value: 'comment',
                                    logicType: 'SINGLE',
                                    id: 'mail_post_method等于(=) comment',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem4',
                          },
                        ],
                        codeName: 'mail_post_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'mail_post',
                                logicType: 'SINGLE',
                                id: 'state等于(=) mail_post',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'mail_post_grouppanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            createDV: 'sms',
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'sms_method',
                            editor: {
                              singleSelect: true,
                              appCodeListId:
                                'ibizodooapp.base__ir_actions_server_sms_method',
                              editorType: 'DROPDOWNLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'sms_method',
                            },
                            allowEmpty: true,
                            needCodeListConfig: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.IR_ACTIONS_SERVER.SMS_METHOD',
                            },
                            caption: '发送短信为',
                            codeName: 'sms_method',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'sms_method',
                          },
                          {
                            rawItem: {
                              caption:
                                '信息将以短信形式发送给模板的收件人，不会出现在信息历史记录中。不会出现在信息历史记录中。',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem5',
                            },
                            codeName: 'rawitem5',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: ['sms_method'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'EQ',
                                    defdname: 'sms_method',
                                    value: 'sms',
                                    logicType: 'SINGLE',
                                    id: 'sms_method等于(=) sms',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem5',
                          },
                          {
                            rawItem: {
                              caption:
                                '短信不会被发送，只会作为内部备注发布在信息历史记录中。内部备注。',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem6',
                            },
                            codeName: 'rawitem6',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: ['sms_method'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'EQ',
                                    defdname: 'sms_method',
                                    value: 'note',
                                    logicType: 'SINGLE',
                                    id: 'sms_method等于(=) note',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem6',
                          },
                          {
                            rawItem: {
                              caption:
                                '短信将以短信的形式发送给模板的收件人，同时也会作为内部备注发布。同时也会作为内部备注发布到消息历史记录中。 作为内部备注发布在信息历史记录中。',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem7',
                            },
                            codeName: 'rawitem7',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: ['sms_method'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'EQ',
                                    defdname: 'sms_method',
                                    value: 'comment',
                                    logicType: 'SINGLE',
                                    id: 'sms_method等于(=) comment',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem7',
                          },
                        ],
                        codeName: 'sms_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'sms',
                                logicType: 'SINGLE',
                                id: 'state等于(=) sms',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'sms_grouppanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        codeName: 'followers_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'followers',
                                logicType: 'SINGLE',
                                id: 'state等于(=) followers',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'followers_grouppanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        codeName: 'remove_followers_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'remove_followers',
                                logicType: 'SINGLE',
                                id: 'state等于(=) remove_followers',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'remove_followers_grouppanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'crud_model_id',
                            editor: {
                              singleSelect: true,
                              appCodeListId: 'ibizodooapp.base__ir_model',
                              editorType: 'DROPDOWNLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'crud_model_id',
                            },
                            needCodeListConfig: true,
                            caption: '创建记录',
                            codeName: 'crud_model_id',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMBLANK',
                                relatedDetailNames: ['state'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'NOTEQ',
                                    defdname: 'state',
                                    value: 'object_create',
                                    logicType: 'SINGLE',
                                    id: 'state不等于(<>) object_create',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'crud_model_id',
                          },
                          {
                            dataType: 21,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'value',
                            editor: {
                              maxLength: 1048576,
                              editorType: 'TEXTBOX',
                              placeHolder: '例如：后续行动',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'create_value',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.VALUE',
                            },
                            caption: '名称',
                            codeName: 'create_value',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'create_value',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'link_field_id',
                            editor: {
                              maxLength: 100,
                              editorType: 'TEXTBOX',
                              placeHolder: '选择要将记录链接到的字段',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'link_field_id',
                            },
                            allowEmpty: true,
                            caption: '链接字段',
                            codeName: 'link_field_id',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'link_field_id',
                          },
                        ],
                        codeName: 'object_create_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'object_create',
                                logicType: 'SINGLE',
                                id: 'state等于(=) object_create',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'object_create_grouppanel',
                      },
                      {
                        deformTabPages: [
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 21,
                                enableCond: 3,
                                itemHeight: 80,
                                labelPos: 'NONE',
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'code',
                                editor: {
                                  maxLength: 1048576,
                                  showMaxLength: true,
                                  editorHeight: 80,
                                  editorParams: {
                                    HEIGHT: '200',
                                  },
                                  editorType: 'TEXTAREA_10',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'code',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.CODE',
                                },
                                caption: 'Python 代码',
                                codeName: 'code',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                id: 'code',
                              },
                            ],
                            caption: '代码',
                            codeName: 'tabpage1',
                            detailStyle: 'DEFAULT',
                            detailType: 'TABPAGE',
                            showCaption: true,
                            id: 'tabpage1',
                          },
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            caption: '帮助',
                            codeName: 'tabpage2',
                            detailStyle: 'DEFAULT',
                            detailType: 'TABPAGE',
                            showCaption: true,
                            id: 'tabpage2',
                          },
                        ],
                        codeName: 'code_tabpanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'code',
                                logicType: 'SINGLE',
                                id: 'state等于(=) code',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'code_tabpanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'webhook_url',
                            editor: {
                              maxLength: 250,
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'webhook_url',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.IR_ACTIONS_SERVER.WEBHOOK_URL',
                            },
                            caption: 'url',
                            codeName: 'webhook_url',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'webhook_url',
                          },
                        ],
                        codeName: 'webhook_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'webhook',
                                logicType: 'SINGLE',
                                id: 'state等于(=) webhook',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'webhook_grouppanel',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        codeName: 'multi_grouppanel',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['state'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'state',
                                value: 'multi',
                                logicType: 'SINGLE',
                                id: 'state等于(=) multi',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'multi_grouppanel',
                      },
                    ],
                    caption: '动作详情',
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel2',
                  },
                ],
                caption: '服务器动作基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'activity_type_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'activity_type_id',
                },
                allowEmpty: true,
                hidden: true,
                caption: '活动类型',
                codeName: 'activity_type_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'activity_type_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'activity_user_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'activity_user_id',
                },
                allowEmpty: true,
                hidden: true,
                caption: '负责人',
                codeName: 'activity_user_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'activity_user_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'template_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'template_id',
                },
                allowEmpty: true,
                hidden: true,
                caption: 'EMail模板',
                codeName: 'template_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'template_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'FORM',
        logicName: '主编辑表单',
        appDataEntityId: 'ibizodooapp.ir_actions_server',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: 'e6d89a0a8cf9d169c4ac4cac6a8e61bc',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ibizodooapp.ir_actions_server.main',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ibizodooapp.ir_actions_server',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_view_toolbar1',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ibizodooapp.ir_actions_server',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.IR_ACTIONS_SERVER',
        },
        caption: '服务器操作',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.ir_actions_server',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'main_view_layout1',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new_没有评论区',
    appDataEntityId: 'ibizodooapp.ir_actions_server',
    controlLogics: [
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId); ',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", async  (state, isTrusted )=> {\n    console.log("");\n    const data = view.getController("form").getData()[0];\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\n});\n\nconst topContext = view.context;\nconst appEntityId = view.model.appDataEntityId;\nconst entityName = appEntityId.split(\'.\').pop();\nconst bExist = topContext[entityName];\nconst drbar = view.getCtrl("DRBAR", "drbar");\nif(!bExist){\n    drbar.disabled({ mode: \'BLANK\' })\n    //  drbar.disabled({ mode: \'MASK\' })\n\n}\n\n',
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\n   if (name === 'drbar') {\n      const topContext = view.context;\n      const appEntityId = view.model.appDataEntityId;\n      const entityName = appEntityId.split('.').pop();\n      const bExist = topContext[entityName];\n      if(!bExist){\n         ctrl?.disableCounter()\n      }\n   }\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '3ea3e353274bcb7a2bf0fee66c7d91cf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout1',
  },
  title: '服务器动作',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '53e62772429048dab55def74039adab7',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_actions_servermain_view',
  id: 'ibizodooapp.ir_actions_server_main_view',
};
