export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '7c4c71906390727254c614245c875094',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_CRON',
  },
  caption: '计划的操作',
  codeName: 'ir_cron_pickup_view',
  appDataEntityId: 'ibizodooapp.ir_cron',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.ir_cron_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.ir_cron',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_CRON',
      },
      caption: '计划的操作',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.ir_cron',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.ir_cron',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '计划的操作数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '310cba957ec9119061f1347d4cb20742',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_cronPickupView',
  id: 'ibizodooapp.ir_cron_pickup_view',
};
