export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '99c54393cba85d61e2ba9de9cd121369',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_CRON',
  },
  caption: '计划的操作',
  codeName: 'ir_cron_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.ir_cron',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'priority',
          excelCaption: '优先级',
          appDEFieldId: 'priority',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_CRON.PRIORITY',
          },
          caption: '优先级',
          codeName: 'priority',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 120,
          widthUnit: 'PX',
          enableSort: true,
          id: 'priority',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'cron_name',
          excelCaption: '名称',
          appDEFieldId: 'cron_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_CRON.CRON_NAME',
          },
          caption: '名称',
          codeName: 'cron_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 1,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'cron_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'model_id',
          excelCaption: '模型',
          appCodeListId: 'ibizodooapp.base__ir_model',
          appDEFieldId: 'model_id',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '模型',
          codeName: 'model_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'model_id',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'nextcall',
          excelCaption: '下一次执行日期',
          appDEFieldId: 'nextcall',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_CRON.NEXTCALL',
          },
          caption: '下一次执行日期',
          codeName: 'nextcall',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'nextcall',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'interval_number',
          excelCaption: '间隔数值',
          appDEFieldId: 'interval_number',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_CRON.INTERVAL_NUMBER',
          },
          caption: '间隔数值',
          codeName: 'interval_number',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'interval_number',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'interval_type',
          excelCaption: '间隔单位',
          appCodeListId: 'ibizodooapp.base__ir_cron_interval_type',
          appDEFieldId: 'interval_type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_CRON.INTERVAL_TYPE',
          },
          caption: '间隔单位',
          codeName: 'interval_type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'interval_type',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'active',
          excelCaption: '有效',
          appCodeListId: 'ibizodooapp.yesno',
          appDEFieldId: 'active',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_CRON.ACTIVE',
          },
          caption: '有效',
          codeName: 'active',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'active',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'priority',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'priority',
        },
        {
          appDEFieldId: 'cron_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'cron_name',
        },
        {
          appDEFieldId: 'model_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'model_id',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'nextcall',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'nextcall',
        },
        {
          appDEFieldId: 'interval_number',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'interval_number',
        },
        {
          appDEFieldId: 'interval_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'interval_type',
        },
        {
          appDEFieldId: 'active',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'active',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'ir_actions_server_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'ir_actions_server_id',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'cron_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '有效',
          codeName: 'active',
          enableCond: 3,
          appDEFieldId: 'active',
          editor: {
            editorType: 'CHECKBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'active',
          },
          allowEmpty: true,
          id: 'active',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.ir_cron',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.ir_cron',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.ir_cron',
      controlParam: {
        id: 'grid',
      },
      modelId: '66f02f0e06606eca1c2b64908f4698b4',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.ir_cron.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.IR_CRON.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.ir_cron',
      controlParam: {
        id: 'searchform',
      },
      modelId: '34358fa524f6363c182d7bef1086f282',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.ir_cron.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.ir_cron',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_CRON',
      },
      caption: '计划的操作',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.ir_cron',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.ir_cron',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '计划的操作选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '2ec1bd3822c36191861450391401951c',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_cronPickupGridView',
  id: 'ibizodooapp.ir_cron_pickup_grid_view',
};
