export default {
  gridRowActiveMode: 1,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: '883a5b7f98f80a38a83e3ffcc789c201',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_MODULE_MODULE',
  },
  caption: '模块',
  codeName: 'ir_module_module_grid_view',
  appDataEntityId: 'ibizodooapp.ir_module_module',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'ibizodooapp.ir_module_module_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.ir_module_module_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'ibizodooapp.ir_module_module_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.ir_module_module_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '模块编辑视图',
      refAppViewId: 'ibizodooapp.ir_module_module_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '模块编辑视图',
      refAppViewId: 'ibizodooapp.ir_module_module_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'app_id',
          excelCaption: '应用标识',
          appDEFieldId: 'app_id',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '应用标识',
          codeName: 'app_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'app_id',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'display_name',
          excelCaption: '显示名称',
          appDEFieldId: 'display_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '显示名称',
          codeName: 'display_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 1,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'display_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'url',
          excelCaption: 'URL',
          appDEFieldId: 'url',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.URL',
          },
          caption: 'URL',
          codeName: 'url',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'url',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'state',
          excelCaption: '状态',
          appCodeListId: 'ibizodooapp.base__ir_module_module_state',
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.STATE',
          },
          caption: '状态',
          codeName: 'state',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'state',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'order',
          excelCaption: '排序值',
          appDEFieldId: 'order',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '排序值',
          codeName: 'order',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'order',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'res_code',
          excelCaption: '资源标识',
          appDEFieldId: 'res_code',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '资源标识',
          codeName: 'res_code',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'res_code',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'app_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'app_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'display_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'display_name',
        },
        {
          appDEFieldId: 'url',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'url',
        },
        {
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'state',
        },
        {
          appDEFieldId: 'order',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'order',
        },
        {
          appDEFieldId: 'res_code',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'res_code',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'category_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.ir_module_module',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.ir_module_module',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main1',
      controlType: 'GRID',
      logicName: '模块主表格',
      appDataEntityId: 'ibizodooapp.ir_module_module',
      controlParam: {
        id: 'grid',
      },
      modelId: '6a11e5b6cad23ed9f46565e4ec77a1d8',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.ir_module_module.main1',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.IR_MODULE_MODULE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.ir_module_module',
      controlParam: {
        id: 'searchform',
      },
      modelId: '5336c58b54e0f8f87c7e608f6839f666',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.ir_module_module.default',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem5',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_editaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EDIT',
          },
          caption: '编辑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-edit',
            glyph: 'xf044@FontAwesome',
          },
          tooltip: '编辑',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EDIT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_copyaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.COPY',
          },
          caption: '拷贝',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-copy',
            glyph: 'xf0c5@FontAwesome',
          },
          tooltip: '拷贝',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.COPY',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem15',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_removeaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.REMOVE',
          },
          caption: '删除',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.REMOVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem8',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem16',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_exportaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EXPORT',
          },
          caption: '导出',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-excel-o',
            glyph: 'xf1c3@FontAwesome',
          },
          tooltip: '导出',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EXPORT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem3',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem17',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_exportxmlaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'MENUITEM.CAPTION.*.EXPORTSRF',
              },
              caption: '导出数据模型',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-download',
                glyph: 'xf019@FontAwesome',
              },
              tooltip: '导出数据模型',
              showCaption: true,
              showIcon: true,
              id: 'tbitem24',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_importbar',
              valid: true,
              caption: '数据导入',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-upload',
                glyph: 'xf093@FontAwesome',
              },
              tooltip: '数据导入',
              showCaption: true,
              showIcon: true,
              id: 'tbitem25',
            },
          ],
          valid: true,
          caption: '其它',
          itemType: 'ITEMS',
          tooltip: '其它',
          showCaption: true,
          showIcon: true,
          id: 'tbitem20',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem21',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_searchbar',
          enableToggleMode: true,
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.FILTER',
          },
          caption: '过滤',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-filter',
            glyph: 'xf0b0@FontAwesome',
          },
          tooltip: '过滤',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.FILTER',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem10',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_helpaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.HELP',
          },
          caption: '帮助',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-question',
            glyph: 'xf128@FontAwesome',
          },
          tooltip: '帮助',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.HELP',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem4',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认表格界面）',
      appDataEntityId: 'ibizodooapp.ir_module_module',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'ec6fbb681f5e3e6783c2af57e5eefaaa',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.ir_module_module',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_MODULE_MODULE',
      },
      caption: '模块',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.ir_module_module',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.ir_module_module',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '模块表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'da9dfbec69a86da8db2a5030fe2e9bb4',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_module_moduleGridView',
  id: 'ibizodooapp.ir_module_module_grid_view',
};
