export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '1db079e23a7cd58c47567b4f3ac489f7',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_MODULE_CATEGORY',
  },
  caption: '应用',
  codeName: 'ir_module_category_pickup_view',
  appDataEntityId: 'ibizodooapp.ir_module_category',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.ir_module_category_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.ir_module_category',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_MODULE_CATEGORY',
      },
      caption: '应用',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.ir_module_category',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.ir_module_category',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '应用数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f835249b47de06111e8eddb900cf91dd',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_module_categoryPickupView',
  id: 'ibizodooapp.ir_module_category_pickup_view',
};
