export default {
  funcViewMode: 'MPICKUPVIEW',
  openMode: 'POPUPMODAL',
  deviewCodeName: 'MPickupView',
  deviewId: 'e8b85ef70541215ee84449fa1cdcd70d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_RULE',
  },
  caption: '规则',
  codeName: 'ir_rule_m_pickup_view',
  height: 700,
  appDataEntityId: 'ibizodooapp.ir_rule',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'MPickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.ir_rule',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.ir_rule',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.ir_rule',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.ir_rule',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.ir_rule',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'ibizodooapp.ir_rule',
      controlParam: {
        id: 'simplelist',
      },
      modelId: '5a6246936731b918a8e0e1434f26e1ae',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'ibizodooapp.ir_rule.simplelist',
    },
    {
      embeddedAppDEViewId: 'ibizodooapp.ir_rule_pickup_grid_view',
      codeName: 'm_pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.ir_rule',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'm_pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_RULE',
      },
      caption: '规则',
      codeName: 'm_pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.ir_rule',
      controlParam: {},
      name: 'captionbar',
      id: 'm_pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.ir_rule',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '规则数据多项选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW',
  width: 1300,
  enableDP: true,
  showCaptionBar: false,
  modelId: '910513cbad8489cb444ca55f59029e6f',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_ruleMPickupView',
  id: 'ibizodooapp.ir_rule_m_pickup_view',
};
