export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '7d4f35769c7b92bbbfc4f026a8b01a4f',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_RULE',
  },
  caption: '规则',
  codeName: 'ir_rule_pickup_view',
  appDataEntityId: 'ibizodooapp.ir_rule',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.ir_rule_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.ir_rule',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_RULE',
      },
      caption: '规则',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.ir_rule',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.ir_rule',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '规则数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c47041d2c8c97416d29d3c3eee8209f9',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_rulePickupView',
  id: 'ibizodooapp.ir_rule_pickup_view',
};
