export default {
  funcViewMode: 'MPICKUPVIEW',
  openMode: 'POPUPMODAL',
  deviewCodeName: 'MPickupView',
  deviewId: 'e422348327b2cca1824544ed8eb871b3',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_UNIRES',
  },
  caption: '统一资源',
  codeName: 'ir_unires_m_pickup_view',
  height: 700,
  appDataEntityId: 'ibizodooapp.ir_unires',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'MPickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.ir_unires',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'ibizodooapp.ir_unires',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.ir_unires',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.ir_unires',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.ir_unires',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'ibizodooapp.ir_unires',
      controlParam: {
        id: 'simplelist',
      },
      modelId: '5f3f5dbfdf071d8b173960d694a44da4',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'ibizodooapp.ir_unires.simplelist',
    },
    {
      embeddedAppDEViewId: 'ibizodooapp.ir_unires_pickup_grid_view',
      codeName: 'm_pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.ir_unires',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'm_pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_UNIRES',
      },
      caption: '统一资源',
      codeName: 'm_pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.ir_unires',
      controlParam: {},
      name: 'captionbar',
      id: 'm_pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.ir_unires',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '统一资源数据多项选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW',
  width: 1300,
  enableDP: true,
  showCaptionBar: false,
  modelId: '5035f958fc521ea25cd94b45245cf529',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_uniresMPickupView',
  id: 'ibizodooapp.ir_unires_m_pickup_view',
};
