export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: 'b7af4d709cf2d5f22c99f121c39a90a2',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_MESSAGE',
  },
  caption: '消息',
  codeName: 'mail_message_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.mail_message',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'date',
          excelCaption: '日期',
          appDEFieldId: 'date',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_MESSAGE.DATE',
          },
          caption: '日期',
          codeName: 'date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'subject',
          excelCaption: '主旨',
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_MESSAGE.SUBJECT',
          },
          caption: '主旨',
          codeName: 'subject',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'subject',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'author_name',
          excelCaption: '作者',
          appDEFieldId: 'author_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '作者',
          codeName: 'author_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'author_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'model',
          excelCaption: '相关单据模型',
          appDEFieldId: 'model',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MODEL',
          },
          caption: '相关单据模型',
          codeName: 'model',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'model',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'res_id',
          excelCaption: '相关单据ID',
          appDEFieldId: 'res_id',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RES_ID',
          },
          caption: '相关单据ID',
          codeName: 'res_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'res_id',
        },
      ],
      degridDataItems: [
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'date',
        },
        {
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'subject',
        },
        {
          appDEFieldId: 'author_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'author_name',
        },
        {
          appDEFieldId: 'model',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'model',
        },
        {
          appDEFieldId: 'res_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'res_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'record_company_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'record_company_id',
        },
        {
          appDEFieldId: 'subtype_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'subtype_id',
        },
        {
          appDEFieldId: 'record_alias_domain_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'record_alias_domain_id',
        },
        {
          appDEFieldId: 'mail_activity_type_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'mail_activity_type_id',
        },
        {
          appDEFieldId: 'author_guest_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'author_guest_id',
        },
        {
          appDEFieldId: 'author_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'author_id',
        },
        {
          appDEFieldId: 'record_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'grid',
      },
      modelId: '5144a36e6e7382b6f25bddbb8dbf3d07',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.mail_message.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 21,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'body',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '搜索',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_body_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.MAIL_MESSAGE.N_BODY_LIKE',
              },
              caption: '内容(%)',
              codeName: 'n_body_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'n_body_like',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.MAIL_MESSAGE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'searchform',
      },
      modelId: '438ca85e1ff6f7dddbc7607a06f3e91d',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.mail_message.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MAIL_MESSAGE',
      },
      caption: '消息',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_message',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '消息选择表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.PICKUPGRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '31acbeb19761ce71ccec960b3b97435e',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_messagePickupGridView',
  id: 'ibizodooapp.mail_message_pickup_grid_view',
};
