export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'MAINVIEW',
  deviewCodeName: 'main_view',
  deviewId: 'd7db7acce82a98cf0a42813e70b173b0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ALIAS',
  },
  caption: '别名',
  codeName: 'mail_alias_main_view',
  appDataEntityId: 'ibizodooapp.mail_alias',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar2',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'u3e46fa4',
                    },
                  ],
                  name: '通用编辑页面删除界面行为组',
                  id: 'auto94538916',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'update',
        },
        deformItemUpdates: [
          {
            codeName: 'compute_alias_full_name',
            defiupdateDetails: [
              {
                id: 'alias_full_name',
              },
            ],
            scriptCode:
              'if (data.alias_domain_id && data.alias_name) {\r\n    data.alias_full_name = data.alias_name + "@" + data.alias_domain_name;\r\n} else if (data.alias_name) {\r\n    data.alias_full_name = data.alias_name;\r\n} else {\r\n    data.alias_full_name = null;\r\n}',
            customCode: true,
            showBusyIndicator: true,
            id: 'compute_alias_full_name',
          },
        ],
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_name',
                    deformItemUpdateId: 'compute_alias_full_name',
                    editor: {
                      maxLength: 500,
                      cssStyle: 'font-weight: var(--ibiz-font-weight-bold);',
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_NAME',
                    },
                    caption: '别名',
                    codeName: 'alias_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'alias_name',
                  },
                  {
                    rawItem: {
                      content: '<p><strong>@</strong></p>',
                      contentType: 'HTML',
                      id: 'rawitem1',
                    },
                    codeName: 'rawitem1',
                    detailStyle: 'DEFAULT',
                    detailType: 'RAWITEM',
                    layoutPos: {
                      colLG: 1,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'rawitem1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_domain_name',
                    deformItemUpdateId: 'compute_alias_full_name',
                    editor: {
                      enablePickupView: true,
                      singleSelect: true,
                      pickupAppViewId:
                        'ibizodooapp.mail_alias_domain_pickup_view',
                      handlerType: 'PickupText',
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'ibizodooapp.mail_alias_domain',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'alias_domain_id',
                      cssStyle: 'font-weight: var(--ibiz-font-weight-bold);',
                      editorParams: {
                        AC: 'TRUE',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'PICKER',
                      editorItems: [
                        {
                          id: 'alias_domain_id',
                        },
                      ],
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_domain_name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DOMAIN_ID',
                    },
                    caption: '别名域名称',
                    codeName: 'alias_domain_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 6,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'alias_domain_name',
                  },
                ],
                codeName: 'grouppanel2',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 20,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel2',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_status',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId:
                        'ibizodooapp.mail__mail_alias_alias_status',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_status',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_STATUS',
                    },
                    caption: '别名状态',
                    codeName: 'alias_status',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'alias_status',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 4,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_model_id',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'ibizodooapp.base__ir_model',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_model_id',
                    },
                    needCodeListConfig: true,
                    caption: '模型别名',
                    codeName: 'alias_model_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'alias_model_id',
                  },
                  {
                    dataType: 9,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_force_thread_id',
                    editor: {
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_force_thread_id',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_FORCE_THREAD_ID',
                    },
                    caption: '记录线索ID',
                    codeName: 'alias_force_thread_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'alias_force_thread_id',
                  },
                  {
                    dataType: 21,
                    enableCond: 3,
                    itemHeight: 80,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_defaults',
                    editor: {
                      maxLength: 1048576,
                      showMaxLength: true,
                      editorHeight: 80,
                      editorParams: {
                        HEIGHT: '200',
                      },
                      editorType: 'TEXTAREA_10',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_defaults',
                    },
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DEFAULTS',
                    },
                    caption: '默认值',
                    codeName: 'alias_defaults',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'alias_defaults',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_contact',
                    editor: {
                      singleSelect: true,
                      appCodeListId:
                        'ibizodooapp.mail__mail_alias_alias_contact',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_contact',
                    },
                    needCodeListConfig: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_CONTACT',
                    },
                    caption: '别名授权于',
                    codeName: 'alias_contact',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'alias_contact',
                  },
                  {
                    dataType: 9,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 166,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_incoming_local',
                    editor: {
                      editorType: 'CHECKBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_incoming_local',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_INCOMING_LOCAL',
                    },
                    caption: '收件时检测本地的别名域',
                    codeName: 'alias_incoming_local',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'alias_incoming_local',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_parent_model_id',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'ibizodooapp.base__ir_model',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_parent_model_id',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    caption: '上级模型',
                    codeName: 'alias_parent_model_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'alias_parent_model_id',
                  },
                  {
                    dataType: 9,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_parent_thread_id',
                    editor: {
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_parent_thread_id',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_PARENT_THREAD_ID',
                    },
                    caption: '上级记录ID',
                    codeName: 'alias_parent_thread_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'alias_parent_thread_id',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'alias_full_name',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'alias_full_name',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_FULL_NAME',
                    },
                    caption: '别名电子邮件',
                    codeName: 'alias_full_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'alias_full_name',
                  },
                ],
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFORM.MAIL_ALIAS.MAIN.GROUPPANEL.GROUP1',
                },
                caption: 'EMail别名基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'alias_domain_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'alias_domain_id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DOMAIN_ID',
                },
                caption: '别名域',
                codeName: 'alias_domain_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'alias_domain_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MAIL_ALIAS.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.MAIL_ALIAS.MAIN.FORMPAGE.FORMPAGE1',
            },
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'FORM',
        logicName: '主编辑表单',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: 'c231336a084710e6d8b022b7952083ad',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ibizodooapp.mail_alias.main',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_view_toolbar1',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MAIL_ALIAS',
        },
        caption: '别名',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'main_view_layout1',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new_没有评论区',
    appDataEntityId: 'ibizodooapp.mail_alias',
    controlLogics: [
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId); ',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", async  (state, isTrusted )=> {\n    console.log("");\n    const data = view.getController("form").getData()[0];\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\n});\n\nconst topContext = view.context;\nconst appEntityId = view.model.appDataEntityId;\nconst entityName = appEntityId.split(\'.\').pop();\nconst bExist = topContext[entityName];\nconst drbar = view.getCtrl("DRBAR", "drbar");\nif(!bExist){\n    drbar.disabled({ mode: \'BLANK\' })\n    //  drbar.disabled({ mode: \'MASK\' })\n\n}\n\n',
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\n   if (name === 'drbar') {\n      const topContext = view.context;\n      const appEntityId = view.model.appDataEntityId;\n      const entityName = appEntityId.split('.').pop();\n      const bExist = topContext[entityName];\n      if(!bExist){\n         ctrl?.disableCounter()\n      }\n   }\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '3ea3e353274bcb7a2bf0fee66c7d91cf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout1',
  },
  title: 'EMail别名实体',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '3848588e2eec33375c48f07951bd6321',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_aliasmain_view',
  id: 'ibizodooapp.mail_alias_main_view',
};
