export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '06962eb8c0e524fac0dfbfd775e9e18b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ACTIVITY_TYPE',
  },
  caption: '活动类型',
  codeName: 'mail_activity_type_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.mail_activity_type',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'DESC',
      minorSortAppDEFieldId: 'write_date',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 1,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'summary',
          excelCaption: '默认摘要',
          appDEFieldId: 'summary',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.SUMMARY',
          },
          caption: '默认摘要',
          codeName: 'summary',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'summary',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'delay_label',
          excelCaption: '计划于',
          appDEFieldId: 'delay_label',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_LABEL',
          },
          caption: '计划于',
          codeName: 'delay_label',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          id: 'delay_label',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'delay_from',
          excelCaption: '类型',
          appCodeListId: 'ibizodooapp.mail__mail_activity_type_delay_from',
          appDEFieldId: 'delay_from',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_FROM',
          },
          caption: '类型',
          codeName: 'delay_from',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'delay_from',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'icon',
          excelCaption: '图标',
          appDEFieldId: 'icon',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.ICON',
          },
          caption: '图标',
          codeName: 'icon',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'icon',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'summary',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'summary',
        },
        {
          appDEFieldId: 'delay_label',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'delay_label',
        },
        {
          appDEFieldId: 'delay_from',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'delay_from',
        },
        {
          appDEFieldId: 'icon',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'icon',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'triggered_next_type_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'triggered_next_type_id',
        },
        {
          appDEFieldId: 'default_user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'default_user_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        id: 'fetch',
      },
      moveControlAction: {
        appDEMethodId: 'move_order',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        id: 'move',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.mail_activity_type',
      controlParam: {
        id: 'grid',
      },
      modelId: '2efee27adab7ec61e9b4d1cab47e7d62',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.mail_activity_type.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.MAIL_ACTIVITY_TYPE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.mail_activity_type',
      controlParam: {
        id: 'searchform',
      },
      modelId: '4c7e91702c0d3ac3ec1ed893a1d96a9b',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.mail_activity_type.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.mail_activity_type',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MAIL_ACTIVITY_TYPE',
      },
      caption: '活动类型',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_activity_type',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_activity_type',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '活动类型选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '0b956f081d067b3ff36dcb28756d8d9f',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_activity_typePickupGridView',
  id: 'ibizodooapp.mail_activity_type_pickup_grid_view',
};
