export default {
  mdctrlActiveMode: 1,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'pinned_list_view',
  deviewId: 'e662b97d130e7b19652e6d545b05a87a',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.MAIL_MESSAGE.PINNED_LIST_VIEW',
  },
  caption: '置顶消息',
  codeName: 'mail_message_pinned_list_view',
  appDataEntityId: 'ibizodooapp.mail_message',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'ibizodooapp.mail_message_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.mail_message_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'ibizodooapp.mail_message_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.mail_message_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'SRFREADONLY',
      value: 'true',
      name: 'SRFREADONLY',
      id: 'srfreadonly',
    },
    {
      key: 'MAIL_THREAD',
      value: 'mail_thread',
      name: 'MAIL_THREAD',
      id: 'mail_thread',
    },
  ],
  appViewRefs: [
    {
      realTitle: '消息编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.EDITVIEW',
      },
      refAppViewId: 'ibizodooapp.mail_message_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '消息编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.EDITVIEW',
      },
      refAppViewId: 'ibizodooapp.mail_message_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 21,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'body',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '搜索',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_body_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.MAIL_MESSAGE.N_BODY_LIKE',
              },
              caption: '内容(%)',
              codeName: 'n_body_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'n_body_like',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.MAIL_MESSAGE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'searchform',
      },
      modelId: '438ca85e1ff6f7dddbc7607a06f3e91d',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.mail_message.default',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'ibizodooapp.sysoperator',
                          editorStyle: 'PERSONNEL_INFO',
                          editorType: 'SPAN',
                          sysPFPluginId: 'personnel_info',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'user_name',
                        },
                        viewFieldName: 'CREATE_UID',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'user_name',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'time',
                        },
                        viewFieldName: 'CREATE_DATE',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        cssStyle:
                          'line-height: var(--ibiz-height-control-default);',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingLeft: 'OUTERMEDIUM',
                        },
                        sysCss: {
                          cssName: 'transition-time',
                        },
                        id: 'time',
                      },
                      {
                        editor: {
                          editorType: 'HIDDEN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_text_dynamic3',
                        },
                        viewFieldName: 'ID',
                        allowEmpty: true,
                        hidden: true,
                        caption: '文本(动态)',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'field_text_dynamic3',
                      },
                      {
                        editor: {
                          editorType: 'HIDDEN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'pid',
                        },
                        viewFieldName: 'PID',
                        allowEmpty: true,
                        hidden: true,
                        caption: '文本(动态)',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'pid',
                      },
                      {
                        editor: {
                          editorType: 'HIDDEN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'id',
                        },
                        viewFieldName: 'ID',
                        allowEmpty: true,
                        hidden: true,
                        caption: '文本(动态)',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'id',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container1',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        buttonListType: 'UIACTIONGROUP',
                        uiactionGroup: {
                          uiactionGroupDetails: [
                            {
                              actionLevel: 100,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              caption: '取消置顶',
                              detailType: 'DEUIACTION',
                              uiactionId: 'unpin@mail_message',
                              visibleScriptCode: 'data.pinned_at!=null',
                              showCaption: true,
                              showIcon: true,
                              sysImage: {
                                cssClass: 'fa fa-thumb-tack',
                                glyph: 'xf08d@FontAwesome',
                              },
                              id: 'u4dba5bd',
                            },
                            {
                              actionLevel: 100,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              caption: '置顶',
                              detailType: 'DEUIACTION',
                              uiactionId: 'pin@mail_message',
                              visibleScriptCode: 'data.pinned_at==null',
                              showCaption: true,
                              showIcon: true,
                              sysImage: {
                                cssClass: 'fa fa-thumb-tack',
                                glyph: 'xf08d@FontAwesome',
                              },
                              id: 'uc963833',
                            },
                            {
                              actionLevel: 100,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              caption: '收藏',
                              detailType: 'DEUIACTION',
                              uiactionId: 'add_favorite@mail_message',
                              tooltip: '收藏',
                              visibleScriptCode: 'data.is_favorite!=1',
                              showCaption: true,
                              showIcon: true,
                              sysImage: {
                                rawContent:
                                  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" class="design-iconfont" width="16" height="16">\n  <path d="M9.54013,6.48742551 L8,3.36677551 L6.45987,6.48742551 L3.01604,6.98784551 L5.50802,9.41692551 L4.91975,12.8468255 L8,11.2274255 L11.08025,12.8468255 L10.49195,9.41692551 L12.98395,6.98784551 L9.54013,6.48742551 Z M14.53135,6.20219551 C14.77745,6.23794551 14.87565,6.54033551 14.69765,6.71389551 L11.56645,9.76604551 L12.30565,14.0757255 C12.34765,14.3208255 12.09045,14.5077255 11.87035,14.3920255 L8,12.3572255 L4.12966,14.3920255 C3.90957,14.5077255 3.65234,14.3208255 3.69437,14.0757255 L4.43354,9.76604551 L1.30237,6.71389551 C1.12431,6.54033551 1.22256,6.23794551 1.46863,6.20219551 L5.79581,5.57341551 L7.73098,1.65232551 C7.84103,1.42934551 8.15898,1.42935551 8.26902,1.65232551 L10.20415,5.57341551 L14.53135,6.20219551 Z" fill-opacity=".9" fill="currentColor" fill-rule="nonzero"></path>\n</svg>',
                              },
                              id: 'uc99fbe9',
                            },
                            {
                              actionLevel: 100,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              caption: '取消收藏',
                              detailType: 'DEUIACTION',
                              uiactionId: 'remove_favorite@mail_message',
                              tooltip: '取消收藏',
                              visibleScriptCode: 'data.is_favorite==1',
                              showCaption: true,
                              showIcon: true,
                              sysImage: {
                                rawContent:
                                  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" class="design-iconfont" width="16" height="16">\n  <path d="M14.53135,6.20219551 C14.77745,6.23794551 14.87565,6.54033551 14.69765,6.71389551 L11.56645,9.76604551 L12.30565,14.0757255 C12.34765,14.3208255 12.09045,14.5077255 11.87035,14.3920255 L8,12.3572255 L4.12966,14.3920255 C3.90957,14.5077255 3.65234,14.3208255 3.69437,14.0757255 L4.43354,9.76604551 L1.30237,6.71389551 C1.12431,6.54033551 1.22256,6.23794551 1.46863,6.20219551 L5.79581,5.57341551 L7.73098,1.65232551 C7.84103,1.42934551 8.15898,1.42935551 8.26902,1.65232551 L10.20415,5.57341551 L14.53135,6.20219551 Z" fill-opacity=".9" fill="#FFB31A" fill-rule="nonzero"></path>\n</svg>',
                              },
                              id: 'u9de05ba',
                            },
                          ],
                          appDataEntityId: 'ibizodooapp.mail_message',
                          uniqueTag: 'mail_message__Auto59229723',
                          name: '频道消息更多操作',
                          id: 'auto59229723',
                        },
                        itemStyle: 'STYLE2',
                        itemType: 'BUTTONLIST',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysImage: {
                          cssClass: 'fa fa-ellipsis-v',
                          glyph: 'xf142@FontAwesome',
                        },
                        id: 'buttonlist',
                      },
                    ],
                    layout: {
                      dir: 'row-reverse',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    controlLogics: [
                      {
                        itemName: 'CONTAINER2',
                        logicTag: 'list_itempanel',
                        logicType: 'SCRIPT',
                        scriptCode: 'context.srfreadonly != true',
                        triggerType: 'ITEMVISIBLE',
                        name: 'readOnly',
                        id: 'readonly',
                      },
                    ],
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    panelItemGroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedItemNames: ['field_text_dynamic2'],
                        groupOP: 'AND',
                        panelItemLogics: [
                          {
                            condOp: 'NOTEQ',
                            dstModelField: 'FIELD_TEXT_DYNAMIC2',
                            value: '<p><del>该评论已删除</del></p>',
                            logicType: 'SINGLE',
                            id: '逻辑项',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    id: 'container2',
                  },
                ],
                layout: {
                  align: 'space-between',
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      contentType: 'HTML',
                      editorParams: {
                        contenttype: 'HTML',
                        LINKVIEWID: 'plmweb.recent_custom_redirect_view',
                        SCRIPTCODE:
                          'data.content?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\'comment-tag\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\'comment-tag\'>@$1</span>").replaceAll(/\\#\\{(\\".+?\\":\\".+?\\")(,\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\")*\\}/g, (x, value, icon) => {const item = JSON.parse("{" + value + "}"); if (icon) { icon = icon.slice(8).slice(1, -1).trim(); } return controller.parseCommentTag({icon, ...item});}).replaceAll(/\\{\\"\\emoji\\":\\"(.+?)\\"\\}/g,(x, emoji) => {const tempVal = decodeURIComponent(atob(emoji)); return `<span class="emoji-tag">${tempVal}</span>`})',
                        TRANSLATEOBJ: '{"&reg":"&amp;reg"}',
                      },
                      editorStyle: 'MAIL_MESSAGE_ITEM',
                      editorType: 'RAW',
                      sysPFPluginId: 'mail_message_item',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'field_text_dynamic2',
                    },
                    viewFieldName: 'BODY',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'field_text_dynamic2',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'ibizodooapp.sysoperator',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'parent_author_id',
                        },
                        viewFieldName: 'PARENT_AUTHOR_ID',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'parent_author_id',
                      },
                      {
                        rawItem: {
                          caption: '：',
                          halign: 'LEFT',
                          renderMode: 'PARAGRAPH',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_LABEL',
                          id: 'static_label',
                        },
                        caption: '标签',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'static_label',
                      },
                      {
                        editor: {
                          contentType: 'HTML',
                          editorParams: {
                            contenttype: 'HTML',
                            SCRIPTCODE:
                              'data.content?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\'comment-tag\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\'comment-tag\'>@$1</span>").replaceAll(/\\#\\{(\\".+?\\":\\".+?\\")(,\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\")*\\}/g, (x, value, icon) => {const item = JSON.parse("{" + value + "}"); if (icon) { icon = icon.slice(8).slice(1, -1).trim(); } return controller.parseCommentTag({icon, ...item});}).replaceAll(/\\{\\"\\emoji\\":\\"(.+?)\\"\\}/g,(x, emoji) => {const tempVal = decodeURIComponent(atob(emoji)); return `<span class="emoji-tag">${tempVal}</span>`})',
                            TRANSLATEOBJ: '{"&reg":"&amp;reg"}',
                          },
                          editorStyle: 'MAIL_MESSAGE_ITEM',
                          editorType: 'RAW',
                          sysPFPluginId: 'mail_message_item',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'parent_body',
                        },
                        viewFieldName: 'PARENT_BODY',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          grow: 1,
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'parent_body',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingBottom: 'OUTERSMALL',
                      spacingLeft: 'OUTERSMALL',
                      spacingRight: 'OUTERSMALL',
                      spacingTop: 'OUTERSMALL',
                    },
                    panelItemGroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedItemNames: ['pid'],
                        groupOP: 'AND',
                        panelItemLogics: [
                          {
                            condOp: 'ISNOTNULL',
                            dstModelField: 'PID',
                            logicType: 'SINGLE',
                            id: '逻辑项',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    sysCss: {
                      cssName: 'comment-replay',
                    },
                    id: 'container3',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                cssStyle: 'padding-left: 36px;',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysCss: {
                  cssName: 'channel-message',
                },
                id: 'container4',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'channel_message_pinned_layout',
        controlType: 'PANEL',
        logicName: '频道置顶消息显示面板',
        appDataEntityId: 'ibizodooapp.mail_message',
        controlParam: {},
        modelId: 'a7be56196155dfc084a1a19672a18c77',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'ibizodooapp.mail_message.channel_message_pinned_layout',
      },
      minorSortDir: 'DESC',
      minorSortAppDEFieldId: 'create_date',
      delistDataItems: [
        {
          appDEFieldId: 'parent_body',
          dataType: 21,
          id: 'parent_body',
        },
        {
          appDEFieldId: 'parent_author_id',
          dataType: 25,
          id: 'parent_author_id',
        },
        {
          appDEFieldId: 'parent_id',
          dataType: 25,
          id: 'pid',
        },
        {
          appDEFieldId: 'body',
          dataType: 21,
          id: 'body',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'create_uid',
          frontCodeListId: 'ibizodooapp.sysoperator',
          dataType: 25,
          id: 'create_uid',
        },
        {
          appDEFieldId: 'create_date',
          dataType: 5,
          format: 'YYYY-MM-DD HH:mm:ss',
          id: 'create_date',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'record_name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'parent_id',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'record_company_id',
          dataType: 25,
          id: 'record_company_id',
        },
        {
          appDEFieldId: 'subtype_id',
          dataType: 25,
          id: 'subtype_id',
        },
        {
          appDEFieldId: 'record_alias_domain_id',
          dataType: 25,
          id: 'record_alias_domain_id',
        },
        {
          appDEFieldId: 'mail_activity_type_id',
          dataType: 25,
          id: 'mail_activity_type_id',
        },
        {
          appDEFieldId: 'author_guest_id',
          dataType: 25,
          id: 'author_guest_id',
        },
        {
          appDEFieldId: 'author_id',
          dataType: 25,
          id: 'author_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      singleSelect: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_pinned',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'discuss_list_pinned',
      controlType: 'LIST',
      logicName: 'discuss_list_pinned',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'list',
      },
      modelId: '840b3a8cbe4c21193e734d11f67bceb5',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'ibizodooapp.mail_message.discuss_list_pinned',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.MAIL_MESSAGE.PINNED_LIST_VIEW',
      },
      caption: '置顶消息',
      codeName: 'pinned_list_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {},
      name: 'captionbar',
      id: 'pinned_list_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_message',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '置顶消息',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.PINNED_LIST_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f85fe5079061f3873ca5fb31d2204c3d',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_messagepinned_list_view',
  id: 'ibizodooapp.mail_message_pinned_list_view',
};
