export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'MAINVIEW',
  deviewCodeName: 'main_view',
  deviewId: '9c2e8f97b1d62fcc3378fc1e99f44a75',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_MAIL',
  },
  caption: 'EMail',
  codeName: 'mail_mail_main_view',
  appDataEntityId: 'ibizodooapp.mail_mail',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar2',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'u3e46fa4',
                    },
                  ],
                  name: '通用编辑页面删除界面行为组',
                  id: 'auto94538916',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ibizodooapp.mail_mail',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ibizodooapp.mail_mail',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_view_toolbar1',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.mail_mail',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ibizodooapp.mail_mail',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.mail_mail',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.mail_mail',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.mail_mail',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.mail_mail',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 21,
                    enableCond: 3,
                    itemHeight: 80,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'email_to',
                    editor: {
                      maxLength: 1048576,
                      showMaxLength: true,
                      editorHeight: 80,
                      editorParams: {
                        HEIGHT: '200',
                      },
                      editorType: 'TEXTAREA_10',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'email_to',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_MAIL.EMAIL_TO',
                    },
                    caption: '至',
                    codeName: 'email_to',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'email_to',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'email_cc',
                    editor: {
                      maxLength: 500,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'email_cc',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_MAIL.EMAIL_CC',
                    },
                    caption: '抄送',
                    codeName: 'email_cc',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'email_cc',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    itemWidth: 290,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'scheduled_date',
                    editor: {
                      dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                      editorParams: {
                        TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                      },
                      editorType: 'DATEPICKER',
                      editorWidth: 160,
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'scheduled_date',
                    },
                    valueFormat: 'YYYY-MM-DD HH:mm:ss',
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_MAIL.SCHEDULED_DATE',
                    },
                    caption: '安排的发送日期',
                    codeName: 'scheduled_date',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'scheduled_date',
                  },
                  {
                    deformTabPages: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 21,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'body_content',
                            editor: {
                              editorType: 'HTMLEDITOR',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'body_content',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_MAIL.BODY_CONTENT',
                            },
                            caption: '富文本内容',
                            codeName: 'body_content',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'body_content',
                          },
                        ],
                        caption: '正文',
                        codeName: 'tabpage1',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage1',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 9,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'auto_delete',
                                editor: {
                                  editorType: 'CHECKBOX',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'auto_delete',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag: 'DEF.LNAME.MAIL_MAIL.AUTO_DELETE',
                                },
                                caption: '自动删除',
                                codeName: 'auto_delete',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'auto_delete',
                              },
                              {
                                dataType: 9,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'is_notification',
                                editor: {
                                  editorType: 'CHECKBOX',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'is_notification',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.MAIL_MAIL.IS_NOTIFICATION',
                                },
                                caption: '通知电子邮件',
                                codeName: 'is_notification',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'is_notification',
                              },
                            ],
                            caption: '状态',
                            codeName: 'grouppanel1',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colLG: 12,
                              colMD: 12,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'grouppanel1',
                          },
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'mail_message_id',
                                editor: {
                                  editorType: 'HIDDEN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'mail_message_id',
                                },
                                allowEmpty: true,
                                hidden: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.MAIL_MAIL.MAIL_MESSAGE_ID',
                                },
                                caption: '消息',
                                codeName: 'mail_message_id',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                id: 'mail_message_id',
                              },
                              {
                                dataType: 21,
                                itemHeight: 80,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'references',
                                editor: {
                                  maxLength: 1048576,
                                  showMaxLength: true,
                                  editorHeight: 80,
                                  editorParams: {
                                    HEIGHT: '200',
                                  },
                                  editorType: 'TEXTAREA_10',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'references',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag: 'DEF.LNAME.MAIL_MAIL.REFERENCES',
                                },
                                caption: '参考',
                                codeName: 'references',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'references',
                              },
                              {
                                dataType: 21,
                                itemHeight: 80,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'headers',
                                editor: {
                                  maxLength: 1048576,
                                  showMaxLength: true,
                                  editorHeight: 80,
                                  editorParams: {
                                    HEIGHT: '200',
                                  },
                                  editorType: 'TEXTAREA_10',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'headers',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag: 'DEF.LNAME.MAIL_MAIL.HEADERS',
                                },
                                caption: '请求头',
                                codeName: 'headers',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'headers',
                              },
                            ],
                            caption: '请求头',
                            codeName: 'grouppanel2',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colLG: 12,
                              colMD: 12,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'grouppanel2',
                          },
                        ],
                        caption: '高级',
                        codeName: 'tabpage2',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage2',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        caption: '附件',
                        codeName: 'tabpage3',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage3',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 21,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'failure_reason',
                            editor: {
                              maxLength: 1048576,
                              showMaxLength: true,
                              editorParams: {
                                isauto: 'true',
                              },
                              editorType: 'TEXTAREA',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'failure_reason',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_MAIL.FAILURE_REASON',
                            },
                            caption: '失败原因',
                            codeName: 'failure_reason',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'failure_reason',
                          },
                        ],
                        caption: '失败原因',
                        codeName: 'tabpage4',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage4',
                      },
                    ],
                    codeName: 'tabpanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'tabpanel1',
                  },
                ],
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFORM.MAIL_MAIL.MAIN2.GROUPPANEL.GROUP1',
                },
                caption: '发出邮件基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MAIL_MAIL.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.MAIL_MAIL.MAIN2.FORMPAGE.FORMPAGE1',
            },
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main2',
        controlType: 'FORM',
        logicName: '发送邮件主视图_表单',
        appDataEntityId: 'ibizodooapp.mail_mail',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: '78d33f62088045960713f41f49504624',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ibizodooapp.mail_mail.main2',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ibizodooapp.mail_mail',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MAIL_MAIL',
        },
        caption: 'EMail',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.mail_mail',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'main_view_layout1',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new_没有评论区',
    appDataEntityId: 'ibizodooapp.mail_mail',
    controlLogics: [
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId); ',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", async  (state, isTrusted )=> {\n    console.log("");\n    const data = view.getController("form").getData()[0];\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\n});\n\nconst topContext = view.context;\nconst appEntityId = view.model.appDataEntityId;\nconst entityName = appEntityId.split(\'.\').pop();\nconst bExist = topContext[entityName];\nconst drbar = view.getCtrl("DRBAR", "drbar");\nif(!bExist){\n    drbar.disabled({ mode: \'BLANK\' })\n    //  drbar.disabled({ mode: \'MASK\' })\n\n}\n\n',
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\n   if (name === 'drbar') {\n      const topContext = view.context;\n      const appEntityId = view.model.appDataEntityId;\n      const entityName = appEntityId.split('.').pop();\n      const bExist = topContext[entityName];\n      if(!bExist){\n         ctrl?.disableCounter()\n      }\n   }\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '3ea3e353274bcb7a2bf0fee66c7d91cf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout1',
  },
  title: '发送邮件',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.MAIL_MAIL.MAIN_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '2d19af1140ba4ad4ed50e1d8b5743571',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_mailmain_view',
  id: 'ibizodooapp.mail_mail_main_view',
};
