export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '0c3a8f4d0efab7d6947b411be509bb3f',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ALIAS_DOMAIN',
  },
  caption: '电子邮件域名',
  codeName: 'mail_alias_domain_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.mail_alias_domain',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'ASC',
      minorSortAppDEFieldId: 'sequence',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'bounce_alias',
          excelCaption: '弹跳别名',
          appDEFieldId: 'bounce_alias',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.BOUNCE_ALIAS',
          },
          caption: '弹跳别名',
          codeName: 'bounce_alias',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'bounce_alias',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'catchall_alias',
          excelCaption: '全部别名',
          appDEFieldId: 'catchall_alias',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.CATCHALL_ALIAS',
          },
          caption: '全部别名',
          codeName: 'catchall_alias',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'catchall_alias',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'default_from',
          excelCaption: '默认发件人别名',
          appDEFieldId: 'default_from',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.DEFAULT_FROM',
          },
          caption: '默认发件人别名',
          codeName: 'default_from',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'default_from',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'bounce_alias',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'bounce_alias',
        },
        {
          appDEFieldId: 'catchall_alias',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'catchall_alias',
        },
        {
          appDEFieldId: 'default_from',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'default_from',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.mail_alias_domain',
        id: 'fetch',
      },
      moveControlAction: {
        appDEMethodId: 'move_order',
        appDataEntityId: 'ibizodooapp.mail_alias_domain',
        id: 'move',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.mail_alias_domain',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.mail_alias_domain',
      controlParam: {
        id: 'grid',
      },
      modelId: '340dc03759083af087e357b7f69ebd6d',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.mail_alias_domain.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.MAIL_ALIAS_DOMAIN.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.mail_alias_domain',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'bda14dd19f94a1a7478efc67a062bb89',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.mail_alias_domain.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.mail_alias_domain',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MAIL_ALIAS_DOMAIN',
      },
      caption: '电子邮件域名',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_alias_domain',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_alias_domain',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '电子邮件域名选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '44af714c926bf182df2687314b66b263',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_alias_domainPickupGridView',
  id: 'ibizodooapp.mail_alias_domain_pickup_grid_view',
};
