export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'main_view',
  deviewId: '97e958f59b17aa21d6cb44a26568b5e6',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_TEMPLATE',
  },
  caption: 'EMail模板',
  codeName: 'mail_template_main_view',
  appDataEntityId: 'ibizodooapp.mail_template',
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'u3e46fa4',
                    },
                  ],
                  name: '通用编辑页面删除界面行为组',
                  id: 'auto94538916',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ibizodooapp.mail_template',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.mail_template',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ibizodooapp.mail_template',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.mail_template',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.mail_template',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.mail_template',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.mail_template',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      showMaxLength: true,
                      editorParams: {
                        ISAUTO: 'true',
                      },
                      editorType: 'TEXTAREA',
                      placeHolder: '例如“欢迎电子邮件”',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 40,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'subject',
                    editor: {
                      maxLength: 500,
                      editorType: 'TEXTBOX',
                      placeHolder:
                        '例如“欢迎来到我的公司”或“很高兴认识你，{{ object.name }}”',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'subject',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.SUBJECT',
                    },
                    caption: '主旨',
                    codeName: 'subject',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'subject',
                  },
                  {
                    deformTabPages: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 21,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 40,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'body_html',
                            editor: {
                              maxLength: 1048576,
                              showMaxLength: true,
                              editorParams: {
                                isauto: 'true',
                              },
                              editorType: 'TEXTAREA',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'body_html',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.BODY_HTML',
                            },
                            caption: '正文',
                            codeName: 'body_html',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'body_html',
                          },
                        ],
                        caption: '内容',
                        codeName: 'tabpage1',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage1',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'email_from',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              placeHolder: '覆盖作者EMail',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'email_from',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.EMAIL_FROM',
                            },
                            caption: '来自',
                            codeName: 'email_from',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'email_from',
                          },
                          {
                            dataType: 9,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'use_default_to',
                            editor: {
                              editorType: 'CHECKBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'use_default_to',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.MAIL_TEMPLATE.USE_DEFAULT_TO',
                            },
                            caption: '默认收件人',
                            codeName: 'use_default_to',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'use_default_to',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'email_to',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              placeHolder: '逗号分隔的收件人邮件地址',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'email_to',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.EMAIL_TO',
                            },
                            caption: '至（EMail）',
                            codeName: 'email_to',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'email_to',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'partner_to',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              placeHolder: '逗号分隔的收件人合作伙伴的邮件地址',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'partner_to',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.PARTNER_TO',
                            },
                            caption: '至（合作伙伴）',
                            codeName: 'partner_to',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'partner_to',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'email_cc',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              placeHolder: '逗号分隔抄送收件人邮件地址',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'email_cc',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.EMAIL_CC',
                            },
                            caption: '抄送',
                            codeName: 'email_cc',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'email_cc',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'reply_to',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              placeHolder:
                                '批量发送电子邮件时将回复重定向到的电子邮件地址',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'reply_to',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.REPLY_TO',
                            },
                            caption: '回复',
                            codeName: 'reply_to',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'reply_to',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'scheduled_date',
                            editor: {
                              maxLength: 500,
                              editorType: 'TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'scheduled_date',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.MAIL_TEMPLATE.SCHEDULED_DATE',
                            },
                            caption: '安排的发送日期',
                            codeName: 'scheduled_date',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'scheduled_date',
                          },
                        ],
                        caption: 'EMail配置',
                        codeName: 'tabpage2',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage2',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'lang',
                                editor: {
                                  maxLength: 500,
                                  editorType: 'TEXTBOX',
                                  placeHolder: '{{ object.partner_id.lang }}',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'lang',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.LANG',
                                },
                                caption: '语言',
                                codeName: 'lang',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 12,
                                  colMD: 12,
                                  colSM: 12,
                                  colXS: 12,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'lang',
                              },
                              {
                                dataType: 9,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'auto_delete',
                                editor: {
                                  editorType: 'CHECKBOX',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'auto_delete',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.MAIL_TEMPLATE.AUTO_DELETE',
                                },
                                caption: '自动删除',
                                codeName: 'auto_delete',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 12,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'auto_delete',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'template_fs',
                                editor: {
                                  maxLength: 500,
                                  editorType: 'TEXTBOX',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'template_fs',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.MAIL_TEMPLATE.TEMPLATE_FS',
                                },
                                caption: '模板文件名',
                                codeName: 'template_fs',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'template_fs',
                              },
                              {
                                dataType: 21,
                                enableCond: 3,
                                itemHeight: 80,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'description',
                                editor: {
                                  maxLength: 1048576,
                                  showMaxLength: true,
                                  editorHeight: 80,
                                  editorParams: {
                                    HEIGHT: '200',
                                  },
                                  editorType: 'TEXTAREA_10',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'description',
                                },
                                allowEmpty: true,
                                capLanguageRes: {
                                  lanResTag:
                                    'DEF.LNAME.MAIL_TEMPLATE.DESCRIPTION',
                                },
                                caption: '模板描述',
                                codeName: 'description',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'description',
                              },
                            ],
                            codeName: 'grouppanel1',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'grouppanel1',
                          },
                        ],
                        caption: '设置',
                        codeName: 'tabpage3',
                        detailStyle: 'DEFAULT',
                        detailType: 'TABPAGE',
                        showCaption: true,
                        id: 'tabpage3',
                      },
                    ],
                    codeName: 'tabpanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'tabpanel1',
                  },
                ],
                caption: 'EMail模板基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main3',
        controlType: 'FORM',
        logicName: 'EMail模板实体主视图_表单',
        appDataEntityId: 'ibizodooapp.mail_template',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: 'fca49a7ef5f3c89493cd9695946ee147',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ibizodooapp.mail_template.main3',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ibizodooapp.mail_template',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_view_toolbar1',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ibizodooapp.mail_template',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MAIL_TEMPLATE',
        },
        caption: 'EMail模板',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.mail_template',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'main_view_layout_nocomment',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_无讨论',
    appDataEntityId: 'ibizodooapp.mail_template',
    controlLogics: [
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", (state, isTrusted )=> {\r\n    console.log("");\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});',
        triggerType: 'CTRLEVENT',
        id: 'init_domain_state_change',
      },
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: 'ef3f9bc56161de3135f01329747f91a3',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout_nocomment',
  },
  title: 'EMail模板',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '131329c777227f00144c1ff6e4447fdc',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_templatemain_view',
  id: 'ibizodooapp.mail_template_main_view',
};
