export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '8cd61163583de84788ef529b6772698e',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_TEMPLATE',
  },
  caption: 'EMail模板',
  codeName: 'mail_template_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.mail_template',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'user_id',
          excelCaption: '用户',
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.USER_ID',
          },
          caption: '用户',
          codeName: 'user_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'user_id',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'description',
          excelCaption: '模板描述',
          appDEFieldId: 'description',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.DESCRIPTION',
          },
          caption: '模板描述',
          codeName: 'description',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          id: 'description',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'subject',
          excelCaption: '主旨',
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.SUBJECT',
          },
          caption: '主旨',
          codeName: 'subject',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'subject',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'email_from',
          excelCaption: '来自',
          appDEFieldId: 'email_from',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.EMAIL_FROM',
          },
          caption: '来自',
          codeName: 'email_from',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'email_from',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'email_to',
          excelCaption: '至（EMail）',
          appDEFieldId: 'email_to',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.EMAIL_TO',
          },
          caption: '至（EMail）',
          codeName: 'email_to',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'email_to',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'partner_to',
          excelCaption: '至（合作伙伴）',
          appDEFieldId: 'partner_to',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAIL_TEMPLATE.PARTNER_TO',
          },
          caption: '至（合作伙伴）',
          codeName: 'partner_to',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'partner_to',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'description',
          valueType: 'SIMPLE',
          dataType: 21,
          id: 'description',
        },
        {
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'subject',
        },
        {
          appDEFieldId: 'email_from',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'email_from',
        },
        {
          appDEFieldId: 'email_to',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'email_to',
        },
        {
          appDEFieldId: 'partner_to',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'partner_to',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.mail_template',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.mail_template',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.mail_template',
      controlParam: {
        id: 'grid',
      },
      modelId: 'bb060438d0f4a63e2fe524d8a75b0bcf',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.mail_template.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.MAIL_TEMPLATE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.mail_template',
      controlParam: {
        id: 'searchform',
      },
      modelId: '277cf8d7ec290c3e0bbbe17374823cdc',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.mail_template.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.mail_template',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MAIL_TEMPLATE',
      },
      caption: 'EMail模板',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_template',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_template',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: 'EMail模板选择表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.MAIL_TEMPLATE.PICKUPGRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b4a3e422a4c1aee3c4a49f1ee7918def',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_templatePickupGridView',
  id: 'ibizodooapp.mail_template_pickup_grid_view',
};
