export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'EditView',
  deviewId: 'f7cd16fb780ea02e103394a59fd11088',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_MESSAGE',
  },
  caption: '消息',
  codeName: 'mail_message_edit_view',
  appDataEntityId: 'ibizodooapp.mail_message',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.SAVE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.SAVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem10',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandnewaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
          },
          caption: '保存并新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存并新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem12',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandexitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
          },
          caption: '保存并关闭',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存并关闭',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem11',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem18',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_removeandexitaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
          },
          caption: '删除并关闭',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除并关闭',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem9',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem19',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem5',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem21',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_copyaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.COPY',
          },
          caption: '拷贝',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-copy',
            glyph: 'xf0c5@FontAwesome',
          },
          tooltip: '拷贝',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.COPY',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem22',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_firstrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '第一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-fast-backward',
            glyph: 'xf049@FontAwesome',
          },
          tooltip: '第一个记录',
          showIcon: true,
          id: 'tbitem2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_prevrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '上一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-step-backward',
            glyph: 'xf048@FontAwesome',
          },
          tooltip: '上一个记录',
          showIcon: true,
          id: 'tbitem7',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_nextrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '下一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-step-forward',
            glyph: 'xf051@FontAwesome',
          },
          tooltip: '下一个记录',
          showIcon: true,
          id: 'tbitem6',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_lastrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '最后一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-fast-forward',
            glyph: 'xf050@FontAwesome',
          },
          tooltip: '最后一个记录',
          showIcon: true,
          id: 'tbitem4',
        },
      ],
      xdataControlName: 'form',
      codeName: 'edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认编辑界面）',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '48c8f789be8a5522d3003293c1cf2ffb',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.mail_message',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'subject',
                      editor: {
                        maxLength: 500,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'subject',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.SUBJECT',
                      },
                      caption: '主旨',
                      codeName: 'subject',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'subject',
                    },
                    {
                      dataType: 5,
                      enableCond: 3,
                      itemWidth: 290,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'date',
                      editor: {
                        dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                        editorParams: {
                          TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                        },
                        editorType: 'DATEPICKER',
                        editorWidth: 160,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'date',
                      },
                      valueFormat: 'YYYY-MM-DD HH:mm:ss',
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.DATE',
                      },
                      caption: '日期',
                      codeName: 'date',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'date',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'email_from',
                      editor: {
                        maxLength: 500,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'email_from',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.EMAIL_FROM',
                      },
                      caption: '来自',
                      codeName: 'email_from',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'email_from',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'author_name',
                      editor: {
                        enablePickupView: true,
                        singleSelect: true,
                        pickupAppViewId: 'ibizodooapp.res_partner_pickup_view',
                        handlerType: 'PickupText',
                        appDEACModeId: 'default',
                        appDEDataSetId: 'fetch_default',
                        appDataEntityId: 'ibizodooapp.res_partner',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'author_id',
                        editorParams: {
                          AC: 'TRUE',
                          PICKUPVIEW: 'TRUE',
                        },
                        editorType: 'PICKER',
                        editorItems: [
                          {
                            id: 'author_id',
                          },
                        ],
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'author_name',
                      },
                      allowEmpty: true,
                      caption: '作者',
                      codeName: 'author_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'author_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'message_type',
                      editor: {
                        singleSelect: true,
                        appCodeListId:
                          'ibizodooapp.mail__mail_message_message_type',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'message_type',
                      },
                      needCodeListConfig: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MESSAGE_TYPE',
                      },
                      caption: '类型',
                      codeName: 'message_type',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'message_type',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'subtype_name',
                      editor: {
                        enablePickupView: true,
                        singleSelect: true,
                        handlerType: 'PickupText',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'subtype_id',
                        editorParams: {
                          AC: 'TRUE',
                          PICKUPVIEW: 'TRUE',
                        },
                        editorType: 'PICKER',
                        editorItems: [
                          {
                            id: 'subtype_id',
                          },
                        ],
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'subtype_name',
                      },
                      allowEmpty: true,
                      caption: '子类型',
                      codeName: 'subtype_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'subtype_name',
                    },
                    {
                      dataType: 9,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'is_internal',
                      editor: {
                        editorType: 'CHECKBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'is_internal',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.IS_INTERNAL',
                      },
                      caption: '仅限员工',
                      codeName: 'is_internal',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'is_internal',
                    },
                  ],
                  codeName: 'grouppanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'model',
                      editor: {
                        maxLength: 500,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'model',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MODEL',
                      },
                      caption: '相关单据模型',
                      codeName: 'model',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'model',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'res_id',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'res_id',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.RES_ID',
                      },
                      caption: '相关单据ID',
                      codeName: 'res_id',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'res_id',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'record_name',
                      editor: {
                        maxLength: 500,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'record_name',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.RECORD_NAME',
                      },
                      caption: '消息记录名称',
                      codeName: 'record_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'record_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'parent_name',
                      editor: {
                        enablePickupView: true,
                        singleSelect: true,
                        pickupAppViewId: 'ibizodooapp.mail_message_pickup_view',
                        handlerType: 'PickupText',
                        appDEACModeId: 'default',
                        appDEDataSetId: 'fetch_default',
                        appDataEntityId: 'ibizodooapp.mail_message',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'parent_id',
                        editorParams: {
                          AC: 'TRUE',
                          PICKUPVIEW: 'TRUE',
                        },
                        editorType: 'PICKER',
                        editorItems: [
                          {
                            id: 'parent_id',
                          },
                        ],
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'parent_name',
                      },
                      allowEmpty: true,
                      caption: '上级消息',
                      codeName: 'parent_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'parent_name',
                    },
                  ],
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel2',
                },
                {
                  deformTabPages: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 21,
                          enableCond: 3,
                          labelPos: 'NONE',
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'body',
                          editor: {
                            editorType: 'HTMLEDITOR',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'body',
                          },
                          allowEmpty: true,
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.MAIL_MESSAGE.BODY',
                          },
                          caption: '内容',
                          codeName: 'body',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          id: 'body',
                        },
                      ],
                      caption: '正文',
                      codeName: 'tabpage1',
                      detailStyle: 'DEFAULT',
                      detailType: 'TABPAGE',
                      showCaption: true,
                      id: 'tabpage1',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          layout: {
                            columnCount: 24,
                            layout: 'TABLE_24COL',
                          },
                          deformDetails: [
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              appDEFieldId: 'reply_to',
                              editor: {
                                maxLength: 500,
                                editorType: 'TEXTBOX',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'reply_to',
                              },
                              allowEmpty: true,
                              capLanguageRes: {
                                lanResTag: 'DEF.LNAME.MAIL_MESSAGE.REPLY_TO',
                              },
                              caption: '回复 至',
                              codeName: 'reply_to',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              showCaption: true,
                              id: 'reply_to',
                            },
                            {
                              dataType: 9,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              appDEFieldId: 'reply_to_force_new',
                              editor: {
                                editorType: 'CHECKBOX',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'reply_to_force_new',
                              },
                              allowEmpty: true,
                              capLanguageRes: {
                                lanResTag:
                                  'DEF.LNAME.MAIL_MESSAGE.REPLY_TO_FORCE_NEW',
                              },
                              caption: '无响应',
                              codeName: 'reply_to_force_new',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              showCaption: true,
                              id: 'reply_to_force_new',
                            },
                          ],
                          codeName: 'grouppanel3',
                          detailStyle: 'DEFAULT',
                          detailType: 'GROUPPANEL',
                          layoutPos: {
                            colLG: 12,
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          id: 'grouppanel3',
                        },
                        {
                          layout: {
                            columnCount: 24,
                            layout: 'TABLE_24COL',
                          },
                          deformDetails: [
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              appDEFieldId: 'message_id',
                              editor: {
                                maxLength: 500,
                                editorType: 'TEXTBOX',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'message_id',
                              },
                              allowEmpty: true,
                              capLanguageRes: {
                                lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MESSAGE_ID',
                              },
                              caption: '消息ID',
                              codeName: 'message_id',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              showCaption: true,
                              id: 'message_id',
                            },
                          ],
                          codeName: 'grouppanel4',
                          detailStyle: 'DEFAULT',
                          detailType: 'GROUPPANEL',
                          layoutPos: {
                            colLG: 12,
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          id: 'grouppanel4',
                        },
                      ],
                      caption: '网关',
                      codeName: 'tabpage2',
                      detailStyle: 'DEFAULT',
                      detailType: 'TABPAGE',
                      showCaption: true,
                      id: 'tabpage2',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      caption: '收件人',
                      codeName: 'tabpage3',
                      detailStyle: 'DEFAULT',
                      detailType: 'TABPAGE',
                      showCaption: true,
                      id: 'tabpage3',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      caption: '追溯',
                      codeName: 'tabpage4',
                      detailStyle: 'DEFAULT',
                      detailType: 'TABPAGE',
                      showCaption: true,
                      id: 'tabpage4',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      caption: '点评',
                      codeName: 'tabpage5',
                      detailStyle: 'DEFAULT',
                      detailType: 'TABPAGE',
                      showCaption: true,
                      id: 'tabpage5',
                    },
                  ],
                  codeName: 'tabpanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'TABPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'tabpanel1',
                },
              ],
              caption: '消息基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'parent_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'parent_id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MAIL_MESSAGE.PARENT_ID',
              },
              caption: '上级消息',
              codeName: 'parent_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'parent_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MAIL_MESSAGE.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'author_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'author_id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MAIL_MESSAGE.AUTHOR_ID',
              },
              caption: '作者',
              codeName: 'author_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'author_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'subtype_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'subtype_id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MAIL_MESSAGE.SUBTYPE_ID',
              },
              caption: '子类型',
              codeName: 'subtype_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'subtype_id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'FORM',
      logicName: '主编辑表单',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'form',
      },
      modelId: '5144a36e6e7382b6f25bddbb8dbf3d07',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'ibizodooapp.mail_message.main',
    },
    {
      codeName: 'edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MAIL_MESSAGE',
      },
      caption: '消息',
      codeName: 'edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_message',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '消息编辑视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.EDITVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a981d251a3a5106cc593610e587be566',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_messageEditView',
  id: 'ibizodooapp.mail_message_edit_view',
};
