export default {
  mdctrlActiveMode: 1,
  loadDefault: true,
  deviewCodeName: 'multi_data_view',
  deviewId: '7d63cbd48f278012cfd590144143980b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ALIAS',
  },
  caption: '别名',
  codeName: 'mail_alias_multi_data_view',
  appDataEntityId: 'ibizodooapp.mail_alias',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '搜索栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-columns',
                            glyph: 'xf0db@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="dataview" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'dataview_toggle',
                        },
                        caption: '卡片',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'dataview_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "dataview")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'visable_card',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-columns',
                          glyph: 'xf0db@FontAwesome',
                        },
                        showCaption: true,
                        id: 'dataview_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-reorder',
                            glyph: 'xf0c9@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="grid" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'grid_toggle',
                        },
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'grid_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "grid")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'visable_grid',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-reorder',
                          glyph: 'xf0c9@FontAwesome',
                        },
                        showCaption: true,
                        id: 'grid_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-clock-o',
                            glyph: 'xf017@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="activity" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'activity_toggle',
                        },
                        caption: '活动',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'activity_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              '\nview.layoutPanel.model.controls.find(ctrl=>ctrl.name === "activity")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'visable_activity',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-clock-o',
                          glyph: 'xf017@FontAwesome',
                        },
                        showCaption: true,
                        id: 'activity_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-table',
                            glyph: 'xf0ce@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="pivottable" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'pivottable_toggle',
                        },
                        caption: '透视表',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'pivottable_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.getCtrl("GRID", "pivottable")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'pivottable_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-table',
                          glyph: 'xf0ce@FontAwesome',
                        },
                        showCaption: true,
                        id: 'pivottable_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-calendar',
                            glyph: 'xf073@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="calendar" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'calendar_toggle',
                        },
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'calendar_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "calendar")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'calendar_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-calendar',
                          glyph: 'xf073@FontAwesome',
                        },
                        showCaption: true,
                        id: 'calendar_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-area-chart',
                            glyph: 'xf1fe@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="chart" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'chart_toggle',
                        },
                        caption: '图表',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'chart_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "chart")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'chart_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-area-chart',
                          glyph: 'xf1fe@FontAwesome',
                        },
                        showCaption: true,
                        id: 'chart_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-sitemap',
                            glyph: 'xf0e8@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="hierarchy" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          tooltip: '层级',
                          id: 'hierarchy_toggle',
                        },
                        caption: '图表',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'hierarchy_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "hierarchy")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'hierarchy_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-sitemap',
                          glyph: 'xf0e8@FontAwesome',
                        },
                        showCaption: true,
                        id: 'hierarchy_toggle',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 0,
                      layout: 'FLEX',
                    },
                    id: 'switch_panel_container',
                  },
                  {
                    editor: {
                      editorType: 'HIDDEN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'active_ctrl',
                    },
                    viewFieldName: 'active_ctrl',
                    allowEmpty: true,
                    hidden: true,
                    caption: '文本(动态)',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysCss: {
                      cssName: 'ctrl-switch-active',
                    },
                    id: 'active_ctrl',
                  },
                  {
                    editor: {
                      editorType: 'HIDDEN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'default_ctrl',
                    },
                    viewFieldName: 'default_ctrl',
                    allowEmpty: true,
                    hidden: true,
                    caption: '文本(动态)',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'default_ctrl',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingLeft: 'INNERMEDIUM',
                  spacingRight: 'INNERMEDIUM',
                },
                id: 'switch_panel',
              },
            ],
            predefinedType: 'PANELPART',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '引用布局面板',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'panelpart',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '数据视图',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'dataview',
          },
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
          {
            caption: '活动',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'activity',
          },
          {
            caption: '日历',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'calendar',
          },
          {
            caption: '图表',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'chart',
          },
          {
            caption: '层级',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'hierarchy',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'ibizodooapp.mail_alias_main_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.mail_alias_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'ibizodooapp.mail_alias_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.mail_alias_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: 'EMail别名实体',
        refAppViewId: 'ibizodooapp.mail_alias_main_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: 'EMail别名实体',
        refAppViewId: 'ibizodooapp.mail_alias_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: 'EMail别名实体',
        refAppViewId: 'ibizodooapp.mail_alias_main_view',
        name: 'OPENDATA',
        id: 'opendata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        codeName: 'multi_data_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（表格界面，只有一个新建按钮）',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'cd9eb7eb8c0facf6084ba1508d888eea',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'multi_data_view_toolbar',
      },
      {
        groupMode: 'AND',
        searchBarGroups: [
          {
            addSeparator: true,
            defaultGroup: true,
            caption: '有效',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"alias_name","condop":"ISNOTNULL","value":""}]}]}}',
            itemType: 'GROUP',
            id: 'alias_name_isnotnull',
          },
        ],
        quickGroupCount: 1,
        quickSearchMode: 1,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'search_bar',
        controlStyle: 'ODOO_SEARCH_BAR',
        controlType: 'SEARCHBAR',
        logicName: 'EMail别名搜索栏',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {
          id: 'searchbar',
        },
        sysPFPluginId: 'odoo_search_bar',
        modelId: 'a8d8e1a375620a1402e9db49cac8f73a',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'ibizodooapp.mail_alias.search_bar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'alias_name',
            excelCaption: '别名',
            appDEFieldId: 'alias_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_NAME',
            },
            caption: '别名',
            codeName: 'alias_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 250,
            widthUnit: 'PX',
            enableSort: true,
            id: 'alias_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'alias_domain_name',
            excelCaption: '别名域',
            appDEFieldId: 'alias_domain_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DOMAIN_ID',
            },
            caption: '别名域',
            codeName: 'alias_domain_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'alias_domain_name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'alias_model_id',
            excelCaption: '模型别名',
            appCodeListId: 'ibizodooapp.base__ir_model',
            appDEFieldId: 'alias_model_id',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '模型别名',
            codeName: 'alias_model_id',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'alias_model_id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'alias_force_thread_id',
            excelCaption: '记录线索ID',
            appDEFieldId: 'alias_force_thread_id',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_FORCE_THREAD_ID',
            },
            caption: '记录线索ID',
            codeName: 'alias_force_thread_id',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'alias_force_thread_id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'alias_parent_thread_id',
            excelCaption: '上级记录ID',
            appDEFieldId: 'alias_parent_thread_id',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'RIGHT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_PARENT_THREAD_ID',
            },
            caption: '上级记录ID',
            codeName: 'alias_parent_thread_id',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            id: 'alias_parent_thread_id',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'alias_parent_model_id',
            excelCaption: '上级模型',
            appCodeListId: 'ibizodooapp.base__ir_model',
            appDEFieldId: 'alias_parent_model_id',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '上级模型',
            codeName: 'alias_parent_model_id',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'alias_parent_model_id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'alias_defaults',
            excelCaption: '默认值',
            appDEFieldId: 'alias_defaults',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DEFAULTS',
            },
            caption: '默认值',
            codeName: 'alias_defaults',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            hideDefault: true,
            id: 'alias_defaults',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'alias_contact',
            excelCaption: '别名授权于',
            appCodeListId: 'ibizodooapp.mail__mail_alias_alias_contact',
            appDEFieldId: 'alias_contact',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_CONTACT',
            },
            caption: '别名授权于',
            codeName: 'alias_contact',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'alias_contact',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'alias_incoming_local',
            excelCaption: '收件时检测本地的别名域',
            appCodeListId: 'ibizodooapp.yesno',
            appDEFieldId: 'alias_incoming_local',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_INCOMING_LOCAL',
            },
            caption: '收件时检测本地的别名域',
            codeName: 'alias_incoming_local',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 210,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            id: 'alias_incoming_local',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'alias_status',
            excelCaption: '别名状态',
            appCodeListId: 'ibizodooapp.mail__mail_alias_alias_status',
            appDEFieldId: 'alias_status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_STATUS',
            },
            caption: '别名状态',
            codeName: 'alias_status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'alias_status',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'alias_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'alias_name',
          },
          {
            appDEFieldId: 'alias_domain_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'alias_domain_name',
          },
          {
            appDEFieldId: 'alias_model_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'alias_model_id',
          },
          {
            appDEFieldId: 'alias_force_thread_id',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'alias_force_thread_id',
          },
          {
            appDEFieldId: 'alias_parent_thread_id',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'alias_parent_thread_id',
          },
          {
            appDEFieldId: 'alias_parent_model_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'alias_parent_model_id',
          },
          {
            appDEFieldId: 'alias_defaults',
            valueType: 'SIMPLE',
            dataType: 21,
            id: 'alias_defaults',
          },
          {
            appDEFieldId: 'alias_contact',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'alias_contact',
          },
          {
            appDEFieldId: 'alias_incoming_local',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'alias_incoming_local',
          },
          {
            appDEFieldId: 'alias_status',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'alias_status',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'alias_domain_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'alias_domain_id',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.mail_alias',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {
          id: 'grid',
        },
        modelId: 'c231336a084710e6d8b022b7952083ad',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'ibizodooapp.mail_alias.main',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MAIL_ALIAS',
        },
        caption: '别名',
        codeName: 'multi_data_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.mail_alias',
        controlParam: {},
        name: 'captionbar',
        id: 'multi_data_view_captionbar',
      },
    ],
    codeName: 'mdcustomview',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '多数据视图布局面板',
    appDataEntityId: 'ibizodooapp.mail_alias',
    controlLogics: [
      {
        eventNames: 'onMounted',
        itemName: 'ACTIVITY',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取视图上下文\nconst appEntityId = view.model.appDataEntityId;\nconst srfmodelname = appEntityId.split('.').pop(); // 取点号后最后一段\n\nview.params.srfmodelname = srfmodelname;",
        triggerType: 'CTRLEVENT',
        id: 'init_activity_params',
      },
      {
        eventNames: 'onControlEvent',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "if (triggerEventName && triggerEventName === 'onActive' && triggerEvent.ctrl.name == view.state.xdatacontrolname) {\n    if(triggerEvent.ctrl.name!=\"activity\"){\n        view.call('Edit', { \n            context: view.context,\n            params: view.params,\n            data: triggerEvent.data,\n            view,\n            ctrl: triggerEvent.ctrl,\n        });\n    }\n   \n}",
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onClick',
        itemName: 'activity_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"activity\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// activity不显示分组筛选\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(searchBar.state.selectedGroup&&searchBar.state.selectedGroup.length>0){\n      viewSession.selectedGroup = [...searchBar.state.selectedGroup];\n      searchBar.state.selectedGroup=[];\n  }\n  searchBar.state.selectedGroup=[];\n  searchBar.state.showGroup=false; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'activity_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'calendar_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"calendar\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// calendar不显示分组筛选\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(searchBar.state.selectedGroup&&searchBar.state.selectedGroup.length>0){\n      viewSession.selectedGroup = [...searchBar.state.selectedGroup];\n      searchBar.state.selectedGroup=[];\n  }\n  searchBar.state.showGroup=false; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'calendar_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'chart_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"chart\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}",
        triggerType: 'CTRLEVENT',
        id: 'chart_click',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "console.log(\"\");\nconst targets = ['dataview', 'grid', 'activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\n\nlet firstVisible = null;\nlet default_ctrl = null;\n// 从路由获取\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\nif(currentRoute.query.srfnav){\n  firstVisible = currentRoute.query.srfnav;\n  const toggleitem = view.layoutPanel.findPanelItemByName(firstVisible+'_toggle');\n  toggleitem.onClick();\n  //activectrlname.setDataValue(firstVisible);\n  //view.state.xdatacontrolname = firstVisible;\n}\n// 挂载清空缓存\nif(appSession.guard){\n    appSession.guard();\n    appSession.guard = undefined;\n}\nif(!appSession.guard){\n  //注册路由监听\n  const afterEachHook = ibiz.appUtil.router.afterEach((to, from) => {\n    let toUrlArray = to.path.split('/');\n    if(toUrlArray.length<=2){\n      return;\n    }\n    const viewName = toUrlArray[toUrlArray.length - 2];\n    // const pathNodes = ibiz.appUtil.route2routeObject().pathNodes;\n    // const viewName = toUrlArray[pathNodes.length - 1].viewName;\n    const cacheView = ibiz.appUtil.viewCacheCenter.get(viewName);\n    const toView = cacheView;\n    // const curView = cacheView ? cacheView : view;\n    console.log('目标视图----',toView);\n    // let toUrlArray = to.path.split('/');\n    // let fromUrlArray = from.path.split('/');\n    // if(toUrlArray.length<=2 || fromUrlArray.length<=2){\n    //   return;\n    // }\n    //判断是否支持切换器\n    if(toView){\n      if(toView.layoutPanel.findPanelItemByName(\"switch_panel\")){\n        var active_ctrl = to.query.srfnav;\n        if(active_ctrl){\n          const toggleitem = toView.layoutPanel.findPanelItemByName(active_ctrl+'_toggle');\n          toggleitem.onClick();\n        }else{\n          // 恢复默认部件\n          const toggleitem = toView.layoutPanel.findPanelItemByName(defaultctrlname.value+'_toggle');\n          toggleitem.onClick();\n        }\n      }\n    }\n  });\n  appSession.guard = afterEachHook;\n}\n// 查找第一个存在的部件\nlet ctrlcount = 0;\nfor (const name of targets) {\n  const item = view.getCtrl(\"\", name);\n  if (item) {\n     if(firstVisible == null){\n        firstVisible = name;\n        activectrlname.setDataValue(firstVisible);\n        view.state.xdatacontrolname = firstVisible;\n      }\n      if(default_ctrl == null){\n        default_ctrl = name;\n        defaultctrlname.setDataValue(default_ctrl);\n      }\n    ctrlcount++;\n  }\n}\n\n// 设置可见性状态\ntargets.forEach(name => {\n  const item = view.layoutPanel.findPanelItemByName(name);\n  if (item) {\n    item.state.visible = name === firstVisible;\n  }\n});\n\n// 仅一个部件时隐藏切换器\nif(ctrlcount == 1){\n   const switch_panel_container = view.layoutPanel.findPanelItemByName('switch_panel_container');\n     if (switch_panel_container) {\n      switch_panel_container.state.visible = false;\n    }\n}\n\nconst searchBar = view.getController('searchbar');\n//解决多数据部件异步加载导致重复加载问题\nif(searchBar.model.searchBarGroups.find(group=> group.defaultGroup)){\n    const item = view.layoutPanel.findPanelItemByName(view.state.xdatacontrolname);\n    item.control.state.loadDefault = false;\n}",
        triggerType: 'CTRLEVENT',
        id: 'ctrl_toggle_init',
      },
      {
        eventNames: 'onClick',
        itemName: 'dataview_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"dataview\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//恢复显示左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.showPanel();\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid', 'activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}",
        triggerType: 'CTRLEVENT',
        id: 'dataview_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'grid_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconsole.log(\"\");\nconst curctrl = \"grid\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//恢复显示左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.showPanel();\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\n\n//默认部件忽略参数\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'grid_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'hierarchy_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"hierarchy\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// hierarchy不显示分组筛选\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(searchBar.state.selectedGroup&&searchBar.state.selectedGroup.length>0){\n      viewSession.selectedGroup = [...searchBar.state.selectedGroup];\n      searchBar.state.selectedGroup=[];\n  }\n  searchBar.state.showGroup=false; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'hierarchy_click',
      },
      {
        eventNames: 'onControlEvent',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 多数据部件\nconst targets = [\n  'dataview',\n  'grid',\n  'activity',\n  'pivottable',\n  'calendar',\n  'chart',\n  'hierarchy',\n];\n// 获取搜索栏\nconst searchBar = view.getController('searchbar');\n// 处理多数据部件事件\nif (searchBar && targets.includes(triggerControlName)) {\n  // 表格默认不加载在执行execGroup时加载\n  if (triggerControlName === 'grid' ) {\n    triggerEvent.ctrl.state.loadDefault = false;\n  }\n  // 多数据部件初始化时合并搜索参数\n  if (triggerEventName === 'onCreated') {\n    triggerEvent.ctrl.state.searchParams = searchBar.getFilterParams();\n  }\n  // 多数据部件绘制完成后执行搜索栏分组\n  if (triggerEventName === 'onMounted') {\n    searchBar.execGroup();\n  }\n}",
        triggerType: 'CTRLEVENT',
        name: 'onControlEvent',
        id: 'oncontrolevent',
      },
      {
        eventNames: 'onClick',
        itemName: 'pivottable_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"pivottable\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}",
        triggerType: 'CTRLEVENT',
        id: 'pivottable_click',
      },
    ],
    controlParam: {},
    modelId: '4db373066a152684f6838426ca29b4a9',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'mdcustomview',
  },
  title: 'EMail别名',
  viewStyle: 'DEFAULT',
  viewType: 'DEMDCUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '40c8321d31e14a458a94959722bd0ecf',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_aliasmulti_data_view',
  id: 'ibizodooapp.mail_alias_multi_data_view',
};
