export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: 'bb52184ac8c57ed7540848c4f89aa393',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ALIAS_DOMAIN',
  },
  caption: '电子邮件域名',
  codeName: 'mail_alias_domain_pickup_view',
  appDataEntityId: 'ibizodooapp.mail_alias_domain',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.mail_alias_domain_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.mail_alias_domain',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MAIL_ALIAS_DOMAIN',
      },
      caption: '电子邮件域名',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_alias_domain',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_alias_domain',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '电子邮件域名数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1dd3e4547cbf746ff6465f832977c20d',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_alias_domainPickupView',
  id: 'ibizodooapp.mail_alias_domain_pickup_view',
};
