export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'main_view',
  deviewId: '114a0daecd5fba69a53e72823de7aac2',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ACTIVITY_TYPE',
  },
  caption: '活动类型',
  codeName: 'mail_activity_type_main_view',
  appDataEntityId: 'ibizodooapp.mail_activity_type',
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar2',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.mail_activity_type',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ibizodooapp.mail_activity_type',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ibizodooapp.mail_activity_type',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.mail_activity_type',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.mail_activity_type',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.mail_activity_type',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      showMaxLength: true,
                      editorParams: {
                        ISAUTO: 'true',
                      },
                      editorType: 'TEXTAREA',
                      placeHolder: '例如安排会议',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'category',
                        editor: {
                          singleSelect: true,
                          appCodeListId:
                            'ibizodooapp.mail__mail_activity_type_category',
                          editorType: 'DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'category',
                        },
                        allowEmpty: true,
                        needCodeListConfig: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.CATEGORY',
                        },
                        caption: '操作',
                        codeName: 'category',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'category',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'default_user_id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'default_user_id',
                        },
                        allowEmpty: true,
                        hidden: true,
                        capLanguageRes: {
                          lanResTag:
                            'DEF.LNAME.MAIL_ACTIVITY_TYPE.DEFAULT_USER_ID',
                        },
                        caption: '默认用户',
                        codeName: 'default_user_id',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'default_user_id',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'summary',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          placeHolder: '例如：讨论提案',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'summary',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.SUMMARY',
                        },
                        caption: '默认摘要',
                        codeName: 'summary',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'summary',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'icon',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'icon',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.ICON',
                        },
                        caption: '图标',
                        codeName: 'icon',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'icon',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'decoration_type',
                        editor: {
                          singleSelect: true,
                          appCodeListId:
                            'ibizodooapp.mail__mail_activity_type_decoration_type',
                          editorType: 'DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'decoration_type',
                        },
                        allowEmpty: true,
                        needCodeListConfig: true,
                        capLanguageRes: {
                          lanResTag:
                            'DEF.LNAME.MAIL_ACTIVITY_TYPE.DECORATION_TYPE',
                        },
                        caption: '排版类型',
                        codeName: 'decoration_type',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'decoration_type',
                      },
                      {
                        dataType: 9,
                        enableCond: 3,
                        inputTip: '在活动视图中保留标记为已完成的活动',
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'keep_done',
                        editor: {
                          editorType: 'CHECKBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'keep_done',
                        },
                        allowEmpty: true,
                        enableInputTip: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.KEEP_DONE',
                        },
                        caption: '保持完成',
                        codeName: 'keep_done',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'keep_done',
                      },
                    ],
                    caption: '活动设置',
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 12,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'chaining_type',
                        editor: {
                          singleSelect: true,
                          appCodeListId:
                            'ibizodooapp.mail__mail_activity_type_chaining_type',
                          editorType: 'DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'chaining_type',
                        },
                        needCodeListConfig: true,
                        capLanguageRes: {
                          lanResTag:
                            'DEF.LNAME.MAIL_ACTIVITY_TYPE.CHAINING_TYPE',
                        },
                        caption: '链接类型',
                        codeName: 'chaining_type',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'chaining_type',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        inputTip: '将当前活动标记为完成后，自动安排此活动。',
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'triggered_next_type_name',
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          pickupAppViewId:
                            'ibizodooapp.mail_activity_type_pickup_view',
                          handlerType: 'PickupText',
                          appDEACModeId: 'default',
                          appDEDataSetId: 'fetch_default',
                          appDataEntityId: 'ibizodooapp.mail_activity_type',
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'triggered_next_type_id',
                          editorParams: {
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'triggered_next_type_id',
                            },
                          ],
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'triggered_next_type_name',
                        },
                        resetItemNames: ['chaining_type'],
                        enableInputTip: true,
                        capLanguageRes: {
                          lanResTag:
                            'DEF.LNAME.MAIL_ACTIVITY_TYPE.TRIGGERED_NEXT_TYPE_ID',
                        },
                        caption: '触发方式',
                        codeName: 'triggered_next_type_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['chaining_type'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'chaining_type',
                                value: 'trigger',
                                logicType: 'SINGLE',
                                id: 'chaining_type等于(=) trigger',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'triggered_next_type_name',
                      },
                      {
                        dataType: 9,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'delay_count',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'delay_count',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_COUNT',
                        },
                        caption: '安排',
                        codeName: 'delay_count',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 8,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'delay_count',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'delay_unit',
                        editor: {
                          singleSelect: true,
                          appCodeListId:
                            'ibizodooapp.mail__mail_activity_type_delay_unit',
                          editorType: 'DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'delay_unit',
                        },
                        needCodeListConfig: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_UNIT',
                        },
                        caption: '延迟单位',
                        codeName: 'delay_unit',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 4,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'delay_unit',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'delay_from',
                        editor: {
                          singleSelect: true,
                          appCodeListId:
                            'ibizodooapp.mail__mail_activity_type_delay_from',
                          editorType: 'DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'delay_from',
                        },
                        needCodeListConfig: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_FROM',
                        },
                        caption: '延迟类型',
                        codeName: 'delay_from',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'delay_from',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'triggered_next_type_id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'triggered_next_type_id',
                        },
                        resetItemNames: ['chaining_type'],
                        allowEmpty: true,
                        hidden: true,
                        capLanguageRes: {
                          lanResTag:
                            'DEF.LNAME.MAIL_ACTIVITY_TYPE.TRIGGERED_NEXT_TYPE_ID',
                        },
                        caption: '触发方式',
                        codeName: 'triggered_next_type_id',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'triggered_next_type_id',
                      },
                    ],
                    caption: '下一个活动',
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 12,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel2',
                  },
                  {
                    dataType: 21,
                    enableCond: 3,
                    itemHeight: 220,
                    labelPos: 'TOP',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'default_note',
                    editor: {
                      editorHeight: 200,
                      editorType: 'HTMLEDITOR',
                      placeHolder: '例如：“查看报价并讨论细节”',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'default_note',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DEFAULT_NOTE',
                    },
                    caption: '默认备注',
                    codeName: 'default_note',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'default_note',
                  },
                ],
                caption: '活动类型基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main3',
        controlType: 'FORM',
        logicName: '活动类型实体主视图_表单',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: '936f4a9ba4f0fb89f4b8931d8a154a8f',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ibizodooapp.mail_activity_type.main3',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_view_toolbar1',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MAIL_ACTIVITY_TYPE',
        },
        caption: '活动类型',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.mail_activity_type',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'main_view_layout1',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new_没有评论区',
    appDataEntityId: 'ibizodooapp.mail_activity_type',
    controlLogics: [
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId); ',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", async  (state, isTrusted )=> {\n    console.log("");\n    const data = view.getController("form").getData()[0];\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\n});\n\nconst topContext = view.context;\nconst appEntityId = view.model.appDataEntityId;\nconst entityName = appEntityId.split(\'.\').pop();\nconst bExist = topContext[entityName];\nconst drbar = view.getCtrl("DRBAR", "drbar");\nif(!bExist){\n    drbar.disabled({ mode: \'BLANK\' })\n    //  drbar.disabled({ mode: \'MASK\' })\n\n}\n\n',
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\n   if (name === 'drbar') {\n      const topContext = view.context;\n      const appEntityId = view.model.appDataEntityId;\n      const entityName = appEntityId.split('.').pop();\n      const bExist = topContext[entityName];\n      if(!bExist){\n         ctrl?.disableCounter()\n      }\n   }\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '3ea3e353274bcb7a2bf0fee66c7d91cf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout1',
  },
  title: '活动类型',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '907503f1616b89a040384cde8e50e1c5',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_activity_typemain_view',
  id: 'ibizodooapp.mail_activity_type_main_view',
};
