export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'discuss_main_view',
  deviewId: '5d825023c2e71bcf6760859a92b5e213',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.MAIL_MESSAGE.DISCUSS_MAIN_VIEW',
  },
  caption: '讨论',
  codeName: 'mail_message_discuss_main_view',
  appDataEntityId: 'ibizodooapp.mail_message',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '讨论频道快速配置视图',
      refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
      name: 'EDITDATA@channels',
      id: 'editdata@channels',
    },
  ],
  controls: [
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '讨论频道主视图',
          refAppViewId: 'ibizodooapp.discuss_channel_main_view',
          name: 'EXPITEM:channels',
          id: 'expitem:channels',
        },
        {
          realTitle: '历史消息',
          realTitleLanguageRes: {
            lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.DISCUSS_HISTORY_LIST_VIEW',
          },
          refAppViewId: 'ibizodooapp.mail_message_discuss_history_list_view',
          name: 'EXPITEM:history',
          id: 'expitem:history',
        },
        {
          realTitle: '收件箱',
          realTitleLanguageRes: {
            lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.DISCUSS_INBOX_LIST_VIEW',
          },
          refAppViewId: 'ibizodooapp.mail_message_discuss_inbox_list_view',
          name: 'EXPITEM:inbox',
          id: 'expitem:inbox',
        },
        {
          realTitle: '讨论频道主视图',
          refAppViewId: 'ibizodooapp.discuss_channel_main_view',
          name: 'EXPITEM:private_channels',
          id: 'expitem:private_channels',
        },
        {
          realTitle: '星标消息',
          realTitleLanguageRes: {
            lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.DISCUSS_STARRED_LIST_VIEW',
          },
          refAppViewId: 'ibizodooapp.mail_message_discuss_starred_list_view',
          name: 'EXPITEM:starred',
          id: 'expitem:starred',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'inbox',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-收件箱（inbox）',
              id: '默认根节点（root）-收件箱（inbox）',
            },
            {
              childDETreeNodeId: 'channels',
              parentDETreeNodeId: 'channel',
              parentValueLevel: 1,
              searchMode: 3,
              id: '频道（channel）-频道（动态）（channels）',
            },
            {
              childDETreeNodeId: 'private_channels',
              parentDETreeNodeId: 'private_channel',
              parentValueLevel: 1,
              searchMode: 3,
              id: '私聊消息（private_channel）-私人频道（动态）（private_channels）',
            },
            {
              childDETreeNodeId: 'starred',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-星标消息（starred）',
              id: '默认根节点（root）-星标消息（starred）',
            },
            {
              childDETreeNodeId: 'history',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-历史（history）',
              id: '默认根节点（root）-历史（history）',
            },
            {
              childDETreeNodeId: 'channel',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-频道（node）',
              id: '默认根节点（root）-频道（node）',
            },
            {
              childDETreeNodeId: 'private_channel',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-私聊消息（privatechannel）',
              id: '默认根节点（root）-私聊消息（privatechannel）',
            },
          ],
          detreeNodes: [
            {
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              nodeValue: 'public',
              text: '频道',
              nodeType: 'channel',
              appDataEntityId: 'ibizodooapp.discuss_channel',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 250,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_discuss_main_view_channel_cm_deuiaction2_click@discuss_channel',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '频道管理',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-cog',
                      glyph: 'xf013@FontAwesome',
                    },
                    tooltip: '频道管理',
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 250,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_discuss_main_view_channel_cm_deuiaction1_click@discuss_channel',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '新建频道',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-plus',
                      glyph: 'xf067@FontAwesome',
                    },
                    tooltip: '新建频道',
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                toolbarStyle: 'CONTEXTMENU',
                codeName: 'discuss_main_view_channel_cm',
                controlType: 'CONTEXTMENU',
                logicName: '公共频道静态树节点工具栏',
                appDataEntityId: 'ibizodooapp.discuss_channel',
                controlParam: {
                  id: 'channel_cm',
                },
                modelId: 'aafe57e0288a1f7b21f312f6a826280a',
                modelType: 'PSDETOOLBAR',
                name: 'channel_cm',
                id: 'discuss_main_view_channel_cm',
              },
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '频道',
              id: 'channel',
            },
            {
              dataSourceType: 'DEDATASET',
              idAppDEFieldId: 'id',
              appDEDataSetId: 'fetch_cur_user_public',
              textAppDEFieldId: 'name',
              navAppViewId: 'ibizodooapp.discuss_channel_main_view',
              nodeType: 'channels',
              appDataEntityId: 'ibizodooapp.discuss_channel',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 200,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_discuss_main_view_channels_cm_deuiaction2_click@discuss_channel',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '频道管理',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-cog',
                      glyph: 'xf013@FontAwesome',
                    },
                    tooltip: '频道管理',
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 200,
                    noPrivDisplayMode: 2,
                    uiactionId: 'action_unfollow@discuss_channel',
                    uiactionTarget: 'SINGLEKEY',
                    valid: true,
                    caption: '离开频道',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-remove',
                      glyph: 'xf00d@FontAwesome',
                    },
                    tooltip: '离开频道',
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'open_chat@discuss_channel',
                    uiactionTarget: 'SINGLEKEY',
                    valid: true,
                    caption: '打开聊天',
                    itemType: 'DEUIACTION',
                    tooltip: '打开聊天',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction3',
                  },
                ],
                toolbarStyle: 'CONTEXTMENU',
                codeName: 'discuss_main_view_channels_cm',
                controlType: 'CONTEXTMENU',
                logicName: '公共频道动态树节点工具栏',
                appDataEntityId: 'ibizodooapp.discuss_channel',
                controlParam: {
                  id: 'channels_cm',
                },
                modelId: '2250a2eeca436224b177d6b2154c7ec6',
                modelType: 'PSDETOOLBAR',
                name: 'channels_cm',
                id: 'discuss_main_view_channels_cm',
              },
              detreeNodeRVs: [
                {
                  refAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
                  name: 'EDITDATA',
                  id: 'editdata',
                },
              ],
              treeNodeType: 'DE',
              controlRenders: [
                {
                  layoutPanel: {
                    layoutMode: 'FLEX',
                    layout: {
                      layout: 'FLEX',
                    },
                    rootPanelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              sysImage: {
                                rawContent:
                                  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 530.06 530.06">\n<circle cx="265.03" cy="265.03" r="265.03" fill="hsl(257, 43%, 45%)"/>\n<path d="M416.74,217.29l5-28a8.4,8.4,0,0,0-8.27-9.88H361.09l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H334.61a8.4,8.4,0,0,0-8.27,6.93L315.57,179.4H246.5l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H220a8.4,8.4,0,0,0-8.27,6.93L201,179.4H145.6a8.42,8.42,0,0,0-8.28,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H193l-16,89.62H121.59a8.4,8.4,0,0,0-8.27,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H169L158.73,416a8.4,8.4,0,0,0,8.27,9.88h28.45a8.42,8.42,0,0,0,8.28-6.93l10.76-60.29h69.07L273.32,416a8.4,8.4,0,0,0,8.27,9.88H310a8.4,8.4,0,0,0,8.27-6.93l10.77-60.29h55.38a8.41,8.41,0,0,0,8.28-6.93l5-28a8.4,8.4,0,0,0-8.27-9.88H337.08l16-89.62h55.38A8.4,8.4,0,0,0,416.74,217.29ZM291.56,313.84H222.5l16-89.62h69.07Z" fill="#ffffff"/>\n</svg>',
                              },
                              contentType: 'IMAGE',
                              predefinedType: 'STATIC_IMAGE',
                              rawItemHeight: 24,
                              rawItemWidth: 24,
                              id: 'static_image',
                            },
                            caption: '图片',
                            contentHeight: 24,
                            contentWidth: 24,
                            height: 24,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              height: 24,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 24,
                              widthMode: 'PX',
                            },
                            sysImage: {
                              rawContent:
                                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 530.06 530.06">\n<circle cx="265.03" cy="265.03" r="265.03" fill="hsl(257, 43%, 45%)"/>\n<path d="M416.74,217.29l5-28a8.4,8.4,0,0,0-8.27-9.88H361.09l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H334.61a8.4,8.4,0,0,0-8.27,6.93L315.57,179.4H246.5l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H220a8.4,8.4,0,0,0-8.27,6.93L201,179.4H145.6a8.42,8.42,0,0,0-8.28,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H193l-16,89.62H121.59a8.4,8.4,0,0,0-8.27,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H169L158.73,416a8.4,8.4,0,0,0,8.27,9.88h28.45a8.42,8.42,0,0,0,8.28-6.93l10.76-60.29h69.07L273.32,416a8.4,8.4,0,0,0,8.27,9.88H310a8.4,8.4,0,0,0,8.27-6.93l10.77-60.29h55.38a8.41,8.41,0,0,0,8.28-6.93l5-28a8.4,8.4,0,0,0-8.27-9.88H337.08l16-89.62h55.38A8.4,8.4,0,0,0,416.74,217.29ZM291.56,313.84H222.5l16-89.62h69.07Z" fill="#ffffff"/>\n</svg>',
                            },
                            width: 24,
                            showCaption: true,
                            id: 'static_image',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'name',
                            },
                            viewFieldName: 'name',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERSMALL',
                            },
                            id: 'name',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 32,
                        height: 32,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          height: 32,
                          heightMode: 'PX',
                          layout: 'FLEX',
                        },
                        id: 'container',
                      },
                    ],
                    layoutPanel: true,
                    mobilePanel: true,
                    codeName: 'discuss_sidebar_node_panel',
                    controlType: 'PANEL',
                    logicName: '讨论边栏节点绘制面板',
                    appDataEntityId: 'ibizodooapp.discuss_channel',
                    controlParam: {},
                    modelId: 'f6923ad9acfcc7058fb95cd9b0f9599b',
                    modelType: 'PSSYSVIEWPANEL',
                    name: 'public_channels_layout',
                    id: 'ibizodooapp.discuss_channel.discuss_sidebar_node_panel',
                  },
                  renderType: 'LAYOUTPANEL',
                  id: 'public_channels_layout',
                },
                {
                  layoutPanel: {
                    layoutMode: 'TABLE_24COL',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    rootPanelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              editorType: 'TEXTBOX',
                              predefinedType: 'FIELD_TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'name',
                            },
                            viewFieldName: 'name',
                            allowEmpty: true,
                            caption: '文本框',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'name',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'container',
                      },
                    ],
                    layoutPanel: true,
                    mobilePanel: true,
                    codeName: 'create_public_channel_node_panel',
                    controlType: 'PANEL',
                    logicName: '创建公共频道节点面板',
                    appDataEntityId: 'ibizodooapp.mail_message',
                    controlParam: {},
                    modelId: '31484271ac3a1f60becc2343cb10c100',
                    modelType: 'PSSYSVIEWPANEL',
                    name: 'newnoderender_channels',
                    id: 'ibizodooapp.mail_message.create_public_channel_node_panel',
                  },
                  renderType: 'LAYOUTPANEL',
                  id: 'newnoderender_channels',
                },
              ],
              name: '频道（动态）',
              id: 'channels',
            },
            {
              text: '历史',
              navAppViewId:
                'ibizodooapp.mail_message_discuss_history_list_view',
              nodeType: 'history',
              sysImage: {
                cssClass: 'fa fa-history',
                glyph: 'xf1da@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '历史',
              id: 'history',
            },
            {
              text: '收件箱',
              navAppViewId: 'ibizodooapp.mail_message_discuss_inbox_list_view',
              nodeType: 'inbox',
              sysImage: {
                cssClass: 'fa fa-inbox',
                glyph: 'xf01c@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '收件箱',
              id: 'inbox',
            },
            {
              nodeValue: 'private',
              text: '私聊消息',
              nodeType: 'private_channel',
              appDataEntityId: 'ibizodooapp.discuss_channel',
              decontextMenu: {
                detoolbarItems: [
                  {
                    actionLevel: 250,
                    noPrivDisplayMode: 2,
                    uiactionId:
                      'toolbar_discuss_main_view_private_channel_cm_deuiaction1_click@discuss_channel',
                    uiactionTarget: 'SINGLEDATA',
                    valid: true,
                    caption: '新建频道',
                    itemType: 'DEUIACTION',
                    sysImage: {
                      cssClass: 'fa fa-plus',
                      glyph: 'xf067@FontAwesome',
                    },
                    tooltip: '新建频道',
                    showIcon: true,
                    id: 'deuiaction1',
                  },
                ],
                toolbarStyle: 'CONTEXTMENU',
                codeName: 'discuss_main_view_private_channel_cm',
                controlType: 'CONTEXTMENU',
                logicName: '私聊频道静态树节点工具栏',
                appDataEntityId: 'ibizodooapp.discuss_channel',
                controlParam: {
                  id: 'private_channel_cm',
                },
                modelId: '54bafcae58941c3285482069c93b3bac',
                modelType: 'PSDETOOLBAR',
                name: 'private_channel_cm',
                id: 'discuss_main_view_private_channel_cm',
              },
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '私聊消息',
              id: 'private_channel',
            },
            {
              dataSourceType: 'DEDATASET',
              idAppDEFieldId: 'id',
              appDEDataSetId: 'fetch_group_private',
              textAppDEFieldId: 'name',
              navAppViewId: 'ibizodooapp.discuss_channel_main_view',
              nodeType: 'private_channels',
              appDataEntityId: 'ibizodooapp.discuss_channel',
              treeNodeType: 'DE',
              controlRenders: [
                {
                  layoutPanel: {
                    layoutMode: 'FLEX',
                    layout: {
                      layout: 'FLEX',
                    },
                    rootPanelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              sysImage: {
                                rawContent:
                                  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 530.06 530.06">\n<circle cx="265.03" cy="265.03" r="265.03" fill="hsl(257, 43%, 45%)"/>\n<path d="M416.74,217.29l5-28a8.4,8.4,0,0,0-8.27-9.88H361.09l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H334.61a8.4,8.4,0,0,0-8.27,6.93L315.57,179.4H246.5l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H220a8.4,8.4,0,0,0-8.27,6.93L201,179.4H145.6a8.42,8.42,0,0,0-8.28,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H193l-16,89.62H121.59a8.4,8.4,0,0,0-8.27,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H169L158.73,416a8.4,8.4,0,0,0,8.27,9.88h28.45a8.42,8.42,0,0,0,8.28-6.93l10.76-60.29h69.07L273.32,416a8.4,8.4,0,0,0,8.27,9.88H310a8.4,8.4,0,0,0,8.27-6.93l10.77-60.29h55.38a8.41,8.41,0,0,0,8.28-6.93l5-28a8.4,8.4,0,0,0-8.27-9.88H337.08l16-89.62h55.38A8.4,8.4,0,0,0,416.74,217.29ZM291.56,313.84H222.5l16-89.62h69.07Z" fill="#ffffff"/>\n</svg>',
                              },
                              contentType: 'IMAGE',
                              predefinedType: 'STATIC_IMAGE',
                              rawItemHeight: 24,
                              rawItemWidth: 24,
                              id: 'static_image',
                            },
                            caption: '图片',
                            contentHeight: 24,
                            contentWidth: 24,
                            height: 24,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              height: 24,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 24,
                              widthMode: 'PX',
                            },
                            sysImage: {
                              rawContent:
                                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 530.06 530.06">\n<circle cx="265.03" cy="265.03" r="265.03" fill="hsl(257, 43%, 45%)"/>\n<path d="M416.74,217.29l5-28a8.4,8.4,0,0,0-8.27-9.88H361.09l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H334.61a8.4,8.4,0,0,0-8.27,6.93L315.57,179.4H246.5l10.24-57.34a8.4,8.4,0,0,0-8.27-9.88H220a8.4,8.4,0,0,0-8.27,6.93L201,179.4H145.6a8.42,8.42,0,0,0-8.28,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H193l-16,89.62H121.59a8.4,8.4,0,0,0-8.27,6.93l-5,28a8.4,8.4,0,0,0,8.27,9.88H169L158.73,416a8.4,8.4,0,0,0,8.27,9.88h28.45a8.42,8.42,0,0,0,8.28-6.93l10.76-60.29h69.07L273.32,416a8.4,8.4,0,0,0,8.27,9.88H310a8.4,8.4,0,0,0,8.27-6.93l10.77-60.29h55.38a8.41,8.41,0,0,0,8.28-6.93l5-28a8.4,8.4,0,0,0-8.27-9.88H337.08l16-89.62h55.38A8.4,8.4,0,0,0,416.74,217.29ZM291.56,313.84H222.5l16-89.62h69.07Z" fill="#ffffff"/>\n</svg>',
                            },
                            width: 24,
                            showCaption: true,
                            id: 'static_image',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'name',
                            },
                            viewFieldName: 'name',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERSMALL',
                            },
                            id: 'name',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 32,
                        height: 32,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          height: 32,
                          heightMode: 'PX',
                          layout: 'FLEX',
                        },
                        id: 'container',
                      },
                    ],
                    layoutPanel: true,
                    mobilePanel: true,
                    codeName: 'discuss_sidebar_node_panel',
                    controlType: 'PANEL',
                    logicName: '讨论边栏节点绘制面板',
                    appDataEntityId: 'ibizodooapp.discuss_channel',
                    controlParam: {},
                    modelId: 'f6923ad9acfcc7058fb95cd9b0f9599b',
                    modelType: 'PSSYSVIEWPANEL',
                    name: 'private_channels_layout',
                    id: 'ibizodooapp.discuss_channel.discuss_sidebar_node_panel',
                  },
                  renderType: 'LAYOUTPANEL',
                  id: 'private_channels_layout',
                },
              ],
              name: '私人频道（动态）',
              id: 'private_channels',
            },
            {
              text: '星标消息',
              navAppViewId:
                'ibizodooapp.mail_message_discuss_starred_list_view',
              nodeType: 'starred',
              sysImage: {
                cssClass: 'fa fa-star-o',
                glyph: 'xf006@FontAwesome',
              },
              treeNodeType: 'STATIC',
              name: '星标消息',
              id: 'starred',
            },
          ],
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'ibizodooapp.mail_message',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'ibizodooapp.mail_message',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'ibizodooapp.mail_message',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'ibizodooapp.mail_message',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'ibizodooapp.mail_message',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          controls: [
            {
              detoolbarItems: [
                {
                  actionLevel: 250,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_discuss_main_view_channel_cm_deuiaction2_click@discuss_channel',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '频道管理',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-cog',
                    glyph: 'xf013@FontAwesome',
                  },
                  tooltip: '频道管理',
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 250,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_discuss_main_view_channel_cm_deuiaction1_click@discuss_channel',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '新建频道',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-plus',
                    glyph: 'xf067@FontAwesome',
                  },
                  tooltip: '新建频道',
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              toolbarStyle: 'CONTEXTMENU',
              codeName: 'discuss_main_view_channel_cm',
              controlType: 'CONTEXTMENU',
              logicName: '公共频道静态树节点工具栏',
              appDataEntityId: 'ibizodooapp.discuss_channel',
              controlParam: {
                id: 'channel_cm',
              },
              modelId: 'aafe57e0288a1f7b21f312f6a826280a',
              modelType: 'PSDETOOLBAR',
              name: 'channel_cm',
              id: 'discuss_main_view_channel_cm',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 200,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_discuss_main_view_channels_cm_deuiaction2_click@discuss_channel',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '频道管理',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-cog',
                    glyph: 'xf013@FontAwesome',
                  },
                  tooltip: '频道管理',
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 200,
                  noPrivDisplayMode: 2,
                  uiactionId: 'action_unfollow@discuss_channel',
                  uiactionTarget: 'SINGLEKEY',
                  valid: true,
                  caption: '离开频道',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-remove',
                    glyph: 'xf00d@FontAwesome',
                  },
                  tooltip: '离开频道',
                  showIcon: true,
                  id: 'deuiaction1',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'open_chat@discuss_channel',
                  uiactionTarget: 'SINGLEKEY',
                  valid: true,
                  caption: '打开聊天',
                  itemType: 'DEUIACTION',
                  tooltip: '打开聊天',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction3',
                },
              ],
              toolbarStyle: 'CONTEXTMENU',
              codeName: 'discuss_main_view_channels_cm',
              controlType: 'CONTEXTMENU',
              logicName: '公共频道动态树节点工具栏',
              appDataEntityId: 'ibizodooapp.discuss_channel',
              controlParam: {
                id: 'channels_cm',
              },
              modelId: '2250a2eeca436224b177d6b2154c7ec6',
              modelType: 'PSDETOOLBAR',
              name: 'channels_cm',
              id: 'discuss_main_view_channels_cm',
            },
            {
              detoolbarItems: [
                {
                  actionLevel: 250,
                  noPrivDisplayMode: 2,
                  uiactionId:
                    'toolbar_discuss_main_view_private_channel_cm_deuiaction1_click@discuss_channel',
                  uiactionTarget: 'SINGLEDATA',
                  valid: true,
                  caption: '新建频道',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-plus',
                    glyph: 'xf067@FontAwesome',
                  },
                  tooltip: '新建频道',
                  showIcon: true,
                  id: 'deuiaction1',
                },
              ],
              toolbarStyle: 'CONTEXTMENU',
              codeName: 'discuss_main_view_private_channel_cm',
              controlType: 'CONTEXTMENU',
              logicName: '私聊频道静态树节点工具栏',
              appDataEntityId: 'ibizodooapp.discuss_channel',
              controlParam: {
                id: 'private_channel_cm',
              },
              modelId: '54bafcae58941c3285482069c93b3bac',
              modelType: 'PSDETOOLBAR',
              name: 'private_channel_cm',
              id: 'discuss_main_view_private_channel_cm',
            },
          ],
          codeName: 'discuss_tree',
          controlType: 'TREEVIEW',
          logicName: '讨论边栏树',
          appDataEntityId: 'ibizodooapp.mail_message',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysCss: {
            cssName: 'discuss_tree_node',
          },
          modelId: '2da852397458eaf071df48756475a139',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'ibizodooapp.mail_message.discuss_tree',
        },
      ],
      codeName: 'discuss_main_view_treeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: 'f19efa06b2f5c01167feac6d3f7f07cc_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'discuss_main_view_treeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.MAIL_MESSAGE.DISCUSS_MAIN_VIEW',
      },
      caption: '讨论',
      codeName: 'discuss_main_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.mail_message',
      controlParam: {},
      name: 'captionbar',
      id: 'discuss_main_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.mail_message',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '讨论',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.MAIL_MESSAGE.DISCUSS_MAIN_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f19efa06b2f5c01167feac6d3f7f07cc',
  modelType: 'PSAPPDEVIEW',
  name: 'mail_messagediscuss_main_view',
  id: 'ibizodooapp.mail_message_discuss_main_view',
};
