export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'InstalledGridView',
  deviewId: '2a079c78777cc3a3988b6e902881e0ba',
  accUserMode: 2,
  caption: '已安装应用',
  codeName: 'ps_core_prd_func_installed_grid_view',
  appDataEntityId: 'ibizodooapp.pscoreprdfunc',
  appViewNavParams: [
    {
      rawValue: true,
      key: 'n_funcstate_eq',
      value: '1',
      id: 'n_funcstate_eq',
    },
    {
      key: 'n_pscoreprdid_eq',
      value: 'srfv2systemid',
      id: 'n_pscoreprdid_eq',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'ibizodooapp.ps_core_prd_func_info_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.ps_core_prd_func_info_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'ibizodooapp.ps_core_prd_func_info_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.ps_core_prd_func_info_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '核心产品功能编辑视图',
        refAppViewId: 'ibizodooapp.ps_core_prd_func_info_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '核心产品功能编辑视图',
        refAppViewId: 'ibizodooapp.ps_core_prd_func_info_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem5',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_editaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.EDIT',
            },
            caption: '编辑',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-edit',
              glyph: 'xf044@FontAwesome',
            },
            tooltip: '编辑',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.EDIT',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem2',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_copyaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.COPY',
            },
            caption: '拷贝',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-copy',
              glyph: 'xf0c5@FontAwesome',
            },
            tooltip: '拷贝',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.COPY',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem1',
          },
          {
            itemType: 'SEPERATOR',
            id: 'tbitem15',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_removeaction',
            uiactionTarget: 'MULTIKEY',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.REMOVE',
            },
            caption: '删除',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-remove',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '删除',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.REMOVE',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem8',
          },
          {
            itemType: 'SEPERATOR',
            id: 'tbitem16',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_exportaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.EXPORT',
            },
            caption: '导出',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-excel-o',
              glyph: 'xf1c3@FontAwesome',
            },
            tooltip: '导出',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.EXPORT',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem3',
          },
          {
            itemType: 'SEPERATOR',
            id: 'tbitem17',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_exportxmlaction',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'MENUITEM.CAPTION.*.EXPORTSRF',
                },
                caption: '导出数据模型',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-download',
                  glyph: 'xf019@FontAwesome',
                },
                tooltip: '导出数据模型',
                showCaption: true,
                showIcon: true,
                id: 'tbitem24',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_importbar',
                valid: true,
                caption: '数据导入',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-upload',
                  glyph: 'xf093@FontAwesome',
                },
                tooltip: '数据导入',
                showCaption: true,
                showIcon: true,
                id: 'tbitem25',
              },
            ],
            valid: true,
            caption: '其它',
            itemType: 'ITEMS',
            tooltip: '其它',
            showCaption: true,
            showIcon: true,
            id: 'tbitem20',
          },
          {
            itemType: 'SEPERATOR',
            id: 'tbitem21',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_searchbar',
            enableToggleMode: true,
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.FILTER',
            },
            caption: '过滤',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-filter',
              glyph: 'xf0b0@FontAwesome',
            },
            tooltip: '过滤',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.FILTER',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem10',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_helpaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.HELP',
            },
            caption: '帮助',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-question',
              glyph: 'xf128@FontAwesome',
            },
            tooltip: '帮助',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.HELP',
            },
            showCaption: true,
            showIcon: true,
            id: 'tbitem4',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'installed_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认表格界面）',
        appDataEntityId: 'ibizodooapp.pscoreprdfunc',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'ec6fbb681f5e3e6783c2af57e5eefaaa',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'installed_grid_view_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        orderValueAppDEFieldId: 'ordervalue',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'pscoreprdfuncname',
            excelCaption: '应用',
            appDEFieldId: 'pscoreprdfuncname',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '应用',
            codeName: 'pscoreprdfuncname',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'pscoreprdfuncname',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'memo',
            excelCaption: '描述',
            appDEFieldId: 'memo',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '描述',
            codeName: 'memo',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'memo',
          },
          {
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  caption: '卸载',
                  detailType: 'DEUIACTION',
                  uiactionId: 'uninstall@pscoreprdfunc',
                  showCaption: true,
                  showIcon: true,
                  sysCss: {
                    cssName: 'red-span',
                  },
                  id: 'u3656f01',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  caption: '详情',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_app_detail_view_logic@pscoreprdfunc',
                  showCaption: true,
                  showIcon: true,
                  id: 'u0c1c246',
                },
              ],
              appDataEntityId: 'ibizodooapp.pscoreprdfunc',
              uniqueTag: 'PSCorePrdFunc__Usr0728525275',
              name: '表格操作列界面行为组',
              id: 'usr0728525275',
            },
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '操作',
            codeName: 'uagridcolumn1',
            columnType: 'UAGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            id: 'uagridcolumn1',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'pscoreprdfuncname',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pscoreprdfuncname',
          },
          {
            appDEFieldId: 'memo',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'memo',
          },
          {
            appDEFieldId: 'avatarurl',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'avatarurl',
          },
          {
            appDEFieldId: 'functype',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'functype',
          },
          {
            appDEFieldId: 'funcstate',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'funcstate',
          },
          {
            appDEFieldId: 'pscoreprdfuncid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pscoreprdfuncid',
          },
          {
            appDEFieldId: 'pscoreprdfuncid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'pscoreprdfuncid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'pscoreprdfuncname',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmstag',
          },
        ],
        degridEditItems: [
          {
            caption: '核心产品功能标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'pscoreprdfuncid',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetchdefault',
          appDataEntityId: 'ibizodooapp.pscoreprdfunc',
          id: 'fetch',
        },
        removeControlAction: {
          appDataEntityId: 'ibizodooapp.pscoreprdfunc',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'ibizodooapp.pscoreprdfunc',
        controlParam: {
          id: 'grid',
        },
        modelId: '9595d01fdf03505df3ce7d640424a983',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'ibizodooapp.pscoreprdfunc.main',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'default',
        controlType: 'SEARCHFORM',
        logicName: '默认搜索表单',
        appDataEntityId: 'ibizodooapp.pscoreprdfunc',
        controlParam: {
          id: 'searchform',
        },
        modelId: '4fa17f094f95c5f4744980248ec18c35',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'ibizodooapp.pscoreprdfunc.default',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        codeName: 'quick_search',
        controlType: 'SEARCHBAR',
        logicName: '快速搜索栏',
        appDataEntityId: 'ibizodooapp.pscoreprdfunc',
        controlParam: {
          ctrlParams: {
            TELEPORTTAG: '#breadcrumb-nav-pos-searchbar',
          },
          id: 'searchbar',
        },
        modelId: '5a6dc1b2f0803a6a9ce835903c7b0ec9',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'ibizodooapp.pscoreprdfunc.quick_search',
      },
      {
        caption: '已安装应用',
        codeName: 'installed_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.pscoreprdfunc',
        controlParam: {},
        name: 'captionbar',
        id: 'installed_grid_view_captionbar',
      },
    ],
    codeName: 'usr1213474323',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'InstalledGridView表格视图布局',
    appDataEntityId: 'ibizodooapp.pscoreprdfunc',
    controlParam: {},
    modelId: 'e995629642b0623c4f11b6abd60d33a3',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr1213474323',
  },
  title: '已安装应用',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '445f18413fb00c7a83b2a000032adb2f',
  modelType: 'PSAPPDEVIEW',
  name: 'PSCorePrdFuncInstalledGridView',
  id: 'ibizodooapp.ps_core_prd_func_installed_grid_view',
};
