export default {
  mdctrlActiveMode: 1,
  loadDefault: true,
  deviewCodeName: 'multi_data_view',
  deviewId: 'a71cfa0d180896dc092afee0852087e4',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_PARTNER',
  },
  caption: '联系人',
  codeName: 'res_partner_multi_data_view',
  appDataEntityId: 'ibizodooapp.res_partner',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '搜索栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-columns',
                            glyph: 'xf0db@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="dataview" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'dataview_toggle',
                        },
                        caption: '卡片',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'dataview_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "dataview")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'visable_card',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-columns',
                          glyph: 'xf0db@FontAwesome',
                        },
                        showCaption: true,
                        id: 'dataview_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-reorder',
                            glyph: 'xf0c9@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="grid" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'grid_toggle',
                        },
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'grid_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "grid")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'visable_grid',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-reorder',
                          glyph: 'xf0c9@FontAwesome',
                        },
                        showCaption: true,
                        id: 'grid_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-clock-o',
                            glyph: 'xf017@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="activity" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'activity_toggle',
                        },
                        caption: '活动',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'activity_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              '\nview.layoutPanel.model.controls.find(ctrl=>ctrl.name === "activity")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'visable_activity',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-clock-o',
                          glyph: 'xf017@FontAwesome',
                        },
                        showCaption: true,
                        id: 'activity_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-table',
                            glyph: 'xf0ce@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="pivottable" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'pivottable_toggle',
                        },
                        caption: '透视表',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'pivottable_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.getCtrl("GRID", "pivottable")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'pivottable_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-table',
                          glyph: 'xf0ce@FontAwesome',
                        },
                        showCaption: true,
                        id: 'pivottable_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-calendar',
                            glyph: 'xf073@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="calendar" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'calendar_toggle',
                        },
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'calendar_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "calendar")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'calendar_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-calendar',
                          glyph: 'xf073@FontAwesome',
                        },
                        showCaption: true,
                        id: 'calendar_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-area-chart',
                            glyph: 'xf1fe@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="chart" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          id: 'chart_toggle',
                        },
                        caption: '图表',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'chart_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "chart")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'chart_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-area-chart',
                          glyph: 'xf1fe@FontAwesome',
                        },
                        showCaption: true,
                        id: 'chart_toggle',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-sitemap',
                            glyph: 'xf0e8@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          dynaClass:
                            '{"ctrl-switch-active": data.active_ctrl ==="hierarchy" }',
                          sysCss: {
                            cssName: 'ctrl-switch',
                          },
                          predefinedType: 'STATIC_IMAGE',
                          tooltip: '层级',
                          id: 'hierarchy_toggle',
                        },
                        caption: '图表',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        controlLogics: [
                          {
                            itemName: 'hierarchy_toggle',
                            logicTag: 'layoutpanel',
                            logicType: 'SCRIPT',
                            scriptCode:
                              'view.layoutPanel.model.controls.find(ctrl=>ctrl.name === "hierarchy")?true:false',
                            triggerType: 'ITEMVISIBLE',
                            id: 'hierarchy_visable',
                          },
                        ],
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        sysCss: {
                          cssName: 'ctrl-switch',
                        },
                        sysImage: {
                          cssClass: 'fa fa-sitemap',
                          glyph: 'xf0e8@FontAwesome',
                        },
                        showCaption: true,
                        id: 'hierarchy_toggle',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 0,
                      layout: 'FLEX',
                    },
                    id: 'switch_panel_container',
                  },
                  {
                    editor: {
                      editorType: 'HIDDEN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'active_ctrl',
                    },
                    viewFieldName: 'active_ctrl',
                    allowEmpty: true,
                    hidden: true,
                    caption: '文本(动态)',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysCss: {
                      cssName: 'ctrl-switch-active',
                    },
                    id: 'active_ctrl',
                  },
                  {
                    editor: {
                      editorType: 'HIDDEN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'default_ctrl',
                    },
                    viewFieldName: 'default_ctrl',
                    allowEmpty: true,
                    hidden: true,
                    caption: '文本(动态)',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'default_ctrl',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingLeft: 'INNERMEDIUM',
                  spacingRight: 'INNERMEDIUM',
                },
                id: 'switch_panel',
              },
            ],
            predefinedType: 'PANELPART',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '引用布局面板',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'panelpart',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '数据视图',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'dataview',
          },
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
          {
            caption: '活动',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'activity',
          },
          {
            caption: '日历',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'calendar',
          },
          {
            caption: '图表',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'chart',
          },
          {
            caption: '层级',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'hierarchy',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'ibizodooapp.res_partner_main_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.res_partner_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'ibizodooapp.res_partner_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.res_partner_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '联系人',
        refAppViewId: 'ibizodooapp.res_partner_main_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '联系人',
        refAppViewId: 'ibizodooapp.res_partner_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'write_date',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'complete_name',
            excelCaption: '名称',
            appDEFieldId: 'complete_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.COMPLETE_NAME',
            },
            caption: '名称',
            codeName: 'complete_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'complete_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'phone',
            excelCaption: '电话',
            appDEFieldId: 'phone',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.PHONE',
            },
            caption: '电话',
            codeName: 'phone',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'phone',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'mobile',
            excelCaption: '手机',
            appDEFieldId: 'mobile',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.MOBILE',
            },
            caption: '手机',
            codeName: 'mobile',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'mobile',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'email',
            excelCaption: '邮箱',
            appDEFieldId: 'email',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.EMAIL',
            },
            caption: '邮箱',
            codeName: 'email',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'email',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'user_name',
            excelCaption: '业务员',
            appDEFieldId: 'user_name',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.USER_ID',
            },
            caption: '业务员',
            codeName: 'user_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'user_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'street',
            excelCaption: '街道',
            appDEFieldId: 'street',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.STREET',
            },
            caption: '街道',
            codeName: 'street',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'street',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'city',
            excelCaption: '城市',
            appDEFieldId: 'city',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.CITY',
            },
            caption: '城市',
            codeName: 'city',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'city',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'country_name',
            excelCaption: '国家/地区',
            appDEFieldId: 'country_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.COUNTRY_ID',
            },
            caption: '国家/地区',
            codeName: 'country_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'country_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'company_name',
            excelCaption: '公司',
            appDEFieldId: 'company_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.COMPANY_NAME',
            },
            caption: '公司',
            codeName: 'company_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'company_name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'complete_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'complete_name',
          },
          {
            appDEFieldId: 'phone',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'phone',
          },
          {
            appDEFieldId: 'mobile',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'mobile',
          },
          {
            appDEFieldId: 'email',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'email',
          },
          {
            appDEFieldId: 'user_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'user_name',
          },
          {
            appDEFieldId: 'street',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'street',
          },
          {
            appDEFieldId: 'city',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'city',
          },
          {
            appDEFieldId: 'country_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'country_name',
          },
          {
            appDEFieldId: 'company_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'company_name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'commercial_partner_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'commercial_partner_id',
          },
          {
            appDEFieldId: 'company_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'company_id',
          },
          {
            appDEFieldId: 'user_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'user_id',
          },
          {
            appDEFieldId: 'buyer_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'buyer_id',
          },
          {
            appDEFieldId: 'country_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'country_id',
          },
          {
            appDEFieldId: 'parent_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'parent_id',
          },
          {
            appDEFieldId: 'state_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'state_id',
          },
          {
            appDEFieldId: 'industry_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'industry_id',
          },
          {
            appDEFieldId: 'property_purchase_currency_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'property_purchase_currency_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '业务员',
            codeName: 'user_name',
            enableCond: 3,
            appDEFieldId: 'user_name',
            editor: {
              singleSelect: true,
              appDEACModeId: 'default',
              appDEDataSetId: 'fetch_default',
              appDataEntityId: 'ibizodooapp.res_users',
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              valueItemName: 'user_id',
              editorParams: {
                URL: '/res_users/fetch_simple',
                ISSHOWTAB: 'false',
                USERMAP: '{"id":"id","name":"name","avatar":"avatar"}',
                userauthentity: 'ibizodooapp.res_users',
                AC: 'TRUE',
                USERMETHOD: 'post',
                TRIGGER: 'TRUE',
                PICKUPVIEW: 'FALSE',
              },
              editorStyle: 'PERSONEL_SELECT_USER_ALL',
              editorType: 'PICKEREX_TRIGGER',
              editorItems: [{}],
              sysPFPluginId: 'person_select',
              valueType: 'SIMPLE',
              editable: true,
              id: 'user_name',
            },
            allowEmpty: true,
            id: 'user_name',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
          {
            enableCond: 3,
            appDEFieldId: 'user_id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
            },
            allowEmpty: true,
            id: 'user_id',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'ibizodooapp.res_partner',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.res_partner',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'ibizodooapp.res_partner',
        controlParam: {
          id: 'grid',
        },
        modelId: 'd9c2d74944ae18e13f91a0f5f3c8c8b1',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'ibizodooapp.res_partner.main',
      },
      {
        cardColLG: 6,
        cardColMD: 8,
        cardColSM: 12,
        cardColXS: 12,
        cardHeight: 150,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorParams: {
                              SHOWNAMETEXT: 'false',
                              avatarfield: 'avatar',
                            },
                            editorStyle: 'ODOO_PERSONNEL_INFO',
                            editorType: 'SPAN',
                            sysPFPluginId: 'odoo_personnel_info',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'personal_info',
                          },
                          viewFieldName: 'NAME',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'personal_info',
                        },
                        {
                          editor: {
                            editorType: 'HIDDEN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'avatar',
                          },
                          viewFieldName: 'avatar',
                          allowEmpty: true,
                          hidden: true,
                          caption: '文本(动态)',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'avatar',
                        },
                      ],
                      layout: {
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 0,
                        layout: 'FLEX',
                      },
                      id: 'container1',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'display_name',
                              },
                              viewFieldName: 'DISPLAY_NAME',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              cssStyle:
                                'font-weight: var(--ibiz-font-weight-bold);',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'display_name',
                            },
                          ],
                          layout: {
                            dir: 'row',
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'container8',
                        },
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'function',
                              },
                              viewFieldName: 'FUNCTION',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'function',
                            },
                            {
                              rawItem: {
                                caption: '在',
                                halign: 'LEFT',
                                renderMode: 'PARAGRAPH',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                contentType: 'RAW',
                                predefinedType: 'STATIC_LABEL',
                                id: 'static_label',
                              },
                              caption: '在',
                              itemStyle: 'DEFAULT',
                              itemType: 'RAWITEM',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              showCaption: true,
                              id: 'static_label',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'parent_name',
                              },
                              viewFieldName: 'PARENT_NAME',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'parent_name',
                            },
                          ],
                          layout: {
                            dir: 'row',
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingTop: 'OUTERSMALL',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['is_company', 'parent_name'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'EQ',
                                  dstModelField: 'IS_COMPANY',
                                  value: '0',
                                  logicType: 'SINGLE',
                                  name: 'IS_COMPANY 等于(=) 0',
                                  id: 'is_company 等于(=) 0',
                                },
                                {
                                  condOp: 'ISNOTNULL',
                                  dstModelField: 'PARENT_NAME',
                                  logicType: 'SINGLE',
                                  name: 'PARENT_NAME 值不为空(NotNil)',
                                  id: 'parent_name 值不为空(notnil)',
                                },
                              ],
                              logicType: 'GROUP',
                            },
                          ],
                          id: 'container6',
                        },
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'city',
                              },
                              viewFieldName: 'CITY',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'city',
                            },
                            {
                              rawItem: {
                                caption: '，',
                                halign: 'LEFT',
                                renderMode: 'PARAGRAPH',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                contentType: 'RAW',
                                predefinedType: 'STATIC_LABEL',
                                id: 'static_label1',
                              },
                              caption: '逗号',
                              itemStyle: 'DEFAULT',
                              itemType: 'RAWITEM',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              showCaption: true,
                              id: 'static_label1',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'country_name',
                              },
                              viewFieldName: 'COUNTRY_NAME',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'country_name',
                            },
                          ],
                          layout: {
                            dir: 'row',
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingTop: 'OUTERSMALL',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['country_name'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'ISNOTNULL',
                                  dstModelField: 'COUNTRY_NAME',
                                  logicType: 'SINGLE',
                                  name: 'COUNTRY_NAME 值不为空(NotNil)',
                                  id: 'country_name 值不为空(notnil)',
                                },
                              ],
                              logicType: 'GROUP',
                            },
                          ],
                          id: 'container7',
                        },
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'email',
                              },
                              viewFieldName: 'EMAIL',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'email',
                            },
                          ],
                          layout: {
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingTop: 'OUTERSMALL',
                          },
                          id: 'container9',
                        },
                      ],
                      layout: {
                        dir: 'column',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        spacingLeft: 'OUTERSMALL',
                      },
                      id: 'container2',
                    },
                  ],
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  sysCss: {
                    cssName: 'car-image',
                  },
                  id: 'container3',
                },
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      layout: {
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      contentHeight: 69,
                      height: 69,
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        height: 69,
                        heightMode: 'PERCENTAGE',
                        layout: 'FLEX',
                      },
                      id: 'container10',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionType: 'UIACTION',
                          buttonStyle: 'DEFAULT',
                          buttonType: 'PANELBUTTON',
                          uiactionId: 'open_partner_act_view@mail_activity',
                          renderMode: 'LINK',
                          tooltip: '显示活动',
                          uiactionTarget: 'NONE',
                          caption: '显示活动',
                          itemStyle: 'DEFAULT',
                          itemType: 'BUTTON',
                          layoutPos: {
                            shrink: 0,
                            layout: 'FLEX',
                          },
                          sysCss: {
                            cssName: 'car-activity',
                          },
                          sysImage: {
                            cssClass: 'fa fa-clock-o',
                            glyph: 'xf017@FontAwesome',
                          },
                          id: 'button_calluilogic',
                        },
                      ],
                      layout: {
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      contentHeight: 31,
                      height: 31,
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        height: 31,
                        heightMode: 'PERCENTAGE',
                        layout: 'FLEX',
                      },
                      id: 'container4',
                    },
                  ],
                  layout: {
                    align: 'space-between',
                    dir: 'column',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container5',
                },
              ],
              layout: {
                align: 'space-between',
                dir: 'row',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              caption: '容器',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container',
            },
            {
              editor: {
                editorType: 'HIDDEN',
                predefinedType: 'FIELD_TEXT_DYNAMIC',
                valueType: 'SIMPLE',
                editable: true,
                id: 'is_company',
              },
              viewFieldName: 'IS_COMPANY',
              allowEmpty: true,
              hidden: true,
              caption: '文本(动态)',
              itemType: 'FIELD',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'is_company',
            },
          ],
          layoutPanel: true,
          codeName: 'partner_info',
          controlType: 'PANEL',
          logicName: 'partner_info卡片视图',
          appDataEntityId: 'ibizodooapp.res_partner',
          controlParam: {},
          modelId: '1fe5d4e5822b6ad53d43fd82167c5e74',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'ibizodooapp.res_partner.partner_info',
        },
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'write_date',
        dedataViewDataItems: [
          {
            frontCodeListId: 'ibizodooapp.yesno',
            dataType: 9,
            id: 'is_company',
          },
          {
            dataType: 25,
            id: 'display_name',
          },
          {
            dataType: 25,
            id: 'name',
          },
          {
            dataType: 25,
            id: 'email',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'commercial_partner_id',
            dataType: 25,
            id: 'commercial_partner_id',
          },
          {
            appDEFieldId: 'company_id',
            dataType: 25,
            id: 'company_id',
          },
          {
            appDEFieldId: 'user_id',
            dataType: 25,
            id: 'user_id',
          },
          {
            appDEFieldId: 'buyer_id',
            dataType: 25,
            id: 'buyer_id',
          },
          {
            appDEFieldId: 'country_id',
            dataType: 25,
            id: 'country_id',
          },
          {
            appDEFieldId: 'parent_id',
            dataType: 25,
            id: 'parent_id',
          },
          {
            appDEFieldId: 'state_id',
            dataType: 25,
            id: 'state_id',
          },
          {
            appDEFieldId: 'industry_id',
            dataType: 25,
            id: 'industry_id',
          },
          {
            appDEFieldId: 'property_purchase_currency_id',
            dataType: 25,
            id: 'property_purchase_currency_id',
          },
        ],
        dedataViewItems: [
          {
            clconvertMode: 'FRONT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.IS_COMPANY',
            },
            caption: '是公司',
            dataItemName: 'is_company',
            itemType: 'DATAITEM',
            appDEFieldId: 'is_company',
            codeListId: 'ibizodooapp.yesno',
            enableSort: true,
            name: 'IS_COMPANY',
            id: 'is_company',
          },
          {
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.DISPLAY_NAME',
            },
            caption: '显示名称',
            dataItemName: 'display_name',
            itemType: 'DATAITEM',
            appDEFieldId: 'display_name',
            enableSort: true,
            name: 'DISPLAY_NAME',
            id: 'display_name',
          },
          {
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.NAME',
            },
            caption: '名称',
            dataItemName: 'name',
            itemType: 'DATAITEM',
            appDEFieldId: 'name',
            enableSort: true,
            name: 'NAME',
            id: 'name',
          },
          {
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RES_PARTNER.EMAIL',
            },
            caption: '邮箱',
            dataItemName: 'email',
            itemType: 'DATAITEM',
            appDEFieldId: 'email',
            enableSort: true,
            name: 'EMAIL',
            id: 'email',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        appendDEItems: true,
        enablePagingBar: true,
        singleSelect: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ibizodooapp.res_partner',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'ibizodooapp.res_partner',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ibizodooapp.res_partner',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.res_partner',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ibizodooapp.res_partner',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'partner_info',
        controlType: 'DATAVIEW',
        logicName: '联系人卡片',
        appDataEntityId: 'ibizodooapp.res_partner',
        controlParam: {
          id: 'dataview',
        },
        modelId: '1fe5d4e5822b6ad53d43fd82167c5e74',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview',
        id: 'ibizodooapp.res_partner.partner_info',
      },
      {
        groupMode: 'AND',
        searchBarGroups: [
          {
            caption: '个人',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"is_company","condop":"EQ","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'personal',
          },
          {
            caption: '公司',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"is_company","condop":"EQ","value":"1"}]}]}}',
            itemType: 'GROUP',
            id: 'company',
          },
          {
            addSeparator: true,
            caption: '员工',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":null,"condop":null,"value":null}]}]}}',
            itemType: 'GROUP',
            id: 'employee',
          },
          {
            caption: '客户发票',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"customer_rank","condop":"GT","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'customer_invoice',
          },
          {
            caption: '供应商账单',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"supplier_rank","condop":"GT","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'supplier_bill',
          },
          {
            addSeparator: true,
            caption: '已归档',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"active","condop":"EQ","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'inactive',
          },
        ],
        quickGroupCount: 1,
        quickSearchMode: 1,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'search_bar',
        controlStyle: 'ODOO_SEARCH_BAR',
        controlType: 'SEARCHBAR',
        logicName: '联系人搜索栏',
        appDataEntityId: 'ibizodooapp.res_partner',
        controlParam: {
          id: 'searchbar',
        },
        sysPFPluginId: 'odoo_search_bar',
        modelId: 'ffde83ae046cc38e19bc76d1d7b59ec6',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'ibizodooapp.res_partner.search_bar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main2',
        controlType: 'SEARCHFORM',
        logicName: '联系人实体管理视图_搜索表单',
        appDataEntityId: 'ibizodooapp.res_partner',
        controlParam: {
          id: 'searchform',
        },
        modelId: '138826e04e4d9787bf124d37228b8a30',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'ibizodooapp.res_partner.main2',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        codeName: 'multi_data_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '联系人实体管理视图_工具栏',
        appDataEntityId: 'ibizodooapp.res_partner',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'bf2fdd83e9d03186d61f18197a527346',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'multi_data_view_toolbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RES_PARTNER',
        },
        caption: '联系人',
        codeName: 'multi_data_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.res_partner',
        controlParam: {},
        name: 'captionbar',
        id: 'multi_data_view_captionbar',
      },
    ],
    codeName: 'mdcustomview',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '多数据视图布局面板',
    appDataEntityId: 'ibizodooapp.res_partner',
    controlLogics: [
      {
        eventNames: 'onMounted',
        itemName: 'ACTIVITY',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取视图上下文\nconst appEntityId = view.model.appDataEntityId;\nconst srfmodelname = appEntityId.split('.').pop(); // 取点号后最后一段\n\nview.params.srfmodelname = srfmodelname;",
        triggerType: 'CTRLEVENT',
        id: 'init_activity_params',
      },
      {
        eventNames: 'onControlEvent',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "if (triggerEventName && triggerEventName === 'onActive' && triggerEvent.ctrl.name == view.state.xdatacontrolname) {\n    if(triggerEvent.ctrl.name!=\"activity\"){\n        view.call('Edit', { \n            context: view.context,\n            params: view.params,\n            data: triggerEvent.data,\n            view,\n            ctrl: triggerEvent.ctrl,\n        });\n    }\n   \n}",
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onClick',
        itemName: 'activity_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"activity\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// activity不显示分组筛选\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(searchBar.state.selectedGroup&&searchBar.state.selectedGroup.length>0){\n      viewSession.selectedGroup = [...searchBar.state.selectedGroup];\n      searchBar.state.selectedGroup=[];\n  }\n  searchBar.state.selectedGroup=[];\n  searchBar.state.showGroup=false; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'activity_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'calendar_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"calendar\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// calendar不显示分组筛选\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(searchBar.state.selectedGroup&&searchBar.state.selectedGroup.length>0){\n      viewSession.selectedGroup = [...searchBar.state.selectedGroup];\n      searchBar.state.selectedGroup=[];\n  }\n  searchBar.state.showGroup=false; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'calendar_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'chart_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"chart\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}",
        triggerType: 'CTRLEVENT',
        id: 'chart_click',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "console.log(\"\");\nconst targets = ['dataview', 'grid', 'activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\n\nlet firstVisible = null;\nlet default_ctrl = null;\n// 从路由获取\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\nif(currentRoute.query.srfnav){\n  firstVisible = currentRoute.query.srfnav;\n  const toggleitem = view.layoutPanel.findPanelItemByName(firstVisible+'_toggle');\n  toggleitem.onClick();\n  //activectrlname.setDataValue(firstVisible);\n  //view.state.xdatacontrolname = firstVisible;\n}\n// 挂载清空缓存\nif(appSession.guard){\n    appSession.guard();\n    appSession.guard = undefined;\n}\nif(!appSession.guard){\n  //注册路由监听\n  const afterEachHook = ibiz.appUtil.router.afterEach((to, from) => {\n    let toUrlArray = to.path.split('/');\n    if(toUrlArray.length<=2){\n      return;\n    }\n    const viewName = toUrlArray[toUrlArray.length - 2];\n    // const pathNodes = ibiz.appUtil.route2routeObject().pathNodes;\n    // const viewName = toUrlArray[pathNodes.length - 1].viewName;\n    const cacheView = ibiz.appUtil.viewCacheCenter.get(viewName);\n    const toView = cacheView;\n    // const curView = cacheView ? cacheView : view;\n    console.log('目标视图----',toView);\n    // let toUrlArray = to.path.split('/');\n    // let fromUrlArray = from.path.split('/');\n    // if(toUrlArray.length<=2 || fromUrlArray.length<=2){\n    //   return;\n    // }\n    //判断是否支持切换器\n    if(toView){\n      if(toView.layoutPanel.findPanelItemByName(\"switch_panel\")){\n        var active_ctrl = to.query.srfnav;\n        if(active_ctrl){\n          const toggleitem = toView.layoutPanel.findPanelItemByName(active_ctrl+'_toggle');\n          toggleitem.onClick();\n        }else{\n          // 恢复默认部件\n          const toggleitem = toView.layoutPanel.findPanelItemByName(defaultctrlname.value+'_toggle');\n          toggleitem.onClick();\n        }\n      }\n    }\n  });\n  appSession.guard = afterEachHook;\n}\n// 查找第一个存在的部件\nlet ctrlcount = 0;\nfor (const name of targets) {\n  const item = view.getCtrl(\"\", name);\n  if (item) {\n     if(firstVisible == null){\n        firstVisible = name;\n        activectrlname.setDataValue(firstVisible);\n        view.state.xdatacontrolname = firstVisible;\n      }\n      if(default_ctrl == null){\n        default_ctrl = name;\n        defaultctrlname.setDataValue(default_ctrl);\n      }\n    ctrlcount++;\n  }\n}\n\n// 设置可见性状态\ntargets.forEach(name => {\n  const item = view.layoutPanel.findPanelItemByName(name);\n  if (item) {\n    item.state.visible = name === firstVisible;\n  }\n});\n\n// 仅一个部件时隐藏切换器\nif(ctrlcount == 1){\n   const switch_panel_container = view.layoutPanel.findPanelItemByName('switch_panel_container');\n     if (switch_panel_container) {\n      switch_panel_container.state.visible = false;\n    }\n}\n\nconst searchBar = view.getController('searchbar');\n//解决多数据部件异步加载导致重复加载问题\nif(searchBar.model.searchBarGroups.find(group=> group.defaultGroup)){\n    const item = view.layoutPanel.findPanelItemByName(view.state.xdatacontrolname);\n    item.control.state.loadDefault = false;\n}",
        triggerType: 'CTRLEVENT',
        id: 'ctrl_toggle_init',
      },
      {
        eventNames: 'onClick',
        itemName: 'dataview_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"dataview\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//恢复显示左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.showPanel();\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid', 'activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}",
        triggerType: 'CTRLEVENT',
        id: 'dataview_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'grid_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconsole.log(\"\");\nconst curctrl = \"grid\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//恢复显示左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.showPanel();\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\n\n//默认部件忽略参数\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'grid_click',
      },
      {
        eventNames: 'onClick',
        itemName: 'hierarchy_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"hierarchy\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// hierarchy不显示分组筛选\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(searchBar.state.selectedGroup&&searchBar.state.selectedGroup.length>0){\n      viewSession.selectedGroup = [...searchBar.state.selectedGroup];\n      searchBar.state.selectedGroup=[];\n  }\n  searchBar.state.showGroup=false; \n  searchBar.state.showCollect=true; \n}\n",
        triggerType: 'CTRLEVENT',
        id: 'hierarchy_click',
      },
      {
        eventNames: 'onControlEvent',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 多数据部件\nconst targets = [\n  'dataview',\n  'grid',\n  'activity',\n  'pivottable',\n  'calendar',\n  'chart',\n  'hierarchy',\n];\n// 获取搜索栏\nconst searchBar = view.getController('searchbar');\n// 处理多数据部件事件\nif (searchBar && targets.includes(triggerControlName)) {\n  // 表格默认不加载在执行execGroup时加载\n  if (triggerControlName === 'grid' ) {\n    triggerEvent.ctrl.state.loadDefault = false;\n  }\n  // 多数据部件初始化时合并搜索参数\n  if (triggerEventName === 'onCreated') {\n    triggerEvent.ctrl.state.searchParams = searchBar.getFilterParams();\n  }\n  // 多数据部件绘制完成后执行搜索栏分组\n  if (triggerEventName === 'onMounted') {\n    searchBar.execGroup();\n  }\n}",
        triggerType: 'CTRLEVENT',
        name: 'onControlEvent',
        id: 'oncontrolevent',
      },
      {
        eventNames: 'onClick',
        itemName: 'pivottable_toggle',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "// 获取部件并显示\nconst curctrl = \"pivottable\";\nconst activectrl = view.layoutPanel.findPanelItemByName(curctrl);\nif (activectrl) {\n  activectrl.state.visible = true;\n}\n//隐藏左侧过滤区\nconst view_exp_split = view.layoutPanel.findPanelItemByName('view_exp_split');\nif (view_exp_split) {\n  view_exp_split.hiddenPanel(\"left\");\n}\n// 定义需要隐藏的部件标识\nconst keepVisibleItems = ['dataview', 'grid','activity', 'pivottable', 'calendar', 'chart','hierarchy'];\nconst index = keepVisibleItems.indexOf(curctrl);\nif (index !== -1) {\n  keepVisibleItems.splice(index, 1);\n}\n// 隐藏部件\nconst allItems = view.layoutPanel.panelItems;\nObject.keys(allItems).forEach(key => {\n  if (keepVisibleItems.includes(key)) {\n    allItems[key].state.visible = false;\n  }\n});\n\nconst activectrlname = view.layoutPanel.findPanelItemByName('active_ctrl');\nactivectrlname.setDataValue(curctrl);\n\nview.state.xdatacontrolname =curctrl;\n\n// 获取当前的路由对象\nconst currentRoute = ibiz.appUtil.router.currentRoute._value;\n\n// 创建一个新的 query 对象，保留现有查询参数，并添加新的参数\nconst newQuery = {\n  ...currentRoute.query, \n  srfnav: curctrl         \n};\nconst defaultctrlname = view.layoutPanel.findPanelItemByName('default_ctrl');\nif(defaultctrlname.value == curctrl){\n  delete newQuery.srfnav;\n}\n// 使用 $router.push 更新 URL 并导航到相同的路径\nif(newQuery.srfnav != currentRoute.query.srfnav){\n  ibiz.appUtil.router.push({\n    path: currentRoute.path, \n    query: newQuery \n  });\n}\n\n// 显示分组筛选，并还原选项\nconst searchBar = view.getController('searchbar');\nif(searchBar){\n  if(viewSession.selectedGroup&&viewSession.selectedGroup.length>0){\n      searchBar.state.selectedGroup=[...viewSession.selectedGroup];\n      viewSession.selectedGroup=[];\n  }\n  searchBar.state.showGroup=true; \n  searchBar.state.showCollect=true; \n}",
        triggerType: 'CTRLEVENT',
        id: 'pivottable_click',
      },
    ],
    controlParam: {},
    modelId: '4db373066a152684f6838426ca29b4a9',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'mdcustomview',
  },
  title: '联系人',
  viewStyle: 'DEFAULT',
  viewType: 'DEMDCUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f8e008548a938a2b89ff3bea17cd6243',
  modelType: 'PSAPPDEVIEW',
  name: 'res_partnermulti_data_view',
  id: 'ibizodooapp.res_partner_multi_data_view',
};
