export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: 'd747488ec6aed971e2115d7f9c491c20',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_CURRENCY',
  },
  caption: '币别',
  codeName: 'res_currency_pickup_view',
  appDataEntityId: 'ibizodooapp.res_currency',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.res_currency_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.res_currency',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_CURRENCY',
      },
      caption: '币别',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_currency',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_currency',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '币别数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3ee6caef893661ee8cfe2d1f5002e2da',
  modelType: 'PSAPPDEVIEW',
  name: 'res_currencyPickupView',
  id: 'ibizodooapp.res_currency_pickup_view',
};
