export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'EditView',
  deviewId: 'cc0f9438ffadbc5256e8955c9aa71254',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS_USERS_REL',
  },
  caption: '权限组成员',
  codeName: 'res_groups_users_rel_edit_view',
  appDataEntityId: 'ibizodooapp.res_groups_users_rel',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.SAVE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.SAVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem10',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandnewaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
          },
          caption: '保存并新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存并新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem12',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandexitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
          },
          caption: '保存并关闭',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存并关闭',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem11',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem18',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_removeandexitaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
          },
          caption: '删除并关闭',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除并关闭',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem9',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem19',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem5',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem21',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_copyaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.COPY',
          },
          caption: '拷贝',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-copy',
            glyph: 'xf0c5@FontAwesome',
          },
          tooltip: '拷贝',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.COPY',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem22',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_firstrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '第一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-fast-backward',
            glyph: 'xf049@FontAwesome',
          },
          tooltip: '第一个记录',
          showIcon: true,
          id: 'tbitem2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_prevrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '上一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-step-backward',
            glyph: 'xf048@FontAwesome',
          },
          tooltip: '上一个记录',
          showIcon: true,
          id: 'tbitem7',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_nextrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '下一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-step-forward',
            glyph: 'xf051@FontAwesome',
          },
          tooltip: '下一个记录',
          showIcon: true,
          id: 'tbitem6',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_lastrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '最后一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-fast-forward',
            glyph: 'xf050@FontAwesome',
          },
          tooltip: '最后一个记录',
          showIcon: true,
          id: 'tbitem4',
        },
      ],
      xdataControlName: 'form',
      codeName: 'edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认编辑界面）',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '48c8f789be8a5522d3003293c1cf2ffb',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'getdraft',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              capLanguageRes: {
                lanResTag:
                  'CONTROL.DEFORM.RES_GROUPS_USERS_REL.MAIN.GROUPPANEL.GROUP1',
              },
              caption: '权限组成员基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.RES_GROUPS_USERS_REL.MAIN.FORMPAGE.FORMPAGE1',
          },
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              capLanguageRes: {
                lanResTag:
                  'CONTROL.DEFORM.RES_GROUPS_USERS_REL.MAIN.GROUPPANEL.GROUP2',
              },
              caption: '操作信息',
              codeName: 'group2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group2',
            },
          ],
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.RES_GROUPS_USERS_REL.MAIN.FORMPAGE.FORMPAGE2',
          },
          caption: '其它',
          codeName: 'formpage2',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage2',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'FORM',
      logicName: '主编辑表单',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {
        id: 'form',
      },
      modelId: 'c2637793ad15f484e66a086d9967ccaf',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'ibizodooapp.res_groups_users_rel.main',
    },
    {
      codeName: 'edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_GROUPS_USERS_REL',
      },
      caption: '权限组成员',
      codeName: 'edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_groups_users_rel',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '权限组成员编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '47835d7a06fa940bf91e2c8f729d46b9',
  modelType: 'PSAPPDEVIEW',
  name: 'res_groups_users_relEditView',
  id: 'ibizodooapp.res_groups_users_rel_edit_view',
};
