export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'edit_view',
  deviewId: '50de0c6be76e713f92327a63edbb3bc2',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_COMPANY',
  },
  caption: '打开公司',
  codeName: 'res_company_edit_view',
  height: 800,
  appDataEntityId: 'ibizodooapp.res_company',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    showMaxLength: true,
                    editorParams: {
                      ISAUTO: 'true',
                    },
                    editorType: 'TEXTAREA',
                    placeHolder: '例如：我的公司',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
              ],
              caption: '基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              deformTabPages: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'partner_name',
                          editor: {
                            linkAppViewId: 'ibizodooapp.res_partner_main_view',
                            enablePickupView: true,
                            singleSelect: true,
                            pickupAppViewId:
                              'ibizodooapp.res_partner_pickup_view',
                            handlerType: 'PickupText',
                            appDEACModeId: 'default',
                            appDEDataSetId: 'fetch_default',
                            appDataEntityId: 'ibizodooapp.res_partner',
                            enableAC: true,
                            forceSelection: true,
                            showTrigger: true,
                            valueItemName: 'partner_id',
                            editorParams: {
                              AC: 'TRUE',
                              PICKUPVIEW: 'TRUE',
                            },
                            editorType: 'PICKER',
                            editorItems: [
                              {
                                id: 'partner_id',
                              },
                            ],
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'partner_name',
                          },
                          allowEmpty: true,
                          caption: '合作伙伴',
                          codeName: 'partner_name',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'partner_name',
                        },
                        {
                          dataType: 25,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'city',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            placeHolder: '城市',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'city',
                          },
                          allowEmpty: true,
                          caption: '城市',
                          codeName: 'city',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'city',
                        },
                        {
                          dataType: 25,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'street',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            placeHolder: '街道...',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'street',
                          },
                          allowEmpty: true,
                          caption: '街道',
                          codeName: 'street',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'street',
                        },
                        {
                          dataType: 25,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'street2',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            placeHolder: '详细地址...',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'street2',
                          },
                          allowEmpty: true,
                          caption: '详细地址',
                          codeName: 'street2',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'street2',
                        },
                        {
                          dataType: 25,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'zip',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            placeHolder: '邮政编码',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'zip',
                          },
                          allowEmpty: true,
                          caption: '邮编',
                          codeName: 'zip',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'zip',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'currency_name',
                          editor: {
                            enablePickupView: true,
                            singleSelect: true,
                            pickupAppViewId:
                              'ibizodooapp.res_currency_pickup_view',
                            handlerType: 'PickupText',
                            appDEACModeId: 'default',
                            appDEDataSetId: 'fetch_default',
                            appDataEntityId: 'ibizodooapp.res_currency',
                            enableAC: true,
                            forceSelection: true,
                            showTrigger: true,
                            valueItemName: 'currency_id',
                            editorParams: {
                              AC: 'TRUE',
                              PICKUPVIEW: 'TRUE',
                            },
                            editorType: 'PICKER',
                            editorItems: [
                              {
                                id: 'currency_id',
                              },
                            ],
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'currency_name',
                          },
                          allowEmpty: true,
                          caption: '币别',
                          codeName: 'currency_name',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'currency_name',
                        },
                      ],
                      codeName: 'group3',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 12,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'group3',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'parent_name',
                          editor: {
                            enablePickupView: true,
                            singleSelect: true,
                            pickupAppViewId:
                              'ibizodooapp.res_company_pickup_view',
                            handlerType: 'PickupText',
                            appDEACModeId: 'default',
                            appDEDataSetId: 'fetch_default',
                            appDataEntityId: 'ibizodooapp.res_company',
                            enableAC: true,
                            forceSelection: true,
                            showTrigger: true,
                            valueItemName: 'parent_id',
                            editorParams: {
                              AC: 'TRUE',
                              PICKUPVIEW: 'TRUE',
                            },
                            editorType: 'PICKER',
                            editorItems: [
                              {
                                id: 'parent_id',
                              },
                            ],
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'parent_name',
                          },
                          allowEmpty: true,
                          caption: '上级公司',
                          codeName: 'parent_name',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'parent_name',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'alias_domain_id',
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'alias_domain_id',
                          },
                          allowEmpty: true,
                          hidden: true,
                          caption: '电子邮件域名',
                          codeName: 'alias_domain_id',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          id: 'alias_domain_id',
                        },
                        {
                          dataType: 25,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'bounce_formatted',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'bounce_formatted',
                          },
                          allowEmpty: true,
                          caption: '退回',
                          codeName: 'bounce_formatted',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'bounce_formatted',
                        },
                        {
                          dataType: 25,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'catchall_formatted',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'catchall_formatted',
                          },
                          allowEmpty: true,
                          caption: '预设',
                          codeName: 'catchall_formatted',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'catchall_formatted',
                        },
                        {
                          dataType: 9,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'color',
                          editor: {
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'color',
                          },
                          allowEmpty: true,
                          caption: '颜色',
                          codeName: 'color',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'color',
                        },
                      ],
                      codeName: 'group4',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 12,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'group4',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'social_twitter',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'social_twitter',
                          },
                          allowEmpty: true,
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.SOCIAL_TWITTER',
                          },
                          caption: 'X 账户',
                          codeName: 'social_twitter',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'social_twitter',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'social_facebook',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'social_facebook',
                          },
                          allowEmpty: true,
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.SOCIAL_FACEBOOK',
                          },
                          caption: 'Facebook 账户',
                          codeName: 'social_facebook',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'social_facebook',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'social_github',
                          editor: {
                            maxLength: 500,
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'social_github',
                          },
                          allowEmpty: true,
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.SOCIAL_GITHUB',
                          },
                          caption: 'GitHub账户',
                          codeName: 'social_github',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'social_github',
                        },
                      ],
                      caption: '社交媒体',
                      codeName: 'group5',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 12,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'group5',
                    },
                  ],
                  caption: '一般信息',
                  codeName: 'tabpage1',
                  detailStyle: 'DEFAULT',
                  detailType: 'TABPAGE',
                  showCaption: true,
                  id: 'tabpage1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  caption: '分公司',
                  codeName: 'tabpage2',
                  detailStyle: 'DEFAULT',
                  detailType: 'TABPAGE',
                  showCaption: true,
                  id: 'tabpage2',
                },
              ],
              codeName: 'tabpanel1',
              detailStyle: 'DEFAULT',
              detailType: 'TABPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'tabpanel1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'partner_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'partner_id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '合作伙伴',
              codeName: 'partner_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'partner_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'parent_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'parent_id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '上级公司',
              codeName: 'parent_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'parent_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'currency_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'currency_id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '币别',
              codeName: 'currency_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'currency_id',
            },
          ],
          caption: '公司信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'FORM',
      logicName: '公司实体主视图_表单',
      appDataEntityId: 'ibizodooapp.res_company',
      controlParam: {
        ctrlParams: {
          EDITMODE: 'hover',
        },
        id: 'form',
      },
      modelId: '587cd02393fe0c1886980631dd3b061e',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'ibizodooapp.res_company.main',
    },
    {
      codeName: 'edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'ibizodooapp.res_company',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_COMPANY',
      },
      caption: '打开公司',
      codeName: 'edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_company',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_company',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '公司',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 1000,
  enableDP: true,
  showCaptionBar: true,
  modelId: '08d40adb7183fe131a00ae88d315db3a',
  modelType: 'PSAPPDEVIEW',
  name: 'res_companyedit_view',
  id: 'ibizodooapp.res_company_edit_view',
};
