export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '6dcb82ffa229fff855a380147b1dd57d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS',
  },
  caption: '权限组',
  codeName: 'res_groups_pickup_view',
  appDataEntityId: 'ibizodooapp.res_groups',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.res_groups_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.res_groups',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_GROUPS',
      },
      caption: '权限组',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_groups',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_groups',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '权限组数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '43a0f6f77ea91570096593303811185b',
  modelType: 'PSAPPDEVIEW',
  name: 'res_groupsPickupView',
  id: 'ibizodooapp.res_groups_pickup_view',
};
