export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'user_group_mgr_view',
  deviewId: '5aecffab743a8da3f2b1ddabeb268f88',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS_USERS_REL',
  },
  caption: '权限组成员',
  codeName: 'res_groups_users_rel_user_group_mgr_view',
  appDataEntityId: 'ibizodooapp.res_groups_users_rel',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        batchAddAppViews: [
          {
            openMode: 'POPUPMODAL',
            refMode: 'RES_GROUPS',
            refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'RES_USERS',
            refAppViewId: 'ibizodooapp.res_users_m_pickup_view',
          },
        ],
        newDataAppView: {
          refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
        },
        enableBatchAdd: true,
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'RES_GROUPS',
            refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
          },
          {
            openMode: 'POPUPMODAL',
            refMode: 'RES_USERS',
            refAppViewId: 'ibizodooapp.res_users_m_pickup_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '权限组成员编辑视图',
      refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '权限组成员编辑视图',
      refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '权限组数据多项选择视图',
      refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
      name: 'MPICKUPVIEW:RES_GROUPS',
      id: 'mpickupview:res_groups',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '用户数据多项选择视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.RES_USERS.MPICKUPVIEW',
      },
      refAppViewId: 'ibizodooapp.res_users_m_pickup_view',
      name: 'MPICKUPVIEW:RES_USERS',
      id: 'mpickupview:res_users',
    },
  ],
  controls: [
    {
      aggMode: 'ALL',
      aggAppDEDataSetId: 'fetch_default',
      aggAppDataEntityId: 'ibizodooapp.res_groups',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'CODELIST',
      groupAppDEFieldId: 'category_id',
      groupCodeListId: 'ibizodooapp.base__module_categroy',
      groupStyle: 'DEFAULT',
      groupTextAppDEFieldId: 'category_name',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'category_name',
          excelCaption: '应用',
          appDEFieldId: 'category_name',
          valueType: 'SIMPLE',
          aggField: 'category_name',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '应用',
          codeName: 'category_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'category_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'category_id',
          excelCaption: '应用',
          appDEFieldId: 'category_id',
          valueType: 'SIMPLE',
          aggField: 'category_id',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '应用',
          codeName: 'category_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'category_id',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'group_name',
          excelCaption: '组名称',
          linkAppViewId: 'ibizodooapp.res_groups_main_view',
          linkValueItem: 'gid',
          appDEFieldId: 'group_name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          aggField: 'group_name',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '组名称',
          codeName: 'group_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 1,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'group_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'state',
          excelCaption: '状态',
          appCodeListId: 'ibizodooapp.base__res_users_state',
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          aggField: 'state',
          aggMode: 'USER',
          align: 'LEFT',
          caption: '状态',
          codeName: 'state',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'state',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'category_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_name',
        },
        {
          appDEFieldId: 'category_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'group_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'group_name',
        },
        {
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'state',
        },
        {
          appDEFieldId: 'gid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'gid',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enableGroup: true,
      singleSelect: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'user_ref',
      controlStyle: 'NTON_GRID',
      controlType: 'GRID',
      logicName: '主表格(用户权限)',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {
        ctrlParams: {
          PROPERTYMAP: 'category_id:category_id,category_name:category_name',
        },
        id: 'grid',
      },
      sysPFPluginId: 'nton_grid',
      modelId: 'e8e913021e43b8c8621dc0fb988b05c3',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.res_groups_users_rel.user_ref',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.RES_GROUPS_USERS_REL.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'dc0da74297a9646c98ae8051f8d24752',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.res_groups_users_rel.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_GROUPS_USERS_REL',
      },
      caption: '权限组成员',
      codeName: 'user_group_mgr_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_groups_users_rel',
      controlParam: {},
      name: 'captionbar',
      id: 'user_group_mgr_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_groups_users_rel',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '用户权限组管理',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ea461a564714e1157b91e1e5a04d3c83',
  modelType: 'PSAPPDEVIEW',
  name: 'res_groups_users_reluser_group_mgr_view',
  id: 'ibizodooapp.res_groups_users_rel_user_group_mgr_view',
};
