export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '354265fddd73439e233e3aa102fd37f5',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_PARTNER',
  },
  caption: '联系人',
  codeName: 'res_partner_pickup_view',
  appDataEntityId: 'ibizodooapp.res_partner',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.res_partner_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.res_partner',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_PARTNER',
      },
      caption: '联系人',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_partner',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_partner',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '联系人数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '0b172457f5ec40df0c892efb0e8a7338',
  modelType: 'PSAPPDEVIEW',
  name: 'res_partnerPickupView',
  id: 'ibizodooapp.res_partner_pickup_view',
};
