export default {
  funcViewMode: 'MPICKUPVIEW',
  openMode: 'POPUPMODAL',
  deviewCodeName: 'MPickupView',
  deviewId: '21f5baac95a78d0e82c2f2fad32e7fe3',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_USERS',
  },
  caption: '用户',
  codeName: 'res_users_m_pickup_view',
  height: 700,
  appDataEntityId: 'ibizodooapp.res_users',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'MPickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'sale_team_id',
          dataType: 25,
          id: 'sale_team_id',
        },
        {
          appDEFieldId: 'partner_id',
          dataType: 25,
          id: 'partner_id',
        },
        {
          appDEFieldId: 'company_id',
          dataType: 25,
          id: 'company_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.res_users',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.res_users',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.res_users',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.res_users',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.res_users',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'ibizodooapp.res_users',
      controlParam: {
        id: 'simplelist',
      },
      modelId: 'cbad97f70dff729194aad82b8c3bd620',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'ibizodooapp.res_users.simplelist',
    },
    {
      embeddedAppDEViewId: 'ibizodooapp.res_users_pickup_grid_view',
      codeName: 'm_pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.res_users',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'm_pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_USERS',
      },
      caption: '用户',
      codeName: 'm_pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_users',
      controlParam: {},
      name: 'captionbar',
      id: 'm_pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_users',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '用户数据多项选择视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.RES_USERS.MPICKUPVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW',
  width: 1200,
  enableDP: true,
  showCaptionBar: false,
  modelId: '01b15bde19dd0a2fba0e50dfa9eb16ea',
  modelType: 'PSAPPDEVIEW',
  name: 'res_usersMPickupView',
  id: 'ibizodooapp.res_users_m_pickup_view',
};
