export default {
  funcViewMode: 'MPICKUPVIEW',
  openMode: 'POPUPMODAL',
  deviewCodeName: 'MPickupView',
  deviewId: '26aebbb0df8603d6fb97a9587f509cd1',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS',
  },
  caption: '权限组',
  codeName: 'res_groups_m_pickup_view',
  height: 600,
  appDataEntityId: 'ibizodooapp.res_groups',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'MPickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'category_id',
          dataType: 25,
          id: 'category_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.res_groups',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.res_groups',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.res_groups',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.res_groups',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.res_groups',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'ibizodooapp.res_groups',
      controlParam: {
        id: 'simplelist',
      },
      modelId: '87643d902babea4d4454d965fb734435',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'ibizodooapp.res_groups.simplelist',
    },
    {
      embeddedAppDEViewId: 'ibizodooapp.res_groups_pickup_grid_view',
      codeName: 'm_pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.res_groups',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'm_pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_GROUPS',
      },
      caption: '权限组',
      codeName: 'm_pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_groups',
      controlParam: {},
      name: 'captionbar',
      id: 'm_pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_groups',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '权限组数据多项选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW',
  width: 1000,
  enableDP: true,
  showCaptionBar: false,
  modelId: '405c474e38cd7eba4acd66e78e303a2b',
  modelType: 'PSAPPDEVIEW',
  name: 'res_groupsMPickupView',
  id: 'ibizodooapp.res_groups_m_pickup_view',
};
