export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'GridView',
  deviewId: 'f229accf2ee1c430c78433b6ef91041a',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS_USERS_REL',
  },
  caption: '权限组成员',
  codeName: 'res_groups_users_rel_grid_view',
  appDataEntityId: 'ibizodooapp.res_groups_users_rel',
  appViewParams: [
    {
      key: 'PROPERTYMAP',
      value:
        'name:user_name,id:user_id,login:login,company_name:company_name,state:state',
      name: 'PROPERTYMAP',
      id: 'propertymap',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                  spacingLeft: 'OUTERLARGE',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          batchAddAppViews: [
            {
              openMode: 'POPUPMODAL',
              refMode: 'RES_GROUPS',
              refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
            },
            {
              openMode: 'POPUPMODAL',
              refMode: 'RES_USERS',
              refAppViewId: 'ibizodooapp.res_users_m_pickup_view',
            },
          ],
          newDataAppView: {
            refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
          },
          enableBatchAdd: true,
          appDataEntityId: 'ibizodooapp.res_groups_users_rel',
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
            },
            {
              openMode: 'POPUPMODAL',
              refMode: 'RES_GROUPS',
              refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
            },
            {
              openMode: 'POPUPMODAL',
              refMode: 'RES_USERS',
              refAppViewId: 'ibizodooapp.res_users_m_pickup_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '权限组成员编辑视图',
        refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '权限组成员编辑视图',
        refAppViewId: 'ibizodooapp.res_groups_users_rel_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '权限组数据多项选择视图',
        refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
        name: 'MPICKUPVIEW:RES_GROUPS',
        id: 'mpickupview:res_groups',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '用户数据多项选择视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.RES_USERS.MPICKUPVIEW',
        },
        refAppViewId: 'ibizodooapp.res_users_m_pickup_view',
        name: 'MPICKUPVIEW:RES_USERS',
        id: 'mpickupview:res_users',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'user_name',
            excelCaption: '名称',
            linkAppViewId: 'ibizodooapp.res_users_edit_view',
            linkValueItem: 'user_id',
            appDEFieldId: 'user_name',
            valueType: 'SIMPLE',
            enableLinkView: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '名称',
            codeName: 'user_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 1,
            widthUnit: 'STAR',
            enableSort: true,
            userParam: {
              'SRFNAVCTX.srfsessionid': '',
            },
            id: 'user_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'login',
            excelCaption: '登录',
            appDEFieldId: 'login',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '登录',
            codeName: 'login',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'login',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'company_name',
            excelCaption: '公司',
            appDEFieldId: 'company_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '公司',
            codeName: 'company_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'company_name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'state',
            excelCaption: '状态',
            appCodeListId: 'ibizodooapp.base__res_users_state',
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'state',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'state',
          },
          {
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'gridview_removeaction',
                  tooltipLanguageRes: {
                    lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                  },
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  id: 'uf676d6d',
                },
              ],
              name: '通用表格界面删除界面行为组',
              id: 'auto83146635',
            },
            aggMode: 'NONE',
            align: 'RIGHT',
            codeName: 'uagridcolumn1',
            columnType: 'UAGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'uagridcolumn1',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'user_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'user_name',
          },
          {
            appDEFieldId: 'login',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'login',
          },
          {
            appDEFieldId: 'company_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'company_name',
          },
          {
            appDEFieldId: 'state',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'state',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'gid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'gid',
          },
          {
            appDEFieldId: 'user_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'user_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetchdefault',
          appDataEntityId: 'ibizodooapp.res_groups_users_rel',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.res_groups_users_rel',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        controlParam: {
          id: 'grid',
        },
        modelId: 'c2637793ad15f484e66a086d9967ccaf',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'ibizodooapp.res_groups_users_rel.main',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '添加行',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '添加行',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '权限组成员实体工具栏',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '158f46cab89d1c86ebef5cc9f4695d47',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            capLanguageRes: {
              lanResTag:
                'CONTROL.DEFORM.RES_GROUPS_USERS_REL.DEFAULT.FORMPAGE.FORMPAGE1',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'default',
        controlType: 'SEARCHFORM',
        logicName: '默认搜索表单',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        controlParam: {
          id: 'searchform',
        },
        modelId: 'dc0da74297a9646c98ae8051f8d24752',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'ibizodooapp.res_groups_users_rel.default',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RES_GROUPS_USERS_REL',
        },
        caption: '权限组成员',
        codeName: 'grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.res_groups_users_rel',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_captionbar',
      },
    ],
    codeName: 'auto94410878',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '表格视图布局_工具栏置底部',
    appDataEntityId: 'ibizodooapp.res_groups_users_rel',
    controlParam: {},
    modelId: 'a13eeb1a845a3db03d246911b7ccb2bf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto94410878',
  },
  title: '权限组成员表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b48e1155b93a3bf59f1916d3e6bc341a',
  modelType: 'PSAPPDEVIEW',
  name: 'res_groups_users_relGridView',
  id: 'ibizodooapp.res_groups_users_rel_grid_view',
};
