export default {
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'pick_up_list_view',
  deviewId: '6b7246572000fe986f4dd4a5688976c1',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_PARTNER',
  },
  caption: '邀请成员',
  codeName: 'res_partner_pick_up_list_view',
  appDataEntityId: 'ibizodooapp.res_partner',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onSelectionChange',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'list',
      scriptCode: "view.evt.emit('onSelectionChange', { data });",
      builtinLogic: true,
      name: 'ONSELECTIONCHANGE',
      id: 'onselectionchange',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'ibizodooapp.res_partner_main_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.res_partner_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'ibizodooapp.res_partner_main_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'ibizodooapp.res_partner_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '联系人',
      refAppViewId: 'ibizodooapp.res_partner_main_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '联系人',
      refAppViewId: 'ibizodooapp.res_partner_main_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'FLEX',
        layout: {
          layout: 'FLEX',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                editor: {
                  halign: 'LEFT',
                  renderMode: 'TEXT_DYNAMIC',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  appCodeListId: 'ibizodooapp.base__res_partner',
                  editorStyle: 'PERSONNEL_INFO',
                  editorType: 'SPAN',
                  sysPFPluginId: 'personnel_info',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'user_name',
                },
                viewFieldName: 'id',
                allowEmpty: true,
                convertToCodeItemText: true,
                caption: '文本(动态)',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'user_name',
              },
            ],
            layout: {
              align: 'flex-start',
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            contentHeight: 40,
            height: 40,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              height: 40,
              heightMode: 'PX',
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layoutPanel: true,
        codeName: 'list_panel',
        controlType: 'PANEL',
        logicName: 'list列表',
        appDataEntityId: 'ibizodooapp.res_partner',
        controlParam: {},
        modelId: 'c31b2d763aa6068f45758e352d83b4cf',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'ibizodooapp.res_partner.list_panel',
      },
      delistDataItems: [
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'commercial_partner_id',
          dataType: 25,
          id: 'commercial_partner_id',
        },
        {
          appDEFieldId: 'company_id',
          dataType: 25,
          id: 'company_id',
        },
        {
          appDEFieldId: 'user_id',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'buyer_id',
          dataType: 25,
          id: 'buyer_id',
        },
        {
          appDEFieldId: 'country_id',
          dataType: 25,
          id: 'country_id',
        },
        {
          appDEFieldId: 'parent_id',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'state_id',
          dataType: 25,
          id: 'state_id',
        },
        {
          appDEFieldId: 'industry_id',
          dataType: 25,
          id: 'industry_id',
        },
        {
          appDEFieldId: 'property_purchase_currency_id',
          dataType: 25,
          id: 'property_purchase_currency_id',
        },
      ],
      pagingMode: 2,
      pagingSize: 20,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ibizodooapp.res_partner',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_channel_invite',
        appDataEntityId: 'ibizodooapp.res_partner',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ibizodooapp.res_partner',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.res_partner',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ibizodooapp.res_partner',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list',
      controlType: 'LIST',
      logicName: 'list',
      appDataEntityId: 'ibizodooapp.res_partner',
      controlParam: {
        id: 'list',
      },
      modelId: '6e017464f0ad6483cc950feacb6be99d',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'ibizodooapp.res_partner.list',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.res_partner',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_PARTNER',
      },
      caption: '邀请成员',
      codeName: 'pick_up_list_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_partner',
      controlParam: {},
      name: 'captionbar',
      id: 'pick_up_list_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_partner',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '联系人',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '45e693adcadbf08016718d2f309dc9d2',
  modelType: 'PSAPPDEVIEW',
  name: 'res_partnerpick_up_list_view',
  id: 'ibizodooapp.res_partner_pick_up_list_view',
};
