export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '9149e0ab55ce90959b6bae98a428ca38',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_COUNTRY',
  },
  caption: '国家/地区',
  codeName: 'res_country_pickup_view',
  appDataEntityId: 'ibizodooapp.res_country',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.res_country_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.res_country',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_COUNTRY',
      },
      caption: '国家/地区',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_country',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_country',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '国家/地区数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '654b7ea2232a9aed599b6d53c47ecf0c',
  modelType: 'PSAPPDEVIEW',
  name: 'res_countryPickupView',
  id: 'ibizodooapp.res_country_pickup_view',
};
