export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: 'a0231f927c8cd654d105cdcacb5d7607',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_COMPANY',
  },
  caption: '公司',
  codeName: 'res_company_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.res_company',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '公司名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '公司名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'partner_name',
          excelCaption: '合作伙伴',
          appDEFieldId: 'partner_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '合作伙伴',
          codeName: 'partner_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 1,
          widthUnit: 'PX',
          enableSort: true,
          id: 'partner_name',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'partner_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'partner_name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'alias_domain_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'alias_domain_id',
        },
        {
          appDEFieldId: 'currency_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'currency_id',
        },
        {
          appDEFieldId: 'partner_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'partner_id',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'batch_payment_sequence_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'batch_payment_sequence_id',
        },
        {
          appDEFieldId: 'account_fiscal_country_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'account_fiscal_country_id',
        },
        {
          appDEFieldId: 'stock_mail_confirmation_template_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'stock_mail_confirmation_template_id',
        },
        {
          appDEFieldId: 'resource_calendar_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'resource_calendar_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.res_company',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.res_company',
      controlParam: {
        id: 'grid',
      },
      modelId: '587cd02393fe0c1886980631dd3b061e',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.res_company.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.RES_COMPANY.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.res_company',
      controlParam: {
        id: 'searchform',
      },
      modelId: '757129b635ea3d29f9a8b03e010ee381',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.res_company.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.res_company',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RES_COMPANY',
      },
      caption: '公司',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.res_company',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.res_company',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '公司选择表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.RES_COMPANY.PICKUPGRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '48dccbe9a112c75fa731702a2f487dd5',
  modelType: 'PSAPPDEVIEW',
  name: 'res_companyPickupGridView',
  id: 'ibizodooapp.res_company_pickup_grid_view',
};
