export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: 'b2acfaf393a7018d80bfcbac93b84168',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_RESOURCE',
  },
  caption: '资源',
  codeName: 'resource_resource_pickup_grid_view',
  appDataEntityId: 'ibizodooapp.resource_resource',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'user_name',
          excelCaption: '用户',
          appDEFieldId: 'user_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.USER_ID',
          },
          caption: '用户',
          codeName: 'user_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'user_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'company_name',
          excelCaption: '公司',
          appDEFieldId: 'company_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.COMPANY_ID',
          },
          caption: '公司',
          codeName: 'company_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'company_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'calendar_name',
          excelCaption: '工时',
          appDEFieldId: 'calendar_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.CALENDAR_ID',
          },
          caption: '工时',
          codeName: 'calendar_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 1,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'calendar_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'resource_type',
          excelCaption: '类型',
          appCodeListId:
            'ibizodooapp.resource__resource_resource_resource_type',
          appDEFieldId: 'resource_type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.RESOURCE_TYPE',
          },
          caption: '类型',
          codeName: 'resource_type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'resource_type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'time_efficiency',
          excelCaption: '效率因子',
          appDEFieldId: 'time_efficiency',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.TIME_EFFICIENCY',
          },
          caption: '效率因子',
          codeName: 'time_efficiency',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'time_efficiency',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'user_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_name',
        },
        {
          appDEFieldId: 'company_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_name',
        },
        {
          appDEFieldId: 'calendar_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'calendar_name',
        },
        {
          appDEFieldId: 'resource_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'resource_type',
        },
        {
          appDEFieldId: 'time_efficiency',
          valueType: 'SIMPLE',
          dataType: 7,
          id: 'time_efficiency',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'calendar_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'calendar_id',
        },
        {
          appDEFieldId: 'company_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_id',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ibizodooapp.resource_resource',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ibizodooapp.resource_resource',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ibizodooapp.resource_resource',
      controlParam: {
        id: 'grid',
      },
      modelId: 'acd4d5da8a45306fca612722684258df',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ibizodooapp.resource_resource.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.RESOURCE_RESOURCE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ibizodooapp.resource_resource',
      controlParam: {
        id: 'searchform',
      },
      modelId: '916406aa97bc7a537e33e1f28828a128',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ibizodooapp.resource_resource.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ibizodooapp.resource_resource',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RESOURCE_RESOURCE',
      },
      caption: '资源',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.resource_resource',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.resource_resource',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '资源选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1c0d344c329e50152564850ad9938b55',
  modelType: 'PSAPPDEVIEW',
  name: 'resource_resourcePickupGridView',
  id: 'ibizodooapp.resource_resource_pickup_grid_view',
};
