export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '8c77428793861f4b5ecb76b4ae948291',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_CALENDAR',
  },
  caption: '资源工作时间',
  codeName: 'resource_calendar_pickup_view',
  appDataEntityId: 'ibizodooapp.resource_calendar',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.resource_calendar_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.resource_calendar',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RESOURCE_CALENDAR',
      },
      caption: '资源工作时间',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.resource_calendar',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.resource_calendar',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '资源工作时间数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '57e7de3d65e8374a0aac39e65ee455b3',
  modelType: 'PSAPPDEVIEW',
  name: 'resource_calendarPickupView',
  id: 'ibizodooapp.resource_calendar_pickup_view',
};
