export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '285e2847d0c6885b08106ee142ca3a92',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_RESOURCE',
  },
  caption: '资源',
  codeName: 'resource_resource_pickup_view',
  appDataEntityId: 'ibizodooapp.resource_resource',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ibizodooapp.resource_resource_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ibizodooapp.resource_resource',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RESOURCE_RESOURCE',
      },
      caption: '资源',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ibizodooapp.resource_resource',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ibizodooapp.resource_resource',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '资源数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f8b0f5ec94e191f255e8a0a6c6816bc1',
  modelType: 'PSAPPDEVIEW',
  name: 'resource_resourcePickupView',
  id: 'ibizodooapp.resource_resource_pickup_view',
};
