export default {
  appSwitchMode: 1,
  mainMenuAlign: 'TOP',
  enableAppSwitch: true,
  caption: '设置',
  codeName: 'setting_index_view',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          predefinedType: 'NAV_BREADCRUMB',
                          id: 'nav_breadcrumb',
                        },
                        caption: '面包屑导航',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_breadcrumb',
                      },
                      {
                        rawItem: {
                          predefinedType: 'NAV_POS_INDEX',
                          id: 'nav_pos_index',
                        },
                        caption: '导航区占位',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          grow: 1,
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_pos_index',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 100,
                    height: 100,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 100,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container4_all',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                },
                id: 'container6_all',
              },
              {
                rawItem: {
                  caption: '标签',
                  halign: 'LEFT',
                  renderMode: 'PARAGRAPH',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_LABEL',
                  id: 'static_label',
                },
                caption: '标签',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                sysPFPluginId: 'odoo_chat',
                showCaption: true,
                id: 'static_label',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
              width: 100,
              widthMode: 'PERCENTAGE',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              contentType: 'USER',
                              rawItemParams: [
                                {
                                  key: 'sourcetype',
                                  value: 'UTIL',
                                },
                              ],
                              predefinedType: 'APP_SWITCH',
                              id: 'app_switch',
                            },
                            caption: '应用切换器',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERMEDIUM',
                            },
                            showCaption: true,
                            id: 'app_switch',
                          },
                          {
                            caption: '首页菜单',
                            contentHeight: 60,
                            contentWidth: 800,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              grow: 1,
                              shrink: 1,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 800,
                              widthMode: 'PX',
                            },
                            width: 800,
                            showCaption: true,
                            id: 'appmenu',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'container2',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '文本内容',
                              halign: 'LEFT',
                              renderMode: 'TEXT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'INDEX_VIEW_SEARCH',
                              id: 'index_view_search',
                            },
                            caption: '搜索栏',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'index_view_search',
                          },
                        ],
                        layout: {
                          align: 'center',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 52,
                        height: 52,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          height: 52,
                          heightMode: 'PX',
                          layout: 'FLEX',
                        },
                        id: 'container',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  contentType: 'IMAGE',
                                  predefinedType: 'USERMESSAGE',
                                  id: 'usermessage',
                                },
                                caption: '消息通知',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 1,
                                  heightMode: 'FULL',
                                  layout: 'FLEX',
                                  widthMode: 'FULL',
                                },
                                showCaption: true,
                                id: 'usermessage',
                              },
                            ],
                            layout: {
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            contentHeight: 48,
                            contentWidth: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              height: 48,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 48,
                              widthMode: 'PX',
                            },
                            width: 48,
                            id: 'container1',
                          },
                          {
                            rawItem: {
                              rawItemParams: [
                                {
                                  key: 'AVATAR',
                                  value: 'avatar',
                                },
                                {
                                  key: 'TITLE',
                                  value: 'srfusername',
                                },
                                {
                                  key: 'SUBTITLE',
                                  value: 'loginname',
                                },
                                {
                                  key: 'NAVVIEWNAME',
                                  value: 'res_users_info_custom_view',
                                },
                              ],
                              predefinedType: 'AUTH_USERINFO',
                              rawItemHeight: 60,
                              id: 'auth_userinfo',
                            },
                            caption: '用户信息',
                            contentHeight: 60,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 0,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                            },
                            sysPFPluginId: 'custom_auth_userinfo',
                            showCaption: true,
                            id: 'auth_userinfo',
                          },
                        ],
                        predefinedType: 'INDEX_ACTIONS',
                        layout: {
                          align: 'space-between',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'indexactions',
                      },
                    ],
                    layout: {
                      align: 'space-between',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container7',
                  },
                ],
                predefinedType: 'AppHeader',
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                  widthMode: 'FULL',
                },
                id: 'app_header',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_HEADER',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentHeight: 60,
            height: 60,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'NORTH',
              height: 60,
              heightMode: 'PX',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_header',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        appMenuStyle: 'EXTVIEW1',
        layoutMode: 'TABLE_24COL',
        appMenuItems: [
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'employee_modifysetting',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            openDefault: true,
            valid: true,
            caption: '一般设置',
            tooltip: '一般设置',
            id: 'base_config_setting',
          },
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'user',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '用户',
                tooltip: '用户',
                id: 'base_user',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'group',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '群组',
                tooltip: '群组',
                id: 'base_group',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'company',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '公司',
                tooltip: '公司',
                id: 'base_company',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '用户和公司',
            tooltip: '用户和公司',
            id: 'userandcompany',
          },
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'ir_module_module',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '模块',
            tooltip: '模块',
            id: 'base_module',
          },
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'app_market',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '应用市场',
            tooltip: '应用市场',
            id: 'base_market',
          },
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'message',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '消息',
                    tooltip: '消息',
                    id: 'mail_message',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'notification',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '通知',
                    tooltip: '通知',
                    id: 'mail_notification',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'followers',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '关注者',
                    tooltip: '关注者',
                    id: 'mail_followers',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '讨论',
                tooltip: '讨论',
                id: 'discuss',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator2',
              },
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail_activity',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '活动概览',
                    tooltip: '活动概览',
                    id: 'mail_activity',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail_activity_type',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '活动类型',
                    tooltip: '活动类型',
                    id: 'mail_activity_type',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail_activity_plan2',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '活动计划',
                    tooltip: '活动计划',
                    id: 'mail_activity_plan',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '活动',
                tooltip: '活动',
                id: 'activity',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator8',
              },
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: 'EMail',
                    tooltip: 'EMail',
                    id: 'mail_mail',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail_server',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '发送服务器',
                    tooltip: '发送服务器',
                    id: 'base_mail_server',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'fetchmail_server',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '收件服务器',
                    tooltip: '收件服务器',
                    id: 'mail_fetchmail_server',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail_template',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: 'EMail模板',
                    tooltip: 'EMail模板',
                    id: 'mail_template',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail_alias',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '别名',
                    tooltip: '别名',
                    id: 'mail_alias',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'mail_alias_domain',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '别名域',
                    tooltip: '别名域',
                    id: 'mail_alias_domain',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '邮箱',
                tooltip: '邮箱',
                id: 'mail',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator7',
              },
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'actions_server',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '服务器操作',
                    tooltip: '服务器操作',
                    id: 'base_actions_server',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'ir_default',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '用户定义的默认值',
                    tooltip: '用户定义的默认值',
                    id: 'base_default',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '操作',
                tooltip: '操作',
                id: 'operation',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator5',
              },
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'model',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '模型',
                    tooltip: '模型',
                    id: 'base_model',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '数据库结构',
                tooltip: '数据库结构',
                id: 'database_structure',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator6',
              },
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'cron',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '计划的操作',
                    tooltip: '计划的操作',
                    id: 'base_cron',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'cron_trigger',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '计划行动触发器',
                    tooltip: '计划行动触发器',
                    id: 'base_cron_trigger',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '自动化',
                tooltip: '自动化',
                id: 'automation',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator4',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'config_parameter',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '系统参数',
                tooltip: '系统参数',
                id: 'base_config_param',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator1',
              },
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'rule',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '记录规则',
                    tooltip: '记录规则',
                    id: 'base_rule',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'ir_model_access',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '访问权限',
                    tooltip: '访问权限',
                    id: 'base_model_access',
                  },
                  {
                    accUserMode: 2,
                    itemType: 'MENUITEM',
                    appFuncId: 'unires',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '统一资源',
                    tooltip: '统一资源',
                    id: 'base_extend_unires',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '安全',
                tooltip: '安全',
                id: 'safety',
              },
              {
                itemType: 'SEPERATOR',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                id: 'seperator3',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'ir_module_category',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '应用分类',
                tooltip: '应用分类',
                id: 'base_module_category',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '技术',
            tooltip: '技术',
            id: 'config',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'setting_index_view',
        controlStyle: 'EXTVIEW1',
        controlType: 'APPMENU',
        logicName: '设置首页视图',
        controlParam: {},
        modelId: 'ee54fe6b6d5724649ed016e36e88b06c',
        modelType: 'PSAPPMENU',
        name: 'appmenu',
        id: 'setting_index_view',
      },
      {
        caption: '设置',
        subCaption: '设置',
        codeName: 'captionbar',
        controlType: 'CAPTIONBAR',
        controlParam: {},
        id: 'captionbar',
      },
    ],
    codeName: 'usr0816975858',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'AppIndexView',
    controlParam: {},
    modelId: '21f3f21b39a12e6aa06af432c6ee2d0b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0816975858',
  },
  subCaption: '设置',
  title: '设置',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '88f77fdace3687e3607d1c1b569380ea',
  modelType: 'PSAPPINDEXVIEW',
  userTag4: '9999',
  name: 'SettingIndexView',
  id: 'ibizodooapp.setting_index_view',
};
