export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'nested_group_grid_view',
  deviewId: '64e307991729d440969573c42ac43af7',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.UNIRES_GROUP_REL',
  },
  caption: '权限组关联统一资源',
  codeName: 'unires_group_rel_nested_group_grid_view',
  appDataEntityId: 'ibizodooapp.unires_group_rel',
  appViewParams: [
    {
      key: 'PROPERTYMAP',
      value: 'res_code:res_code,name:unires_name,id:unires_id',
      name: 'PROPERTYMAP',
      id: 'propertymap',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                  spacingLeft: 'OUTERLARGE',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          batchAddAppViews: [
            {
              openMode: 'POPUPMODAL',
              refMode: 'IR_UNIRES',
              refAppViewId: 'ibizodooapp.ir_unires_m_pickup_view',
            },
            {
              openMode: 'POPUPMODAL',
              refMode: 'RES_GROUPS',
              refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
            },
          ],
          newDataAppView: {
            refAppViewId: 'ibizodooapp.unires_group_rel_edit_view',
          },
          enableBatchAdd: true,
          appDataEntityId: 'ibizodooapp.unires_group_rel',
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.unires_group_rel_edit_view',
            },
            {
              openMode: 'POPUPMODAL',
              refMode: 'IR_UNIRES',
              refAppViewId: 'ibizodooapp.ir_unires_m_pickup_view',
            },
            {
              openMode: 'POPUPMODAL',
              refMode: 'RES_GROUPS',
              refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'ibizodooapp.unires_group_rel_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'ibizodooapp.unires_group_rel_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '权限组关联统一资源编辑视图',
        refAppViewId: 'ibizodooapp.unires_group_rel_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '权限组关联统一资源编辑视图',
        refAppViewId: 'ibizodooapp.unires_group_rel_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '统一资源数据多项选择视图',
        refAppViewId: 'ibizodooapp.ir_unires_m_pickup_view',
        name: 'MPICKUPVIEW:IR_UNIRES',
        id: 'mpickupview:ir_unires',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '权限组数据多项选择视图',
        refAppViewId: 'ibizodooapp.res_groups_m_pickup_view',
        name: 'MPICKUPVIEW:RES_GROUPS',
        id: 'mpickupview:res_groups',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'unires_name',
            excelCaption: '名称',
            linkAppViewId: 'ibizodooapp.ir_unires_info_view',
            linkValueItem: 'unires_id',
            appDEFieldId: 'unires_name',
            valueType: 'SIMPLE',
            enableLinkView: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '名称',
            codeName: 'unires_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 380,
            widthUnit: 'PX',
            enableSort: true,
            userParam: {
              'SRFNAVCTX.srfsessionid': '',
            },
            id: 'unires_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'res_code',
            excelCaption: '资源代码',
            appDEFieldId: 'res_code',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '资源代码',
            codeName: 'res_code',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'PX',
            enableSort: true,
            id: 'res_code',
          },
          {
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'gridview_removeaction',
                  tooltipLanguageRes: {
                    lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                  },
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-trash-o',
                    glyph: 'xf014@FontAwesome',
                  },
                  id: 'uf676d6d',
                },
              ],
              name: '通用表格界面删除界面行为组',
              id: 'auto83146635',
            },
            aggMode: 'NONE',
            align: 'RIGHT',
            codeName: 'uagridcolumn1',
            columnType: 'UAGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'uagridcolumn1',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'unires_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'unires_name',
          },
          {
            appDEFieldId: 'res_code',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'res_code',
          },
          {
            appDEFieldId: 'unires_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'unires_id',
          },
          {
            appDEFieldId: 'gid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'gid',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetchdefault',
          appDataEntityId: 'ibizodooapp.unires_group_rel',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ibizodooapp.unires_group_rel',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'group',
        controlType: 'GRID',
        logicName: '嵌入权限组表格',
        appDataEntityId: 'ibizodooapp.unires_group_rel',
        controlParam: {
          id: 'grid',
        },
        modelId: 'd8374b0a2b6917999ce9421f4e4c2619',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'ibizodooapp.unires_group_rel.group',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '添加行',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '添加行',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'nested_group_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '权限组关联统一资源实体工具栏',
        appDataEntityId: 'ibizodooapp.unires_group_rel',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'd5183f9d6a001c6c6658bb660647e5a0',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'nested_group_grid_view_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            capLanguageRes: {
              lanResTag:
                'CONTROL.DEFORM.UNIRES_GROUP_REL.DEFAULT.FORMPAGE.FORMPAGE1',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'default',
        controlType: 'SEARCHFORM',
        logicName: '默认搜索表单',
        appDataEntityId: 'ibizodooapp.unires_group_rel',
        controlParam: {
          id: 'searchform',
        },
        modelId: '51a6c48d95687a34d43065e83906e2d0',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'ibizodooapp.unires_group_rel.default',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'ibizodooapp.unires_group_rel',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.UNIRES_GROUP_REL',
        },
        caption: '权限组关联统一资源',
        codeName: 'nested_group_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ibizodooapp.unires_group_rel',
        controlParam: {},
        name: 'captionbar',
        id: 'nested_group_grid_view_captionbar',
      },
    ],
    codeName: 'auto94410878',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '表格视图布局_工具栏置底部',
    appDataEntityId: 'ibizodooapp.unires_group_rel',
    controlParam: {},
    modelId: 'a13eeb1a845a3db03d246911b7ccb2bf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto94410878',
  },
  title: '权限组关联统一资源',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '92b8e53e6d54c1a8d30f050d3e664a9c',
  modelType: 'PSAPPDEVIEW',
  name: 'unires_group_relnested_group_grid_view',
  id: 'ibizodooapp.unires_group_rel_nested_group_grid_view',
};
