export default {
  codeListTag: 'extension__pscoreprdfunc_category',
  codeListType: 'DYNAMIC',
  codeName: 'extension__pscoreprdfunc_category',
  emptyText: '未定义',
  orMode: 'STR',
  appDEDataSetId: 'fetchdefault',
  appDataEntityId: 'ibizodooapp.pscoreprdfunc',
  textAppDEFieldId: 'category',
  textSeparator: '、',
  valueAppDEFieldId: 'category',
  valueSeparator: ';',
  enableCache: true,
  name: '应用模型分类',
  id: 'ibizodooapp.extension__pscoreprdfunc_category',
};
