export default {
  appDEFields: [
    {
      codeName: 'duration_tracking',
      logicName: '状态时间',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DURATION_TRACKING',
      id: 'duration_tracking',
    },
    {
      codeName: 'activities',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_MIXIN.ACTIVITIES',
      },
      logicName: '活动集合',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ACTIVITIES',
      id: 'activities',
    },
    {
      codeName: 'attachments',
      logicName: '附件集合',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'followers',
      logicName: '关注者',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'FOLLOWERS',
      id: 'followers',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'active',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.ACTIVE',
      },
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'prorated_revenue',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PRORATED_REVENUE',
      },
      logicName: '按比例分配的收入',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'PRORATED_REVENUE',
      id: 'prorated_revenue',
    },
    {
      codeName: 'expected_revenue',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.EXPECTED_REVENUE',
      },
      logicName: '预期收入',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'EXPECTED_REVENUE',
      id: 'expected_revenue',
    },
    {
      codeName: 'iap_enrich_done',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.IAP_ENRICH_DONE',
      },
      logicName: '丰富结束',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IAP_ENRICH_DONE',
      id: 'iap_enrich_done',
    },
    {
      codeName: 'day_close',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DAY_CLOSE',
      },
      logicName: '待关闭天数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'DAY_CLOSE',
      id: 'day_close',
    },
    {
      codeName: 'recurring_revenue_monthly',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.RECURRING_REVENUE_MONTHLY',
      },
      logicName: '预期 MRR',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'RECURRING_REVENUE_MONTHLY',
      id: 'recurring_revenue_monthly',
    },
    {
      codeName: 'recurring_revenue_monthly_prorated',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.RECURRING_REVENUE_MONTHLY_PRORATED',
      },
      logicName: '按比例分配的 MRR',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'RECURRING_REVENUE_MONTHLY_PRORATED',
      id: 'recurring_revenue_monthly_prorated',
    },
    {
      codeName: 'date_closed',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_CLOSED',
      },
      logicName: '关闭日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_CLOSED',
      id: 'date_closed',
    },
    {
      codeName: 'recurring_revenue',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.RECURRING_REVENUE',
      },
      logicName: '经常性收入',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'RECURRING_REVENUE',
      id: 'recurring_revenue',
    },
    {
      codeName: 'automated_probability',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.AUTOMATED_PROBABILITY',
      },
      logicName: '自动概率',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'AUTOMATED_PROBABILITY',
      id: 'automated_probability',
    },
    {
      codeName: 'probability',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PROBABILITY',
      },
      logicName: '概率',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'PROBABILITY',
      id: 'probability',
    },
    {
      codeName: 'day_open',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DAY_OPEN',
      },
      logicName: '待分配天数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'DAY_OPEN',
      id: 'day_open',
    },
    {
      codeName: 'recurring_revenue_prorated',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.RECURRING_REVENUE_PRORATED',
      },
      logicName: '按比例分配的经常性收入',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'RECURRING_REVENUE_PRORATED',
      id: 'recurring_revenue_prorated',
    },
    {
      codeName: 'date_automation_last',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_AUTOMATION_LAST',
      },
      logicName: '最后操作',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_AUTOMATION_LAST',
      id: 'date_automation_last',
    },
    {
      codeName: 'date_last_stage_update',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_LAST_STAGE_UPDATE',
      },
      logicName: '最后阶段更新',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_LAST_STAGE_UPDATE',
      id: 'date_last_stage_update',
    },
    {
      codeName: 'date_deadline',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_DEADLINE',
      },
      logicName: '预期结束',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'DATE_DEADLINE',
      id: 'date_deadline',
    },
    {
      codeName: 'date_conversion',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_CONVERSION',
      },
      logicName: '转化日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_CONVERSION',
      id: 'date_conversion',
    },
    {
      codeName: 'date_open',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DATE_OPEN',
      },
      logicName: '指派日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_OPEN',
      id: 'date_open',
    },
    {
      codeName: 'message_bounce',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_BOUNCE',
      },
      logicName: '退回',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_BOUNCE',
      id: 'message_bounce',
    },
    {
      codeName: 'color',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.COLOR',
      },
      logicName: '颜色索引',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'COLOR',
      id: 'color',
    },
    {
      codeName: 'email_cc',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.EMAIL_CC',
      },
      logicName: '电子邮件抄送',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_CC',
      id: 'email_cc',
    },
    {
      codeName: 'description',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DESCRIPTION',
      },
      logicName: '备注',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'referred',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.REFERRED',
      },
      logicName: '推荐人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'REFERRED',
      id: 'referred',
    },
    {
      codeName: 'city',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.CITY',
      },
      logicName: '城市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CITY',
      id: 'city',
    },
    {
      codeName: 'contact_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.CONTACT_NAME',
      },
      logicName: '联系人姓名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CONTACT_NAME',
      id: 'contact_name',
    },
    {
      codeName: 'email_domain_criterion',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.EMAIL_DOMAIN_CRITERION',
      },
      logicName: '电子邮箱域名标准',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_DOMAIN_CRITERION',
      id: 'email_domain_criterion',
    },
    {
      codeName: 'zip',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.ZIP',
      },
      logicName: '邮编',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ZIP',
      id: 'zip',
    },
    {
      codeName: 'mobile',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MOBILE',
      },
      logicName: '手机号码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'MOBILE',
      id: 'mobile',
    },
    {
      codeName: 'email_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.EMAIL_FROM',
      },
      logicName: '电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_FROM',
      id: 'email_from',
    },
    {
      codeName: 'phone',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PHONE',
      },
      logicName: '电话号码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PHONE',
      id: 'phone',
    },
    {
      codeName: 'function',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.FUNCTION',
      },
      logicName: '工作岗位',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'FUNCTION',
      id: 'function',
    },
    {
      codeName: 'street2',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.STREET2',
      },
      logicName: '街道2',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'STREET2',
      id: 'street2',
    },
    {
      codeName: 'street',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.STREET',
      },
      logicName: '街道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'STREET',
      id: 'street',
    },
    {
      codeName: 'email_normalized',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.EMAIL_NORMALIZED',
      },
      logicName: '规范化电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_NORMALIZED',
      id: 'email_normalized',
    },
    {
      codeName: 'reveal_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.REVEAL_ID',
      },
      logicName: '显示 ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'REVEAL_ID',
      id: 'reveal_id',
    },
    {
      codeName: 'type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.TYPE',
      },
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'TYPE',
      id: 'type',
    },
    {
      codeName: 'website',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.WEBSITE',
      },
      logicName: '网站',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'WEBSITE',
      id: 'website',
    },
    {
      codeName: 'partner_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PARTNER_NAME',
      },
      logicName: '公司名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PARTNER_NAME',
      id: 'partner_name',
    },
    {
      codeName: 'phone_sanitized',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PHONE_SANITIZED',
      },
      logicName: '已净化号码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PHONE_SANITIZED',
      id: 'phone_sanitized',
    },
    {
      codeName: 'email_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.EMAIL_STATE',
      },
      logicName: '电子邮件质量',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'EMAIL_STATE',
      id: 'email_state',
    },
    {
      codeName: 'phone_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PHONE_STATE',
      },
      logicName: '电话号码质量',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'PHONE_STATE',
      id: 'phone_state',
    },
    {
      codeName: 'priority',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PRIORITY',
      },
      logicName: '优先级',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'PRIORITY',
      id: 'priority',
    },
    {
      codeName: 'lang_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.LANG_ID',
      },
      logicName: '语言',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LANG_ID',
      id: 'lang_id',
    },
    {
      codeName: 'company_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.COMPANY_ID',
      },
      logicName: '公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COMPANY_ID',
      id: 'company_id',
    },
    {
      codeName: 'user_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.USER_ID',
      },
      logicName: '销售人员',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USER_ID',
      id: 'user_id',
    },
    {
      codeName: 'state_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.STATE_ID',
      },
      logicName: '省/州',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'STATE_ID',
      id: 'state_id',
    },
    {
      codeName: 'stage_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.STAGE_ID',
      },
      logicName: '阶段',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'STAGE_ID',
      id: 'stage_id',
    },
    {
      codeName: 'team_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.TEAM_ID',
      },
      logicName: '销售团队',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TEAM_ID',
      id: 'team_id',
    },
    {
      codeName: 'lost_reason_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.LOST_REASON_ID',
      },
      logicName: '丢失原因',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LOST_REASON_ID',
      id: 'lost_reason_id',
    },
    {
      codeName: 'country_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.COUNTRY_ID',
      },
      logicName: '国家/地区',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COUNTRY_ID',
      id: 'country_id',
    },
    {
      codeName: 'partner_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PARTNER_ID',
      },
      logicName: '客户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARTNER_ID',
      id: 'partner_id',
    },
    {
      codeName: 'lead_mining_request_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.LEAD_MINING_REQUEST_ID',
      },
      logicName: '线索挖掘申请',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LEAD_MINING_REQUEST_ID',
      id: 'lead_mining_request_id',
    },
    {
      codeName: 'partner_phone_update',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PARTNER_PHONE_UPDATE',
      },
      logicName: '合作伙伴电话号码将更新',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PARTNER_PHONE_UPDATE',
      id: 'partner_phone_update',
    },
    {
      codeName: 'message_has_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_HAS_ERROR',
      },
      logicName: '消息发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR',
      id: 'message_has_error',
    },
    {
      codeName: 'is_partner_visible',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.IS_PARTNER_VISIBLE',
      },
      logicName: '是可见合作伙伴',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_PARTNER_VISIBLE',
      id: 'is_partner_visible',
    },
    {
      codeName: 'partner_email_update',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PARTNER_EMAIL_UPDATE',
      },
      logicName: '合作伙伴电子邮箱将更新',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PARTNER_EMAIL_UPDATE',
      id: 'partner_email_update',
    },
    {
      codeName: 'message_needaction',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_NEEDACTION',
      },
      logicName: '所需操作',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION',
      id: 'message_needaction',
    },
    {
      codeName: 'message_is_follower',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_IS_FOLLOWER',
      },
      logicName: '是关注者',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_IS_FOLLOWER',
      id: 'message_is_follower',
    },
    {
      codeName: 'has_message',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.HAS_MESSAGE',
      },
      logicName: '有消息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_MESSAGE',
      id: 'has_message',
    },
    {
      codeName: 'is_automated_probability',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.IS_AUTOMATED_PROBABILITY',
      },
      logicName: '是自动概率？',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_AUTOMATED_PROBABILITY',
      id: 'is_automated_probability',
    },
    {
      codeName: 'phone_blacklisted',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PHONE_BLACKLISTED',
      },
      logicName: '列入黑名单的电话是电话',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PHONE_BLACKLISTED',
      id: 'phone_blacklisted',
    },
    {
      codeName: 'message_has_sms_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_HAS_SMS_ERROR',
      },
      logicName: '短信发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_SMS_ERROR',
      id: 'message_has_sms_error',
    },
    {
      codeName: 'mobile_blacklisted',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MOBILE_BLACKLISTED',
      },
      logicName: '列入黑名单的电话号码是手机号码',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MOBILE_BLACKLISTED',
      id: 'mobile_blacklisted',
    },
    {
      codeName: 'phone_sanitized_blacklisted',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PHONE_SANITIZED_BLACKLISTED',
      },
      logicName: '电话号码已被列入黑名单',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PHONE_SANITIZED_BLACKLISTED',
      id: 'phone_sanitized_blacklisted',
    },
    {
      codeName: 'sale_amount_total',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.SALE_AMOUNT_TOTAL',
      },
      logicName: '销售订单的总数',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'SALE_AMOUNT_TOTAL',
      id: 'sale_amount_total',
    },
    {
      codeName: 'show_enrich_button',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.SHOW_ENRICH_BUTTON',
      },
      logicName: '允许手动丰富',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SHOW_ENRICH_BUTTON',
      id: 'show_enrich_button',
    },
    {
      codeName: 'is_blacklisted',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.IS_BLACKLISTED',
      },
      logicName: '黑名单',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_BLACKLISTED',
      id: 'is_blacklisted',
    },
    {
      codeName: 'my_activity_date_deadline',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MY_ACTIVITY_DATE_DEADLINE',
      },
      logicName: '我的活动截止时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'MY_ACTIVITY_DATE_DEADLINE',
      id: 'my_activity_date_deadline',
    },
    {
      codeName: 'meeting_display_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MEETING_DISPLAY_DATE',
      },
      logicName: '会议显示日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'MEETING_DISPLAY_DATE',
      id: 'meeting_display_date',
    },
    {
      codeName: 'activity_date_deadline',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.ACTIVITY_DATE_DEADLINE',
      },
      logicName: '下一活动截止日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'ACTIVITY_DATE_DEADLINE',
      id: 'activity_date_deadline',
    },
    {
      codeName: 'lang_active_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.LANG_ACTIVE_COUNT',
      },
      logicName: '有效语言数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LANG_ACTIVE_COUNT',
      id: 'lang_active_count',
    },
    {
      codeName: 'message_attachment_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_ATTACHMENT_COUNT',
      },
      logicName: '附件数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_ATTACHMENT_COUNT',
      id: 'message_attachment_count',
    },
    {
      codeName: 'duplicate_lead_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DUPLICATE_LEAD_COUNT',
      },
      logicName: '潜在的重复线索数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DUPLICATE_LEAD_COUNT',
      id: 'duplicate_lead_count',
    },
    {
      codeName: 'sale_order_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.SALE_ORDER_COUNT',
      },
      logicName: '销售订单数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SALE_ORDER_COUNT',
      id: 'sale_order_count',
    },
    {
      codeName: 'quotation_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.QUOTATION_COUNT',
      },
      logicName: '报价的数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'QUOTATION_COUNT',
      id: 'quotation_count',
    },
    {
      codeName: 'message_has_error_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_HAS_ERROR_COUNTER',
      },
      logicName: '错误数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR_COUNTER',
      id: 'message_has_error_counter',
    },
    {
      codeName: 'message_needaction_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MESSAGE_NEEDACTION_COUNTER',
      },
      logicName: '操作数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION_COUNTER',
      id: 'message_needaction_counter',
    },
    {
      codeName: 'phone_mobile_search',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.PHONE_MOBILE_SEARCH',
      },
      logicName: '电话号码/手机号码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PHONE_MOBILE_SEARCH',
      id: 'phone_mobile_search',
    },
    {
      codeName: 'meeting_display_label',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.MEETING_DISPLAY_LABEL',
      },
      logicName: '会议显示标签',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'MEETING_DISPLAY_LABEL',
      id: 'meeting_display_label',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'activity_exception_icon',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.ACTIVITY_EXCEPTION_ICON',
      },
      logicName: '图标',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ACTIVITY_EXCEPTION_ICON',
      id: 'activity_exception_icon',
    },
    {
      codeName: 'activity_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.ACTIVITY_STATE',
      },
      logicName: '活动状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_STATE',
      id: 'activity_state',
    },
    {
      codeName: 'activity_exception_decoration',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CRM_LEAD.ACTIVITY_EXCEPTION_DECORATION',
      },
      logicName: '活动异常标示',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_EXCEPTION_DECORATION',
      id: 'activity_exception_decoration',
    },
    {
      codeName: 'file',
      logicName: '文件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'FILE',
      id: 'file',
    },
    {
      codeName: 'image',
      logicName: '图片',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'IMAGE',
      id: 'image',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'crm_lead_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'duration_tracking',
          logicName: '状态时间',
          appDEFieldId: 'duration_tracking',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'duration_tracking',
        },
        {
          codeName: 'activities',
          logicName: '活动集合',
          appDEFieldId: 'activities',
          refAppDEMethodDTOId: 'mail_activity_dto',
          refAppDataEntityId: 'ibizodooapp.mail_activity',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'activities',
        },
        {
          codeName: 'attachments',
          logicName: '附件集合',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'ir_attachment_dto',
          refAppDataEntityId: 'ibizodooapp.ir_attachment',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'followers',
          logicName: '关注者',
          appDEFieldId: 'followers',
          refAppDEMethodDTOId: 'mail_followers_dto',
          refAppDataEntityId: 'ibizodooapp.mail_followers',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'followers',
        },
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'activity_date_deadline',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '下一活动截止日期',
          appDEFieldId: 'activity_date_deadline',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_date_deadline',
        },
        {
          codeName: 'activity_exception_decoration',
          logicName: '活动异常标示',
          appDEFieldId: 'activity_exception_decoration',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_exception_decoration',
        },
        {
          codeName: 'activity_exception_icon',
          logicName: '图标',
          appDEFieldId: 'activity_exception_icon',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_exception_icon',
        },
        {
          codeName: 'activity_state',
          logicName: '活动状态',
          appDEFieldId: 'activity_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_state',
        },
        {
          codeName: 'automated_probability',
          logicName: '自动概率',
          appDEFieldId: 'automated_probability',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'automated_probability',
        },
        {
          codeName: 'city',
          logicName: '城市',
          appDEFieldId: 'city',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'city',
        },
        {
          codeName: 'color',
          logicName: '颜色索引',
          appDEFieldId: 'color',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'color',
        },
        {
          codeName: 'company_id',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_id',
        },
        {
          codeName: 'contact_name',
          logicName: '联系人姓名',
          appDEFieldId: 'contact_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'contact_name',
        },
        {
          codeName: 'country_id',
          logicName: '国家/地区',
          appDEFieldId: 'country_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'country_id',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'date_automation_last',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最后操作',
          appDEFieldId: 'date_automation_last',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_automation_last',
        },
        {
          codeName: 'date_closed',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '关闭日期',
          appDEFieldId: 'date_closed',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_closed',
        },
        {
          codeName: 'date_conversion',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '转化日期',
          appDEFieldId: 'date_conversion',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_conversion',
        },
        {
          codeName: 'date_deadline',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '预期结束',
          appDEFieldId: 'date_deadline',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_deadline',
        },
        {
          codeName: 'date_last_stage_update',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最后阶段更新',
          appDEFieldId: 'date_last_stage_update',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_last_stage_update',
        },
        {
          codeName: 'date_open',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '指派日期',
          appDEFieldId: 'date_open',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_open',
        },
        {
          codeName: 'day_close',
          logicName: '待关闭天数',
          appDEFieldId: 'day_close',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'day_close',
        },
        {
          codeName: 'day_open',
          logicName: '待分配天数',
          appDEFieldId: 'day_open',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'day_open',
        },
        {
          codeName: 'description',
          logicName: '备注',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'duplicate_lead_count',
          logicName: '潜在的重复线索数量',
          appDEFieldId: 'duplicate_lead_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'duplicate_lead_count',
        },
        {
          codeName: 'email_cc',
          logicName: '电子邮件抄送',
          appDEFieldId: 'email_cc',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_cc',
        },
        {
          codeName: 'email_domain_criterion',
          logicName: '电子邮箱域名标准',
          appDEFieldId: 'email_domain_criterion',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_domain_criterion',
        },
        {
          codeName: 'email_from',
          logicName: '电子邮件',
          appDEFieldId: 'email_from',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_from',
        },
        {
          codeName: 'email_normalized',
          logicName: '规范化电子邮件',
          appDEFieldId: 'email_normalized',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_normalized',
        },
        {
          codeName: 'email_state',
          logicName: '电子邮件质量',
          appDEFieldId: 'email_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_state',
        },
        {
          codeName: 'expected_revenue',
          logicName: '预期收入',
          appDEFieldId: 'expected_revenue',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'expected_revenue',
        },
        {
          codeName: 'function',
          logicName: '工作岗位',
          appDEFieldId: 'function',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'function',
        },
        {
          codeName: 'has_message',
          logicName: '有消息',
          appDEFieldId: 'has_message',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_message',
        },
        {
          codeName: 'iap_enrich_done',
          logicName: '丰富结束',
          appDEFieldId: 'iap_enrich_done',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'iap_enrich_done',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'is_automated_probability',
          logicName: '是自动概率？',
          appDEFieldId: 'is_automated_probability',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_automated_probability',
        },
        {
          codeName: 'is_blacklisted',
          logicName: '黑名单',
          appDEFieldId: 'is_blacklisted',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_blacklisted',
        },
        {
          codeName: 'is_partner_visible',
          logicName: '是可见合作伙伴',
          appDEFieldId: 'is_partner_visible',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_partner_visible',
        },
        {
          codeName: 'lang_active_count',
          logicName: '有效语言数量',
          appDEFieldId: 'lang_active_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lang_active_count',
        },
        {
          codeName: 'lang_id',
          logicName: '语言',
          appDEFieldId: 'lang_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lang_id',
        },
        {
          codeName: 'lead_mining_request_id',
          logicName: '线索挖掘申请',
          appDEFieldId: 'lead_mining_request_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lead_mining_request_id',
        },
        {
          codeName: 'lost_reason_id',
          logicName: '丢失原因',
          appDEFieldId: 'lost_reason_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lost_reason_id',
        },
        {
          codeName: 'meeting_display_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '会议显示日期',
          appDEFieldId: 'meeting_display_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'meeting_display_date',
        },
        {
          codeName: 'meeting_display_label',
          logicName: '会议显示标签',
          appDEFieldId: 'meeting_display_label',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'meeting_display_label',
        },
        {
          codeName: 'message_attachment_count',
          logicName: '附件数量',
          appDEFieldId: 'message_attachment_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_attachment_count',
        },
        {
          codeName: 'message_bounce',
          logicName: '退回',
          appDEFieldId: 'message_bounce',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_bounce',
        },
        {
          codeName: 'message_has_error',
          logicName: '消息发送错误',
          appDEFieldId: 'message_has_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error',
        },
        {
          codeName: 'message_has_error_counter',
          logicName: '错误数量',
          appDEFieldId: 'message_has_error_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error_counter',
        },
        {
          codeName: 'message_has_sms_error',
          logicName: '短信发送错误',
          appDEFieldId: 'message_has_sms_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_sms_error',
        },
        {
          codeName: 'message_is_follower',
          logicName: '是关注者',
          appDEFieldId: 'message_is_follower',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_is_follower',
        },
        {
          codeName: 'message_needaction',
          logicName: '所需操作',
          appDEFieldId: 'message_needaction',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction',
        },
        {
          codeName: 'message_needaction_counter',
          logicName: '操作数量',
          appDEFieldId: 'message_needaction_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction_counter',
        },
        {
          codeName: 'mobile',
          logicName: '手机号码',
          appDEFieldId: 'mobile',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mobile',
        },
        {
          codeName: 'mobile_blacklisted',
          logicName: '列入黑名单的电话号码是手机号码',
          appDEFieldId: 'mobile_blacklisted',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mobile_blacklisted',
        },
        {
          codeName: 'my_activity_date_deadline',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '我的活动截止时间',
          appDEFieldId: 'my_activity_date_deadline',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'my_activity_date_deadline',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'partner_email_update',
          logicName: '合作伙伴电子邮箱将更新',
          appDEFieldId: 'partner_email_update',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_email_update',
        },
        {
          codeName: 'partner_id',
          logicName: '客户',
          appDEFieldId: 'partner_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_id',
        },
        {
          codeName: 'partner_name',
          logicName: '公司名称',
          appDEFieldId: 'partner_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_name',
        },
        {
          codeName: 'partner_phone_update',
          logicName: '合作伙伴电话号码将更新',
          appDEFieldId: 'partner_phone_update',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_phone_update',
        },
        {
          codeName: 'phone',
          logicName: '电话号码',
          appDEFieldId: 'phone',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone',
        },
        {
          codeName: 'phone_blacklisted',
          logicName: '列入黑名单的电话是电话',
          appDEFieldId: 'phone_blacklisted',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone_blacklisted',
        },
        {
          codeName: 'phone_mobile_search',
          logicName: '电话号码/手机号码',
          appDEFieldId: 'phone_mobile_search',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone_mobile_search',
        },
        {
          codeName: 'phone_sanitized',
          logicName: '已净化号码',
          appDEFieldId: 'phone_sanitized',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone_sanitized',
        },
        {
          codeName: 'phone_sanitized_blacklisted',
          logicName: '电话号码已被列入黑名单',
          appDEFieldId: 'phone_sanitized_blacklisted',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone_sanitized_blacklisted',
        },
        {
          codeName: 'phone_state',
          logicName: '电话号码质量',
          appDEFieldId: 'phone_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone_state',
        },
        {
          codeName: 'priority',
          logicName: '优先级',
          appDEFieldId: 'priority',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'priority',
        },
        {
          codeName: 'probability',
          logicName: '概率',
          appDEFieldId: 'probability',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'probability',
        },
        {
          codeName: 'prorated_revenue',
          logicName: '按比例分配的收入',
          appDEFieldId: 'prorated_revenue',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'prorated_revenue',
        },
        {
          codeName: 'quotation_count',
          logicName: '报价的数量',
          appDEFieldId: 'quotation_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'quotation_count',
        },
        {
          codeName: 'recurring_revenue',
          logicName: '经常性收入',
          appDEFieldId: 'recurring_revenue',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'recurring_revenue',
        },
        {
          codeName: 'recurring_revenue_monthly',
          logicName: '预期 MRR',
          appDEFieldId: 'recurring_revenue_monthly',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'recurring_revenue_monthly',
        },
        {
          codeName: 'recurring_revenue_monthly_prorated',
          logicName: '按比例分配的 MRR',
          appDEFieldId: 'recurring_revenue_monthly_prorated',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'recurring_revenue_monthly_prorated',
        },
        {
          codeName: 'recurring_revenue_prorated',
          logicName: '按比例分配的经常性收入',
          appDEFieldId: 'recurring_revenue_prorated',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'recurring_revenue_prorated',
        },
        {
          codeName: 'referred',
          logicName: '推荐人',
          appDEFieldId: 'referred',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'referred',
        },
        {
          codeName: 'reveal_id',
          logicName: '显示 ID',
          appDEFieldId: 'reveal_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'reveal_id',
        },
        {
          codeName: 'sale_amount_total',
          logicName: '销售订单的总数',
          appDEFieldId: 'sale_amount_total',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sale_amount_total',
        },
        {
          codeName: 'sale_order_count',
          logicName: '销售订单数量',
          appDEFieldId: 'sale_order_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sale_order_count',
        },
        {
          codeName: 'show_enrich_button',
          logicName: '允许手动丰富',
          appDEFieldId: 'show_enrich_button',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'show_enrich_button',
        },
        {
          codeName: 'stage_id',
          logicName: '阶段',
          appDEFieldId: 'stage_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'stage_id',
        },
        {
          codeName: 'state_id',
          logicName: '省/州',
          appDEFieldId: 'state_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state_id',
        },
        {
          codeName: 'street',
          logicName: '街道',
          appDEFieldId: 'street',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'street',
        },
        {
          codeName: 'street2',
          logicName: '街道2',
          appDEFieldId: 'street2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'street2',
        },
        {
          codeName: 'team_id',
          logicName: '销售团队',
          appDEFieldId: 'team_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'team_id',
        },
        {
          codeName: 'type',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'type',
        },
        {
          codeName: 'user_id',
          logicName: '销售人员',
          appDEFieldId: 'user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_id',
        },
        {
          codeName: 'website',
          logicName: '网站',
          appDEFieldId: 'website',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'website',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
        {
          codeName: 'zip',
          logicName: '邮编',
          appDEFieldId: 'zip',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'zip',
        },
        {
          codeName: 'file',
          logicName: '文件',
          appDEFieldId: 'file',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'file',
        },
        {
          codeName: 'image',
          logicName: '图片',
          appDEFieldId: 'image',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'image',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'crm_lead_dto',
    },
    {
      codeName: 'crm_lead_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_activity_exception_decoration_eq',
          logicName: '活动异常标示',
          appDEFieldId: 'activity_exception_decoration',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_exception_decoration_eq',
        },
        {
          codeName: 'n_activity_state_eq',
          logicName: '活动状态',
          appDEFieldId: 'activity_state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_state_eq',
        },
        {
          codeName: 'n_company_id_eq',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_id_eq',
        },
        {
          codeName: 'n_country_id_eq',
          logicName: '国家/地区',
          appDEFieldId: 'country_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_country_id_eq',
        },
        {
          codeName: 'n_email_state_eq',
          logicName: '电子邮件质量',
          appDEFieldId: 'email_state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_email_state_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_lang_id_eq',
          logicName: '语言',
          appDEFieldId: 'lang_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lang_id_eq',
        },
        {
          codeName: 'n_lead_mining_request_id_eq',
          logicName: '线索挖掘申请',
          appDEFieldId: 'lead_mining_request_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lead_mining_request_id_eq',
        },
        {
          codeName: 'n_lost_reason_id_eq',
          logicName: '丢失原因',
          appDEFieldId: 'lost_reason_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lost_reason_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_partner_id_eq',
          logicName: '客户',
          appDEFieldId: 'partner_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_partner_id_eq',
        },
        {
          codeName: 'n_phone_state_eq',
          logicName: '电话号码质量',
          appDEFieldId: 'phone_state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_phone_state_eq',
        },
        {
          codeName: 'n_priority_eq',
          logicName: '优先级',
          appDEFieldId: 'priority',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_priority_eq',
        },
        {
          codeName: 'n_stage_id_eq',
          logicName: '阶段',
          appDEFieldId: 'stage_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_stage_id_eq',
        },
        {
          codeName: 'n_state_id_eq',
          logicName: '省/州',
          appDEFieldId: 'state_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_state_id_eq',
        },
        {
          codeName: 'n_team_id_eq',
          logicName: '销售团队',
          appDEFieldId: 'team_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_team_id_eq',
        },
        {
          codeName: 'n_type_eq',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_type_eq',
        },
        {
          codeName: 'n_user_id_eq',
          logicName: '销售人员',
          appDEFieldId: 'user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'crm_lead_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'message_post_with_source',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/message_post_with_source',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'message_post_with_source',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'crm_lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'crm_lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'crm_lead',
  deapicodeName: 'crm_lead',
  deapicodeName2: 'crm_leads',
  deapitag: 'CRM_LEAD',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.CRM_LEAD',
  },
  logicName: '线索/商机',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'CRM_LEAD',
  id: 'ibizodooapp.crm_lead',
  codeName2: 'crm_leads',
  requestPaths: [],
};
