export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'attachments',
      logicName: '附件集合',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'followers',
      logicName: '关注者',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'FOLLOWERS',
      id: 'followers',
    },
    {
      codeName: 'members',
      logicName: '成员',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MEMBERS',
      id: 'members',
    },
    {
      codeName: 'channel_members',
      logicName: '频道成员',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CHANNEL_MEMBERS',
      id: 'channel_members',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'allow_public_upload',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.ALLOW_PUBLIC_UPLOAD',
      },
      logicName: '允许公开上传',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ALLOW_PUBLIC_UPLOAD',
      id: 'allow_public_upload',
    },
    {
      codeName: 'active',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.ACTIVE',
      },
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'description',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.DESCRIPTION',
      },
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'sfu_channel_uuid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.SFU_CHANNEL_UUID',
      },
      logicName: 'Sfu 频道 Uuid',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SFU_CHANNEL_UUID',
      id: 'sfu_channel_uuid',
    },
    {
      codeName: 'last_interest_dt',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.LAST_INTEREST_DT',
      },
      logicName: '持续的兴趣',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_INTEREST_DT',
      id: 'last_interest_dt',
    },
    {
      codeName: 'uuid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.UUID',
      },
      logicName: 'UUID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'UUID',
      id: 'uuid',
    },
    {
      codeName: 'sfu_server_url',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.SFU_SERVER_URL',
      },
      logicName: 'Sfu 服务器网址',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SFU_SERVER_URL',
      id: 'sfu_server_url',
    },
    {
      codeName: 'channel_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.CHANNEL_TYPE',
      },
      logicName: '频道类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CHANNEL_TYPE',
      id: 'channel_type',
    },
    {
      codeName: 'default_display_mode',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.DEFAULT_DISPLAY_MODE',
      },
      logicName: '默认显示模式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'DEFAULT_DISPLAY_MODE',
      id: 'default_display_mode',
    },
    {
      codeName: 'message_has_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MESSAGE_HAS_ERROR',
      },
      logicName: '消息发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR',
      id: 'message_has_error',
    },
    {
      codeName: 'message_needaction',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MESSAGE_NEEDACTION',
      },
      logicName: '待处理',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION',
      id: 'message_needaction',
    },
    {
      codeName: 'is_member',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.IS_MEMBER',
      },
      logicName: '是会员',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_MEMBER',
      id: 'is_member',
    },
    {
      codeName: 'has_message',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.HAS_MESSAGE',
      },
      logicName: '有消息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_MESSAGE',
      id: 'has_message',
    },
    {
      codeName: 'message_is_follower',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MESSAGE_IS_FOLLOWER',
      },
      logicName: '是关注者',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_IS_FOLLOWER',
      id: 'message_is_follower',
    },
    {
      codeName: 'is_editable',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.IS_EDITABLE',
      },
      logicName: '能编辑',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_EDITABLE',
      id: 'is_editable',
    },
    {
      codeName: 'avatar_cache_key',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.AVATAR_CACHE_KEY',
      },
      logicName: '头像缓存键',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'AVATAR_CACHE_KEY',
      id: 'avatar_cache_key',
    },
    {
      codeName: 'message_has_error_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MESSAGE_HAS_ERROR_COUNTER',
      },
      logicName: '错误数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR_COUNTER',
      id: 'message_has_error_counter',
    },
    {
      codeName: 'message_has_sms_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MESSAGE_HAS_SMS_ERROR',
      },
      logicName: '短信发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_SMS_ERROR',
      id: 'message_has_sms_error',
    },
    {
      codeName: 'member_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MEMBER_COUNT',
      },
      logicName: '成员计数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MEMBER_COUNT',
      id: 'member_count',
    },
    {
      codeName: 'message_needaction_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MESSAGE_NEEDACTION_COUNTER',
      },
      logicName: '操作数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION_COUNTER',
      id: 'message_needaction_counter',
    },
    {
      codeName: 'message_attachment_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.MESSAGE_ATTACHMENT_COUNT',
      },
      logicName: '附件数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_ATTACHMENT_COUNT',
      id: 'message_attachment_count',
    },
    {
      codeName: 'invitation_url',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.INVITATION_URL',
      },
      logicName: '邀请URL',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'INVITATION_URL',
      id: 'invitation_url',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'from_message_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.FROM_MESSAGE_ID',
      },
      logicName: '来自消息',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'FROM_MESSAGE_ID',
      id: 'from_message_id',
    },
    {
      codeName: 'parent_channel_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.PARENT_CHANNEL_ID',
      },
      logicName: '父频道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_CHANNEL_ID',
      id: 'parent_channel_id',
    },
    {
      codeName: 'group_public_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.GROUP_PUBLIC_ID',
      },
      logicName: '授权群组',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'GROUP_PUBLIC_ID',
      id: 'group_public_id',
    },
    {
      codeName: 'parent_channel_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.PARENT_CHANNEL_ID',
      },
      logicName: '父频道名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PARENT_CHANNEL_NAME',
      id: 'parent_channel_name',
    },
    {
      codeName: 'group_public_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL.GROUP_PUBLIC_ID',
      },
      logicName: '授权群组',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'GROUP_PUBLIC_NAME',
      id: 'group_public_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'discuss_channel_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'attachments',
          logicName: '附件集合',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'ir_attachment_dto',
          refAppDataEntityId: 'ibizodooapp.ir_attachment',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'followers',
          logicName: '关注者',
          appDEFieldId: 'followers',
          refAppDEMethodDTOId: 'mail_followers_dto',
          refAppDataEntityId: 'ibizodooapp.mail_followers',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'followers',
        },
        {
          codeName: 'members',
          logicName: '成员',
          appDEFieldId: 'members',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'members',
        },
        {
          codeName: 'channel_members',
          logicName: '频道成员',
          appDEFieldId: 'channel_members',
          refAppDEDataSetId: 'fetch_default',
          refAppDEMethodDTOId: 'discuss_channel_member_dto',
          refAppDataEntityId: 'ibizodooapp.discuss_channel_member',
          refPickupAppDEFieldId: 'channel_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'channel_members',
        },
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'allow_public_upload',
          logicName: '允许公开上传',
          appDEFieldId: 'allow_public_upload',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'allow_public_upload',
        },
        {
          codeName: 'avatar_cache_key',
          logicName: '头像缓存键',
          appDEFieldId: 'avatar_cache_key',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'avatar_cache_key',
        },
        {
          codeName: 'channel_type',
          logicName: '频道类型',
          appDEFieldId: 'channel_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'channel_type',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'default_display_mode',
          logicName: '默认显示模式',
          appDEFieldId: 'default_display_mode',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'default_display_mode',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'from_message_id',
          logicName: '来自消息',
          appDEFieldId: 'from_message_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'from_message_id',
        },
        {
          codeName: 'group_public_id',
          logicName: '授权群组',
          appDEFieldId: 'group_public_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'group_public_id',
        },
        {
          codeName: 'group_public_name',
          logicName: '授权群组',
          appDEFieldId: 'group_public_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'group_public_name',
        },
        {
          codeName: 'has_message',
          logicName: '有消息',
          appDEFieldId: 'has_message',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_message',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'invitation_url',
          logicName: '邀请URL',
          appDEFieldId: 'invitation_url',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'invitation_url',
        },
        {
          codeName: 'is_editable',
          logicName: '能编辑',
          appDEFieldId: 'is_editable',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_editable',
        },
        {
          codeName: 'is_member',
          logicName: '是会员',
          appDEFieldId: 'is_member',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_member',
        },
        {
          codeName: 'last_interest_dt',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '持续的兴趣',
          appDEFieldId: 'last_interest_dt',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_interest_dt',
        },
        {
          codeName: 'member_count',
          logicName: '成员计数',
          appDEFieldId: 'member_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'member_count',
        },
        {
          codeName: 'message_attachment_count',
          logicName: '附件数量',
          appDEFieldId: 'message_attachment_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_attachment_count',
        },
        {
          codeName: 'message_has_error',
          logicName: '消息发送错误',
          appDEFieldId: 'message_has_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error',
        },
        {
          codeName: 'message_has_error_counter',
          logicName: '错误数量',
          appDEFieldId: 'message_has_error_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error_counter',
        },
        {
          codeName: 'message_has_sms_error',
          logicName: '短信发送错误',
          appDEFieldId: 'message_has_sms_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_sms_error',
        },
        {
          codeName: 'message_is_follower',
          logicName: '是关注者',
          appDEFieldId: 'message_is_follower',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_is_follower',
        },
        {
          codeName: 'message_needaction',
          logicName: '待处理',
          appDEFieldId: 'message_needaction',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction',
        },
        {
          codeName: 'message_needaction_counter',
          logicName: '操作数量',
          appDEFieldId: 'message_needaction_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction_counter',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'parent_channel_id',
          logicName: '父频道',
          appDEFieldId: 'parent_channel_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_channel_id',
        },
        {
          codeName: 'parent_channel_name',
          logicName: '父频道名称',
          appDEFieldId: 'parent_channel_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_channel_name',
        },
        {
          codeName: 'sfu_channel_uuid',
          logicName: 'Sfu 频道 Uuid',
          appDEFieldId: 'sfu_channel_uuid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sfu_channel_uuid',
        },
        {
          codeName: 'sfu_server_url',
          logicName: 'Sfu 服务器网址',
          appDEFieldId: 'sfu_server_url',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sfu_server_url',
        },
        {
          codeName: 'uuid',
          logicName: 'UUID',
          appDEFieldId: 'uuid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'uuid',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'discuss_channel_dto',
    },
    {
      codeName: 'discuss_channel_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_channel_type_eq',
          logicName: '频道类型',
          appDEFieldId: 'channel_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_channel_type_eq',
        },
        {
          codeName: 'n_default_display_mode_eq',
          logicName: '默认显示模式',
          appDEFieldId: 'default_display_mode',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_default_display_mode_eq',
        },
        {
          codeName: 'n_from_message_id_eq',
          logicName: '来自消息',
          appDEFieldId: 'from_message_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_from_message_id_eq',
        },
        {
          codeName: 'n_group_public_id_eq',
          logicName: '授权群组',
          appDEFieldId: 'group_public_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_group_public_id_eq',
        },
        {
          codeName: 'n_group_public_name_eq',
          logicName: '授权群组',
          appDEFieldId: 'group_public_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_group_public_name_eq',
        },
        {
          codeName: 'n_group_public_name_like',
          logicName: '授权群组',
          appDEFieldId: 'group_public_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_group_public_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_parent_channel_id_eq',
          logicName: '父频道',
          appDEFieldId: 'parent_channel_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_channel_id_eq',
        },
        {
          codeName: 'n_parent_channel_name_eq',
          logicName: '父频道名称',
          appDEFieldId: 'parent_channel_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_channel_name_eq',
        },
        {
          codeName: 'n_parent_channel_name_like',
          logicName: '父频道名称',
          appDEFieldId: 'parent_channel_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_channel_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'discuss_channel_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'action_unfollow',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/action_unfollow',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'action_unfollow',
    },
    {
      codeName: 'add_members',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_members',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_members',
    },
    {
      codeName: 'channel_join',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/channel_join',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'channel_join',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'join_channel',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/join_channel',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'join_channel',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'set_message_pin',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/set_message_pin',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'set_message_pin',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_cur_user_public',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_cur_user_public',
      actionType: 'REMOTE',
      dataSetName: 'cur_user_public',
      dataSetTag: 'cur_user_public',
      dataSetType: 'REMOTE',
      id: 'fetch_cur_user_public',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_group_private',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_group_private',
      actionType: 'REMOTE',
      dataSetName: 'group_private',
      dataSetTag: 'group_private',
      dataSetType: 'REMOTE',
      id: 'fetch_group_private',
    },
    {
      codeName: 'fetch_public',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_public',
      actionType: 'REMOTE',
      dataSetName: 'public',
      dataSetTag: 'public',
      dataSetType: 'REMOTE',
      id: 'fetch_public',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '离开频道',
      codeName: 'action_unfollow',
      confirmMsg: '确认离开频道？',
      fullCodeName: 'discuss_channel_action_unfollow',
      appDEMethodId: 'action_unfollow',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'action_unfollow',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'AFTER',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'refresh__channel',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '离开频道',
      id: 'action_unfollow@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '邀请人员',
      codeName: 'invite_member',
      frontAppViewId: 'ibizodooapp.discuss_channel_invite_member_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'discuss_channel_invite_member',
      navigateParams: [
        {
          key: 'channel_id',
          value: 'discuss_channel',
          id: 'channel_id',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'invite_member',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '邀请人员',
      id: 'invite_member@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '加入频道',
      codeName: 'join_channel',
      fullCodeName: 'discuss_channel_join_channel',
      appDEMethodId: 'join_channel',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'join_channel',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'AFTER',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'refresh__channel',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '加入频道',
      id: 'join_channel@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '打开聊天',
      codeName: 'open_chat',
      frontAppViewId: 'ibizodooapp.discuss_channel_main_pop_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'discuss_channel_open_chat',
      navigateParams: [
        {
          key: 'icon',
          value: 'avater',
          rawValue: true,
          id: 'icon',
        },
      ],
      sysPFPluginId: 'open_odoo_chat',
      uiactionMode: 'FRONT',
      uiactionParamJO: {
        icon: 'avater',
      },
      uiactionTag: 'open_chat',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '打开聊天',
      id: 'open_chat@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '附件',
      codeName: 'show_attachments',
      frontProcessType: 'OTHER',
      fullCodeName: 'discuss_channel_show_attachments',
      sysImage: {
        cssClass: 'fa fa-paperclip',
        glyph: 'xf0c6@FontAwesome',
      },
      scriptCode:
        'let  container_h_split = view.layoutPanel.findPanelItemByName("container_h_split");\r\nlet  active_panel = view.layoutPanel.findPanelItemByName("active_panel");\r\nif(!container_h_split.state.isHiddenTrigger){\r\n    if(active_panel.value=="attachment"){\r\n        container_h_split.hiddenPanel(\'right\');\r\n    }\r\n}else{\r\n    container_h_split.showPanel();\r\n}\r\nactive_panel.setDataValue("attachment");',
      uiactionMode: 'FRONT',
      uiactionTag: 'show_attachments',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '打开附件栏',
      id: 'show_attachments@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '成员',
      codeName: 'show_members',
      frontProcessType: 'OTHER',
      fullCodeName: 'discuss_channel_show_members',
      scriptCode:
        'let  active_panel = view.layoutPanel.findPanelItemByName("active_panel");\r\nlet  container_h_split = view.layoutPanel.findPanelItemByName("container_h_split");\r\nif(!container_h_split.state.isHiddenTrigger){\r\n    if(active_panel.value=="member"){\r\n        container_h_split.hiddenPanel(\'right\');\r\n    }\r\n}else{\r\n    container_h_split.showPanel();\r\n}\r\nactive_panel.setDataValue("member");',
      uiactionMode: 'FRONT',
      uiactionTag: 'show_members',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '打开成员列表栏',
      id: 'show_members@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '消息检索',
      codeName: 'show_search_messages',
      frontProcessType: 'OTHER',
      fullCodeName: 'discuss_channel_show_search_messages',
      sysImage: {
        cssClass: 'fa fa-search',
        glyph: 'xf002@FontAwesome',
      },
      scriptCode:
        'let  container_h_split = view.layoutPanel.findPanelItemByName("container_h_split");\r\nlet  active_panel = view.layoutPanel.findPanelItemByName("active_panel");\r\nif(!container_h_split.state.isHiddenTrigger){\r\n    if(active_panel.value=="search"){\r\n        container_h_split.hiddenPanel(\'right\');\r\n    }\r\n}else{\r\n    container_h_split.showPanel();\r\n}\r\nactive_panel.setDataValue("search");',
      uiactionMode: 'FRONT',
      uiactionTag: 'show_search_messages',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '打开消息检索',
      id: 'show_search_messages@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '新建频道',
      codeName: 'toolbar_discuss_main_view_channel_cm_deuiaction1_click',
      frontProcessType: 'OTHER',
      fullCodeName:
        'discuss_channel_toolbar_discuss_main_view_channel_cm_deuiaction1_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'toolbar_discuss_main_view_channel_cm_deuiaction1_click',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      uilogicType: 'DELOGIC',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'create_public_channel',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '新建频道',
      id: 'toolbar_discuss_main_view_channel_cm_deuiaction1_click@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '公共频道',
      codeName: 'toolbar_discuss_main_view_channel_cm_deuiaction2_click',
      frontAppViewId: 'ibizodooapp.discuss_channel_public_multi_data_view',
      frontProcessType: 'WIZARD',
      fullCodeName:
        'discuss_channel_toolbar_discuss_main_view_channel_cm_deuiaction2_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'toolbar_discuss_main_view_channel_cm_deuiaction2_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '频道管理',
      id: 'toolbar_discuss_main_view_channel_cm_deuiaction2_click@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '讨论频道',
      codeName: 'toolbar_discuss_main_view_channels_cm_deuiaction2_click',
      frontAppViewId: 'ibizodooapp.discuss_channel_quick_cfg_view',
      frontProcessType: 'WIZARD',
      fullCodeName:
        'discuss_channel_toolbar_discuss_main_view_channels_cm_deuiaction2_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'toolbar_discuss_main_view_channels_cm_deuiaction2_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '频道管理',
      id: 'toolbar_discuss_main_view_channels_cm_deuiaction2_click@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '新建频道',
      codeName:
        'toolbar_discuss_main_view_private_channel_cm_deuiaction1_click',
      frontProcessType: 'OTHER',
      fullCodeName:
        'discuss_channel_toolbar_discuss_main_view_private_channel_cm_deuiaction1_click',
      uiactionMode: 'FRONT',
      uiactionTag:
        'toolbar_discuss_main_view_private_channel_cm_deuiaction1_click',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      uilogicType: 'DELOGIC',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'create_private_channel',
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '新建频道',
      id: 'toolbar_discuss_main_view_private_channel_cm_deuiaction1_click@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '讨论串',
      codeName: 'toolbar_main_view_toolbar_deuiaction5_click',
      fullCodeName:
        'discuss_channel_toolbar_main_view_toolbar_deuiaction5_click',
      timeout: 60000,
      uiactionMode: 'CUSTOM',
      uiactionTag: 'toolbar_main_view_toolbar_deuiaction5_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '讨论串',
      id: 'toolbar_main_view_toolbar_deuiaction5_click@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '显示置顶消息',
      codeName: 'toolbar_main_view_toolbar_deuiaction6_click',
      fullCodeName:
        'discuss_channel_toolbar_main_view_toolbar_deuiaction6_click',
      scriptCode:
        'let  container_h_split = view.layoutPanel.findPanelItemByName("container_h_split");\nlet  active_panel = view.layoutPanel.findPanelItemByName("active_panel");\nif(!container_h_split.state.isHiddenTrigger){\n    if(active_panel.value=="pinned"){\n        container_h_split.hiddenPanel(\'right\');\n    }\n}else{\n    container_h_split.showPanel();\n}\nactive_panel.setDataValue("pinned");',
      timeout: 60000,
      uiactionMode: 'CUSTOM',
      uiactionTag: 'toolbar_main_view_toolbar_deuiaction6_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '显示置顶消息',
      id: 'toolbar_main_view_toolbar_deuiaction6_click@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '通知设置',
      codeName: 'toolbar_main_view_toolbar_deuiaction7_click',
      fullCodeName:
        'discuss_channel_toolbar_main_view_toolbar_deuiaction7_click',
      scriptCode: 'console.log(1111);',
      timeout: 60000,
      uiactionMode: 'CUSTOM',
      uiactionTag: 'toolbar_main_view_toolbar_deuiaction7_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '通知设置',
      id: 'toolbar_main_view_toolbar_deuiaction7_click@discuss_channel',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'create_private_channel',
      defaultParamName: 'Default',
      logicName: '新建私聊频道',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 70,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 202,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 317,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'nodeType',
              dstDEUILogicParamId: 'node_param',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'private_channels',
              srcValueType: 'SRCVALUE',
              name: '直接值[node_3] ==> node_param[nodeType]',
              id: '直接值[node_3] ==> node_param[nodetype]',
            },
            {
              dstFieldName: 'channel_type',
              dstDEUILogicParamId: 'defaultvalue',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'chat',
              srcValueType: 'SRCVALUE',
              name: '直接值[1] ==> defaultValue[is_published]',
              id: '直接值[1] ==> defaultvalue[is_published]',
            },
            {
              dstFieldName: 'active',
              dstDEUILogicParamId: 'defaultvalue',
              paramAction: 'SETPARAMVALUE',
              srcValue: '1',
              srcValueType: 'SRCVALUE',
              name: '直接值[undefined] ==> defaultValue[FORMAT_TYPE]',
              id: '直接值[undefined] ==> defaultvalue[format_type]',
            },
            {
              dstFieldName: 'defaultValue',
              dstDEUILogicParamId: 'node_param',
              paramAction: 'SETPARAMVALUE',
              srcDEUILogicParamId: 'defaultvalue',
              srcValueType: 'SRCDLPARAM',
              name: 'defaultValue ==> node_param[defaultValue]',
              id: 'defaultvalue ==> node_param[defaultvalue]',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '准备参数',
          id: 'preparejsparam1',
        },
        {
          invokeCtrlId: 'treeexpbar_tree',
          invokeMethod: 'newTreeNode',
          invokeParamId: 'node_param',
          codeName: 'VIEWCTRLINVOKE1',
          leftPos: 681,
          logicNodeType: 'VIEWCTRLINVOKE',
          topPos: 200,
          name: '视图部件调用',
          id: 'viewctrlinvoke1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'defaultValue',
          entityParam: true,
          name: '默认值对象',
          id: 'defaultvalue',
        },
        {
          codeName: 'context',
          navContextParam: true,
          name: '上下文对象',
          id: 'context',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'treeexpbar_tree',
          ctrlParam: true,
          name: '树部件',
          id: 'treeexpbar_tree',
        },
        {
          codeName: 'node_param',
          entityParam: true,
          name: '节点参数',
          id: 'node_param',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '新建私聊频道',
      id: 'create_private_channel',
    },
    {
      codeName: 'create_public_channel',
      defaultParamName: 'Default',
      logicName: '新建公共频道',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 70,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 202,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          invokeCtrlId: 'treeexpbar_tree',
          invokeMethod: 'newTreeNode',
          invokeParamId: 'node_param',
          codeName: 'VIEWCTRLINVOKE1',
          leftPos: 681,
          logicNodeType: 'VIEWCTRLINVOKE',
          topPos: 200,
          name: '视图部件调用',
          id: 'viewctrlinvoke1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 317,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'nodeType',
              dstDEUILogicParamId: 'node_param',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'channels',
              srcValueType: 'SRCVALUE',
              name: '直接值[node_3] ==> node_param[nodeType]',
              id: '直接值[node_3] ==> node_param[nodetype]',
            },
            {
              dstFieldName: 'channel_type',
              dstDEUILogicParamId: 'defaultvalue',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'channel',
              srcValueType: 'SRCVALUE',
              name: '直接值[1] ==> defaultValue[is_published]',
              id: '直接值[1] ==> defaultvalue[is_published]',
            },
            {
              dstFieldName: 'active',
              dstDEUILogicParamId: 'defaultvalue',
              paramAction: 'SETPARAMVALUE',
              srcValue: '1',
              srcValueType: 'SRCVALUE',
              name: '直接值[undefined] ==> defaultValue[FORMAT_TYPE]',
              id: '直接值[undefined] ==> defaultvalue[format_type]',
            },
            {
              dstFieldName: 'defaultValue',
              dstDEUILogicParamId: 'node_param',
              paramAction: 'SETPARAMVALUE',
              srcDEUILogicParamId: 'defaultvalue',
              srcValueType: 'SRCDLPARAM',
              name: 'defaultValue ==> node_param[defaultValue]',
              id: 'defaultvalue ==> node_param[defaultvalue]',
            },
            {
              dstFieldName: 'parentKey',
              dstDEUILogicParamId: 'node_param',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: '_id',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '准备参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'context',
          navContextParam: true,
          name: '上下文对象',
          id: 'context',
        },
        {
          codeName: 'defaultValue',
          entityParam: true,
          name: '默认值对象',
          id: 'defaultvalue',
        },
        {
          codeName: 'node_param',
          entityParam: true,
          name: '节点参数',
          id: 'node_param',
        },
        {
          codeName: 'treeexpbar_tree',
          ctrlParam: true,
          name: '树部件',
          id: 'treeexpbar_tree',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '新建公共频道',
      id: 'create_public_channel',
    },
    {
      codeName: 'refresh__channel',
      defaultParamName: 'Default',
      logicName: '刷新频道列表',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 310,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: "ibiz.mc.command.update.send({ srfdecodename: 'discuss_channel',srfkey: uiLogic.ctx.discuss_channel})",
          codeName: 'RAWJSCODE1',
          leftPos: 538,
          logicNodeType: 'RAWJSCODE',
          topPos: 198,
          name: '注入脚本代码',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          id: 'ctx',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '刷新频道列表',
      id: 'refresh__channel',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'discuss_channel',
  deapicodeName: 'discuss_channel',
  deapicodeName2: 'discuss_channels',
  deapitag: 'DISCUSS_CHANNEL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL',
  },
  logicName: '讨论频道',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'DISCUSS_CHANNEL',
  id: 'ibizodooapp.discuss_channel',
  codeName2: 'discuss_channels',
  requestPaths: [],
};
