export default {
  appDEFields: [
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'new_message_separator',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.NEW_MESSAGE_SEPARATOR',
      },
      logicName: '新信息分割符',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'NEW_MESSAGE_SEPARATOR',
      id: 'new_message_separator',
    },
    {
      codeName: 'unpin_dt',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.UNPIN_DT',
      },
      logicName: '取消置顶日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UNPIN_DT',
      id: 'unpin_dt',
    },
    {
      codeName: 'last_seen_dt',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.LAST_SEEN_DT',
      },
      logicName: '上次查看日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_SEEN_DT',
      id: 'last_seen_dt',
    },
    {
      codeName: 'custom_channel_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.CUSTOM_CHANNEL_NAME',
      },
      logicName: '自定义频道名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'CUSTOM_CHANNEL_NAME',
      id: 'custom_channel_name',
    },
    {
      codeName: 'mute_until_dt',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.MUTE_UNTIL_DT',
      },
      logicName: '静音通知，直到',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'MUTE_UNTIL_DT',
      id: 'mute_until_dt',
    },
    {
      codeName: 'last_interest_dt',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.LAST_INTEREST_DT',
      },
      logicName: '持续的兴趣',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_INTEREST_DT',
      id: 'last_interest_dt',
    },
    {
      codeName: 'fold_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.FOLD_STATE',
      },
      logicName: '对话收拢状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'FOLD_STATE',
      id: 'fold_state',
    },
    {
      codeName: 'custom_notifications',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.CUSTOM_NOTIFICATIONS',
      },
      logicName: '定制通知',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CUSTOM_NOTIFICATIONS',
      id: 'custom_notifications',
    },
    {
      codeName: 'is_self',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.IS_SELF',
      },
      logicName: '是自我',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_SELF',
      id: 'is_self',
    },
    {
      codeName: 'is_pinned',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.IS_PINNED',
      },
      logicName: '是否置顶',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_PINNED',
      id: 'is_pinned',
    },
    {
      codeName: 'message_unread_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.MESSAGE_UNREAD_COUNTER',
      },
      logicName: '未读消息数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_UNREAD_COUNTER',
      id: 'message_unread_counter',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'guest_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.GUEST_ID',
      },
      logicName: '访客',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'GUEST_ID',
      id: 'guest_id',
    },
    {
      codeName: 'channel_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.CHANNEL_ID',
      },
      logicName: '频道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CHANNEL_ID',
      id: 'channel_id',
    },
    {
      codeName: 'fetched_message_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.FETCHED_MESSAGE_ID',
      },
      logicName: '最后一次提取',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'FETCHED_MESSAGE_ID',
      id: 'fetched_message_id',
    },
    {
      codeName: 'partner_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.PARTNER_ID',
      },
      logicName: '合作伙伴',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARTNER_ID',
      id: 'partner_id',
    },
    {
      codeName: 'seen_message_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.SEEN_MESSAGE_ID',
      },
      logicName: '最近一次查阅',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SEEN_MESSAGE_ID',
      id: 'seen_message_id',
    },
    {
      codeName: 'rtc_inviting_session_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.RTC_INVITING_SESSION_ID',
      },
      logicName: '振铃会话',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RTC_INVITING_SESSION_ID',
      id: 'rtc_inviting_session_id',
    },
    {
      codeName: 'partner_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.PARTNER_ID',
      },
      logicName: '合作伙伴',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PARTNER_NAME',
      id: 'partner_name',
    },
    {
      codeName: 'guest_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DISCUSS_CHANNEL_MEMBER.GUEST_ID',
      },
      logicName: '访客',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'GUEST_NAME',
      id: 'guest_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'discuss_channel_member_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'channel_id',
          logicName: '频道',
          appDEFieldId: 'channel_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'channel_id',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'custom_channel_name',
          logicName: '自定义频道名称',
          appDEFieldId: 'custom_channel_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'custom_channel_name',
        },
        {
          codeName: 'custom_notifications',
          logicName: '定制通知',
          appDEFieldId: 'custom_notifications',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'custom_notifications',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'fetched_message_id',
          logicName: '最后一次提取',
          appDEFieldId: 'fetched_message_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'fetched_message_id',
        },
        {
          codeName: 'fold_state',
          logicName: '对话收拢状态',
          appDEFieldId: 'fold_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'fold_state',
        },
        {
          codeName: 'guest_id',
          logicName: '访客',
          appDEFieldId: 'guest_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'guest_id',
        },
        {
          codeName: 'guest_name',
          logicName: '访客',
          appDEFieldId: 'guest_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'guest_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'is_pinned',
          logicName: '是否置顶',
          appDEFieldId: 'is_pinned',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_pinned',
        },
        {
          codeName: 'is_self',
          logicName: '是自我',
          appDEFieldId: 'is_self',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_self',
        },
        {
          codeName: 'last_interest_dt',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '持续的兴趣',
          appDEFieldId: 'last_interest_dt',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_interest_dt',
        },
        {
          codeName: 'last_seen_dt',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '上次查看日期',
          appDEFieldId: 'last_seen_dt',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_seen_dt',
        },
        {
          codeName: 'message_unread_counter',
          logicName: '未读消息数',
          appDEFieldId: 'message_unread_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_unread_counter',
        },
        {
          codeName: 'mute_until_dt',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '静音通知，直到',
          appDEFieldId: 'mute_until_dt',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mute_until_dt',
        },
        {
          codeName: 'new_message_separator',
          logicName: '新信息分割符',
          appDEFieldId: 'new_message_separator',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          id: 'new_message_separator',
        },
        {
          codeName: 'partner_id',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_id',
        },
        {
          codeName: 'partner_name',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_name',
        },
        {
          codeName: 'rtc_inviting_session_id',
          logicName: '振铃会话',
          appDEFieldId: 'rtc_inviting_session_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rtc_inviting_session_id',
        },
        {
          codeName: 'seen_message_id',
          logicName: '最近一次查阅',
          appDEFieldId: 'seen_message_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'seen_message_id',
        },
        {
          codeName: 'unpin_dt',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '取消置顶日期',
          appDEFieldId: 'unpin_dt',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'unpin_dt',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'discuss_channel_member_dto',
    },
    {
      codeName: 'discuss_channel_member_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_channel_id_eq',
          logicName: '频道',
          appDEFieldId: 'channel_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_channel_id_eq',
        },
        {
          codeName: 'n_custom_notifications_eq',
          logicName: '定制通知',
          appDEFieldId: 'custom_notifications',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_custom_notifications_eq',
        },
        {
          codeName: 'n_fetched_message_id_eq',
          logicName: '最后一次提取',
          appDEFieldId: 'fetched_message_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_fetched_message_id_eq',
        },
        {
          codeName: 'n_fold_state_eq',
          logicName: '对话收拢状态',
          appDEFieldId: 'fold_state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_fold_state_eq',
        },
        {
          codeName: 'n_guest_id_eq',
          logicName: '访客',
          appDEFieldId: 'guest_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_guest_id_eq',
        },
        {
          codeName: 'n_guest_name_eq',
          logicName: '访客',
          appDEFieldId: 'guest_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_guest_name_eq',
        },
        {
          codeName: 'n_guest_name_like',
          logicName: '访客',
          appDEFieldId: 'guest_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_guest_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_partner_id_eq',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_partner_id_eq',
        },
        {
          codeName: 'n_partner_name_eq',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_partner_name_eq',
        },
        {
          codeName: 'n_partner_name_like',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_partner_name_like',
        },
        {
          codeName: 'n_rtc_inviting_session_id_eq',
          logicName: '振铃会话',
          appDEFieldId: 'rtc_inviting_session_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rtc_inviting_session_id_eq',
        },
        {
          codeName: 'n_seen_message_id_eq',
          logicName: '最近一次查阅',
          appDEFieldId: 'seen_message_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_seen_message_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'discuss_channel_member_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'discuss_channel_member_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'discuss_channel_member_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'discuss_channel_member',
  deapicodeName: 'discuss_channel_member',
  deapicodeName2: 'discuss_channel_members',
  deapitag: 'DISCUSS_CHANNEL_MEMBER',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.DISCUSS_CHANNEL_MEMBER',
  },
  logicName: '频道成员',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'channel_members',
      majorAppDataEntityId: 'ibizodooapp.discuss_channel',
      parentAppDEFieldId: 'channel_id',
      rsmode: 2,
      tempDataOrder: 10,
      name: '频道-频道成员',
      id: 'channel_members',
    },
  ],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['channel_id', 'partner_id'],
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'DISCUSS_CHANNEL_MEMBER',
  id: 'ibizodooapp.discuss_channel_member',
  codeName2: 'discuss_channel_members',
  requestPaths: [
    'discuss_channels/${discuss_channel}/discuss_channel_members/${discuss_channel_member}',
  ],
};
