export default {
  appDEFields: [
    {
      codeName: 'object_id',
      logicName: '创建新记录',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OBJECT_ID',
      id: 'object_id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'is_ssl',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.IS_SSL',
      },
      logicName: 'SSL/TLS',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_SSL',
      id: 'is_ssl',
    },
    {
      codeName: 'active',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.ACTIVE',
      },
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'attach',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.ATTACH',
      },
      logicName: '保存附件',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ATTACH',
      id: 'attach',
    },
    {
      codeName: 'original',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.ORIGINAL',
      },
      logicName: '保留原件',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ORIGINAL',
      id: 'original',
    },
    {
      codeName: 'user',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.USER',
      },
      logicName: '用户名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'USER',
      id: 'user',
    },
    {
      codeName: 'configuration',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.CONFIGURATION',
      },
      logicName: '配置',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CONFIGURATION',
      id: 'configuration',
    },
    {
      codeName: 'date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.DATE',
      },
      logicName: '最后收取日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE',
      id: 'date',
    },
    {
      codeName: 'server',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.SERVER',
      },
      logicName: '服务器名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SERVER',
      id: 'server',
    },
    {
      codeName: 'port',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.PORT',
      },
      logicName: '端口',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PORT',
      id: 'port',
    },
    {
      codeName: 'priority',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.PRIORITY',
      },
      logicName: '服务器优先级',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PRIORITY',
      id: 'priority',
    },
    {
      codeName: 'google_gmail_access_token_expiration',
      lnlanguageRes: {
        lanResTag:
          'DEF.LNAME.FETCHMAIL_SERVER.GOOGLE_GMAIL_ACCESS_TOKEN_EXPIRATION',
      },
      logicName: '访问令牌到期时间戳',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'GOOGLE_GMAIL_ACCESS_TOKEN_EXPIRATION',
      id: 'google_gmail_access_token_expiration',
    },
    {
      codeName: 'script',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.SCRIPT',
      },
      logicName: '脚本',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SCRIPT',
      id: 'script',
    },
    {
      codeName: 'google_gmail_authorization_code',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.GOOGLE_GMAIL_AUTHORIZATION_CODE',
      },
      logicName: '授权码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'GOOGLE_GMAIL_AUTHORIZATION_CODE',
      id: 'google_gmail_authorization_code',
    },
    {
      codeName: 'password',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.PASSWORD',
      },
      logicName: '密码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'PASSWORD',
      id: 'password',
    },
    {
      codeName: 'google_gmail_refresh_token',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.GOOGLE_GMAIL_REFRESH_TOKEN',
      },
      logicName: '更新 Token',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'GOOGLE_GMAIL_REFRESH_TOKEN',
      id: 'google_gmail_refresh_token',
    },
    {
      codeName: 'state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.STATE',
      },
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'google_gmail_access_token',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.GOOGLE_GMAIL_ACCESS_TOKEN',
      },
      logicName: '访问令牌',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'GOOGLE_GMAIL_ACCESS_TOKEN',
      id: 'google_gmail_access_token',
    },
    {
      codeName: 'server_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FETCHMAIL_SERVER.SERVER_TYPE',
      },
      logicName: '服务器类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SERVER_TYPE',
      id: 'server_type',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'fetchmail_server_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'object_id',
          logicName: '创建新记录',
          appDEFieldId: 'object_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'object_id',
        },
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'attach',
          logicName: '保存附件',
          appDEFieldId: 'attach',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attach',
        },
        {
          codeName: 'configuration',
          logicName: '配置',
          appDEFieldId: 'configuration',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'configuration',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最后收取日期',
          appDEFieldId: 'date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date',
        },
        {
          codeName: 'google_gmail_access_token',
          logicName: '访问令牌',
          appDEFieldId: 'google_gmail_access_token',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_access_token',
        },
        {
          codeName: 'google_gmail_access_token_expiration',
          logicName: '访问令牌到期时间戳',
          appDEFieldId: 'google_gmail_access_token_expiration',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_access_token_expiration',
        },
        {
          codeName: 'google_gmail_authorization_code',
          logicName: '授权码',
          appDEFieldId: 'google_gmail_authorization_code',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_authorization_code',
        },
        {
          codeName: 'google_gmail_refresh_token',
          logicName: '更新 Token',
          appDEFieldId: 'google_gmail_refresh_token',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_refresh_token',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'is_ssl',
          logicName: 'SSL/TLS',
          appDEFieldId: 'is_ssl',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_ssl',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'original',
          logicName: '保留原件',
          appDEFieldId: 'original',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'original',
        },
        {
          codeName: 'password',
          logicName: '密码',
          appDEFieldId: 'password',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'password',
        },
        {
          codeName: 'port',
          logicName: '端口',
          appDEFieldId: 'port',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'port',
        },
        {
          codeName: 'priority',
          logicName: '服务器优先级',
          appDEFieldId: 'priority',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'priority',
        },
        {
          codeName: 'script',
          logicName: '脚本',
          appDEFieldId: 'script',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'script',
        },
        {
          codeName: 'server',
          logicName: '服务器名称',
          appDEFieldId: 'server',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'server',
        },
        {
          codeName: 'server_type',
          logicName: '服务器类型',
          appDEFieldId: 'server_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'server_type',
        },
        {
          codeName: 'state',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'user',
          logicName: '用户名',
          appDEFieldId: 'user',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'fetchmail_server_dto',
    },
    {
      codeName: 'fetchmail_server_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_server_type_eq',
          logicName: '服务器类型',
          appDEFieldId: 'server_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_server_type_eq',
        },
        {
          codeName: 'n_state_eq',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_state_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'fetchmail_server_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'fetch_mail',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_mail',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'fetch_mail',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'set_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/set_draft',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'set_draft',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'fetchmail_server_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'fetchmail_server_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '测试和确认',
      codeName: 'button_confirm_login',
      fullCodeName: 'fetchmail_server_button_confirm_login',
      appDEMethodId: 'get',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'button_confirm_login',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.fetchmail_server',
      name: '测试和确认',
      id: 'button_confirm_login@fetchmail_server',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '现在收取',
      codeName: 'fetch_mail',
      fullCodeName: 'fetchmail_server_fetch_mail',
      appDEMethodId: 'get',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'fetch_mail',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.fetchmail_server',
      name: '现在收取',
      id: 'fetch_mail@fetchmail_server',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '重置确认',
      codeName: 'set_draft',
      fullCodeName: 'fetchmail_server_set_draft',
      appDEMethodId: 'set_draft',
      refreshMode: 1,
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'set_draft',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.fetchmail_server',
      name: '重置确认',
      id: 'set_draft@fetchmail_server',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'fetchmail_server',
  deapicodeName: 'fetchmail_server',
  deapicodeName2: 'fetchmail_servers',
  deapitag: 'FETCHMAIL_SERVER',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.FETCHMAIL_SERVER',
  },
  logicName: '收件服务器',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'FETCHMAIL_SERVER',
  id: 'ibizodooapp.fetchmail_server',
  codeName2: 'fetchmail_servers',
  requestPaths: [],
};
