export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'ibizodooapp.hr_leave',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'request_unit_half',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.REQUEST_UNIT_HALF',
      },
      logicName: '半天',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'REQUEST_UNIT_HALF',
      id: 'request_unit_half',
    },
    {
      codeName: 'request_unit_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.REQUEST_UNIT_HOURS',
      },
      logicName: '自定义时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'REQUEST_UNIT_HOURS',
      id: 'request_unit_hours',
    },
    {
      codeName: 'request_hour_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.REQUEST_HOUR_FROM',
      },
      logicName: '时间从',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'REQUEST_HOUR_FROM',
      id: 'request_hour_from',
    },
    {
      codeName: 'request_hour_to',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.REQUEST_HOUR_TO',
      },
      logicName: '时间到',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'REQUEST_HOUR_TO',
      id: 'request_hour_to',
    },
    {
      codeName: 'number_of_days',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.NUMBER_OF_DAYS',
      },
      logicName: '持续时间（天）',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'NUMBER_OF_DAYS',
      id: 'number_of_days',
    },
    {
      codeName: 'number_of_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.NUMBER_OF_HOURS',
      },
      logicName: '持续时间(小时)',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'NUMBER_OF_HOURS',
      id: 'number_of_hours',
    },
    {
      codeName: 'date_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.DATE_FROM',
      },
      logicName: '开始日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_FROM',
      id: 'date_from',
    },
    {
      codeName: 'date_to',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.DATE_TO',
      },
      logicName: '结束日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_TO',
      id: 'date_to',
    },
    {
      codeName: 'request_date_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.REQUEST_DATE_FROM',
      },
      logicName: '请假开始日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'REQUEST_DATE_FROM',
      id: 'request_date_from',
    },
    {
      codeName: 'request_date_to',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.REQUEST_DATE_TO',
      },
      logicName: '请求结束日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'REQUEST_DATE_TO',
      id: 'request_date_to',
    },
    {
      codeName: 'notes',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.NOTES',
      },
      logicName: '理由',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'NOTES',
      id: 'notes',
    },
    {
      codeName: 'private_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.PRIVATE_NAME',
      },
      logicName: '休假描述',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PRIVATE_NAME',
      id: 'private_name',
    },
    {
      codeName: 'duration_display',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.DURATION_DISPLAY',
      },
      logicName: '要求的（天/小时）',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DURATION_DISPLAY',
      id: 'duration_display',
    },
    {
      codeName: 'request_date_from_period',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.REQUEST_DATE_FROM_PERIOD',
      },
      logicName: '日期开始',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'REQUEST_DATE_FROM_PERIOD',
      id: 'request_date_from_period',
    },
    {
      codeName: 'state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.STATE',
      },
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'manager_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MANAGER_ID',
      },
      logicName: '管理员',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MANAGER_ID',
      id: 'manager_id',
    },
    {
      codeName: 'user_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.USER_ID',
      },
      logicName: '用户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USER_ID',
      id: 'user_id',
    },
    {
      codeName: 'message_main_attachment_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_MAIN_ATTACHMENT_ID',
      },
      logicName: '主要附件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MESSAGE_MAIN_ATTACHMENT_ID',
      id: 'message_main_attachment_id',
    },
    {
      codeName: 'company_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.COMPANY_ID',
      },
      logicName: '公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COMPANY_ID',
      id: 'company_id',
    },
    {
      codeName: 'holiday_status_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.HOLIDAY_STATUS_ID',
      },
      logicName: '休假类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'HOLIDAY_STATUS_ID',
      id: 'holiday_status_id',
    },
    {
      codeName: 'department_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.DEPARTMENT_ID',
      },
      logicName: '部门',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPARTMENT_ID',
      id: 'department_id',
    },
    {
      codeName: 'employee_company_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.EMPLOYEE_COMPANY_ID',
      },
      logicName: '员工公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EMPLOYEE_COMPANY_ID',
      id: 'employee_company_id',
    },
    {
      codeName: 'employee_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.EMPLOYEE_ID',
      },
      logicName: '员工',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EMPLOYEE_ID',
      id: 'employee_id',
    },
    {
      codeName: 'overtime_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.OVERTIME_ID',
      },
      logicName: '加班时间',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OVERTIME_ID',
      id: 'overtime_id',
    },
    {
      codeName: 'second_approver_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.SECOND_APPROVER_ID',
      },
      logicName: '第二次审批',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SECOND_APPROVER_ID',
      id: 'second_approver_id',
    },
    {
      codeName: 'first_approver_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.FIRST_APPROVER_ID',
      },
      logicName: '首次审批',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'FIRST_APPROVER_ID',
      id: 'first_approver_id',
    },
    {
      codeName: 'message_is_follower',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_IS_FOLLOWER',
      },
      logicName: '是关注者',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_IS_FOLLOWER',
      id: 'message_is_follower',
    },
    {
      codeName: 'tz_mismatch',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.TZ_MISMATCH',
      },
      logicName: '时区不匹配',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'TZ_MISMATCH',
      id: 'tz_mismatch',
    },
    {
      codeName: 'has_message',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.HAS_MESSAGE',
      },
      logicName: '有消息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_MESSAGE',
      id: 'has_message',
    },
    {
      codeName: 'is_striked',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.IS_STRIKED',
      },
      logicName: '罢工',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_STRIKED',
      id: 'is_striked',
    },
    {
      codeName: 'leave_type_increases_duration',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.LEAVE_TYPE_INCREASES_DURATION',
      },
      logicName: '假期类型 增加持续时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LEAVE_TYPE_INCREASES_DURATION',
      id: 'leave_type_increases_duration',
    },
    {
      codeName: 'has_mandatory_day',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.HAS_MANDATORY_DAY',
      },
      logicName: '有义务日',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_MANDATORY_DAY',
      id: 'has_mandatory_day',
    },
    {
      codeName: 'is_hatched',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.IS_HATCHED',
      },
      logicName: '已孵化',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_HATCHED',
      id: 'is_hatched',
    },
    {
      codeName: 'can_reset',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.CAN_RESET',
      },
      logicName: '能重置',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CAN_RESET',
      id: 'can_reset',
    },
    {
      codeName: 'can_approve',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.CAN_APPROVE',
      },
      logicName: '能批准',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CAN_APPROVE',
      id: 'can_approve',
    },
    {
      codeName: 'last_several_days',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.LAST_SEVERAL_DAYS',
      },
      logicName: '全天',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LAST_SEVERAL_DAYS',
      id: 'last_several_days',
    },
    {
      codeName: 'can_cancel',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.CAN_CANCEL',
      },
      logicName: '可以取消',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CAN_CANCEL',
      id: 'can_cancel',
    },
    {
      codeName: 'message_has_sms_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_HAS_SMS_ERROR',
      },
      logicName: '短信发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_SMS_ERROR',
      id: 'message_has_sms_error',
    },
    {
      codeName: 'message_has_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_HAS_ERROR',
      },
      logicName: '消息发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR',
      id: 'message_has_error',
    },
    {
      codeName: 'overtime_deductible',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.OVERTIME_DEDUCTIBLE',
      },
      logicName: '加班费免赔额',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OVERTIME_DEDUCTIBLE',
      id: 'overtime_deductible',
    },
    {
      codeName: 'message_needaction',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_NEEDACTION',
      },
      logicName: '所需操作',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION',
      id: 'message_needaction',
    },
    {
      codeName: 'activity_date_deadline',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.ACTIVITY_DATE_DEADLINE',
      },
      logicName: '下一活动截止日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'ACTIVITY_DATE_DEADLINE',
      id: 'activity_date_deadline',
    },
    {
      codeName: 'my_activity_date_deadline',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MY_ACTIVITY_DATE_DEADLINE',
      },
      logicName: '我的活动截止时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'MY_ACTIVITY_DATE_DEADLINE',
      id: 'my_activity_date_deadline',
    },
    {
      codeName: 'supported_attachment_ids_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.SUPPORTED_ATTACHMENT_IDS_COUNT',
      },
      logicName: '支持的附件ID计数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SUPPORTED_ATTACHMENT_IDS_COUNT',
      id: 'supported_attachment_ids_count',
    },
    {
      codeName: 'message_attachment_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_ATTACHMENT_COUNT',
      },
      logicName: '附件数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_ATTACHMENT_COUNT',
      id: 'message_attachment_count',
    },
    {
      codeName: 'message_needaction_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_NEEDACTION_COUNTER',
      },
      logicName: '操作数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION_COUNTER',
      id: 'message_needaction_counter',
    },
    {
      codeName: 'message_has_error_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.MESSAGE_HAS_ERROR_COUNTER',
      },
      logicName: '错误数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR_COUNTER',
      id: 'message_has_error_counter',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'activity_exception_icon',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.ACTIVITY_EXCEPTION_ICON',
      },
      logicName: '图标',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ACTIVITY_EXCEPTION_ICON',
      id: 'activity_exception_icon',
    },
    {
      codeName: 'activity_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.ACTIVITY_STATE',
      },
      logicName: '活动状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_STATE',
      id: 'activity_state',
    },
    {
      codeName: 'activity_exception_decoration',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.ACTIVITY_EXCEPTION_DECORATION',
      },
      logicName: '活动异常标示',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_EXCEPTION_DECORATION',
      id: 'activity_exception_decoration',
    },
    {
      codeName: 'resource_calendar_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HR_LEAVE.RESOURCE_CALENDAR_ID',
      },
      logicName: '资源行事历',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RESOURCE_CALENDAR_ID',
      id: 'resource_calendar_id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'hr_leave_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'activity_date_deadline',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '下一活动截止日期',
          appDEFieldId: 'activity_date_deadline',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_date_deadline',
        },
        {
          codeName: 'activity_exception_decoration',
          logicName: '活动异常标示',
          appDEFieldId: 'activity_exception_decoration',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_exception_decoration',
        },
        {
          codeName: 'activity_exception_icon',
          logicName: '图标',
          appDEFieldId: 'activity_exception_icon',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_exception_icon',
        },
        {
          codeName: 'activity_state',
          logicName: '活动状态',
          appDEFieldId: 'activity_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_state',
        },
        {
          codeName: 'can_approve',
          logicName: '能批准',
          appDEFieldId: 'can_approve',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'can_approve',
        },
        {
          codeName: 'can_cancel',
          logicName: '可以取消',
          appDEFieldId: 'can_cancel',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'can_cancel',
        },
        {
          codeName: 'can_reset',
          logicName: '能重置',
          appDEFieldId: 'can_reset',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'can_reset',
        },
        {
          codeName: 'company_id',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_id',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'date_from',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '开始日期',
          appDEFieldId: 'date_from',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_from',
        },
        {
          codeName: 'date_to',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '结束日期',
          appDEFieldId: 'date_to',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_to',
        },
        {
          codeName: 'department_id',
          logicName: '部门',
          appDEFieldId: 'department_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'department_id',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'duration_display',
          logicName: '要求的（天/小时）',
          appDEFieldId: 'duration_display',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'duration_display',
        },
        {
          codeName: 'employee_company_id',
          logicName: '员工公司',
          appDEFieldId: 'employee_company_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'employee_company_id',
        },
        {
          codeName: 'employee_id',
          logicName: '员工',
          appDEFieldId: 'employee_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'employee_id',
        },
        {
          codeName: 'first_approver_id',
          logicName: '首次审批',
          appDEFieldId: 'first_approver_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'first_approver_id',
        },
        {
          codeName: 'has_mandatory_day',
          logicName: '有义务日',
          appDEFieldId: 'has_mandatory_day',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_mandatory_day',
        },
        {
          codeName: 'has_message',
          logicName: '有消息',
          appDEFieldId: 'has_message',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_message',
        },
        {
          codeName: 'holiday_status_id',
          logicName: '休假类型',
          appDEFieldId: 'holiday_status_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'holiday_status_id',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'is_hatched',
          logicName: '已孵化',
          appDEFieldId: 'is_hatched',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_hatched',
        },
        {
          codeName: 'is_striked',
          logicName: '罢工',
          appDEFieldId: 'is_striked',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_striked',
        },
        {
          codeName: 'last_several_days',
          logicName: '全天',
          appDEFieldId: 'last_several_days',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_several_days',
        },
        {
          codeName: 'leave_type_increases_duration',
          logicName: '假期类型 增加持续时间',
          appDEFieldId: 'leave_type_increases_duration',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'leave_type_increases_duration',
        },
        {
          codeName: 'manager_id',
          logicName: '管理员',
          appDEFieldId: 'manager_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'manager_id',
        },
        {
          codeName: 'message_attachment_count',
          logicName: '附件数量',
          appDEFieldId: 'message_attachment_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_attachment_count',
        },
        {
          codeName: 'message_has_error',
          logicName: '消息发送错误',
          appDEFieldId: 'message_has_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error',
        },
        {
          codeName: 'message_has_error_counter',
          logicName: '错误数量',
          appDEFieldId: 'message_has_error_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error_counter',
        },
        {
          codeName: 'message_has_sms_error',
          logicName: '短信发送错误',
          appDEFieldId: 'message_has_sms_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_sms_error',
        },
        {
          codeName: 'message_is_follower',
          logicName: '是关注者',
          appDEFieldId: 'message_is_follower',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_is_follower',
        },
        {
          codeName: 'message_main_attachment_id',
          logicName: '主要附件',
          appDEFieldId: 'message_main_attachment_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_main_attachment_id',
        },
        {
          codeName: 'message_needaction',
          logicName: '所需操作',
          appDEFieldId: 'message_needaction',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction',
        },
        {
          codeName: 'message_needaction_counter',
          logicName: '操作数量',
          appDEFieldId: 'message_needaction_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction_counter',
        },
        {
          codeName: 'my_activity_date_deadline',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '我的活动截止时间',
          appDEFieldId: 'my_activity_date_deadline',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'my_activity_date_deadline',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'notes',
          logicName: '理由',
          appDEFieldId: 'notes',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'notes',
        },
        {
          codeName: 'number_of_days',
          logicName: '持续时间（天）',
          appDEFieldId: 'number_of_days',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'number_of_days',
        },
        {
          codeName: 'number_of_hours',
          logicName: '持续时间(小时)',
          appDEFieldId: 'number_of_hours',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'number_of_hours',
        },
        {
          codeName: 'overtime_deductible',
          logicName: '加班费免赔额',
          appDEFieldId: 'overtime_deductible',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overtime_deductible',
        },
        {
          codeName: 'overtime_id',
          logicName: '加班时间',
          appDEFieldId: 'overtime_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overtime_id',
        },
        {
          codeName: 'private_name',
          logicName: '休假描述',
          appDEFieldId: 'private_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'private_name',
        },
        {
          codeName: 'request_date_from',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '请假开始日期',
          appDEFieldId: 'request_date_from',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'request_date_from',
        },
        {
          codeName: 'request_date_from_period',
          logicName: '日期开始',
          appDEFieldId: 'request_date_from_period',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'request_date_from_period',
        },
        {
          codeName: 'request_date_to',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '请求结束日期',
          appDEFieldId: 'request_date_to',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'request_date_to',
        },
        {
          codeName: 'request_hour_from',
          logicName: '时间从',
          appDEFieldId: 'request_hour_from',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'request_hour_from',
        },
        {
          codeName: 'request_hour_to',
          logicName: '时间到',
          appDEFieldId: 'request_hour_to',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'request_hour_to',
        },
        {
          codeName: 'request_unit_half',
          logicName: '半天',
          appDEFieldId: 'request_unit_half',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'request_unit_half',
        },
        {
          codeName: 'request_unit_hours',
          logicName: '自定义时间',
          appDEFieldId: 'request_unit_hours',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'request_unit_hours',
        },
        {
          codeName: 'resource_calendar_id',
          logicName: '资源行事历',
          appDEFieldId: 'resource_calendar_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'resource_calendar_id',
        },
        {
          codeName: 'second_approver_id',
          logicName: '第二次审批',
          appDEFieldId: 'second_approver_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'second_approver_id',
        },
        {
          codeName: 'state',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'supported_attachment_ids_count',
          logicName: '支持的附件ID计数',
          appDEFieldId: 'supported_attachment_ids_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'supported_attachment_ids_count',
        },
        {
          codeName: 'tz_mismatch',
          logicName: '时区不匹配',
          appDEFieldId: 'tz_mismatch',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'tz_mismatch',
        },
        {
          codeName: 'user_id',
          logicName: '用户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_id',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'hr_leave_dto',
    },
    {
      codeName: 'hr_leave_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_activity_exception_decoration_eq',
          logicName: '活动异常标示',
          appDEFieldId: 'activity_exception_decoration',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_exception_decoration_eq',
        },
        {
          codeName: 'n_activity_state_eq',
          logicName: '活动状态',
          appDEFieldId: 'activity_state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_state_eq',
        },
        {
          codeName: 'n_company_id_eq',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_id_eq',
        },
        {
          codeName: 'n_department_id_eq',
          logicName: '部门',
          appDEFieldId: 'department_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_department_id_eq',
        },
        {
          codeName: 'n_employee_company_id_eq',
          logicName: '员工公司',
          appDEFieldId: 'employee_company_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_employee_company_id_eq',
        },
        {
          codeName: 'n_employee_id_eq',
          logicName: '员工',
          appDEFieldId: 'employee_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_employee_id_eq',
        },
        {
          codeName: 'n_first_approver_id_eq',
          logicName: '首次审批',
          appDEFieldId: 'first_approver_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_first_approver_id_eq',
        },
        {
          codeName: 'n_holiday_status_id_eq',
          logicName: '休假类型',
          appDEFieldId: 'holiday_status_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_holiday_status_id_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_manager_id_eq',
          logicName: '管理员',
          appDEFieldId: 'manager_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_manager_id_eq',
        },
        {
          codeName: 'n_message_main_attachment_id_eq',
          logicName: '主要附件',
          appDEFieldId: 'message_main_attachment_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_message_main_attachment_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_overtime_id_eq',
          logicName: '加班时间',
          appDEFieldId: 'overtime_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_overtime_id_eq',
        },
        {
          codeName: 'n_request_date_from_period_eq',
          logicName: '日期开始',
          appDEFieldId: 'request_date_from_period',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_request_date_from_period_eq',
        },
        {
          codeName: 'n_resource_calendar_id_eq',
          logicName: '资源行事历',
          appDEFieldId: 'resource_calendar_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_resource_calendar_id_eq',
        },
        {
          codeName: 'n_second_approver_id_eq',
          logicName: '第二次审批',
          appDEFieldId: 'second_approver_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_second_approver_id_eq',
        },
        {
          codeName: 'n_state_eq',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_state_eq',
        },
        {
          codeName: 'n_user_id_eq',
          logicName: '用户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'hr_leave_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_leave_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_leave_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'hr_leave',
  deapicodeName: 'hr_leave',
  deapicodeName2: 'hr_leaves',
  deapitag: 'HR_LEAVE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.HR_LEAVE',
  },
  logicName: '休假',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'HR_LEAVE',
  id: 'ibizodooapp.hr_leave',
  codeName2: 'hr_leaves',
  requestPaths: [],
};
