export default {
  appDEFields: [
    {
      codeName: 'model_id',
      logicName: '模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MODEL_ID',
      id: 'model_id',
    },
    {
      codeName: 'update_field_id',
      logicName: '要更新的字段',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_FIELD_ID',
      id: 'update_field_id',
    },
    {
      codeName: 'update_related_model_id',
      logicName: '更新相关模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_RELATED_MODEL_ID',
      id: 'update_related_model_id',
    },
    {
      codeName: 'crud_model_id',
      logicName: '创建记录',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CRUD_MODEL_ID',
      id: 'crud_model_id',
    },
    {
      codeName: 'link_field_id',
      logicName: '链接字段',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LINK_FIELD_ID',
      id: 'link_field_id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'value',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.VALUE',
      },
      logicName: '值',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'VALUE',
      id: 'value',
    },
    {
      codeName: 'type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.TYPE',
      },
      logicName: '动作类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'TYPE',
      id: 'type',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'mail_post_autofollow',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.MAIL_POST_AUTOFOLLOW',
      },
      logicName: '订阅收件人',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MAIL_POST_AUTOFOLLOW',
      id: 'mail_post_autofollow',
    },
    {
      codeName: 'code',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.CODE',
      },
      logicName: 'Python 代码',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CODE',
      id: 'code',
    },
    {
      codeName: 'help',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.HELP',
      },
      logicName: '动作描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'HELP',
      id: 'help',
    },
    {
      codeName: 'sequence',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.SEQUENCE',
      },
      logicName: '序列',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'activity_note',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_NOTE',
      },
      logicName: '备注',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ACTIVITY_NOTE',
      id: 'activity_note',
    },
    {
      codeName: 'activity_date_deadline_range',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_DATE_DEADLINE_RANGE',
      },
      logicName: '截止日期至',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVITY_DATE_DEADLINE_RANGE',
      id: 'activity_date_deadline_range',
    },
    {
      codeName: 'activity_summary',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_SUMMARY',
      },
      logicName: '标题',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'ACTIVITY_SUMMARY',
      id: 'activity_summary',
    },
    {
      codeName: 'activity_user_field_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_USER_FIELD_NAME',
      },
      logicName: '用户字段',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'ACTIVITY_USER_FIELD_NAME',
      id: 'activity_user_field_name',
    },
    {
      codeName: 'binding_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.BINDING_TYPE',
      },
      logicName: '绑定类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'BINDING_TYPE',
      id: 'binding_type',
    },
    {
      codeName: 'update_path',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.UPDATE_PATH',
      },
      logicName: '字段更新路径',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'UPDATE_PATH',
      id: 'update_path',
    },
    {
      codeName: 'path',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.PATH',
      },
      logicName: '网站中显示的路径',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'PATH',
      id: 'path',
    },
    {
      codeName: 'webhook_url',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.WEBHOOK_URL',
      },
      logicName: 'Webhook URL',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'WEBHOOK_URL',
      id: 'webhook_url',
    },
    {
      codeName: 'binding_view_types',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.BINDING_VIEW_TYPES',
      },
      logicName: '绑定视图类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'BINDING_VIEW_TYPES',
      id: 'binding_view_types',
    },
    {
      codeName: 'update_boolean_value',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.UPDATE_BOOLEAN_VALUE',
      },
      logicName: '布尔值',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATE_BOOLEAN_VALUE',
      id: 'update_boolean_value',
    },
    {
      codeName: 'mail_post_method',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.MAIL_POST_METHOD',
      },
      logicName: '发送电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'MAIL_POST_METHOD',
      id: 'mail_post_method',
    },
    {
      codeName: 'usage',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.USAGE',
      },
      logicName: '用途',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'USAGE',
      id: 'usage',
    },
    {
      codeName: 'update_m2m_operation',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.UPDATE_M2M_OPERATION',
      },
      logicName: 'Many2many 业务',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATE_M2M_OPERATION',
      id: 'update_m2m_operation',
    },
    {
      codeName: 'state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.STATE',
      },
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'evaluation_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.EVALUATION_TYPE',
      },
      logicName: '值类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'EVALUATION_TYPE',
      id: 'evaluation_type',
    },
    {
      codeName: 'activity_user_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_USER_TYPE',
      },
      logicName: '用户类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ACTIVITY_USER_TYPE',
      id: 'activity_user_type',
    },
    {
      codeName: 'sms_method',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_ACTIONS_SERVER.SMS_METHOD',
      },
      logicName: '发送短信为',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SMS_METHOD',
      id: 'sms_method',
    },
    {
      codeName: 'activity_date_deadline_range_type',
      lnlanguageRes: {
        lanResTag:
          'DEF.LNAME.IR_ACTIONS_SERVER.ACTIVITY_DATE_DEADLINE_RANGE_TYPE',
      },
      logicName: '到期类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ACTIVITY_DATE_DEADLINE_RANGE_TYPE',
      id: 'activity_date_deadline_range_type',
    },
    {
      codeName: 'template_name',
      logicName: 'EMail模板',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'TEMPLATE_NAME',
      id: 'template_name',
    },
    {
      codeName: 'activity_user_name',
      logicName: '负责人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_USER_NAME',
      id: 'activity_user_name',
    },
    {
      codeName: 'template_id',
      logicName: 'EMail模板',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TEMPLATE_ID',
      id: 'template_id',
    },
    {
      codeName: 'activity_type_name',
      logicName: '活动类型名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_TYPE_NAME',
      id: 'activity_type_name',
    },
    {
      codeName: 'activity_type_id',
      logicName: '活动类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACTIVITY_TYPE_ID',
      id: 'activity_type_id',
    },
    {
      codeName: 'activity_user_id',
      logicName: '负责人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACTIVITY_USER_ID',
      id: 'activity_user_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'ir_actions_server_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'model_id',
          logicName: '模型',
          appDEFieldId: 'model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'model_id',
        },
        {
          codeName: 'update_field_id',
          logicName: '要更新的字段',
          appDEFieldId: 'update_field_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_field_id',
        },
        {
          codeName: 'update_related_model_id',
          logicName: '更新相关模型',
          appDEFieldId: 'update_related_model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_related_model_id',
        },
        {
          codeName: 'crud_model_id',
          logicName: '创建记录',
          appDEFieldId: 'crud_model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'crud_model_id',
        },
        {
          codeName: 'link_field_id',
          logicName: '链接字段',
          appDEFieldId: 'link_field_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'link_field_id',
        },
        {
          codeName: 'activity_date_deadline_range',
          logicName: '截止日期至',
          appDEFieldId: 'activity_date_deadline_range',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_date_deadline_range',
        },
        {
          codeName: 'activity_date_deadline_range_type',
          logicName: '到期类型',
          appDEFieldId: 'activity_date_deadline_range_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_date_deadline_range_type',
        },
        {
          codeName: 'activity_note',
          logicName: '备注',
          appDEFieldId: 'activity_note',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_note',
        },
        {
          codeName: 'activity_summary',
          logicName: '标题',
          appDEFieldId: 'activity_summary',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_summary',
        },
        {
          codeName: 'activity_type_id',
          logicName: '活动类型',
          appDEFieldId: 'activity_type_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_type_id',
        },
        {
          codeName: 'activity_type_name',
          logicName: '活动类型名称',
          appDEFieldId: 'activity_type_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_type_name',
        },
        {
          codeName: 'activity_user_field_name',
          logicName: '用户字段',
          appDEFieldId: 'activity_user_field_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_field_name',
        },
        {
          codeName: 'activity_user_id',
          logicName: '负责人',
          appDEFieldId: 'activity_user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_id',
        },
        {
          codeName: 'activity_user_name',
          logicName: '负责人',
          appDEFieldId: 'activity_user_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_name',
        },
        {
          codeName: 'activity_user_type',
          logicName: '用户类型',
          appDEFieldId: 'activity_user_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_type',
        },
        {
          codeName: 'binding_type',
          logicName: '绑定类型',
          appDEFieldId: 'binding_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'binding_type',
        },
        {
          codeName: 'binding_view_types',
          logicName: '绑定视图类型',
          appDEFieldId: 'binding_view_types',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'binding_view_types',
        },
        {
          codeName: 'code',
          logicName: 'Python 代码',
          appDEFieldId: 'code',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'code',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'evaluation_type',
          logicName: '值类型',
          appDEFieldId: 'evaluation_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'evaluation_type',
        },
        {
          codeName: 'help',
          logicName: '动作描述',
          appDEFieldId: 'help',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'help',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'mail_post_autofollow',
          logicName: '订阅收件人',
          appDEFieldId: 'mail_post_autofollow',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mail_post_autofollow',
        },
        {
          codeName: 'mail_post_method',
          logicName: '发送电子邮件',
          appDEFieldId: 'mail_post_method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mail_post_method',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'path',
          logicName: '网站中显示的路径',
          appDEFieldId: 'path',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'path',
        },
        {
          codeName: 'sequence',
          logicName: '序列',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'sms_method',
          logicName: '发送短信为',
          appDEFieldId: 'sms_method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sms_method',
        },
        {
          codeName: 'state',
          logicName: '类型',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'state',
        },
        {
          codeName: 'template_id',
          logicName: 'EMail模板',
          appDEFieldId: 'template_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'template_id',
        },
        {
          codeName: 'template_name',
          logicName: 'EMail模板',
          appDEFieldId: 'template_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'template_name',
        },
        {
          codeName: 'type',
          logicName: '动作类型',
          appDEFieldId: 'type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'type',
        },
        {
          codeName: 'update_boolean_value',
          logicName: '布尔值',
          appDEFieldId: 'update_boolean_value',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_boolean_value',
        },
        {
          codeName: 'update_m2m_operation',
          logicName: 'Many2many 业务',
          appDEFieldId: 'update_m2m_operation',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_m2m_operation',
        },
        {
          codeName: 'update_path',
          logicName: '字段更新路径',
          appDEFieldId: 'update_path',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_path',
        },
        {
          codeName: 'usage',
          logicName: '用途',
          appDEFieldId: 'usage',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'usage',
        },
        {
          codeName: 'value',
          logicName: '值',
          appDEFieldId: 'value',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'value',
        },
        {
          codeName: 'webhook_url',
          logicName: 'Webhook URL',
          appDEFieldId: 'webhook_url',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'webhook_url',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'ir_actions_server_dto',
    },
    {
      codeName: 'ir_actions_server_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_activity_date_deadline_range_type_eq',
          logicName: '到期类型',
          appDEFieldId: 'activity_date_deadline_range_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_date_deadline_range_type_eq',
        },
        {
          codeName: 'n_activity_type_id_eq',
          logicName: '活动类型',
          appDEFieldId: 'activity_type_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_type_id_eq',
        },
        {
          codeName: 'n_activity_type_name_eq',
          logicName: '活动类型名称',
          appDEFieldId: 'activity_type_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_type_name_eq',
        },
        {
          codeName: 'n_activity_type_name_like',
          logicName: '活动类型名称',
          appDEFieldId: 'activity_type_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_type_name_like',
        },
        {
          codeName: 'n_activity_user_id_eq',
          logicName: '负责人',
          appDEFieldId: 'activity_user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_user_id_eq',
        },
        {
          codeName: 'n_activity_user_name_eq',
          logicName: '负责人',
          appDEFieldId: 'activity_user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_user_name_eq',
        },
        {
          codeName: 'n_activity_user_name_like',
          logicName: '负责人',
          appDEFieldId: 'activity_user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_user_name_like',
        },
        {
          codeName: 'n_activity_user_type_eq',
          logicName: '用户类型',
          appDEFieldId: 'activity_user_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_activity_user_type_eq',
        },
        {
          codeName: 'n_binding_type_eq',
          logicName: '绑定类型',
          appDEFieldId: 'binding_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_binding_type_eq',
        },
        {
          codeName: 'n_evaluation_type_eq',
          logicName: '值类型',
          appDEFieldId: 'evaluation_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_evaluation_type_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_mail_post_method_eq',
          logicName: '发送电子邮件',
          appDEFieldId: 'mail_post_method',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mail_post_method_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_sms_method_eq',
          logicName: '发送短信为',
          appDEFieldId: 'sms_method',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_sms_method_eq',
        },
        {
          codeName: 'n_state_eq',
          logicName: '类型',
          appDEFieldId: 'state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_state_eq',
        },
        {
          codeName: 'n_template_id_eq',
          logicName: 'EMail模板',
          appDEFieldId: 'template_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_template_id_eq',
        },
        {
          codeName: 'n_template_name_eq',
          logicName: 'EMail模板',
          appDEFieldId: 'template_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_template_name_eq',
        },
        {
          codeName: 'n_template_name_like',
          logicName: 'EMail模板',
          appDEFieldId: 'template_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_template_name_like',
        },
        {
          codeName: 'n_update_boolean_value_eq',
          logicName: '布尔值',
          appDEFieldId: 'update_boolean_value',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_update_boolean_value_eq',
        },
        {
          codeName: 'n_update_m2m_operation_eq',
          logicName: 'Many2many 业务',
          appDEFieldId: 'update_m2m_operation',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_update_m2m_operation_eq',
        },
        {
          codeName: 'n_usage_eq',
          logicName: '用途',
          appDEFieldId: 'usage',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_usage_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'ir_actions_server_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_actions_server_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_actions_server_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'ir_actions_server',
  deapicodeName: 'ir_actions_server',
  deapicodeName2: 'ir_actions_servers',
  deapitag: 'IR_ACTIONS_SERVER',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.IR_ACTIONS_SERVER',
  },
  logicName: '服务器动作',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'IR_ACTIONS_SERVER',
  id: 'ibizodooapp.ir_actions_server',
  codeName2: 'ir_actions_servers',
  requestPaths: [],
};
