export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'cron_name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'ibizodooapp.ir_cron',
      textAppDEFieldId: 'cron_name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'model_id',
      logicName: '模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MODEL_ID',
      id: 'model_id',
    },
    {
      codeName: 'code',
      logicName: '代码',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CODE',
      id: 'code',
    },
    {
      codeName: 'evaluation_type',
      logicName: '值类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'EVALUATION_TYPE',
      id: 'evaluation_type',
    },
    {
      codeName: 'update_path',
      logicName: '字段更新路径',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'UPDATE_PATH',
      id: 'update_path',
    },
    {
      codeName: 'update_field_id',
      logicName: '要更新的字段',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_FIELD_ID',
      id: 'update_field_id',
    },
    {
      codeName: 'update_related_model_id',
      logicName: '更新相关模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_RELATED_MODEL_ID',
      id: 'update_related_model_id',
    },
    {
      codeName: 'value',
      logicName: '值',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'VALUE',
      id: 'value',
    },
    {
      codeName: 'update_boolean_value',
      logicName: '布尔值',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATE_BOOLEAN_VALUE',
      id: 'update_boolean_value',
    },
    {
      codeName: 'crud_model_id',
      logicName: '创建记录',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CRUD_MODEL_ID',
      id: 'crud_model_id',
    },
    {
      codeName: 'link_field_id',
      logicName: '链接字段',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LINK_FIELD_ID',
      id: 'link_field_id',
    },
    {
      codeName: 'sms_method',
      logicName: '发送短信为',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SMS_METHOD',
      id: 'sms_method',
    },
    {
      codeName: 'template_id',
      logicName: 'EMail模板',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TEMPLATE_ID',
      id: 'template_id',
    },
    {
      codeName: 'mail_post_autofollow',
      logicName: '订阅收件人',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MAIL_POST_AUTOFOLLOW',
      id: 'mail_post_autofollow',
    },
    {
      codeName: 'activity_type_id',
      logicName: '活动类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACTIVITY_TYPE_ID',
      id: 'activity_type_id',
    },
    {
      codeName: 'activity_user_type',
      logicName: '用户类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ACTIVITY_USER_TYPE',
      id: 'activity_user_type',
    },
    {
      codeName: 'activity_user_field_name',
      logicName: '用户字段',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'ACTIVITY_USER_FIELD_NAME',
      id: 'activity_user_field_name',
    },
    {
      codeName: 'activity_user_id',
      logicName: '负责人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACTIVITY_USER_ID',
      id: 'activity_user_id',
    },
    {
      codeName: 'activity_note',
      logicName: '备注',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ACTIVITY_NOTE',
      id: 'activity_note',
    },
    {
      codeName: 'usage',
      logicName: '用途',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'USAGE',
      id: 'usage',
    },
    {
      codeName: 'state',
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'activity_type_name',
      logicName: '活动类型名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_TYPE_NAME',
      id: 'activity_type_name',
    },
    {
      codeName: 'activity_user_name',
      logicName: '负责人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_USER_NAME',
      id: 'activity_user_name',
    },
    {
      codeName: 'activity_summary',
      logicName: '标题',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'ACTIVITY_SUMMARY',
      id: 'activity_summary',
    },
    {
      codeName: 'activity_date_deadline_range_type',
      logicName: '到期类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ACTIVITY_DATE_DEADLINE_RANGE_TYPE',
      id: 'activity_date_deadline_range_type',
    },
    {
      codeName: 'activity_date_deadline_range',
      logicName: '截止日期至',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVITY_DATE_DEADLINE_RANGE',
      id: 'activity_date_deadline_range',
    },
    {
      codeName: 'mail_post_method',
      logicName: '发送电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'MAIL_POST_METHOD',
      id: 'mail_post_method',
    },
    {
      codeName: 'webhook_url',
      logicName: 'Webhook URL',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'WEBHOOK_URL',
      id: 'webhook_url',
    },
    {
      codeName: 'template_name',
      logicName: 'EMail模板',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'TEMPLATE_NAME',
      id: 'template_name',
    },
    {
      codeName: 'name',
      logicName: '动作名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'active',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.ACTIVE',
      },
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'nextcall',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.NEXTCALL',
      },
      logicName: '下一次执行日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'NEXTCALL',
      id: 'nextcall',
    },
    {
      codeName: 'interval_number',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.INTERVAL_NUMBER',
      },
      logicName: '间隔数值',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'INTERVAL_NUMBER',
      id: 'interval_number',
    },
    {
      codeName: 'first_failure_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.FIRST_FAILURE_DATE',
      },
      logicName: '首次失败日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'FIRST_FAILURE_DATE',
      id: 'first_failure_date',
    },
    {
      codeName: 'lastcall',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.LASTCALL',
      },
      logicName: '最后执行日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LASTCALL',
      id: 'lastcall',
    },
    {
      codeName: 'priority',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.PRIORITY',
      },
      logicName: '优先级',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PRIORITY',
      id: 'priority',
    },
    {
      codeName: 'cron_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.CRON_NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      enableQuickSearch: true,
      name: 'CRON_NAME',
      id: 'cron_name',
    },
    {
      codeName: 'failure_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.FAILURE_COUNT',
      },
      logicName: '失败次数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'FAILURE_COUNT',
      id: 'failure_count',
    },
    {
      codeName: 'interval_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_CRON.INTERVAL_TYPE',
      },
      logicName: '间隔单位',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'INTERVAL_TYPE',
      id: 'interval_type',
    },
    {
      codeName: 'user_name',
      logicName: '执行帐户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'USER_NAME',
      id: 'user_name',
    },
    {
      codeName: 'ir_actions_server_id',
      logicName: '服务器动作标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'IR_ACTIONS_SERVER_ID',
      id: 'ir_actions_server_id',
    },
    {
      codeName: 'user_id',
      logicName: '执行帐户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USER_ID',
      id: 'user_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'ir_cron_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'model_id',
          logicName: '模型',
          appDEFieldId: 'model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'model_id',
        },
        {
          codeName: 'code',
          logicName: '代码',
          appDEFieldId: 'code',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'code',
        },
        {
          codeName: 'evaluation_type',
          logicName: '值类型',
          appDEFieldId: 'evaluation_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'evaluation_type',
        },
        {
          codeName: 'update_path',
          logicName: '字段更新路径',
          appDEFieldId: 'update_path',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_path',
        },
        {
          codeName: 'update_field_id',
          logicName: '要更新的字段',
          appDEFieldId: 'update_field_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_field_id',
        },
        {
          codeName: 'update_related_model_id',
          logicName: '更新相关模型',
          appDEFieldId: 'update_related_model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_related_model_id',
        },
        {
          codeName: 'value',
          logicName: '值',
          appDEFieldId: 'value',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'value',
        },
        {
          codeName: 'update_boolean_value',
          logicName: '布尔值',
          appDEFieldId: 'update_boolean_value',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'update_boolean_value',
        },
        {
          codeName: 'crud_model_id',
          logicName: '创建记录',
          appDEFieldId: 'crud_model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'crud_model_id',
        },
        {
          codeName: 'link_field_id',
          logicName: '链接字段',
          appDEFieldId: 'link_field_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'link_field_id',
        },
        {
          codeName: 'sms_method',
          logicName: '发送短信为',
          appDEFieldId: 'sms_method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sms_method',
        },
        {
          codeName: 'template_id',
          logicName: 'EMail模板',
          appDEFieldId: 'template_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'template_id',
        },
        {
          codeName: 'mail_post_autofollow',
          logicName: '订阅收件人',
          appDEFieldId: 'mail_post_autofollow',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mail_post_autofollow',
        },
        {
          codeName: 'activity_type_id',
          logicName: '活动类型',
          appDEFieldId: 'activity_type_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_type_id',
        },
        {
          codeName: 'activity_user_type',
          logicName: '用户类型',
          appDEFieldId: 'activity_user_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_type',
        },
        {
          codeName: 'activity_user_field_name',
          logicName: '用户字段',
          appDEFieldId: 'activity_user_field_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_field_name',
        },
        {
          codeName: 'activity_user_id',
          logicName: '负责人',
          appDEFieldId: 'activity_user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_id',
        },
        {
          codeName: 'activity_note',
          logicName: '备注',
          appDEFieldId: 'activity_note',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_note',
        },
        {
          codeName: 'usage',
          logicName: '用途',
          appDEFieldId: 'usage',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'usage',
        },
        {
          codeName: 'state',
          logicName: '类型',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'activity_type_name',
          logicName: '活动类型名称',
          appDEFieldId: 'activity_type_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_type_name',
        },
        {
          codeName: 'activity_user_name',
          logicName: '负责人',
          appDEFieldId: 'activity_user_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_user_name',
        },
        {
          codeName: 'activity_summary',
          logicName: '标题',
          appDEFieldId: 'activity_summary',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_summary',
        },
        {
          codeName: 'activity_date_deadline_range_type',
          logicName: '到期类型',
          appDEFieldId: 'activity_date_deadline_range_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_date_deadline_range_type',
        },
        {
          codeName: 'activity_date_deadline_range',
          logicName: '截止日期至',
          appDEFieldId: 'activity_date_deadline_range',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_date_deadline_range',
        },
        {
          codeName: 'mail_post_method',
          logicName: '发送电子邮件',
          appDEFieldId: 'mail_post_method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mail_post_method',
        },
        {
          codeName: 'webhook_url',
          logicName: 'Webhook URL',
          appDEFieldId: 'webhook_url',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'webhook_url',
        },
        {
          codeName: 'template_name',
          logicName: 'EMail模板',
          appDEFieldId: 'template_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'template_name',
        },
        {
          codeName: 'name',
          logicName: '动作名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'cron_name',
          logicName: '名称',
          appDEFieldId: 'cron_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'cron_name',
        },
        {
          codeName: 'failure_count',
          logicName: '失败次数',
          appDEFieldId: 'failure_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'failure_count',
        },
        {
          codeName: 'first_failure_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '首次失败日期',
          appDEFieldId: 'first_failure_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'first_failure_date',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'interval_number',
          logicName: '间隔数值',
          appDEFieldId: 'interval_number',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          id: 'interval_number',
        },
        {
          codeName: 'interval_type',
          logicName: '间隔单位',
          appDEFieldId: 'interval_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'interval_type',
        },
        {
          codeName: 'ir_actions_server_id',
          logicName: '服务器动作标识',
          appDEFieldId: 'ir_actions_server_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'ir_actions_server_id',
        },
        {
          codeName: 'lastcall',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最后执行日期',
          appDEFieldId: 'lastcall',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lastcall',
        },
        {
          codeName: 'nextcall',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '下一次执行日期',
          appDEFieldId: 'nextcall',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'nextcall',
        },
        {
          codeName: 'priority',
          logicName: '优先级',
          appDEFieldId: 'priority',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'priority',
        },
        {
          codeName: 'user_id',
          logicName: '执行帐户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_id',
        },
        {
          codeName: 'user_name',
          logicName: '执行帐户',
          appDEFieldId: 'user_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_name',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'ir_cron_dto',
    },
    {
      codeName: 'ir_cron_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_interval_type_eq',
          logicName: '间隔单位',
          appDEFieldId: 'interval_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_interval_type_eq',
        },
        {
          codeName: 'n_ir_actions_server_id_eq',
          logicName: '服务器动作标识',
          appDEFieldId: 'ir_actions_server_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_ir_actions_server_id_eq',
        },
        {
          codeName: 'n_name_eq',
          logicName: '动作名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '动作名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_user_id_eq',
          logicName: '执行帐户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_id_eq',
        },
        {
          codeName: 'n_user_name_eq',
          logicName: '执行帐户',
          appDEFieldId: 'user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_name_eq',
        },
        {
          codeName: 'n_user_name_like',
          logicName: '执行帐户',
          appDEFieldId: 'user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'ir_cron_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_cron_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_cron_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'ir_cron',
  deapicodeName: 'ir_cron',
  deapicodeName2: 'ir_crons',
  deapitag: 'IR_CRON',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.IR_CRON',
  },
  logicName: '计划的操作',
  majorAppDEFieldId: 'cron_name',
  quickSearchAppDEFieldIds: ['cron_name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'IR_CRON',
  id: 'ibizodooapp.ir_cron',
  codeName2: 'ir_crons',
  requestPaths: [],
};
