export default {
  appDEFields: [
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'smtp_debug',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SMTP_DEBUG',
      },
      logicName: '调试',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SMTP_DEBUG',
      id: 'smtp_debug',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'active',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.ACTIVE',
      },
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'google_gmail_access_token_expiration',
      lnlanguageRes: {
        lanResTag:
          'DEF.LNAME.IR_MAIL_SERVER.GOOGLE_GMAIL_ACCESS_TOKEN_EXPIRATION',
      },
      logicName: '访问令牌到期时间戳',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'GOOGLE_GMAIL_ACCESS_TOKEN_EXPIRATION',
      id: 'google_gmail_access_token_expiration',
    },
    {
      codeName: 'max_email_size',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.MAX_EMAIL_SIZE',
      },
      logicName: '最大电子邮件大小',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'MAX_EMAIL_SIZE',
      id: 'max_email_size',
    },
    {
      codeName: 'google_gmail_access_token',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.GOOGLE_GMAIL_ACCESS_TOKEN',
      },
      logicName: '访问令牌',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'GOOGLE_GMAIL_ACCESS_TOKEN',
      id: 'google_gmail_access_token',
    },
    {
      codeName: 'google_gmail_refresh_token',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.GOOGLE_GMAIL_REFRESH_TOKEN',
      },
      logicName: '更新 Token',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'GOOGLE_GMAIL_REFRESH_TOKEN',
      id: 'google_gmail_refresh_token',
    },
    {
      codeName: 'from_filter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.FROM_FILTER',
      },
      logicName: 'FROM 过滤',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'FROM_FILTER',
      id: 'from_filter',
    },
    {
      codeName: 'smtp_port',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SMTP_PORT',
      },
      logicName: 'SMTP端口',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SMTP_PORT',
      id: 'smtp_port',
    },
    {
      codeName: 'sequence',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SEQUENCE',
      },
      logicName: '优先级',
      predefinedType: 'ORDERVALUE',
      stdDataType: 9,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'google_gmail_authorization_code',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.GOOGLE_GMAIL_AUTHORIZATION_CODE',
      },
      logicName: '授权码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'GOOGLE_GMAIL_AUTHORIZATION_CODE',
      id: 'google_gmail_authorization_code',
    },
    {
      codeName: 'smtp_authentication',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SMTP_AUTHENTICATION',
      },
      logicName: '验证',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SMTP_AUTHENTICATION',
      id: 'smtp_authentication',
    },
    {
      codeName: 'smtp_pass',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SMTP_PASS',
      },
      logicName: '密码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SMTP_PASS',
      id: 'smtp_pass',
    },
    {
      codeName: 'smtp_encryption',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SMTP_ENCRYPTION',
      },
      logicName: '连接加密',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SMTP_ENCRYPTION',
      id: 'smtp_encryption',
    },
    {
      codeName: 'smtp_user',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SMTP_USER',
      },
      logicName: '用户名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SMTP_USER',
      id: 'smtp_user',
    },
    {
      codeName: 'smtp_host',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MAIL_SERVER.SMTP_HOST',
      },
      logicName: 'SMTP服务器',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SMTP_HOST',
      id: 'smtp_host',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'ir_mail_server_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'from_filter',
          logicName: 'FROM 过滤',
          appDEFieldId: 'from_filter',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'from_filter',
        },
        {
          codeName: 'google_gmail_access_token',
          logicName: '访问令牌',
          appDEFieldId: 'google_gmail_access_token',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_access_token',
        },
        {
          codeName: 'google_gmail_access_token_expiration',
          logicName: '访问令牌到期时间戳',
          appDEFieldId: 'google_gmail_access_token_expiration',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_access_token_expiration',
        },
        {
          codeName: 'google_gmail_authorization_code',
          logicName: '授权码',
          appDEFieldId: 'google_gmail_authorization_code',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_authorization_code',
        },
        {
          codeName: 'google_gmail_refresh_token',
          logicName: '更新 Token',
          appDEFieldId: 'google_gmail_refresh_token',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'google_gmail_refresh_token',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'max_email_size',
          logicName: '最大电子邮件大小',
          appDEFieldId: 'max_email_size',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'max_email_size',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'sequence',
          logicName: '优先级',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'smtp_authentication',
          logicName: '验证',
          appDEFieldId: 'smtp_authentication',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'smtp_authentication',
        },
        {
          codeName: 'smtp_debug',
          logicName: '调试',
          appDEFieldId: 'smtp_debug',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'smtp_debug',
        },
        {
          codeName: 'smtp_encryption',
          logicName: '连接加密',
          appDEFieldId: 'smtp_encryption',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'smtp_encryption',
        },
        {
          codeName: 'smtp_host',
          logicName: 'SMTP服务器',
          appDEFieldId: 'smtp_host',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'smtp_host',
        },
        {
          codeName: 'smtp_pass',
          logicName: '密码',
          appDEFieldId: 'smtp_pass',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'smtp_pass',
        },
        {
          codeName: 'smtp_port',
          logicName: 'SMTP端口',
          appDEFieldId: 'smtp_port',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'smtp_port',
        },
        {
          codeName: 'smtp_user',
          logicName: '用户名',
          appDEFieldId: 'smtp_user',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'smtp_user',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'ir_mail_server_dto',
    },
    {
      codeName: 'ir_mail_server_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_smtp_authentication_eq',
          logicName: '验证',
          appDEFieldId: 'smtp_authentication',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_smtp_authentication_eq',
        },
        {
          codeName: 'n_smtp_encryption_eq',
          logicName: '连接加密',
          appDEFieldId: 'smtp_encryption',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_smtp_encryption_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'ir_mail_server_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'move_order',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTOS',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/move_order',
      needResourceKey: true,
      actionMode: 'MOVEORDER',
      actionTag: 'MoveOrder',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'MoveOrder',
      id: 'move_order',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_mail_server_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_mail_server_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'ir_mail_server',
  deapicodeName: 'ir_mail_server',
  deapicodeName2: 'ir_mail_servers',
  deapitag: 'IR_MAIL_SERVER',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.IR_MAIL_SERVER',
  },
  logicName: '邮件服务器',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'IR_MAIL_SERVER',
  id: 'ibizodooapp.ir_mail_server',
  codeName2: 'ir_mail_servers',
  requestPaths: [],
};
