export default {
  appDEFields: [
    {
      codeName: 'app_id',
      logicName: '应用标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'APP_ID',
      id: 'app_id',
    },
    {
      codeName: 'order',
      logicName: '排序值',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ORDER',
      id: 'order',
    },
    {
      codeName: 'res_code',
      logicName: '资源标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'RES_CODE',
      id: 'res_code',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'application',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.APPLICATION',
      },
      logicName: '应用',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'APPLICATION',
      id: 'application',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'demo',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.DEMO',
      },
      logicName: '演示数据',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DEMO',
      id: 'demo',
    },
    {
      codeName: 'sequence',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.SEQUENCE',
      },
      logicName: '序列',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'auto_install',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.AUTO_INSTALL',
      },
      logicName: '自动安装',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'AUTO_INSTALL',
      id: 'auto_install',
    },
    {
      codeName: 'imported',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.IMPORTED',
      },
      logicName: '导入的模块',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IMPORTED',
      id: 'imported',
    },
    {
      codeName: 'to_buy',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.TO_BUY',
      },
      logicName: 'ERP 企业版专属模块',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'TO_BUY',
      id: 'to_buy',
    },
    {
      codeName: 'description',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.DESCRIPTION',
      },
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'maintainer',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.MAINTAINER',
      },
      logicName: '维护者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'MAINTAINER',
      id: 'maintainer',
    },
    {
      codeName: 'reports_by_module',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.REPORTS_BY_MODULE',
      },
      logicName: '报表',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'REPORTS_BY_MODULE',
      id: 'reports_by_module',
    },
    {
      codeName: 'contributors',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.CONTRIBUTORS',
      },
      logicName: '协作者',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CONTRIBUTORS',
      id: 'contributors',
    },
    {
      codeName: 'icon',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.ICON',
      },
      logicName: '图标网址',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'ICON',
      id: 'icon',
    },
    {
      codeName: 'views_by_module',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.VIEWS_BY_MODULE',
      },
      logicName: '视图',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'VIEWS_BY_MODULE',
      id: 'views_by_module',
    },
    {
      codeName: 'menus_by_module',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.MENUS_BY_MODULE',
      },
      logicName: '菜单',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'MENUS_BY_MODULE',
      id: 'menus_by_module',
    },
    {
      codeName: 'author',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.AUTHOR',
      },
      logicName: '作者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'AUTHOR',
      id: 'author',
    },
    {
      codeName: 'license',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.LICENSE',
      },
      logicName: '许可证',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'LICENSE',
      id: 'license',
    },
    {
      codeName: 'latest_version',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.LATEST_VERSION',
      },
      logicName: '已安装版本',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'LATEST_VERSION',
      id: 'latest_version',
    },
    {
      codeName: 'summary',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.SUMMARY',
      },
      logicName: '摘要',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SUMMARY',
      id: 'summary',
    },
    {
      codeName: 'shortdesc',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.SHORTDESC',
      },
      logicName: '模块名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'SHORTDESC',
      id: 'shortdesc',
    },
    {
      codeName: 'url',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.URL',
      },
      logicName: 'URL',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'URL',
      id: 'url',
    },
    {
      codeName: 'published_version',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.PUBLISHED_VERSION',
      },
      logicName: '出版版本',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'PUBLISHED_VERSION',
      id: 'published_version',
    },
    {
      codeName: 'website',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.WEBSITE',
      },
      logicName: '网站',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'WEBSITE',
      id: 'website',
    },
    {
      codeName: 'module_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.MODULE_TYPE',
      },
      logicName: '模块类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'MODULE_TYPE',
      id: 'module_type',
    },
    {
      codeName: 'state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.STATE',
      },
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'category_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODULE_MODULE.CATEGORY_ID',
      },
      logicName: '类别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CATEGORY_ID',
      id: 'category_id',
    },
    {
      codeName: 'display_name',
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'ir_module_module_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'app_id',
          logicName: '应用标识',
          appDEFieldId: 'app_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'app_id',
        },
        {
          codeName: 'order',
          logicName: '排序值',
          appDEFieldId: 'order',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'order',
        },
        {
          codeName: 'res_code',
          logicName: '资源标识',
          appDEFieldId: 'res_code',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_code',
        },
        {
          codeName: 'application',
          logicName: '应用',
          appDEFieldId: 'application',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'application',
        },
        {
          codeName: 'author',
          logicName: '作者',
          appDEFieldId: 'author',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'author',
        },
        {
          codeName: 'auto_install',
          logicName: '自动安装',
          appDEFieldId: 'auto_install',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'auto_install',
        },
        {
          codeName: 'category_id',
          logicName: '类别',
          appDEFieldId: 'category_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'category_id',
        },
        {
          codeName: 'contributors',
          logicName: '协作者',
          appDEFieldId: 'contributors',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'contributors',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'demo',
          logicName: '演示数据',
          appDEFieldId: 'demo',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'demo',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'icon',
          logicName: '图标网址',
          appDEFieldId: 'icon',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'icon',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'imported',
          logicName: '导入的模块',
          appDEFieldId: 'imported',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'imported',
        },
        {
          codeName: 'latest_version',
          logicName: '已安装版本',
          appDEFieldId: 'latest_version',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'latest_version',
        },
        {
          codeName: 'license',
          logicName: '许可证',
          appDEFieldId: 'license',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'license',
        },
        {
          codeName: 'maintainer',
          logicName: '维护者',
          appDEFieldId: 'maintainer',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'maintainer',
        },
        {
          codeName: 'menus_by_module',
          logicName: '菜单',
          appDEFieldId: 'menus_by_module',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'menus_by_module',
        },
        {
          codeName: 'module_type',
          logicName: '模块类型',
          appDEFieldId: 'module_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'module_type',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'published_version',
          logicName: '出版版本',
          appDEFieldId: 'published_version',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'published_version',
        },
        {
          codeName: 'reports_by_module',
          logicName: '报表',
          appDEFieldId: 'reports_by_module',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'reports_by_module',
        },
        {
          codeName: 'sequence',
          logicName: '序列',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'shortdesc',
          logicName: '模块名',
          appDEFieldId: 'shortdesc',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'shortdesc',
        },
        {
          codeName: 'state',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'summary',
          logicName: '摘要',
          appDEFieldId: 'summary',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'summary',
        },
        {
          codeName: 'to_buy',
          logicName: 'ERP 企业版专属模块',
          appDEFieldId: 'to_buy',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'to_buy',
        },
        {
          codeName: 'url',
          logicName: 'URL',
          appDEFieldId: 'url',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'url',
        },
        {
          codeName: 'views_by_module',
          logicName: '视图',
          appDEFieldId: 'views_by_module',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'views_by_module',
        },
        {
          codeName: 'website',
          logicName: '网站',
          appDEFieldId: 'website',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'website',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'ir_module_module_dto',
    },
    {
      codeName: 'ir_module_module_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_category_id_eq',
          logicName: '类别',
          appDEFieldId: 'category_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_category_id_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_license_eq',
          logicName: '许可证',
          appDEFieldId: 'license',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_license_eq',
        },
        {
          codeName: 'n_module_type_eq',
          logicName: '模块类型',
          appDEFieldId: 'module_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_module_type_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_state_eq',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_state_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'ir_module_module_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_cur_user_app',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_cur_user_app',
      actionType: 'REMOTE',
      dataSetName: 'cur_user_app',
      dataSetTag: 'cur_user_app',
      dataSetType: 'REMOTE',
      id: 'fetch_cur_user_app',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_installed',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_installed',
      actionType: 'REMOTE',
      dataSetName: 'installed',
      dataSetTag: 'installed',
      dataSetType: 'REMOTE',
      id: 'fetch_installed',
    },
    {
      codeName: 'fetch_installed_app',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_module_module_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_module_module_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_installed_app',
      actionType: 'REMOTE',
      dataSetName: 'installed_app',
      dataSetTag: 'installed_app',
      dataSetType: 'REMOTE',
      id: 'fetch_installed_app',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'ir_module_module',
  deapicodeName: 'ir_module_module',
  deapicodeName2: 'ir_module_modules',
  deapitag: 'IR_MODULE_MODULE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.IR_MODULE_MODULE',
  },
  logicName: '模块',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'IR_MODULE_MODULE',
  id: 'ibizodooapp.ir_module_module',
  codeName2: 'ir_module_modules',
  requestPaths: [],
};
