export default {
  appDEFields: [
    {
      codeName: 'field_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.FIELD_ID',
      },
      logicName: '属性标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'FIELD_ID',
      id: 'field_id',
    },
    {
      codeName: 'field_info',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.FIELD_INFO',
      },
      logicName: '属性信息',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'FIELD_INFO',
      id: 'field_info',
    },
    {
      codeName: 'model',
      logicName: '相关模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'MODEL',
      id: 'model',
    },
    {
      codeName: 'res_id',
      logicName: '资源标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RES_ID',
      id: 'res_id',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'old_value_float',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.OLD_VALUE_FLOAT',
      },
      logicName: '旧浮点值',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'OLD_VALUE_FLOAT',
      id: 'old_value_float',
    },
    {
      codeName: 'new_value_datetime',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.NEW_VALUE_DATETIME',
      },
      logicName: '新日期时间值',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'NEW_VALUE_DATETIME',
      id: 'new_value_datetime',
    },
    {
      codeName: 'old_value_datetime',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.OLD_VALUE_DATETIME',
      },
      logicName: '旧日期时间值',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'OLD_VALUE_DATETIME',
      id: 'old_value_datetime',
    },
    {
      codeName: 'new_value_float',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.NEW_VALUE_FLOAT',
      },
      logicName: '新浮点值',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'NEW_VALUE_FLOAT',
      id: 'new_value_float',
    },
    {
      codeName: 'old_value_integer',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.OLD_VALUE_INTEGER',
      },
      logicName: '旧整数值',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OLD_VALUE_INTEGER',
      id: 'old_value_integer',
    },
    {
      codeName: 'new_value_integer',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.NEW_VALUE_INTEGER',
      },
      logicName: '新整数值',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'NEW_VALUE_INTEGER',
      id: 'new_value_integer',
    },
    {
      codeName: 'new_value_text',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.NEW_VALUE_TEXT',
      },
      logicName: '新文本值',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'NEW_VALUE_TEXT',
      id: 'new_value_text',
    },
    {
      codeName: 'old_value_text',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.OLD_VALUE_TEXT',
      },
      logicName: '旧文本值',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'OLD_VALUE_TEXT',
      id: 'old_value_text',
    },
    {
      codeName: 'old_value_char',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.OLD_VALUE_CHAR',
      },
      logicName: '旧字符值',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'OLD_VALUE_CHAR',
      id: 'old_value_char',
    },
    {
      codeName: 'new_value_char',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.NEW_VALUE_CHAR',
      },
      logicName: '新字符值',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'NEW_VALUE_CHAR',
      id: 'new_value_char',
    },
    {
      codeName: 'currency_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.CURRENCY_ID',
      },
      logicName: '币别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CURRENCY_ID',
      id: 'currency_id',
    },
    {
      codeName: 'mail_message_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.MAIL_MESSAGE_ID',
      },
      logicName: '消息ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MAIL_MESSAGE_ID',
      id: 'mail_message_id',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_TRACKING_VALUE.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'mail_tracking_value_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'field_id',
          logicName: '属性标识',
          appDEFieldId: 'field_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'field_id',
        },
        {
          codeName: 'field_info',
          logicName: '属性信息',
          appDEFieldId: 'field_info',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'field_info',
        },
        {
          codeName: 'model',
          logicName: '相关模型',
          appDEFieldId: 'model',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'model',
        },
        {
          codeName: 'res_id',
          logicName: '资源标识',
          appDEFieldId: 'res_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_id',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'currency_id',
          logicName: '币别',
          appDEFieldId: 'currency_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'currency_id',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'mail_message_id',
          logicName: '消息ID',
          appDEFieldId: 'mail_message_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'mail_message_id',
        },
        {
          codeName: 'new_value_char',
          logicName: '新字符值',
          appDEFieldId: 'new_value_char',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'new_value_char',
        },
        {
          codeName: 'new_value_datetime',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '新日期时间值',
          appDEFieldId: 'new_value_datetime',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'new_value_datetime',
        },
        {
          codeName: 'new_value_float',
          logicName: '新浮点值',
          appDEFieldId: 'new_value_float',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'new_value_float',
        },
        {
          codeName: 'new_value_integer',
          logicName: '新整数值',
          appDEFieldId: 'new_value_integer',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'new_value_integer',
        },
        {
          codeName: 'new_value_text',
          logicName: '新文本值',
          appDEFieldId: 'new_value_text',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'new_value_text',
        },
        {
          codeName: 'old_value_char',
          logicName: '旧字符值',
          appDEFieldId: 'old_value_char',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'old_value_char',
        },
        {
          codeName: 'old_value_datetime',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '旧日期时间值',
          appDEFieldId: 'old_value_datetime',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'old_value_datetime',
        },
        {
          codeName: 'old_value_float',
          logicName: '旧浮点值',
          appDEFieldId: 'old_value_float',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'old_value_float',
        },
        {
          codeName: 'old_value_integer',
          logicName: '旧整数值',
          appDEFieldId: 'old_value_integer',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'old_value_integer',
        },
        {
          codeName: 'old_value_text',
          logicName: '旧文本值',
          appDEFieldId: 'old_value_text',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'old_value_text',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'mail_tracking_value_dto',
    },
    {
      codeName: 'mail_tracking_value_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_currency_id_eq',
          logicName: '币别',
          appDEFieldId: 'currency_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_currency_id_eq',
        },
        {
          codeName: 'n_field_id_eq',
          logicName: '属性标识',
          appDEFieldId: 'field_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_field_id_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_mail_message_id_eq',
          logicName: '消息ID',
          appDEFieldId: 'mail_message_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mail_message_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'mail_tracking_value_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_tracking_value_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_tracking_value_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'mail_tracking_value',
  deapicodeName: 'mail_tracking_value',
  deapicodeName2: 'mail_tracking_values',
  deapitag: 'MAIL_TRACKING_VALUE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_TRACKING_VALUE',
  },
  logicName: '邮件跟踪值',
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'MAIL_TRACKING_VALUE',
  id: 'ibizodooapp.mail_tracking_value',
  codeName2: 'mail_tracking_values',
  requestPaths: [],
};
