export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'ibizodooapp.mail_alias_domain',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'sequence',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.SEQUENCE',
      },
      logicName: '序列',
      predefinedType: 'ORDERVALUE',
      stdDataType: 9,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'default_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.DEFAULT_FROM',
      },
      logicName: '默认发件人别名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DEFAULT_FROM',
      id: 'default_from',
    },
    {
      codeName: 'bounce_alias',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.BOUNCE_ALIAS',
      },
      logicName: '弹跳别名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'BOUNCE_ALIAS',
      id: 'bounce_alias',
    },
    {
      codeName: 'catchall_alias',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.CATCHALL_ALIAS',
      },
      logicName: '全部别名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CATCHALL_ALIAS',
      id: 'catchall_alias',
    },
    {
      codeName: 'catchall_email',
      computeAppDEFLogicId: 'compute_catchall_email',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.CATCHALL_EMAIL',
      },
      logicName: '预设邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CATCHALL_EMAIL',
      id: 'catchall_email',
    },
    {
      codeName: 'bounce_email',
      computeAppDEFLogicId: 'compute_bounce_email',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.BOUNCE_EMAIL',
      },
      logicName: '退件电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'BOUNCE_EMAIL',
      id: 'bounce_email',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'default_from_email',
      computeAppDEFLogicId: 'compute_default_from_email',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS_DOMAIN.DEFAULT_FROM_EMAIL',
      },
      logicName: '默认从',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DEFAULT_FROM_EMAIL',
      id: 'default_from_email',
    },
  ],
  appDELogics: [
    {
      deflogicMode: 'COMPUTE',
      appDEFieldId: 'bounce_email',
      codeName: 'compute_bounce_email',
      defaultParamName: 'DEFAULT',
      logicName: 'compute_bounce_email',
      logicSubType: 'DEFIELD',
      scriptCode: "data.bounce_email=data.bounce_alias+'@'+data.name;",
      customCode: true,
      enableFront: true,
      valid: true,
      id: 'compute_bounce_email',
    },
    {
      deflogicMode: 'COMPUTE',
      appDEFieldId: 'catchall_email',
      codeName: 'compute_catchall_email',
      defaultParamName: 'DEFAULT',
      logicName: 'compute_catchall_email',
      logicSubType: 'DEFIELD',
      scriptCode: "data.catchall_email=data.catchall_alias+'@'+data.name;",
      customCode: true,
      enableFront: true,
      valid: true,
      id: 'compute_catchall_email',
    },
    {
      deflogicMode: 'COMPUTE',
      appDEFieldId: 'default_from_email',
      codeName: 'compute_default_from_email',
      defaultParamName: 'DEFAULT',
      logicName: 'compute_default_from_email',
      logicSubType: 'DEFIELD',
      scriptCode:
        "if (data.default_from && data.default_from.includes('@')) {\r\n    data.default_from_email = data.default_from;\r\n} else {\r\n    data.default_from_email=data.default_from+'@'+data.name;\r\n}",
      customCode: true,
      enableFront: true,
      valid: true,
      id: 'compute_default_from_email',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'mail_alias_domain_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'bounce_alias',
          logicName: '弹跳别名',
          appDEFieldId: 'bounce_alias',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'bounce_alias',
        },
        {
          codeName: 'bounce_email',
          logicName: '退件电子邮件',
          appDEFieldId: 'bounce_email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'bounce_email',
        },
        {
          codeName: 'catchall_alias',
          logicName: '全部别名',
          appDEFieldId: 'catchall_alias',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'catchall_alias',
        },
        {
          codeName: 'catchall_email',
          logicName: '预设邮件',
          appDEFieldId: 'catchall_email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'catchall_email',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'default_from',
          logicName: '默认发件人别名',
          appDEFieldId: 'default_from',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'default_from',
        },
        {
          codeName: 'default_from_email',
          logicName: '默认从',
          appDEFieldId: 'default_from_email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'default_from_email',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'sequence',
          logicName: '序列',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'mail_alias_domain_dto',
    },
    {
      codeName: 'mail_alias_domain_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'mail_alias_domain_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'move_order',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTOS',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/move_order',
      needResourceKey: true,
      actionMode: 'MOVEORDER',
      actionTag: 'MoveOrder',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'MoveOrder',
      id: 'move_order',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_domain_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_domain_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'mail_alias_domain',
  deapicodeName: 'mail_alias_domain',
  deapicodeName2: 'mail_alias_domains',
  deapitag: 'MAIL_ALIAS_DOMAIN',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ALIAS_DOMAIN',
  },
  logicName: '电子邮件域名',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'MAIL_ALIAS_DOMAIN',
  id: 'ibizodooapp.mail_alias_domain',
  codeName2: 'mail_alias_domains',
  requestPaths: [],
};
