export default {
  appDEFields: [
    {
      codeName: 'alias_model_id',
      logicName: '模型别名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ALIAS_MODEL_ID',
      id: 'alias_model_id',
    },
    {
      codeName: 'alias_parent_model_id',
      logicName: '上级模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ALIAS_PARENT_MODEL_ID',
      id: 'alias_parent_model_id',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'alias_incoming_local',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_INCOMING_LOCAL',
      },
      logicName: '收件时检测本地的别名域',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ALIAS_INCOMING_LOCAL',
      id: 'alias_incoming_local',
    },
    {
      codeName: 'alias_parent_thread_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_PARENT_THREAD_ID',
      },
      logicName: '上级记录ID',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ALIAS_PARENT_THREAD_ID',
      id: 'alias_parent_thread_id',
    },
    {
      codeName: 'alias_force_thread_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_FORCE_THREAD_ID',
      },
      logicName: '记录线索ID',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ALIAS_FORCE_THREAD_ID',
      id: 'alias_force_thread_id',
    },
    {
      codeName: 'alias_bounced_content',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_BOUNCED_CONTENT',
      },
      logicName: '自定义退回消息',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ALIAS_BOUNCED_CONTENT',
      id: 'alias_bounced_content',
    },
    {
      codeName: 'alias_defaults',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DEFAULTS',
      },
      logicName: '默认值',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ALIAS_DEFAULTS',
      id: 'alias_defaults',
    },
    {
      codeName: 'alias_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_NAME',
      },
      logicName: '别名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ALIAS_NAME',
      id: 'alias_name',
    },
    {
      codeName: 'alias_full_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_FULL_NAME',
      },
      logicName: '别名电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ALIAS_FULL_NAME',
      id: 'alias_full_name',
    },
    {
      codeName: 'alias_status',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_STATUS',
      },
      logicName: '别名状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ALIAS_STATUS',
      id: 'alias_status',
    },
    {
      codeName: 'alias_contact',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_CONTACT',
      },
      logicName: '别名授权于',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ALIAS_CONTACT',
      id: 'alias_contact',
    },
    {
      codeName: 'alias_domain_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DOMAIN_ID',
      },
      logicName: '别名域',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ALIAS_DOMAIN_ID',
      id: 'alias_domain_id',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'alias_domain_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ALIAS.ALIAS_DOMAIN_ID',
      },
      logicName: '别名域名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ALIAS_DOMAIN_NAME',
      id: 'alias_domain_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'mail_alias_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'alias_model_id',
          logicName: '模型别名',
          appDEFieldId: 'alias_model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_model_id',
        },
        {
          codeName: 'alias_parent_model_id',
          logicName: '上级模型',
          appDEFieldId: 'alias_parent_model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_parent_model_id',
        },
        {
          codeName: 'alias_bounced_content',
          logicName: '自定义退回消息',
          appDEFieldId: 'alias_bounced_content',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_bounced_content',
        },
        {
          codeName: 'alias_contact',
          logicName: '别名授权于',
          appDEFieldId: 'alias_contact',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'alias_contact',
        },
        {
          codeName: 'alias_defaults',
          logicName: '默认值',
          appDEFieldId: 'alias_defaults',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          id: 'alias_defaults',
        },
        {
          codeName: 'alias_domain_id',
          logicName: '别名域',
          appDEFieldId: 'alias_domain_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_domain_id',
        },
        {
          codeName: 'alias_domain_name',
          logicName: '别名域名称',
          appDEFieldId: 'alias_domain_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_domain_name',
        },
        {
          codeName: 'alias_force_thread_id',
          logicName: '记录线索ID',
          appDEFieldId: 'alias_force_thread_id',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_force_thread_id',
        },
        {
          codeName: 'alias_full_name',
          logicName: '别名电子邮件',
          appDEFieldId: 'alias_full_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_full_name',
        },
        {
          codeName: 'alias_incoming_local',
          logicName: '收件时检测本地的别名域',
          appDEFieldId: 'alias_incoming_local',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_incoming_local',
        },
        {
          codeName: 'alias_name',
          logicName: '别名',
          appDEFieldId: 'alias_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_name',
        },
        {
          codeName: 'alias_parent_thread_id',
          logicName: '上级记录ID',
          appDEFieldId: 'alias_parent_thread_id',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_parent_thread_id',
        },
        {
          codeName: 'alias_status',
          logicName: '别名状态',
          appDEFieldId: 'alias_status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_status',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'mail_alias_dto',
    },
    {
      codeName: 'mail_alias_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_alias_contact_eq',
          logicName: '别名授权于',
          appDEFieldId: 'alias_contact',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_alias_contact_eq',
        },
        {
          codeName: 'n_alias_domain_id_eq',
          logicName: '别名域',
          appDEFieldId: 'alias_domain_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_alias_domain_id_eq',
        },
        {
          codeName: 'n_alias_domain_name_eq',
          logicName: '别名域名称',
          appDEFieldId: 'alias_domain_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_alias_domain_name_eq',
        },
        {
          codeName: 'n_alias_domain_name_like',
          logicName: '别名域名称',
          appDEFieldId: 'alias_domain_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_alias_domain_name_like',
        },
        {
          codeName: 'n_alias_status_eq',
          logicName: '别名状态',
          appDEFieldId: 'alias_status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_alias_status_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'mail_alias_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_alias_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_alias_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'mail_alias',
  deapicodeName: 'mail_alias',
  deapicodeName2: 'mail_aliases',
  deapitag: 'MAIL_ALIAS',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ALIAS',
  },
  logicName: 'EMail别名',
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'MAIL_ALIAS',
  id: 'ibizodooapp.mail_alias',
  codeName2: 'mail_aliases',
  requestPaths: [],
};
