export default {
  appDEFields: [
    {
      codeName: 'message_content',
      logicName: '消息内容',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'MESSAGE_CONTENT',
      id: 'message_content',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'is_read',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.IS_READ',
      },
      logicName: '已读',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_READ',
      id: 'is_read',
    },
    {
      codeName: 'read_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.READ_DATE',
      },
      logicName: '读取日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'READ_DATE',
      id: 'read_date',
    },
    {
      codeName: 'sms_id_int',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.SMS_ID_INT',
      },
      logicName: '短信 ID',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SMS_ID_INT',
      id: 'sms_id_int',
    },
    {
      codeName: 'failure_reason',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.FAILURE_REASON',
      },
      logicName: '失败原因',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'FAILURE_REASON',
      id: 'failure_reason',
    },
    {
      codeName: 'sms_number',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.SMS_NUMBER',
      },
      logicName: '短信息号码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SMS_NUMBER',
      id: 'sms_number',
    },
    {
      codeName: 'notification_status',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.NOTIFICATION_STATUS',
      },
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'NOTIFICATION_STATUS',
      id: 'notification_status',
    },
    {
      codeName: 'notification_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.NOTIFICATION_TYPE',
      },
      logicName: '通知类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'NOTIFICATION_TYPE',
      id: 'notification_type',
    },
    {
      codeName: 'failure_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.FAILURE_TYPE',
      },
      logicName: '失败类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'FAILURE_TYPE',
      id: 'failure_type',
    },
    {
      codeName: 'mail_mail_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.MAIL_MAIL_ID',
      },
      logicName: '邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MAIL_MAIL_ID',
      id: 'mail_mail_id',
    },
    {
      codeName: 'mail_message_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.MAIL_MESSAGE_ID',
      },
      logicName: '消息',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MAIL_MESSAGE_ID',
      id: 'mail_message_id',
    },
    {
      codeName: 'author_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.AUTHOR_ID',
      },
      logicName: '作者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'AUTHOR_ID',
      id: 'author_id',
    },
    {
      codeName: 'res_partner_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.RES_PARTNER_ID',
      },
      logicName: '收件人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RES_PARTNER_ID',
      id: 'res_partner_id',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_NOTIFICATION.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'mail_message_record_name',
      logicName: '消息记录名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'MAIL_MESSAGE_RECORD_NAME',
      id: 'mail_message_record_name',
    },
    {
      codeName: 'res_partner_name',
      logicName: '收件人名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'RES_PARTNER_NAME',
      id: 'res_partner_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'mail_notification_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'message_content',
          logicName: '消息内容',
          appDEFieldId: 'message_content',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_content',
        },
        {
          codeName: 'author_id',
          logicName: '作者',
          appDEFieldId: 'author_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'author_id',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'failure_reason',
          logicName: '失败原因',
          appDEFieldId: 'failure_reason',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'failure_reason',
        },
        {
          codeName: 'failure_type',
          logicName: '失败类型',
          appDEFieldId: 'failure_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'failure_type',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'is_read',
          logicName: '已读',
          appDEFieldId: 'is_read',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_read',
        },
        {
          codeName: 'mail_mail_id',
          logicName: '邮件',
          appDEFieldId: 'mail_mail_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mail_mail_id',
        },
        {
          codeName: 'mail_message_id',
          logicName: '消息',
          appDEFieldId: 'mail_message_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'mail_message_id',
        },
        {
          codeName: 'mail_message_record_name',
          logicName: '消息记录名称',
          appDEFieldId: 'mail_message_record_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'mail_message_record_name',
        },
        {
          codeName: 'notification_status',
          logicName: '状态',
          appDEFieldId: 'notification_status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'notification_status',
        },
        {
          codeName: 'notification_type',
          logicName: '通知类型',
          appDEFieldId: 'notification_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'notification_type',
        },
        {
          codeName: 'read_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '读取日期',
          appDEFieldId: 'read_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'read_date',
        },
        {
          codeName: 'res_partner_id',
          logicName: '收件人',
          appDEFieldId: 'res_partner_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_partner_id',
        },
        {
          codeName: 'res_partner_name',
          logicName: '收件人名称',
          appDEFieldId: 'res_partner_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_partner_name',
        },
        {
          codeName: 'sms_id_int',
          logicName: '短信 ID',
          appDEFieldId: 'sms_id_int',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sms_id_int',
        },
        {
          codeName: 'sms_number',
          logicName: '短信息号码',
          appDEFieldId: 'sms_number',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sms_number',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'mail_notification_dto',
    },
    {
      codeName: 'mail_notification_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_author_id_eq',
          logicName: '作者',
          appDEFieldId: 'author_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_author_id_eq',
        },
        {
          codeName: 'n_failure_type_eq',
          logicName: '失败类型',
          appDEFieldId: 'failure_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_failure_type_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_mail_mail_id_eq',
          logicName: '邮件',
          appDEFieldId: 'mail_mail_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mail_mail_id_eq',
        },
        {
          codeName: 'n_mail_message_id_eq',
          logicName: '消息',
          appDEFieldId: 'mail_message_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mail_message_id_eq',
        },
        {
          codeName: 'n_mail_message_record_name_eq',
          logicName: '消息记录名称',
          appDEFieldId: 'mail_message_record_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mail_message_record_name_eq',
        },
        {
          codeName: 'n_mail_message_record_name_like',
          logicName: '消息记录名称',
          appDEFieldId: 'mail_message_record_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mail_message_record_name_like',
        },
        {
          codeName: 'n_notification_status_eq',
          logicName: '状态',
          appDEFieldId: 'notification_status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_notification_status_eq',
        },
        {
          codeName: 'n_notification_type_eq',
          logicName: '通知类型',
          appDEFieldId: 'notification_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_notification_type_eq',
        },
        {
          codeName: 'n_res_partner_id_eq',
          logicName: '收件人',
          appDEFieldId: 'res_partner_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_res_partner_id_eq',
        },
        {
          codeName: 'n_res_partner_name_eq',
          logicName: '收件人名称',
          appDEFieldId: 'res_partner_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_res_partner_name_eq',
        },
        {
          codeName: 'n_res_partner_name_like',
          logicName: '收件人名称',
          appDEFieldId: 'res_partner_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_res_partner_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'mail_notification_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_notification_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_notification_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'mail_notification',
  deapicodeName: 'mail_notification',
  deapicodeName2: 'mail_notifications',
  deapitag: 'MAIL_NOTIFICATION',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_NOTIFICATION',
  },
  logicName: '消息通知',
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'MAIL_NOTIFICATION',
  id: 'ibizodooapp.mail_notification',
  codeName2: 'mail_notifications',
  requestPaths: [],
};
