export default {
  appDEFields: [
    {
      codeName: 'PPSCorePrdCatId',
      logicName: '上级分类',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PPSCOREPRDCATID',
      id: 'ppscoreprdcatid',
    },
    {
      codeName: 'AvatarUrl',
      logicName: '图标路径',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'AVATARURL',
      id: 'avatarurl',
    },
    {
      codeName: 'UpdateDate',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATEDATE',
      id: 'updatedate',
    },
    {
      codeName: 'Memo',
      logicName: '备注',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 4000,
      name: 'MEMO',
      id: 'memo',
    },
    {
      codeName: 'UpdateMan',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATEMAN',
      id: 'updateman',
    },
    {
      codeName: 'PSCorePrdCatName',
      logicName: '核心产品分类名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'PSCOREPRDCATNAME',
      id: 'pscoreprdcatname',
    },
    {
      codeName: 'CreateMan',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 60,
      name: 'CREATEMAN',
      id: 'createman',
    },
    {
      codeName: 'PPSCorePrdCatName',
      logicName: '上级分类',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PPSCOREPRDCATNAME',
      id: 'ppscoreprdcatname',
    },
    {
      codeName: 'FullName',
      logicName: '完全名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 1000,
      name: 'FULLNAME',
      id: 'fullname',
    },
    {
      codeName: 'CreateDate',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATEDATE',
      id: 'createdate',
    },
    {
      codeName: 'PSCorePrdCatId',
      logicName: '核心产品分类标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSCOREPRDCATID',
      id: 'pscoreprdcatid',
    },
    {
      codeName: 'FullPath',
      logicName: '完全路径',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 1000,
      name: 'FULLPATH',
      id: 'fullpath',
    },
    {
      codeName: 'Path',
      logicName: '路径',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PATH',
      id: 'path',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PSCorePrdCatDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'PPSCorePrdCatId',
          logicName: '上级分类',
          appDEFieldId: 'ppscoreprdcatid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PPSCorePrdCatId',
          id: 'ppscoreprdcatid',
        },
        {
          codeName: 'AvatarUrl',
          logicName: '图标路径',
          appDEFieldId: 'avatarurl',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'AvatarUrl',
          id: 'avatarurl',
        },
        {
          codeName: 'CreateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'createdate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'CreateDate',
          id: 'createdate',
        },
        {
          codeName: 'CreateMan',
          logicName: '建立人',
          appDEFieldId: 'createman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'CreateMan',
          id: 'createman',
        },
        {
          codeName: 'FullName',
          logicName: '完全名称',
          appDEFieldId: 'fullname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'FullName',
          id: 'fullname',
        },
        {
          codeName: 'FullPath',
          logicName: '完全路径',
          appDEFieldId: 'fullpath',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'FullPath',
          id: 'fullpath',
        },
        {
          codeName: 'Memo',
          logicName: '备注',
          appDEFieldId: 'memo',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Memo',
          id: 'memo',
        },
        {
          codeName: 'PPSCorePrdCatName',
          logicName: '上级分类',
          appDEFieldId: 'ppscoreprdcatname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PPSCorePrdCatName',
          id: 'ppscoreprdcatname',
        },
        {
          codeName: 'PSCorePrdCatId',
          logicName: '核心产品分类标识',
          appDEFieldId: 'pscoreprdcatid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSCorePrdCatId',
          id: 'pscoreprdcatid',
        },
        {
          codeName: 'PSCorePrdCatName',
          logicName: '核心产品分类名称',
          appDEFieldId: 'pscoreprdcatname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSCorePrdCatName',
          id: 'pscoreprdcatname',
        },
        {
          codeName: 'Path',
          logicName: '路径',
          appDEFieldId: 'path',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Path',
          id: 'path',
        },
        {
          codeName: 'UpdateDate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'updatedate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          name: 'UpdateDate',
          id: 'updatedate',
        },
        {
          codeName: 'UpdateMan',
          logicName: '更新人',
          appDEFieldId: 'updateman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'UpdateMan',
          id: 'updateman',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PSCorePrdCatDTO',
      id: 'pscoreprdcatdto',
    },
    {
      codeName: 'PSCorePrdCatFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_PSCOREPRDCATID_EQ',
          logicName: '核心产品分类标识',
          appDEFieldId: 'pscoreprdcatid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSCOREPRDCATID_EQ',
          id: 'n_pscoreprdcatid_eq',
        },
        {
          codeName: 'N_PSCOREPRDCATNAME_LIKE',
          logicName: '核心产品分类名称',
          appDEFieldId: 'pscoreprdcatname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSCOREPRDCATNAME_LIKE',
          id: 'n_pscoreprdcatname_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PSCorePrdCatFilterDTO',
      id: 'pscoreprdcatfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'pscoreprdcatfilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pscoreprdcatdto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  codeName: 'PSCorePrdCat',
  deapicodeName: 'pscoreprdcat',
  deapicodeName2: 'pscoreprdcats',
  deapitag: 'PSCOREPRDCAT',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'pscoreprdcatid',
  logicName: '核心产品分类',
  majorAppDEFieldId: 'pscoreprdcatname',
  quickSearchAppDEFieldIds: ['pscoreprdcatname'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PSCOREPRDCAT',
  id: 'ibizodooapp.pscoreprdcat',
  codeName2: 'PSCorePrdCats',
  requestPaths: [],
};
