export default {
  appDEFields: [
    {
      codeName: 'login',
      logicName: '登录',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'LOGIN',
      id: 'login',
    },
    {
      codeName: 'state',
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'company_name',
      logicName: '公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'COMPANY_NAME',
      id: 'company_name',
    },
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'gid',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'GID',
      id: 'gid',
    },
    {
      codeName: 'user_id',
      logicName: '用户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USER_ID',
      id: 'user_id',
    },
    {
      codeName: 'user_name',
      logicName: '用户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'USER_NAME',
      id: 'user_name',
    },
    {
      codeName: 'group_name',
      logicName: '组名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'GROUP_NAME',
      id: 'group_name',
    },
    {
      codeName: 'category_id',
      logicName: '应用',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CATEGORY_ID',
      id: 'category_id',
    },
    {
      codeName: 'category_name',
      logicName: '应用',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'CATEGORY_NAME',
      id: 'category_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'res_groups_users_rel_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'login',
          logicName: '登录',
          appDEFieldId: 'login',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'login',
        },
        {
          codeName: 'state',
          logicName: '状态',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'company_name',
          logicName: '公司',
          appDEFieldId: 'company_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_name',
        },
        {
          codeName: 'category_id',
          logicName: '应用',
          appDEFieldId: 'category_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'category_id',
        },
        {
          codeName: 'category_name',
          logicName: '应用',
          appDEFieldId: 'category_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'category_name',
        },
        {
          codeName: 'gid',
          logicName: '标识',
          appDEFieldId: 'gid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'gid',
        },
        {
          codeName: 'group_name',
          logicName: '组名称',
          appDEFieldId: 'group_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'group_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'user_id',
          logicName: '用户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_id',
        },
        {
          codeName: 'user_name',
          logicName: '用户',
          appDEFieldId: 'user_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_name',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'res_groups_users_rel_dto',
    },
    {
      codeName: 'res_groups_users_rel_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_gid_eq',
          logicName: '标识',
          appDEFieldId: 'gid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_gid_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_user_id_eq',
          logicName: '用户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_id_eq',
        },
        {
          codeName: 'n_user_name_eq',
          logicName: '用户',
          appDEFieldId: 'user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_name_eq',
        },
        {
          codeName: 'n_user_name_like',
          logicName: '用户',
          appDEFieldId: 'user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'res_groups_users_rel_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'DTO',
        name: 'CheckKeyInput',
        id: 'checkkeyinput',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        name: 'CheckKeyResult',
        id: 'checkkeyresult',
      },
      builtinMethod: true,
      actionMode: 'CHECKKEY',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'DTO',
        output: true,
        name: 'CreateInput',
        id: 'createinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateResult',
        id: 'createresult',
      },
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetInput',
        id: 'getinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'DTO',
        name: 'GetResult',
        id: 'getresult',
      },
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'DTO',
        name: 'GetDraftInput',
        id: 'getdraftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'DTO',
        name: 'GetDraftResult',
        id: 'getdraftresult',
      },
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveInput',
        id: 'removeinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveResult',
        id: 'removeresult',
      },
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'DTO',
        output: true,
        name: 'SaveInput',
        id: 'saveinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'SaveResult',
        id: 'saveresult',
      },
      builtinMethod: true,
      actionMode: 'SAVE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateInput',
        id: 'updateinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateResult',
        id: 'updateresult',
      },
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_users_rel_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchdefault',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_users_rel_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_users_rel_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'res_groups_users_rel',
  deapicodeName: 'res_groups_users_rel',
  deapicodeName2: 'res_groups_users_rels',
  deapitag: 'RES_GROUPS_USERS_REL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 2,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS_USERS_REL',
  },
  logicName: '权限组成员',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'res_groups',
      majorAppDataEntityId: 'ibizodooapp.res_groups',
      nestedAppDEDataSetId: 'fetchdefault',
      parentAppDEFieldId: 'gid',
      parentTextAppDEFieldId: 'group_name',
      rsmode: 1,
      rstype: 'DER1N',
      tempDataOrder: 10,
      name: 'DER1N_RES_GROUPS_USERS_REL_RES_GROUPS_GID',
      id: 'res_groups',
    },
    {
      actionRSMode: 1,
      codeName: 'res_users',
      majorAppDataEntityId: 'ibizodooapp.res_users',
      nestedAppDEDataSetId: 'fetchdefault',
      parentAppDEFieldId: 'user_id',
      parentTextAppDEFieldId: 'user_name',
      rsmode: 1,
      rstype: 'DER1N',
      tempDataOrder: 10,
      name: 'DER1N_RES_GROUPS_USERS_REL_RES_USERS_USER_ID',
      id: 'res_users',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['gid', 'user_id'],
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  name: 'RES_GROUPS_USERS_REL',
  id: 'ibizodooapp.res_groups_users_rel',
  codeName2: 'res_groups_users_rels',
  requestPaths: [],
};
