export default {
  appDEFields: [
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_UID',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'date_to',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.DATE_TO',
      },
      logicName: '结束日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_TO',
      id: 'date_to',
    },
    {
      codeName: 'date_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.DATE_FROM',
      },
      logicName: '开始日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE_FROM',
      id: 'date_from',
    },
    {
      codeName: 'time_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.TIME_TYPE',
      },
      logicName: '时间类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'TIME_TYPE',
      id: 'time_type',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'company_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.COMPANY_ID',
      },
      logicName: '公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COMPANY_ID',
      id: 'company_id',
    },
    {
      codeName: 'calendar_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.CALENDAR_ID',
      },
      logicName: '工作时间',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CALENDAR_ID',
      id: 'calendar_id',
    },
    {
      codeName: 'resource_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.RESOURCE_ID',
      },
      logicName: '资源',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RESOURCE_ID',
      id: 'resource_id',
    },
    {
      codeName: 'holiday_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.HOLIDAY_ID',
      },
      logicName: '休假要求',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'HOLIDAY_ID',
      id: 'holiday_id',
    },
    {
      codeName: 'calendar_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.CALENDAR_ID',
      },
      logicName: '工作时间名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'CALENDAR_NAME',
      id: 'calendar_name',
    },
    {
      codeName: 'resource_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.RESOURCE_ID',
      },
      logicName: '资源名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'RESOURCE_NAME',
      id: 'resource_name',
    },
    {
      codeName: 'company_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.COMPANY_ID',
      },
      logicName: '公司名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'COMPANY_NAME',
      id: 'company_name',
    },
    {
      codeName: 'holnameay_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_LEAVES.HOLIDAY_ID',
      },
      logicName: '休假要求',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'HOLNAMEAY_NAME',
      id: 'holnameay_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'resource_calendar_leaves_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'calendar_id',
          logicName: '工作时间',
          appDEFieldId: 'calendar_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'calendar_id',
        },
        {
          codeName: 'calendar_name',
          logicName: '工作时间名称',
          appDEFieldId: 'calendar_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'calendar_name',
        },
        {
          codeName: 'company_id',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_id',
        },
        {
          codeName: 'company_name',
          logicName: '公司名称',
          appDEFieldId: 'company_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_name',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'date_from',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '开始日期',
          appDEFieldId: 'date_from',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'date_from',
        },
        {
          codeName: 'date_to',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '结束日期',
          appDEFieldId: 'date_to',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'date_to',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'holiday_id',
          logicName: '休假要求',
          appDEFieldId: 'holiday_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'holiday_id',
        },
        {
          codeName: 'holnameay_name',
          logicName: '休假要求',
          appDEFieldId: 'holnameay_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'holnameay_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'resource_id',
          logicName: '资源',
          appDEFieldId: 'resource_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'resource_id',
        },
        {
          codeName: 'resource_name',
          logicName: '资源名称',
          appDEFieldId: 'resource_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'resource_name',
        },
        {
          codeName: 'time_type',
          logicName: '时间类型',
          appDEFieldId: 'time_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'time_type',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'resource_calendar_leaves_dto',
    },
    {
      codeName: 'resource_calendar_leaves_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_calendar_id_eq',
          logicName: '工作时间',
          appDEFieldId: 'calendar_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_calendar_id_eq',
        },
        {
          codeName: 'n_calendar_name_eq',
          logicName: '工作时间名称',
          appDEFieldId: 'calendar_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_calendar_name_eq',
        },
        {
          codeName: 'n_calendar_name_like',
          logicName: '工作时间名称',
          appDEFieldId: 'calendar_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_calendar_name_like',
        },
        {
          codeName: 'n_company_id_eq',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_id_eq',
        },
        {
          codeName: 'n_company_name_eq',
          logicName: '公司名称',
          appDEFieldId: 'company_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_name_eq',
        },
        {
          codeName: 'n_company_name_like',
          logicName: '公司名称',
          appDEFieldId: 'company_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_name_like',
        },
        {
          codeName: 'n_date_from_gtandeq',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '开始日期',
          appDEFieldId: 'date_from',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_date_from_gtandeq',
        },
        {
          codeName: 'n_date_from_ltandeq',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '开始日期',
          appDEFieldId: 'date_from',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_date_from_ltandeq',
        },
        {
          codeName: 'n_date_to_gtandeq',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '结束日期',
          appDEFieldId: 'date_to',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_date_to_gtandeq',
        },
        {
          codeName: 'n_date_to_ltandeq',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '结束日期',
          appDEFieldId: 'date_to',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_date_to_ltandeq',
        },
        {
          codeName: 'n_holiday_id_eq',
          logicName: '休假要求',
          appDEFieldId: 'holiday_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_holiday_id_eq',
        },
        {
          codeName: 'n_holnameay_name_eq',
          logicName: '休假要求',
          appDEFieldId: 'holnameay_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_holnameay_name_eq',
        },
        {
          codeName: 'n_holnameay_name_like',
          logicName: '休假要求',
          appDEFieldId: 'holnameay_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_holnameay_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_resource_id_eq',
          logicName: '资源',
          appDEFieldId: 'resource_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_resource_id_eq',
        },
        {
          codeName: 'n_resource_name_eq',
          logicName: '资源名称',
          appDEFieldId: 'resource_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_resource_name_eq',
        },
        {
          codeName: 'n_resource_name_like',
          logicName: '资源名称',
          appDEFieldId: 'resource_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_resource_name_like',
        },
        {
          codeName: 'n_time_type_eq',
          logicName: '时间类型',
          appDEFieldId: 'time_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_time_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'resource_calendar_leaves_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_calendar_leaves_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_public',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_calendar_leaves_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_calendar_leaves_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_public',
      actionType: 'REMOTE',
      dataSetName: 'PUBLIC',
      dataSetTag: 'public',
      dataSetType: 'REMOTE',
      id: 'fetch_public',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'resource_calendar_leaves',
  deapicodeName: 'resource_calendar_leaves',
  deapicodeName2: 'resource_calendar_leaves',
  deapitag: 'RESOURCE_CALENDAR_LEAVES',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_CALENDAR_LEAVES',
  },
  logicName: '休假详细信息',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'resource_calendar_leaves',
      majorAppDataEntityId: 'ibizodooapp.resource_calendar',
      parentAppDEFieldId: 'calendar_id',
      parentTextAppDEFieldId: 'calendar_name',
      rsmode: 2,
      name: '资源工作时间-休假详细信息',
      id: 'resource_calendar_leaves',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'RESOURCE_CALENDAR_LEAVES',
  id: 'ibizodooapp.resource_calendar_leaves',
  codeName2: 'resource_calendar_leaves',
  requestPaths: [
    'resource_calendars/${resource_calendar}/resource_calendar_leaves/${resource_calendar_leaves}',
  ],
};
