export default {
  appDEFields: [
    {
      codeName: 'model_id',
      logicName: '模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'MODEL_ID',
      id: 'model_id',
    },
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'gid',
      logicName: '组标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'GID',
      id: 'gid',
    },
    {
      codeName: 'rule_id',
      logicName: '规则标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RULE_ID',
      id: 'rule_id',
    },
    {
      codeName: 'perm_unlink',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_RULE.PERM_UNLINK',
      },
      logicName: '删除',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PERM_UNLINK',
      id: 'perm_unlink',
    },
    {
      codeName: 'domain_force',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_RULE.DOMAIN_FORCE',
      },
      logicName: '域名',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DOMAIN_FORCE',
      id: 'domain_force',
    },
    {
      codeName: 'perm_write',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_RULE.PERM_WRITE',
      },
      logicName: '写入',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PERM_WRITE',
      id: 'perm_write',
    },
    {
      codeName: 'perm_read',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_RULE.PERM_READ',
      },
      logicName: '读取',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PERM_READ',
      id: 'perm_read',
    },
    {
      codeName: 'perm_create',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_RULE.PERM_CREATE',
      },
      logicName: '创建',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PERM_CREATE',
      id: 'perm_create',
    },
    {
      codeName: 'gname',
      logicName: '组名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'GNAME',
      id: 'gname',
    },
    {
      codeName: 'rule_name',
      logicName: '规则名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'RULE_NAME',
      id: 'rule_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'rule_group_rel_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'model_id',
          logicName: '模型',
          appDEFieldId: 'model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'model_id',
        },
        {
          codeName: 'domain_force',
          logicName: '域名',
          appDEFieldId: 'domain_force',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'domain_force',
        },
        {
          codeName: 'gid',
          logicName: '组标识',
          appDEFieldId: 'gid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'gid',
        },
        {
          codeName: 'gname',
          logicName: '组名称',
          appDEFieldId: 'gname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'gname',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'perm_create',
          logicName: '创建',
          appDEFieldId: 'perm_create',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'perm_create',
        },
        {
          codeName: 'perm_read',
          logicName: '读取',
          appDEFieldId: 'perm_read',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'perm_read',
        },
        {
          codeName: 'perm_unlink',
          logicName: '删除',
          appDEFieldId: 'perm_unlink',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'perm_unlink',
        },
        {
          codeName: 'perm_write',
          logicName: '写入',
          appDEFieldId: 'perm_write',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'perm_write',
        },
        {
          codeName: 'rule_id',
          logicName: '规则标识',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rule_id',
        },
        {
          codeName: 'rule_name',
          logicName: '规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rule_name',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'rule_group_rel_dto',
    },
    {
      codeName: 'rule_group_rel_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_gid_eq',
          logicName: '组标识',
          appDEFieldId: 'gid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_gid_eq',
        },
        {
          codeName: 'n_gname_eq',
          logicName: '组名称',
          appDEFieldId: 'gname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_gname_eq',
        },
        {
          codeName: 'n_gname_like',
          logicName: '组名称',
          appDEFieldId: 'gname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_gname_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_rule_id_eq',
          logicName: '规则标识',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_id_eq',
        },
        {
          codeName: 'n_rule_name_eq',
          logicName: '规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_name_eq',
        },
        {
          codeName: 'n_rule_name_like',
          logicName: '规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'rule_group_rel_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'DTO',
        name: 'CheckKeyInput',
        id: 'checkkeyinput',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        name: 'CheckKeyResult',
        id: 'checkkeyresult',
      },
      builtinMethod: true,
      actionMode: 'CHECKKEY',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'DTO',
        output: true,
        name: 'CreateInput',
        id: 'createinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateResult',
        id: 'createresult',
      },
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetInput',
        id: 'getinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'DTO',
        name: 'GetResult',
        id: 'getresult',
      },
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'DTO',
        name: 'GetDraftInput',
        id: 'getdraftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'DTO',
        name: 'GetDraftResult',
        id: 'getdraftresult',
      },
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveInput',
        id: 'removeinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveResult',
        id: 'removeresult',
      },
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'DTO',
        output: true,
        name: 'SaveInput',
        id: 'saveinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'SaveResult',
        id: 'saveresult',
      },
      builtinMethod: true,
      actionMode: 'SAVE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateInput',
        id: 'updateinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateResult',
        id: 'updateresult',
      },
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'rule_group_rel_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchdefault',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'rule_group_rel_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'rule_group_rel_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'rule_group_rel',
  deapicodeName: 'rule_group_rel',
  deapicodeName2: 'rule_group_rels',
  deapitag: 'RULE_GROUP_REL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 2,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.RULE_GROUP_REL',
  },
  logicName: '权限组关联规则',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'ir_rule',
      majorAppDataEntityId: 'ibizodooapp.ir_rule',
      nestedAppDEDataSetId: 'fetchdefault',
      parentAppDEFieldId: 'rule_id',
      parentTextAppDEFieldId: 'rule_name',
      rsmode: 1,
      rstype: 'DER1N',
      removeActionType: 1,
      tempDataOrder: 10,
      name: 'DER1N_RULE_GROUP_REL_IR_RULE_RULE_ID',
      id: 'ir_rule',
    },
    {
      actionRSMode: 1,
      codeName: 'res_groups',
      majorAppDataEntityId: 'ibizodooapp.res_groups',
      nestedAppDEDataSetId: 'fetchdefault',
      parentAppDEFieldId: 'gid',
      parentTextAppDEFieldId: 'gname',
      rsmode: 1,
      rstype: 'DER1N',
      tempDataOrder: 10,
      name: 'DER1N_RULE_GROUP_REL_RES_GROUPS_GID',
      id: 'res_groups',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['gid', 'rule_id'],
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  name: 'RULE_GROUP_REL',
  id: 'ibizodooapp.rule_group_rel',
  codeName2: 'rule_group_rels',
  requestPaths: [],
};
