export default {
  appDEFields: [
    {
      codeName: 'res_code',
      logicName: '资源代码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'RES_CODE',
      id: 'res_code',
    },
    {
      codeName: 'name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'unires_id',
      logicName: '统一资源标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'UNIRES_ID',
      id: 'unires_id',
    },
    {
      codeName: 'gid',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'GID',
      id: 'gid',
    },
    {
      codeName: 'unires_name',
      logicName: '统一资源名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'UNIRES_NAME',
      id: 'unires_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'unires_group_relDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'res_code',
          logicName: '资源代码',
          appDEFieldId: 'res_code',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_code',
        },
        {
          codeName: 'gid',
          logicName: '标识',
          appDEFieldId: 'gid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'gid',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'unires_id',
          logicName: '统一资源标识',
          appDEFieldId: 'unires_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'unires_id',
        },
        {
          codeName: 'unires_name',
          logicName: '统一资源名称',
          appDEFieldId: 'unires_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'unires_name',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'unires_group_relDTO',
      id: 'unires_group_reldto',
    },
    {
      codeName: 'unires_group_relFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_GID_EQ',
          logicName: '标识',
          appDEFieldId: 'gid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_GID_EQ',
          id: 'n_gid_eq',
        },
        {
          codeName: 'N_ID_EQ',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_ID_EQ',
          id: 'n_id_eq',
        },
        {
          codeName: 'N_UNIRES_ID_EQ',
          logicName: '统一资源标识',
          appDEFieldId: 'unires_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_UNIRES_ID_EQ',
          id: 'n_unires_id_eq',
        },
        {
          codeName: 'N_UNIRES_NAME_EQ',
          logicName: '统一资源名称',
          appDEFieldId: 'unires_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_UNIRES_NAME_EQ',
          id: 'n_unires_name_eq',
        },
        {
          codeName: 'N_UNIRES_NAME_LIKE',
          logicName: '统一资源名称',
          appDEFieldId: 'unires_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_UNIRES_NAME_LIKE',
          id: 'n_unires_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'unires_group_relFilterDTO',
      id: 'unires_group_relfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'DTO',
        name: 'CheckKeyInput',
        id: 'checkkeyinput',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        name: 'CheckKeyResult',
        id: 'checkkeyresult',
      },
      builtinMethod: true,
      actionMode: 'CHECKKEY',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'DTO',
        output: true,
        name: 'CreateInput',
        id: 'createinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateResult',
        id: 'createresult',
      },
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetInput',
        id: 'getinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'DTO',
        name: 'GetResult',
        id: 'getresult',
      },
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'DTO',
        name: 'GetDraftInput',
        id: 'getdraftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'DTO',
        name: 'GetDraftResult',
        id: 'getdraftresult',
      },
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveInput',
        id: 'removeinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveResult',
        id: 'removeresult',
      },
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'DTO',
        output: true,
        name: 'SaveInput',
        id: 'saveinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'SaveResult',
        id: 'saveresult',
      },
      builtinMethod: true,
      actionMode: 'SAVE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'DTO',
        output: true,
        name: 'UpdateInput',
        id: 'updateinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateResult',
        id: 'updateresult',
      },
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'unires_group_relfilterdto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'unires_group_reldto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'unires_group_rel',
  deapicodeName: 'unires_group_rel',
  deapicodeName2: 'unires_group_rels',
  deapitag: 'UNIRES_GROUP_REL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 2,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.UNIRES_GROUP_REL',
  },
  logicName: '权限组关联统一资源',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'IR_UNIRES',
      majorAppDataEntityId: 'ibizodooapp.ir_unires',
      nestedAppDEDataSetId: 'fetchdefault',
      parentAppDEFieldId: 'unires_id',
      parentTextAppDEFieldId: 'unires_name',
      rsmode: 1,
      rstype: 'DER1N',
      tempDataOrder: 10,
      name: 'DER1N_UNIRES_GROUP_REL_IR_UNIRES_UNIRES_ID',
      id: 'ir_unires',
    },
    {
      actionRSMode: 1,
      codeName: 'RES_GROUPS',
      majorAppDataEntityId: 'ibizodooapp.res_groups',
      nestedAppDEDataSetId: 'fetchdefault',
      parentAppDEFieldId: 'gid',
      rsmode: 1,
      rstype: 'DER1N',
      tempDataOrder: 10,
      name: 'DER1N_UNIRES_GROUP_REL_RES_GROUPS_GID',
      id: 'res_groups',
    },
    {
      actionRSMode: 1,
      codeName: 'unires_group_rels',
      majorAppDataEntityId: 'ibizodooapp.res_groups',
      parentAppDEFieldId: 'gid',
      rsmode: 2,
      tempDataOrder: 10,
      name: '权限组-权限组关联统一资源',
      id: 'unires_group_rels',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['gid', 'unires_id'],
  defaultMode: true,
  enableFilterActions: true,
  name: 'UNIRES_GROUP_REL',
  id: 'ibizodooapp.unires_group_rel',
  codeName2: 'unires_group_rels',
  requestPaths: [
    'res_groups/${res_groups}/unires_group_rels/${unires_group_rel}',
  ],
};
