export default {
  appBISchemeIds: ['ibizodooapp.default'],
  appDEUIActions: [
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '添加全部',
      codeName: 'AddAll',
      fullCodeName: 'AddAll',
      predefinedType: 'UTIL_ADDALL',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'AddAll',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '添加全部数据（数据选择）',
      id: 'util_addall',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '添加选中',
      codeName: 'AddSelection',
      fullCodeName: 'AddSelection',
      predefinedType: 'UTIL_ADDSELECTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'AddSelection',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '添加选中数据（数据选择）',
      id: 'util_addselection',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组2',
      codeName: 'Auto10605015',
      fullCodeName: 'Auto10605015',
      predefinedType: 'VIEW_DEBHGROUP002',
      uiactionMode: 'SYS',
      uiactionTag: 'Auto10605015',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组2',
      id: 'auto10605015',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组3',
      codeName: 'Auto66936409',
      fullCodeName: 'Auto66936409',
      predefinedType: 'VIEW_DEBHGROUP003',
      uiactionMode: 'SYS',
      uiactionTag: 'Auto66936409',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组3',
      id: 'auto66936409',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组1',
      codeName: 'Auto76922936',
      fullCodeName: 'Auto76922936',
      predefinedType: 'VIEW_DEBHGROUP001',
      uiactionMode: 'SYS',
      uiactionTag: 'Auto76922936',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组1',
      id: 'auto76922936',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '取消',
      codeName: 'Cancel',
      fullCodeName: 'Cancel',
      predefinedType: 'VIEW_CANCELACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Cancel',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_取消',
      id: 'view_cancelaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '取消变更',
      codeName: 'CancelChanges',
      fullCodeName: 'CancelChanges',
      predefinedType: 'DATA_CANCELCHANGES',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'CancelChanges',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '取消变更',
      id: 'data_cancelchanges',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.COPY',
      },
      caption: '拷贝',
      codeName: 'Copy',
      fullCodeName: 'Copy',
      sysImage: {
        cssClass: 'fa fa-copy',
        glyph: 'xf0c5@FontAwesome',
      },
      predefinedType: 'EDITVIEW_COPYACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.COPY',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Copy',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_拷贝操作',
      id: 'editview_copyaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.COPY',
      },
      caption: '拷贝',
      codeName: 'Copy',
      fullCodeName: 'Copy',
      sysImage: {
        cssClass: 'fa fa-copy',
        glyph: 'xf0c5@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_COPYACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.COPY',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Copy',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_拷贝操作',
      id: 'gridview_copyaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '建立数据',
      codeName: 'CreateObject',
      fullCodeName: 'CreateObject',
      predefinedType: 'DATA_CREATEOBJECT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'CreateObject',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '建立数据',
      id: 'data_createobject',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.EDIT',
      },
      caption: '编辑',
      codeName: 'Edit',
      fullCodeName: 'Edit',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_EDITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.EDIT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Edit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_编辑操作',
      id: 'gridview_editaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.EXPORT',
      },
      caption: '导出',
      codeName: 'ExportExcel',
      fullCodeName: 'ExportExcel',
      sysImage: {
        cssClass: 'fa fa-file-excel-o',
        glyph: 'xf1c3@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_EXPORTACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.EXPORT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'ExportExcel',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_导出操作（Excel）',
      id: 'gridview_exportaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'MENUITEM.CAPTION.*.EXPORTSRF',
      },
      caption: '导出数据模型',
      codeName: 'ExportModel',
      fullCodeName: 'ExportModel',
      sysImage: {
        cssClass: 'fa fa-download',
        glyph: 'xf019@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_EXPORTXMLACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'ExportModel',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_导出数据模型',
      id: 'gridview_exportxmlaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '完成',
      codeName: 'Finish',
      fullCodeName: 'Finish',
      predefinedType: 'UTIL_FINISH',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Finish',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '完成（向导）',
      id: 'util_finish',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '第一个记录',
      codeName: 'FirstRecord',
      fullCodeName: 'FirstRecord',
      sysImage: {
        cssClass: 'fa fa-fast-backward',
        glyph: 'xf049@FontAwesome',
      },
      predefinedType: 'EDITVIEW_FIRSTRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'FirstRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_第一个记录',
      id: 'editview_firstrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组1（新模式）',
      codeName: 'Group001',
      fullCodeName: 'Group001',
      predefinedType: 'VIEW_DEBHGROUPEX001',
      uiactionMode: 'SYS',
      uiactionTag: 'Group001',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组1（新模式）',
      id: 'group001',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.HELP',
      },
      caption: '帮助',
      codeName: 'Help',
      fullCodeName: 'Help',
      sysImage: {
        cssClass: 'fa fa-question',
        glyph: 'xf128@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_HELPACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.HELP',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Help',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_帮助操作',
      id: 'gridview_helpaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '数据导入',
      codeName: 'Import',
      fullCodeName: 'Import',
      sysImage: {
        cssClass: 'fa fa-upload',
        glyph: 'xf093@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_IMPORTBAR',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Import',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_数据导入栏',
      id: 'gridview_importbar',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '最后一个记录',
      codeName: 'LastRecord',
      fullCodeName: 'LastRecord',
      sysImage: {
        cssClass: 'fa fa-fast-forward',
        glyph: 'xf050@FontAwesome',
      },
      predefinedType: 'EDITVIEW_LASTRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'LastRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_最后一个记录',
      id: 'editview_lastrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '登录',
      codeName: 'Login',
      fullCodeName: 'Login',
      predefinedType: 'APP_LOGIN',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Login',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '应用登录',
      id: 'app_login',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '登出',
      codeName: 'Logout',
      fullCodeName: 'Logout',
      predefinedType: 'APP_LOGOUT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Logout',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '应用登出',
      id: 'app_logout',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.NEW',
      },
      caption: '新建',
      codeName: 'New',
      fullCodeName: 'New',
      sysImage: {
        cssClass: 'fa fa-file-text-o',
        glyph: 'xf0f6@FontAwesome',
      },
      predefinedType: 'EDITVIEW_NEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.NEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'New',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_新建操作',
      id: 'editview_newaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.NEW',
      },
      caption: '新建',
      codeName: 'New',
      fullCodeName: 'New',
      sysImage: {
        cssClass: 'fa fa-file-text-o',
        glyph: 'xf0f6@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_NEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.NEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'New',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_新建操作',
      id: 'gridview_newaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '新建行',
      codeName: 'NewRow',
      fullCodeName: 'NewRow',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_NEWROWACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NewRow',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_新建行',
      id: 'gridview_newrowaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '下一个记录',
      codeName: 'NextRecord',
      fullCodeName: 'NextRecord',
      sysImage: {
        cssClass: 'fa fa-step-forward',
        glyph: 'xf051@FontAwesome',
      },
      predefinedType: 'EDITVIEW_NEXTRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NextRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_下一个记录',
      id: 'editview_nextrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '下一步',
      codeName: 'NextStep',
      fullCodeName: 'NextStep',
      predefinedType: 'UTIL_NEXTSTEP',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NextStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '下一步（向导）',
      id: 'util_nextstep',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '否',
      codeName: 'No',
      fullCodeName: 'No',
      predefinedType: 'VIEW_NOACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'No',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_否',
      id: 'view_noaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '确定',
      codeName: 'Ok',
      fullCodeName: 'Ok',
      predefinedType: 'VIEW_OKACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Ok',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_确定',
      id: 'view_okaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '上一个记录',
      codeName: 'PrevRecord',
      fullCodeName: 'PrevRecord',
      sysImage: {
        cssClass: 'fa fa-step-backward',
        glyph: 'xf048@FontAwesome',
      },
      predefinedType: 'EDITVIEW_PREVRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'PrevRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_上一个记录',
      id: 'editview_prevrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '上一步',
      codeName: 'PrevStep',
      fullCodeName: 'PrevStep',
      predefinedType: 'UTIL_PREVSTEP',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'PrevStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '上一步（向导）',
      id: 'util_prevstep',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.PRINT',
      },
      caption: '打印',
      codeName: 'Print',
      fullCodeName: 'Print',
      sysImage: {
        cssClass: 'fa fa-print',
        glyph: 'xf02f@FontAwesome',
      },
      predefinedType: 'EDITVIEW_PRINTACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.PRINT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Print',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_打印操作',
      id: 'editview_printaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.PRINT',
      },
      caption: '打印',
      codeName: 'Print',
      fullCodeName: 'Print',
      sysImage: {
        cssClass: 'fa fa-print',
        glyph: 'xf02f@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_PRINTACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.PRINT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Print',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_打印操作',
      id: 'gridview_printaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '刷新',
      codeName: 'Refresh',
      fullCodeName: 'Refresh',
      sysImage: {
        cssClass: 'fa fa-refresh',
        glyph: 'xf021@FontAwesome',
      },
      predefinedType: 'EDITVIEW_REFRESHACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Refresh',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_刷新操作',
      id: 'editview_refreshaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.REMOVE',
      },
      caption: '删除',
      codeName: 'Remove',
      fullCodeName: 'Remove',
      sysImage: {
        cssClass: 'fa fa-remove',
        glyph: 'xf00d@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_REMOVEACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.REMOVE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Remove',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_删除操作',
      id: 'gridview_removeaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '移除全部',
      codeName: 'RemoveAll',
      fullCodeName: 'RemoveAll',
      predefinedType: 'UTIL_REMOVEALL',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveAll',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '移除全部数据（数据选择）',
      id: 'util_removeall',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
      },
      caption: '删除并关闭',
      codeName: 'RemoveAndExit',
      fullCodeName: 'RemoveAndExit',
      sysImage: {
        cssClass: 'fa fa-remove',
        glyph: 'xf00d@FontAwesome',
      },
      predefinedType: 'EDITVIEW_REMOVEANDEXITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveAndExit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_删除并退出操作',
      id: 'editview_removeandexitaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '删除数据',
      codeName: 'RemoveObject',
      fullCodeName: 'RemoveObject',
      predefinedType: 'DATA_REMOVEOBJECT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveObject',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '删除数据',
      id: 'data_removeobject',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '移除选中',
      codeName: 'RemoveSelection',
      fullCodeName: 'RemoveSelection',
      predefinedType: 'UTIL_REMOVESELECTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveSelection',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '移除选中数据（数据选择）',
      id: 'util_removeselection',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '重置',
      codeName: 'Reset',
      fullCodeName: 'Reset',
      predefinedType: 'UTIL_RESET',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Reset',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '重置（搜索栏）',
      id: 'util_reset',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.SAVE',
      },
      caption: '保存',
      codeName: 'Save',
      fullCodeName: 'Save',
      sysImage: {
        cssClass: 'fa fa-save',
        glyph: 'xf0c7@FontAwesome',
      },
      predefinedType: 'EDITVIEW_SAVEACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.SAVE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Save',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存操作',
      id: 'editview_saveaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
      },
      caption: '保存并关闭',
      codeName: 'SaveAndExit',
      fullCodeName: 'SaveAndExit',
      sysImage: {
        cssClass: 'fa fa-save',
        glyph: 'xf0c7@FontAwesome',
      },
      predefinedType: 'EDITVIEW_SAVEANDEXITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'SaveAndExit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存并退出操作',
      id: 'editview_saveandexitaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
      },
      caption: '保存并新建',
      codeName: 'SaveAndNew',
      fullCodeName: 'SaveAndNew',
      sysImage: {
        cssClass: 'fa fa-save',
        glyph: 'xf0c7@FontAwesome',
      },
      predefinedType: 'EDITVIEW_SAVEANDNEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'SaveAndNew',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存并新建操作',
      id: 'editview_saveandnewaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.STARTWF',
      },
      caption: '开始流程',
      codeName: 'SaveAndStart',
      fullCodeName: 'SaveAndStart',
      sysImage: {
        cssClass: 'fa fa-play',
        glyph: 'xf04b@FontAwesome',
      },
      predefinedType: 'EDITVIEW_SAVEANDSTARTWFACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.STARTWF',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'SaveAndStart',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存并开始流程操作',
      id: 'editview_saveandstartwfaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '保存变更',
      codeName: 'SaveChanges',
      fullCodeName: 'SaveChanges',
      predefinedType: 'DATA_SAVECHANGES',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'SaveChanges',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '保存变更',
      id: 'data_savechanges',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '搜索',
      codeName: 'Search',
      fullCodeName: 'Search',
      predefinedType: 'UTIL_SEARCH',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Search',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '搜索（搜索栏）',
      id: 'util_search',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '同步数据',
      codeName: 'Synchronize',
      fullCodeName: 'Synchronize',
      predefinedType: 'DATA_SYNCHRONIZE',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Synchronize',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '同步数据',
      id: 'data_synchronize',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.FILTER',
      },
      caption: '过滤',
      codeName: 'ToggleFilter',
      fullCodeName: 'ToggleFilter',
      sysImage: {
        cssClass: 'fa fa-filter',
        glyph: 'xf0b0@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_SEARCHBAR',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.FILTER',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'ToggleFilter',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_搜索栏',
      id: 'gridview_searchbar',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '行编辑',
      codeName: 'ToggleRowEdit',
      fullCodeName: 'ToggleRowEdit',
      sysImage: {
        cssClass: 'fa fa-table',
        glyph: 'xf0ce@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_ROWEDITACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'ToggleRowEdit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_行编辑开关操作',
      id: 'gridview_roweditaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.VIEW',
      },
      caption: '查看',
      codeName: 'View',
      fullCodeName: 'View',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_VIEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.VIEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'View',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_查看操作',
      id: 'gridview_viewaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.VIEWWFSTEP',
      },
      caption: '当前流程步骤',
      codeName: 'ViewWFStep',
      fullCodeName: 'ViewWFStep',
      sysImage: {
        cssClass: 'sx-tb-stepactor',
      },
      predefinedType: 'EDITVIEW_VIEWWFSTEPACTORACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'ViewWFStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_查看当前流程步骤用户操作',
      id: 'editview_viewwfstepactoraction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '是',
      codeName: 'Yes',
      fullCodeName: 'Yes',
      predefinedType: 'VIEW_YESACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Yes',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_是',
      id: 'view_yesaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '邀请人员',
      codeName: 'invite_member',
      frontAppViewId: 'ibizodooapp.discuss_channel_invite_member_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'discuss_channel_invite_member',
      navigateParams: [
        {
          key: 'channel_id',
          value: 'discuss_channel',
          id: 'channel_id',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'invite_member',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.discuss_channel',
      name: '邀请人员',
      id: 'invite_member@discuss_channel',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '新建行',
      codeName: 'newRow',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_departure_reason_newRow',
      uiactionMode: 'FRONT',
      uiactionTag: 'newRow',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'new_row',
      appDataEntityId: 'ibizodooapp.hr_departure_reason',
      name: '表格新建行_脚本',
      id: 'newrow@hr_departure_reason',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '配置设定',
      codeName: 'open_settings_view',
      frontAppViewId: 'ibizodooapp.res_config_settings_modify_setting',
      frontProcessType: 'WIZARD',
      fullCodeName: 'res_config_settings_open_settings_view',
      uiactionMode: 'FRONT',
      uiactionTag: 'open_settings_view',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.res_config_settings',
      name: '打开配置设定视图',
      id: 'open_settings_view@res_config_settings',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '用户详情',
      codeName: 'open_user_create_view',
      frontAppViewId: 'ibizodooapp.res_users_create_user_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'res_users_open_user_create_view',
      navigateContexts: [
        {
          key: 'DEFAULT_COMPANY_NAME',
          value: 'company_name',
          name: 'DEFAULT_COMPANY_NAME',
          id: 'default_company_name',
        },
        {
          key: 'DEFAULT_LOGIN',
          value: 'work_email',
          name: 'DEFAULT_LOGIN',
          id: 'default_login',
        },
        {
          key: 'DEFAULT_MOBILE',
          value: 'mobile_phone',
          name: 'DEFAULT_MOBILE',
          id: 'default_mobile',
        },
        {
          key: 'DEFAULT_NAME',
          value: 'name',
          name: 'DEFAULT_NAME',
          id: 'default_name',
        },
        {
          key: 'DEFAULT_PARTNER_ID',
          value: 'work_contact_id',
          name: 'DEFAULT_PARTNER_ID',
          id: 'default_partner_id',
        },
        {
          key: 'DEFAULT_PHONE',
          value: 'work_phone',
          name: 'DEFAULT_PHONE',
          id: 'default_phone',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'open_user_create_view',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.res_users',
      name: '打开用户创建页面',
      id: 'open_user_create_view@res_users',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '展开',
      codeName: 'tree_node_expanded',
      frontProcessType: 'OTHER',
      fullCodeName: 'hr_employee_tree_node_expanded',
      scriptCode:
        "\r\nevent.stopPropagation();\r\nevent.preventDefault();\r\nctrl.evt.emit('onPanelItemEvent', {\r\n    panelItemName: ctrl.model.id,\r\n    panelItemEventName: 'onExpanded',\r\n    event,\r\n    data: data,\r\n})",
      uiactionMode: 'FRONT',
      uiactionTag: 'tree_node_expanded',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'ibizodooapp.hr_employee',
      name: '树节点展开',
      id: 'tree_node_expanded@hr_employee',
    },
  ],
  appFuncs: [
    {
      appFuncType: 'APPVIEW',
      codeName: 'employee',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_employee_multi_data_view',
      name: '员工管理',
      id: 'employee',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'group',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.res_groups_multi_data_view',
      name: '群组管理',
      id: 'group',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'model',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_model_multi_data_view',
      name: '模型',
      id: 'model',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_activity_plan2',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_activity_plan_multi_data_view2',
      name: '活动计划_设置',
      id: 'mail_activity_plan2',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'my_lead',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.crm_lead_multi_data_view',
      name: 'CRM-我的渠道',
      id: 'my_lead',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_job',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_job_multi_data_view',
      name: '员工管理-工作岗位',
      id: 'hr_job',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'app_market',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ps_core_prd_func_tree_exp_view',
      name: '应用市场',
      id: 'app_market',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'ir_module_module',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_module_module_grid_view',
      name: '模块管理',
      id: 'ir_module_module',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'department',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_department_multi_data_view',
      name: '员工管理-部门',
      id: 'department',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'followers',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_followers_multi_data_view',
      name: '单据关注者',
      id: 'followers',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_mail_multi_data_view',
      name: 'EMail',
      id: 'mail',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'ir_model_access',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_model_access_multi_data_view',
      name: '访问权限',
      id: 'ir_model_access',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'user',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.res_users_multi_data_view',
      name: '用户管理',
      id: 'user',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_activity_plan',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_activity_plan_multi_data_view',
      name: '活动计划_员工',
      id: 'mail_activity_plan',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_employee_category',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_employee_category_multi_data_view',
      name: '员工管理-员工类别',
      id: 'hr_employee_category',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'unires',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_unires_multi_data_view',
      name: '统一资源',
      id: 'unires',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_work_location',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_work_location_multi_data_view',
      name: '员工管理-工作地点',
      id: 'hr_work_location',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'test',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_module_module_grid_view_test',
      name: '测试',
      id: 'test',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_server',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_mail_server_multi_data_view',
      name: '发送服务器',
      id: 'mail_server',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'actions_server',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_actions_server_multi_data_view',
      name: '服务器动作',
      id: 'actions_server',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'resource_calendar',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.resource_calendar_multi_data_view',
      name: '员工管理-资源工作时间',
      id: 'resource_calendar',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_employee_org',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_employee_org_tree_view9',
      name: '员工组织架构',
      id: 'hr_employee_org',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'cron_trigger',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_cron_trigger_multi_data_view',
      name: '触发行动',
      id: 'cron_trigger',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'message',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_message_multi_data_view',
      name: '消息',
      id: 'message',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_alias',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_alias_multi_data_view',
      name: '别名',
      id: 'mail_alias',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'ir_module_category',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_module_category_grid_view',
      name: '应用分类',
      id: 'ir_module_category',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_resume_line_type',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_resume_line_type_multi_data_view',
      name: '员工管理-简历明细的类型',
      id: 'hr_resume_line_type',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_activity_type',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_activity_type_multi_data_view',
      name: '活动类型',
      id: 'mail_activity_type',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'company',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.res_company_multi_data_view',
      name: '公司管理',
      id: 'company',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_template',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_template_multi_data_view',
      name: 'EMail模板',
      id: 'mail_template',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'rule',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_rule_multi_data_view',
      name: '规则',
      id: 'rule',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_skill_type',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_skill_type_multi_data_view',
      name: '员工管理-技能类型',
      id: 'hr_skill_type',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_departure_reason',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_departure_reason_multi_data_view',
      name: '员工管理-离职原因',
      id: 'hr_departure_reason',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'notification',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_notification_multi_data_view',
      name: '消息通知',
      id: 'notification',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_alias_domain',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_alias_domain_multi_data_view',
      name: '别名域',
      id: 'mail_alias_domain',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'ir_default',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_default_multi_data_view',
      name: '用户定义的默认值',
      id: 'ir_default',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'config_parameter',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_config_parameter_multi_data_view',
      name: '系统参数',
      id: 'config_parameter',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'partner',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.res_partner_multi_data_view',
      name: '联系人管理',
      id: 'partner',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'mail_activity',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_activity_multi_data_view',
      name: '活动',
      id: 'mail_activity',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'employee_modifysetting',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.res_config_settings_modify_setting',
      name: '员工管理-设置修改',
      id: 'employee_modifysetting',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'cron',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.ir_cron_multi_data_view',
      name: '计划的操作',
      id: 'cron',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'hr_contract_type',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.hr_contract_type_multi_data_view',
      name: '员工管理-就业类型',
      id: 'hr_contract_type',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'discuss',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.mail_message_discuss_main_view',
      name: '讨论',
      id: 'discuss',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'fetchmail_server',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'ibizodooapp.fetchmail_server_multi_data_view',
      name: '收件服务器',
      id: 'fetchmail_server',
    },
  ],
  appPFPluginRefs: [
    {
      pluginCode: 'COMMENT',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizHtmlComment',
      rtobjectRepo: '@ibiz-template-plm/html-comment@0.0.3-alpha.262',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      name: 'HTML（评论）',
      id: 'html（评论）',
    },
    {
      pluginCode: 'ODOO_PERSONNEL_INFO',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizOdooPersonalInfo',
      rtobjectRepo: '@ibiz-template-odoo/odoo-personal-info@0.1.8-alpha.308',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: 'odoo人员信息',
    },
    {
      pluginCode: 'ODOO_GROUP_GRID',
      pluginParams: {
        replaceglobal: 'true',
      },
      pluginType: 'GRID_RENDER',
      rtobjectName: 'IBizOdooGroupGrid',
      rtobjectRepo: '@ibiz-template-odoo/odoo-group-grid@0.1.8-alpha.311',
      refMode: 'CONTROL',
      refTag: 'GRID',
      runtimeObject: true,
      id: 'odoo分组表格',
    },
    {
      pluginCode: 'ODOO_CHART',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizOdooChartControl',
      rtobjectRepo: '@ibiz-template-odoo/odoo-chart@0.1.8-alpha.335',
      refMode: 'CONTROL',
      refTag: 'CHART',
      runtimeObject: true,
      id: 'odoo图表',
    },
    {
      pluginCode: 'ODOO_DRBAR',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizOdooDRbarControl',
      rtobjectRepo: '@ibiz-template-odoo/odoo-drbar@0.1.8-alpha.315',
      refMode: 'CONTROL',
      refTag: 'DRBAR',
      runtimeObject: true,
      id: 'odoo数据关系栏',
    },
    {
      pluginCode: 'ODOO_SWIMLANE_KANBAN',
      pluginType: 'DATAVIEW_RENDER',
      rtobjectName: 'ODOO_SWIMLANE_KANBAN',
      rtobjectRepo: '@ibiz-template-odoo/odoo-swimlane-kanban@0.1.8-alpha.295',
      refMode: 'CONTROL',
      refTag: 'KANBAN',
      runtimeObject: true,
      id: 'odoo泳道看板',
    },
    {
      pluginCode: 'ODOO_STATUS_BAR',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizOdooStatusBar',
      rtobjectRepo: '@ibiz-template-odoo/odoo-status-bar@0.1.8-alpha.276',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: 'odoo状态栏',
    },
    {
      pluginCode: 'ODOO_ORG_TREE',
      pluginType: 'TREE_RENDER',
      rtobjectName: 'IBizOdooOrgTreeControl',
      rtobjectRepo: '@ibiz-template-odoo/odoo-org-tree@0.1.8-alpha.280',
      refMode: 'CONTROL',
      refTag: 'TREEVIEW',
      runtimeObject: true,
      id: 'odoo组织结构树',
    },
    {
      pluginCode: 'ODOO_CHAT',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizOdooChat',
      rtobjectRepo: '@ibiz-template-odoo/odoo-chat@0.1.8-alpha.243',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'RAWITEM',
      runtimeObject: true,
      id: 'odoo聊天窗',
    },
    {
      pluginCode: 'ODOO_SEARCH_BAR',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizStyleSearchBarControl',
      rtobjectRepo: '@ibiz-template-odoo/odoo-search-bar@0.1.8-alpha.279',
      refMode: 'CONTROL',
      refTag: 'SEARCHBAR',
      runtimeObject: true,
      id: 'odoo风格搜索栏',
    },
    {
      pluginCode: 'PERSONNEL_INFO',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizPersonalInfo',
      rtobjectRepo: '@ibiz-template-plm/personal-info@0.0.3-alpha.256',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '人员信息',
    },
    {
      pluginCode: 'AVATAR_UPLOAD',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'AvatarUpload',
      rtobjectRepo: '@ibiz-template-plm/avatar-upload@0.0.3-alpha.265',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '人员头像上传',
    },
    {
      pluginCode: 'PERSON_SELECT',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizPersonelSelect',
      rtobjectRepo: '@ibiz-template-plm/person-select@0.0.3-alpha.256',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '人员选择',
    },
    {
      pluginCode: 'ATTENTION',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizAttention',
      rtobjectRepo: '@ibiz-template-plm/attention@0.0.3-alpha.256',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '关注',
    },
    {
      pluginCode: 'LIST_TREE',
      pluginType: 'TREE_RENDER',
      rtobjectName: 'IBizListTreeControl',
      rtobjectRepo: '@ibiz-template-plm/list-tree@0.0.3-dev.198',
      refMode: 'CONTROL',
      refTag: 'TREEVIEW',
      runtimeObject: true,
      id: '列表树',
    },
    {
      pluginCode: 'NTON_GRID',
      pluginType: 'GRID_RENDER',
      rtobjectName: 'IBizNToNGridControl',
      rtobjectRepo: '@ibiz-template-plugin/nton-grid@0.1.8-alpha.313',
      refMode: 'CONTROL',
      refTag: 'GRID',
      runtimeObject: true,
      id: '多对多表格',
    },
    {
      pluginCode: 'OPEN_ODOO_CHAT',
      pluginType: 'DEUIACTION',
      rtobjectName: 'IBizOdooChatAction',
      rtobjectRepo: '@ibiz-template-odoo/odoo-chat@0.1.8-alpha.243',
      refMode: 'UIACTION',
      refTag: 'FRONT',
      runtimeObject: true,
      id: '打开odoo聊天窗',
    },
    {
      pluginCode: 'IDENTIFIER_TITLE',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizIdentifierTitle',
      rtobjectRepo: '@ibiz-template-plm/identifier-title@0.0.3-alpha.138',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'CTRLPOS',
      runtimeObject: true,
      id: '编号标题栏',
    },
    {
      pluginCode: 'CUSTOM_AUTH_USERINFO',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizCustomUserInfo',
      rtobjectRepo: '@ibiz-template-plm/custom-user-info@0.0.3-dev.98',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'RAWITEM',
      runtimeObject: true,
      id: '自定义用户信息',
    },
    {
      pluginCode: 'MAIL_MESSAGE_ITEM',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizCommentItemRawItem',
      rtobjectRepo: '@ibiz-template-plm/comment-item@0.0.3-alpha.209',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '评论列表项',
    },
    {
      pluginCode: 'PIVOTTABLE',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizPivotTable',
      rtobjectRepo: '@ibiz-template-plugin/pivottable@1.1.0',
      refMode: 'CONTROL',
      refTag: 'GRID',
      runtimeObject: true,
      id: '透视表',
    },
    {
      pluginCode: 'ANCHO_HTML',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'AnchoHtml',
      rtobjectRepo: '@ibiz-template-plm/ancho-html@0.0.3-alpha.216',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '锚点富文本',
    },
    {
      pluginCode: 'BREADCRUMB_NAV_POS',
      pluginType: 'CUSTOM',
      rtobjectName: 'BREADCRUMB_NAV_POS',
      rtobjectRepo: '@ibiz-template-plm/breadcrumb-nav-pos@0.0.3-alpha.164',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'RAWITEM',
      runtimeObject: true,
      id: '面包屑导航区占位',
    },
  ],
  appUIThemes: [
    {
      themeParams: {
        'theme-package-path': '@ibiz-template-odoo/odoo-dark@0.1.8-alpha.339',
      },
      themeTag: 'odoo_dark',
      id: 'odoo_dark',
    },
  ],
  appUtils: [
    {
      codeName: 'hub_app',
      utilDEName: 'IR_MODULE_MODULE',
      utilParams: {
        saveAppDEActionId: 'save',
        getAppDEActionId: 'fetch_cur_user_app',
        modelMapping:
          'id:app_id|caption:display_name|order:order|dataId:id|indexViewName:url',
      },
      utilTag: 'HUBAPP',
      utilType: 'USER',
      name: '集成应用',
      id: 'hub_app',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '拒绝',
      name: 'DENY',
      id: 'deny',
    },
    {
      logicName: '无控制',
      name: 'NONE',
      id: 'none',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '子数据权限',
      name: 'SUBDATA',
      id: 'subdata',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
    {
      logicName: '流程启动',
      name: 'WFSTART',
      id: 'wfstart',
    },
  ],
  appFolder: 'ibizodooapp',
  appMode: 'CLOUDHUBAPP',
  appType: 'WEBAPP_HTML5',
  appVersion: '1.0.0.0',
  codeName: 'ibizodooapp',
  dynaSysMode: 1,
  engineVer: 240,
  pfstyle: 'VUE_R7_EMPTY',
  pftype: 'VUE_R7',
  pkgcodeName: 'ibizodooapp',
  serviceCodeName: 'ibizodooapp',
  sysCodeName: 'iBizOdoo',
  title: 'ibizodooapp',
  viewCodeNameMode: 'LOWER_UNDERSCORE',
  enableServiceAPIDTO: true,
  enableUIModelEx: true,
  useServiceApi: true,
  userParam: {
    enableMqtt: 'true',
    'globalConfig.mdctrldefaultsort': 'write_date,desc',
    'globalConfig.appMenu.echoMode': 'MENUITEM',
    'globalConfig.common.emptyShowMode': 'PLACEHOLDER',
    'globalConfig.searchform.enableStoredFilters': 'true',
    'globalConfig.grid.saveErrorHandleMode': 'reset',
    'globalConfig.grid.overflowMode': 'ellipsis',
    'globalConfig.contextMenuRightClickInvoke': 'false',
    enableAI: 'true',
    'globalConfig.common.enableDownloadTicket': 'false',
    DefaultOSSCat: 'ibizodoo',
    'globalConfig.common.drawerOption': '{"showClose":false}',
    'globalConfig.pickerdefaultsort': 'write_date,desc',
  },
  id: 'ibizodooapp',
  appId: 'ibizodoo__ibizodooapp',
};
